BL-6220 Clean up Epub preview and ACE generation
BloomBooks/BloomDesktop pull request #2591
Opened 2018-07-16 21:46 UTC by JohnThomson

- Remove use of background worker for making epubs, since creation is already on a background (server) thread
- making the epub is now a single step
- Use checksum to reliably tell whether we need to regenerate the epub
- Save the PublishView's Form rather than retrieving Form.ActiveForm
- Fix a problem in Link.tsx that caused excessive page  refreshes (and extra epub creation)
- Fix a glitch that could make epub generation fail to terminate
- Added support for api handlers that deal with their own threading issues (so changing a setting can abort preview creation)

2018-07-16 21:56 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591)* status: 0 of 11 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 196 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LH_4uuLCOe3GiUqvWii:-LH_4uuM9OJx5fUzwBnn:bd2bofr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/Publish/Epub/EpubMaker.cs#L196)):*
> ```Smalltalk
> 			StagingEpub = true;
> 			try
> 			{
> ```

The changes in this section are just automatic reformatting. I'm pretty sure all I actually changed was to wrap it in the try...finally. (But don't skip the changes after the finallly.)


<!-- Sent from Reviewable.io -->

2018-07-16 23:54 UTC, andrew-polk reviewed
No glaring issues, but I admit I didn't fully synthesize what was going on.
@hatton should take a look, but perhaps the best thing would be if @john-thomson reviews it himself after sleeping as if he was reviewing someone else's code.

> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-:-LH_VnfPAESJOzPqVMyt:b-vv3nrg)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 335 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LH_TSLP31qdSfj11N_N:-LH_TSLP31qdSfj11N_O:bngsr5n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L335)):*
> ```Smalltalk
> 				// is when things got messed up because debugging prevented there being an active Bloom
> 				// form at a critical moment.
> 				//if (_previewWorker != null && EpubMaker != null)
> ```

Reason to keep this commented code?
___
*[src/BloomExe/web/EnhancedImageServer.cs, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LH_PsZj7pXsYaLQooZt:-LH_PsZj7pXsYaLQooZu:bl06sfo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/web/EnhancedImageServer.cs#L70)):*
> ```Smalltalk
> 		/// There's also danger of deadlock if something in the UI thread is somehow waiting for this request to complete.
> 		/// But, beware of race conditions or anything that manipulates UI controls if you make it false.</param>
> 		/// <param name="requiresSync">True if the handler wants the server to ensure no other thread is doing an api
> ```

Our future selves will be grateful to have a good explanation of when we want this true and when we want this false, perhaps even with examples.
___
*[src/BloomExe/web/EnhancedImageServer.cs, line 124 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LH_PYqSDvUcgG1KxmOA:-LH_PYqSDvUcgG1KxmOB:b-4e21vc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/web/EnhancedImageServer.cs#L124)):*
> ```Smalltalk
> 					catch (InvalidOperationException)
> 					{
> 						// Todo: remove this; temporary work-around.
> ```

Remove this when? Workaround for what?


<!-- Sent from Reviewable.io -->

2018-07-17 16:55 UTC, hatton reviewed
> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHd4hTT2ducMg9OFE9k:-LHd4hTT2ducMg9OFE9l:b-8bcmnf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx#L37)):*
> ```XML
>             })
>             .catch(error => {
>                 this.progressBox.writeLine("Failed");
> ```

Is there information in that error that would be helpful to print? E.g. did it timeout?T
___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1822 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHd0lr14CZhv_wKvLuO:-LHd0lr14CZhv_wKvLuP:bprtw5d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/Publish/Epub/EpubMaker.cs#L1822)):*
> ```Smalltalk
> 			AddEpubVisibilityStylesheetAndClass (normalDom);
> 
> 			var dummy = _browser.Handle; // gets WebBrowser created along with handle
> ```

All of this wants to be in the exiting Browser-wrapping class.
___
*[src/BloomExe/Publish/Epub/EpubPublishUiSettings.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHd1Rpi7eB4zzEeVlpE:-LHd1Rpi7eB4zzEeVlpF:b-opphto) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/Publish/Epub/EpubPublishUiSettings.cs#L29)):*
> ```Smalltalk
> 		public EpubPublishUiSettings Clone()
> 		{
> 			return new EpubPublishUiSettings() {howToPublishImageDescriptions = howToPublishImageDescriptions, removeFontSizes = removeFontSizes};
> ```

Any chance here some way to write this that doesn't depend on us thinking about it every time  we need a new setting?


<!-- Sent from Reviewable.io -->

2018-07-19 17:28 UTC, hatton requested changes
I still haven't finished this review, but I'll publish the comments I have thus far.

> Reviewed 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-:-LHn_Tib3LwP8yuoykSf:b-6vhf9u)* status: 12 of 14 files reviewed, 10 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Browser.cs, line 822 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHnMie48X8QF2OYUEEg:-LHnMie48X8QF2OYUEEh:b-ev6c41) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Browser.cs#L822)):*
> ```Smalltalk
> 		}
> 
> 		// Should be called on UI thread. Since it is quite typical for this method to create the
> ```

I think this can be done with an assert instead of a comment?

    assert(!Program.RunningOnUiThread, "Must be called on UI thread");
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 80 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHn_72L6HSUyHRhnM_I:-LHn_72L6HSUyHRhnM_J:b-7e5jiz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L80)):*
> ```Smalltalk
> 		private string _lastDirectory; // where we saved the most recent previous epub, if any
> 
> 		private string _saveAsPath;
> ```

How about ``_pendingSaveAsPath`` with a comment saying that it is null unless the user has told us what path to use but we're waiting to complete the build before we save.
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 126 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHnSCOz2aiLEwuav76v:-LHnSCOz2aiLEwuav76w:b9gq16n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L126)):*
> ```Smalltalk
> 							{
> 								_saveAsPath = dlg.FileName;
> 								if (!_stagingEpub)
> ```

Hmm, I'm not following something. Is it possible to get the lock a few lines above, but then still be staging? Assuming yes, then .... what happens? We've already collected a path from the user, bu then we... just don't actually save it?

Oh my. Ok. So later I found that SaveAsEpub is actually something like SaveEpubIfSaveIsPending, and it will be called at the end of an epub creation. Rather surprising organization, even with the clarified name. But... I suppose it must work. Should comment here about that.
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 203 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHnX3ZfBY6QHh00k4Jo:-LHnX3Zg-KaxM_tTeRXm:bxc560l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L203)):*
> ```Smalltalk
> 		{
> 			if (UpdatePreview(newSettings, true))
> 				ControlForInvoke.Invoke((Action)(() => _webSocketServer.SendString(kWebsocketContext, kWebsocketEventId_Preview, _previewSrc)));
> ```

Can you add a comment saying why we have to go to the UI thread to talk on the websocket. This surprises me greatly.
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 260 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHnXcSN1h61KUh9N70e:-LHnXcSN1h61KUh9N70f:bx6rddd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L260)):*
> ```Smalltalk
> 			// This gets called on a background thread but one step needs to happen on the UI thread,
> 			// so the Maker needs a control to Invoke on.
> 			EpubMaker.ControlForInvoke = ControlForInvoke;
> ```

So I suppose this is because there are multiple windows? Would be worth a comment.


<!-- Sent from Reviewable.io -->

2018-07-19 19:21 UTC, JohnThomson reviewed
I've responded to those...

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-:-LHnyIrA-lxEc672NDZp:b-vm2vh0)* status: 12 of 14 files reviewed, 10 unresolved discussions (waiting on @andrew-polk, @JohnThomson, and @hatton)

___
*[src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHd4hTT2ducMg9OFE9k:-LHdCRym4RtKcE7z_uVd:b-8zz73p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomBrowserUI/publish/accessibilityCheck/daisyChecks.tsx#L37)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there information in that error that would be helpful to print? E.g. did it timeout?T
</blockquote></details>

I suppose it's possible, but I don't think so. I'm just putting it back the way it was before I tried changing from a get to a post that leads to a websocket notification. The C# code running ACE pushes lots of error information into progress; this is just notifying the user that after it failed (and errors were reported) three times, we gave up.
___
*[src/BloomExe/Browser.cs, line 822 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHnMie48X8QF2OYUEEg:-LHnv3vp8Sr5qqv3_r4l:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Browser.cs#L822)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think this can be done with an assert instead of a comment?

    assert(!Program.RunningOnUiThread, "Must be called on UI thread");
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/Epub/EpubMaker.cs, line 1822 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHd0lr14CZhv_wKvLuO:-LHdGHNpAV2XlMrzKt_5:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/Publish/Epub/EpubMaker.cs#L1822)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

All of this wants to be in the exiting Browser-wrapping class.
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/Epub/EpubPublishUiSettings.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHd1Rpi7eB4zzEeVlpE:-LHdGtUVCDwPxGXh4ixp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/Publish/Epub/EpubPublishUiSettings.cs#L29)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Any chance here some way to write this that doesn't depend on us thinking about it every time  we need a new setting?
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 335 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LH_TSLP31qdSfj11N_N:-LHdH22-9Qx_y_01Agaf:b-pyrbqy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L335)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Reason to keep this commented code?
</blockquote></details>

No. Removed.
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 80 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHn_72L6HSUyHRhnM_I:-LHnvsAK54RWPa0hbXO4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L80)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about ``_pendingSaveAsPath`` with a comment saying that it is null unless the user has told us what path to use but we're waiting to complete the build before we save.
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 126 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHnSCOz2aiLEwuav76v:-LHnwevMAk6B5Cr9_25r:bs3mhdg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L126)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Hmm, I'm not following something. Is it possible to get the lock a few lines above, but then still be staging? Assuming yes, then .... what happens? We've already collected a path from the user, bu then we... just don't actually save it?

Oh my. Ok. So later I found that SaveAsEpub is actually something like SaveEpubIfSaveIsPending, and it will be called at the end of an epub creation. Rather surprising organization, even with the clarified name. But... I suppose it must work. Should comment here about that.
</blockquote></details>

Comment added.
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 203 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHnX3ZfBY6QHh00k4Jo:-LHnxELMDra2v4VWpzx-:b2qns98) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L203)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Can you add a comment saying why we have to go to the UI thread to talk on the websocket. This surprises me greatly.
</blockquote></details>

Apparently we don't--which surprised me! My impression was that Gecko is single threaded and touching it required Invoke. But I guess this isn't actually calling any methods of it directly. Removed.
___
*[src/BloomExe/Publish/Epub/PublishEpubApi.cs, line 260 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LHnXcSN1h61KUh9N70e:-LHnyDI54AaclXFWIRgV:b-uo62vp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e67d73946754c14af7ca00faf1209a5544459942/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L260)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So I suppose this is because there are multiple windows? Would be worth a comment.
</blockquote></details>

Not really. See new comment.
___
*[src/BloomExe/web/EnhancedImageServer.cs, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LH_PsZj7pXsYaLQooZt:-LHdH4j7-8Y7Ka1A-0pS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/web/EnhancedImageServer.cs#L70)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Our future selves will be grateful to have a good explanation of when we want this true and when we want this false, perhaps even with examples.
</blockquote></details>

Done.
___
*[src/BloomExe/web/EnhancedImageServer.cs, line 124 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2591#-LH_PYqSDvUcgG1KxmOA:-LHdBMfv251UkS8IKscN:bdmo673) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f1a5039c3e5281b2b130ff85b3071829f7d28433/src/BloomExe/web/EnhancedImageServer.cs#L124)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Remove this when? Workaround for what?
</blockquote></details>

Immediately! For something I did just while debugging! Good catch.


<!-- Sent from Reviewable.io -->

2018-07-19 20:03 UTC, merged