BL-6349 Add Enterprise Subscription Codes and Settings page
BloomBooks/BloomDesktop pull request #2685
Opened 2018-08-21 19:17 UTC by JohnThomson

Also adds BloomLowPriority.xlf localization file

2018-08-21 19:25 UTC, hatton requested changes
> Reviewed 9 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 9 of 29 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/branding/Papua Literacy/summary.htm, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSvb1rB1Q6UJHhRqkj:-LKSvb1s40daWQ3jDQQK:bz6652o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/DistFiles/branding/Papua Literacy/summary.htm#L2)):*
> ```HTML
> <div class="vertical">
> 	<div>Organizations: Papua Karya Swadaya, SIL, Suluh Insan Lestari, YMP3, YABN, Tut Wuri Handayani</div>
> ```

I would think "Papua Literacy" is the label we want, no need to list the constituents.
___
*[DistFiles/branding/PNG-RISE/summary.htm, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSvtjtCB_VTaaz9WUb:-LKSvtjtCB_VTaaz9WUc:b-5m9nmp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/DistFiles/branding/PNG-RISE/summary.htm#L2)):*
> ```HTML
> <div class="horizontal">
> 	<div>Organizations: Rapidly Improving Standards in Elementary, Save The Children in Papua New Guinea, Callan Services for Persons with Disabilities, Summer Institute of Linguistics Papua New Guinea</div>
> ```

Should just be "RISE PNG"
___
*[DistFiles/branding/PNG-RISE/summary.htm, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSw0Ei2FIu_GuEBz9e:-LKSw0Ei2FIu_GuEBz9f:bm87oql) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/DistFiles/branding/PNG-RISE/summary.htm#L3)):*
> ```HTML
> <div class="horizontal">
> 	<div>Organizations: Rapidly Improving Standards in Elementary, Save The Children in Papua New Guinea, Callan Services for Persons with Disabilities, Summer Institute of Linguistics Papua New Guinea</div>
> 	<img src="/bloom/branding/PNG-RISE/summary.svg"/>
> ```

We can't reuse some existing something? It's not really worth carrying a new logo, could leave it out.
___
*[DistFiles/branding/UBB-GMIT/summary.htm, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSwQY99r93Ch3iEIPk:-LKSwQY99r93Ch3iEIPl:br2zmgj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/DistFiles/branding/UBB-GMIT/summary.htm#L3)):*
> ```HTML
> <div class="horizontal">
> 	<div>Organization: UBB-GMIT</div>
> 	<img src="/bloom/branding/UBB-GMIT/credits-page-bottom.png"/>
> ```

Would be nice if these didn't require a path, but I guess that's hard?


<!-- Sent from Reviewable.io -->

2018-08-21 19:49 UTC, hatton requested changes
> Reviewed 5 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 14 of 29 files reviewed, 13 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSyiT0206J39u_SlSM:-LKSyiT0206J39u_SlSN:b-hcqhpm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L24)):*
> ```XML
>     constructor(props) {
>         super(props);
>         this.state = {
> ```

We've switched over to the new approach. See https://github.com/BloomBooks/BloomDesktop/pull/2678
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSzAWP90F7WSK41lcx:-LKSzAWP90F7WSK41lcy:b-go8ls0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L32)):*
> ```XML
>         };
> 
>         this.handleSubscriptionCodeChanged = this.handleSubscriptionCodeChanged.bind(
> ```

I think arrow functions are more idiomatic typescript/modern JS. There is a theoretical performance cost, but not one that would show up in UI code.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 75 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSznYADb30l3HwLluy:-LKSznYADb30l3HwLluz:bhmgt3f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L75)):*
> ```XML
>                     </Label>
>                 </div>
>                 <div className="learnMoreLink">
> ```

Are these extra divs necessary? I Link needs to be able to take a className, we should add that ability.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 88 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSzwP00_4YDnEcOMCw:-LKSzwP00_4YDnEcOMCx:b-k1fv0g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L88)):*
> ```XML
>                     </Label>
>                 </div>
>                 <div>
> ```

Is this extra div necessary?
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 133 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSz4OV0H5tt2G-qOwD:-LKSz4OV0H5tt2G-qOwE:b-ginvw7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L133)):*
> ```XML
>                         type="text"
>                         value={this.state.subscriptionCode}
>                         onChange={this.handleSubscriptionCodeChanged}
> ```

 change to 
    () => this._____
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT-M0x3LD2CMLZi7zM:-LKT-M0x3LD2CMLZi7zN:byfllve) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L139)):*
> ```XML
>                         this.state.subscriptionExpiry !== null &&
>                         !this.state.subscriptionUnknown
>                             ? "\u2713"
> ```

Would be clearer with the actual character instead of the code.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 143 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT-sGKBBzD1p8doP2Y:-LKT-sGKBBzD1p8doP2Z:b-8knfvq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L143)):*
> ```XML
>                     </span>
>                 </div>
>                 <div
> ```

Two other ways to handle state:
1) use code, as in ``if(this.state....){ <Label> ``
2) use stylesheets. Give some parent element classes representing the state

I expect either would be cleaner?

It's not that this is a problem as is, it's just that state machines can dramatically simplify code, and its maintenance.  Then I find folks tend to just copy the "closest thing they can find" to what their task is, which makes me want the exemplar to be as clean as possible.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT0_TJ37w4F_bqrcNf:-LKT0_TJ37w4F_bqrcNg:b-57m1v5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L158)):*
> ```XML
>                     </Label>
>                 </div>
>                 <div
> ```

I can't tell what role these extra divs are playing
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 266 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT15JJ2f9531rXoEvM:-LKT15JJ2f9531rXoEvN:b8aufkg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L266)):*
> ```XML
>             { enterpriseCode: event.target.value },
>             {
>                 headers: { "Content-Type": "application/json" }
> ```

Seems like BloomApi wants a way of encapsulating such a common case?


<!-- Sent from Reviewable.io -->

2018-08-21 19:56 UTC, hatton requested changes
> Reviewed 3 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 17 of 29 files reviewed, 17 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Program.cs, line 1001 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT1RZ-7Uh5PSOxgd-d:-LKT1RZ-7Uh5PSOxgd-e:b-i43mcw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Program.cs#L1001)):*
> ```Smalltalk
> 											Resources.BloomIcon, "issues@bloomlibrary.org", "SIL");
> 
> 				unusedGoesIntoStatic = LocalizationManager.Create(uiLanguage,
> ```

I feel dumb asking, because it says "unused", but... why is it there then?
___
*[src/BloomExe/web/controllers/SettingsApi.cs, line 20 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT1gUx8x9WbQoZHQTC:-LKT1gUx8x9WbQoZHQTD:b7aysqa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/web/controllers/SettingsApi.cs#L20)):*
> ```Smalltalk
> 	/// Used by the settings dialog (currently just the EnterpriseSettings tab)
> 	/// </summary>
> 	public class SettingsApi
> ```

--> CollectionSettingsApi
___
*[src/BloomExe/web/controllers/SettingsApi.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT1vhc7TNUWgTkplv7:-LKT1vhc7TNUWgTkplv8:b-5mndty) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/web/controllers/SettingsApi.cs#L36)):*
> ```Smalltalk
> 		private static EnterpriseStatus _enterpriseStatus;
> 		
> 		public void RegisterWithServer(EnhancedImageServer server)
> ```

If "Community" could just be another subscription, then you could drop EntrpriseStatus and a lot of code here.
___
*[src/BloomExe/web/controllers/SettingsApi.cs, line 82 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT2NinAW5zB76ZqtBw:-LKT2NinAW5zB76ZqtBx:bv67ukx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/web/controllers/SettingsApi.cs#L82)):*
> ```Smalltalk
> 				}
> 			}, false);
> 			server.RegisterEndpointHandler(kApiUrlPart + "enterpriseFeedback", request =>
> ```

Do you mean "subscriptionSummary"? Feedback sounds like something the user sends us.


<!-- Sent from Reviewable.io -->

2018-08-21 20:39 UTC, hatton requested changes
> Reviewed 4 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 21 of 29 files reviewed, 20 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Collection/BrandingProject.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTCNjQ5adp7guHnHkl:-LKTCNjR36D25j86ghwR:bngpyej) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/BrandingProject.cs#L32)):*
> ```Smalltalk
> 				if (_legacyBrandings == null)
> 				{
> 					_legacyBrandings = new Dictionary<string, string>();
> ```

I'm having second thoughts about publishing these (which is what it is to put in the source code). Any other way?
___
*[src/BloomTests/web/controllers/SettingsApiTests.cs, line 11 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT2ncvDYVfzw3PbNdr:-LKT2ncvDYVfzw3PbNds:beor9lb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomTests/web/controllers/SettingsApiTests.cs#L11)):*
> ```Smalltalk
> namespace BloomTests.web.controllers
> {
> 	public class SettingsApiTests
> ```

--> CollectionSettingsApiTests
___
*[src/BloomTests/web/controllers/SettingsApiTests.cs, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT2scjBO3ajg3xWqNA:-LKT2scjBO3ajg3xWqNB:b-2yrvod) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomTests/web/controllers/SettingsApiTests.cs#L29)):*
> ```Smalltalk
> 		[TestCase("SIL748410821")] // no dashes
> 		[TestCase("SIL-74847709")] // too few dashes
> 		[TestCase("SIL-7484-7709-nonsence")] // extra at end
> ```

Andrew's gonna make you change that spelling :-)


<!-- Sent from Reviewable.io -->

2018-08-21 20:54 UTC, hatton requested changes
> Reviewed 1 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 22 of 29 files reviewed, 23 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTE6RF1zDJbYn5V-00:-LKTE6RF1zDJbYn5V-01:b39fal2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L77)):*
> ```Smalltalk
> 		private void SetupEnterpriseBrowser()
> 		{
> 			_enterpriseBrowser = new Browser {Dock = DockStyle.Fill};
> ```

I notice that the class HtmlPublishPanel has a line about cleaning up react stuff, presumably a hard-won lesson that we may have to re-learn here. So should we introduce a similar one that we will use as we continue to replay bits of winforms with windows? Just a thought.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 287 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTEwzU7AupQH7-tmUM:-LKTEwzU7AupQH7-tmUN:b3v9vu9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L287)):*
> ```Smalltalk
> 			LoadBrandingCombo();
> 			AdjustFontComboDropdownWidth();
> 			_brand = _collectionSettings.BrandingProjectKey;
> ```

We should have a thinking session about the names we want to use... I think a new dev would get all mixed up in branding vs. Enterprise vs. subscription. These are definitely not synonymous, but are we using them consistently?  

Possibly, anything "Code" / "Expiry" is a *subscription*. Anything related to layout is a *branding*?
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 541 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTFhpEC9FhEFg3kQ4N:-LKTFhpF89updenYGfMP:bu60xu7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L541)):*
> ```Smalltalk
> 				// The only time this can happen is when the browser is not visible and may not even
> 				// have started loading, so sending stuff to its websocket might not work, anyway.
> 				_enterpriseBrowser.WebBrowser.Reload();
> ```

Is this an artifact of the old ui coexisting? I think I asked for that, but at the moment I can't see why it's worth the bother. Do you remember?


<!-- Sent from Reviewable.io -->

2018-08-21 20:57 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 22 of 29 files reviewed, 25 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 548 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTGByh0LLwLqQq24Ft:-LKTGByh0LLwLqQq24Fu:b-c7waoz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L548)):*
> ```Smalltalk
> 		}
> 
> 		private SettingsApi.EnterpriseStatus GetEnterpriseStatus()
> ```

Could all this just be a simple string? e.g. "", "local community", some-subscription-code
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 560 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTGfosCDmPhpuP-xox:-LKTGfosCDmPhpuP-xoy:bz8kbm2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L560)):*
> ```Smalltalk
> 		private bool _disableBrandingSelectionChanged = false;
> 
> 		public bool ChangeBranding(string brand, string brandingCode)
> ```

I can't tell what this is for. Since it is a public method, can you comment it? I can't figure out why in the world there is a "branding combo" that c# know about.


<!-- Sent from Reviewable.io -->

2018-08-21 21:01 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 22 of 29 files reviewed, 27 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/I18NHandler.cs, line 87 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTHB88DrZ4foyJY5Bs:-LKTHB88DrZ4foyJY5Bt:b-nqbs4v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/web/I18NHandler.cs#L87)):*
> ```Smalltalk
> 						info.ContentType = "text/plain";
> 						string langIdUsedDummy;
> 						info.WriteCompleteOutput(LocalizationManager.GetString(id, englishText, null, new[] {langId}, out langIdUsedDummy));
> ```

I'm not clear this is ok, to use the non-dynamic version to do a dynamic lookup. Certainly it's abusing the design, so will lead to confusion.
___
*[src/BloomExe/web/I18NHandler.cs, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTHVat1JbF1j0owk0_:-LKTHVau7UIZn-EYOxKR:ba8zwpq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/web/I18NHandler.cs#L169)):*
> ```Smalltalk
> 				{
> 					// try low priority
> 					translation = LocalizationManager.GetDynamicString("BloomLowPriority", key, null);
> ```

SHouldn't it be up to the LocalizationManager to look through its list, rather than hack it like this?


<!-- Sent from Reviewable.io -->

2018-08-21 21:02 UTC, hatton reviewed
> Reviewed 7 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: all files reviewed, 27 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2018-08-21 21:51 UTC, JohnThomson reviewed
Dealt with about half the comments...some may need follow-up, so I'm pushing what I got done.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-:-LKTSxwN-rV0fq5LwFPA:bg91faw)* status: 24 of 28 files reviewed, 27 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[DistFiles/branding/Papua Literacy/summary.htm, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSvb1rB1Q6UJHhRqkj:-LKT9YVb4Jt8_uw8yQJn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/DistFiles/branding/Papua Literacy/summary.htm#L2)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I would think "Papua Literacy" is the label we want, no need to list the constituents.
</blockquote></details>

Done.
___
*[DistFiles/branding/PNG-RISE/summary.htm, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSw0Ei2FIu_GuEBz9e:-LKT9wXJ1d6TGrmA2snw:bbczdun) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/DistFiles/branding/PNG-RISE/summary.htm#L3)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We can't reuse some existing something? It's not really worth carrying a new logo, could leave it out.
</blockquote></details>

title-page.png is just an SIL PNG logo. Back-cover-outside-wide.svg is what I have here, plus a whole lot of text above it. I found a way to reuse the back cover image by clipping the text. Ugly, but saves a megabyte or so.
___
*[DistFiles/branding/UBB-GMIT/summary.htm, line 3 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSwQY99r93Ch3iEIPk:-LKTFkeo5pSUmeJznQuj:b-n1s30i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/DistFiles/branding/UBB-GMIT/summary.htm#L3)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would be nice if these didn't require a path, but I guess that's hard?
</blockquote></details>

It's tricky because the HTML ends up embedded in a file whose root is something like output/browser/enterpriseStatus.html, while the image is off over at distfiles/branding/whatever/image.svg. We can tell the image server to always search all the branding folders, but we don't want it to search them all for everything (and might easily find the wrong one for something like outside-back-cover.svg).  A relative path that is right on a dev machine won't be for an end user (and will still be long and non-obvious). We could make the summary.htm's complete files and load them into an iframe, but I'm not sure it's worth it. What do you think?
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 24 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSyiT0206J39u_SlSM:-LKTLjct6eTUTqamkbIg:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L24)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We've switched over to the new approach. See https://github.com/BloomBooks/BloomDesktop/pull/2678
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSzAWP90F7WSK41lcx:-LKTLlfz1LTkZZ28CbGj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L32)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think arrow functions are more idiomatic typescript/modern JS. There is a theoretical performance cost, but not one that would show up in UI code.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 75 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSznYADb30l3HwLluy:-LKTMZXU2jkLA873PPDo:b-gkjij0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L75)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Are these extra divs necessary? I Link needs to be able to take a className, we should add that ability.
</blockquote></details>

I already added className to Link. Link evaluates to <a> which is inline and ignores margin-top, so I had to make the stylesheet use display:block to get that working. Not absolutely sure it's a net improvement. It's fairly conventional to wrap a div around an inline element you want to apply block properties to, I think.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 88 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSzwP00_4YDnEcOMCw:-LKTN8dQ1Tg1ns-aobt1:b3el2s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L88)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is this extra div necessary?
</blockquote></details>

Apparently not :-)
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 133 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSz4OV0H5tt2G-qOwD:-LKTNCJ16kWonRNxWiG3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L133)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

 change to 
    () => this._____
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 139 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT-M0x3LD2CMLZi7zM:-LKTNM0dB2wuZpq6-Sre:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L139)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would be clearer with the actual character instead of the code.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 143 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT-sGKBBzD1p8doP2Y:-LKTQsWw3QW60Euzs0dy:b4nwrw7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L143)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Two other ways to handle state:
1) use code, as in ``if(this.state....){ <Label> ``
2) use stylesheets. Give some parent element classes representing the state

I expect either would be cleaner?

It's not that this is a problem as is, it's just that state machines can dramatically simplify code, and its maintenance.  Then I find folks tend to just copy the "closest thing they can find" to what their task is, which makes me want the exemplar to be as clean as possible.
</blockquote></details>

It works fine to use the same code to control whether a "hidden" class is added to the element, but I'm not sure whether that addresses what you're objecting to. See what you think.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 158 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT0_TJ37w4F_bqrcNf:-LKTSM0F9zfbm8GgMZjH:b-ec0rq8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L158)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I can't tell what role these extra divs are playing
</blockquote></details>

Well, it  [...]

2018-08-22 15:21 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 16 of 29 files reviewed, 27 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[DistFiles/branding/PNG-RISE/summary.htm, line 2 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKSvtjtCB_VTaaz9WUb:-LKWmTKa0NCfp-2maUnb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/DistFiles/branding/PNG-RISE/summary.htm#L2)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Should just be "RISE PNG"
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/collection/enterpriseSettings.tsx, line 266 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT15JJ2f9531rXoEvM:-LKWnVxLBLtifRa9isA3:b-fukh23) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomBrowserUI/collection/enterpriseSettings.tsx#L266)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Seems like BloomApi wants a way of encapsulating such a common case?
</blockquote></details>

Done. (Though I haven't tried to find all the other places it could be used.)
___
*[src/BloomExe/Program.cs, line 1001 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKT1RZ-7Uh5PSOxgd-d:-LKWnq1JCOnXtLMXdeM9:b-hfpv0l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Program.cs#L1001)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I feel dumb asking, because it says "unused", but... why is it there then?
</blockquote></details>

removed
___
*[src/BloomExe/Collection/BrandingProject.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTCNjQ5adp7guHnHkl:-LKXAPw04vOm23ptfDTC:bynz8k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/BrandingProject.cs#L32)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm having second thoughts about publishing these (which is what it is to put in the source code). Any other way?
</blockquote></details>

We could decide that LegacySubscriptions just don't expire and so don't require a code, maybe hide all that part of the UI when one of those names is entered as the code.
We could generate them on the fly...but publishing how to generate codes seems even less desirable (not that it isn't easy to deduce from the published way of validating them).
We could hide them in a pretend-binary file like we do with some other 'secret' keys.
We could decide that any code works for known legacy enterprises...make the algorithm that computes expiry date from code recognize codes that start with legacy enterprises, ignore the numbers, and come up with a far-off date. Then we can replace these codes with totally spurious ones and confuse any hackers :-)
That last appeals to me most of this set of ideas.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTE6RF1zDJbYn5V-00:-LKWpxZD9ZYkEx4G6WmA:b-zabu7t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L77)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I notice that the class HtmlPublishPanel has a line about cleaning up react stuff, presumably a hard-won lesson that we may have to re-learn here. So should we introduce a similar one that we will use as we continue to replay bits of winforms with windows? Just a thought.
</blockquote></details>

You mean, introduce a new base class , or try to extract a base class from HtmlPublishPanel, for stuff that is common to any control that contains a browser containing a React component? I vaguely recall thinking about that and deciding that there was hardly enough common code to justify it. (At this point by adding a whole class I think we would save one line of code in CollectionSettings.cs.) But maybe we'll discover more. You may have found one more bit. Unfortunately the comment only captures half of the hard-won lesson: what cleanup does React need to do that is best achieved by navigating away from the page? What if we don't want to do that? In this dialog, we don't regenerate the browser when switching to the tab; we assume it is still there. So navigating away from it would require (at least) other changes. 
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 287 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTEwzU7AupQH7-tmUM:-LKWryMM7eWOuQW7iTW6:b79uz9o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L287)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We should have a thinking session about the names we want to use... I think a new dev would get all mixed up in branding vs. Enterprise vs. subscription. These are definitely not synonymous, but are we using them consistently?  

Possibly, anything "Code" / "Expiry" is a *subscription*. Anything related to layout is a *branding*?
</blockquote></details>

Probably not, because this senior developer gets mixed up about them, too. So the idea would be that branding is (anything related to) how a book or page or our UI looks when a particular Enterprise's subscription is current and active? I can think about what names should change to be consistent with that.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 541 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTFhpEC9FhEFg3kQ4N:-LKWseoVER9e4PbY3fhe:bavz8r2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L541)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is this an artifact of the old ui coexisting? I think I asked for that, but at the moment I can't see why it's worth the bother. Do you remember?
</blockquote></details>

At this point, we don't have another easy way (unless we share the spreadsheet around, which would still be less easy) for testers to activate a branding. I _think_ that was one reason...another may have been that you just wanted to keep the old until (field?) testing verifies that the new is really satisfactory?
And yes, this is an artifact of the ability to change the state of enterprise subscription from the C# side (i.e., by using the old combo). This particular thing is not a lot of bother, but the sum total of bother to keep two ways of doing the same thing in sync is not trivial. Of course, it's now done...but further bugs could of course emerge.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 548 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTGByh0LLwLqQq24Ft:-LKXCbc2CHMt7lsjSAU2:b-vk3dam) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L548)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Could all this just be a simple string? e.g. "", "local community", some-subscription-code
</blockquote></details>

Probably could. A backing enum seems to have become our standard way of dealing with sets of radio buttons in React controls where we want to persist the status, but in this case, the status is derived from the code and not persisted independently. It's not obvious to me that the net effect of getting rid of it would be to make things clearer or shorter, but you might be right. Discuss?
___
*[src/BloomExe/Collection/Collecti [...]

2018-08-22 16:14 UTC, hatton requested changes
> Reviewed 10 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 26 of 29 files reviewed, 10 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 287 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTEwzU7AupQH7-tmUM:-LKXOK9x5hGRsm8lnLsr:bb18qvu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L287)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Probably not, because this senior developer gets mixed up about them, too. So the idea would be that branding is (anything related to) how a book or page or our UI looks when a particular Enterprise's subscription is current and active? I can think about what names should change to be consistent with that.
</blockquote></details>

That sounds right.
___
*[src/BloomExe/web/I18NHandler.cs, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTHVat1JbF1j0owk0_:-LKXP7GpDL8OdNTnVO0g:b-46kusw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/web/I18NHandler.cs#L169)):*
> effect of adding missing strings to the relevant backing file

Are we using that feature anymore, with Steve's new system? @stephenmcconnel   I.e., are devs still finding the modified file in their localdata directory (or where it lives) and copying it into the code base, etc.


<!-- Sent from Reviewable.io -->

2018-08-22 20:25 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 26 of 29 files reviewed, 10 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/web/I18NHandler.cs, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTHVat1JbF1j0owk0_:-LKYIeyy3S2Zdghfd7QG:b2973o0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/web/I18NHandler.cs#L169)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> effect of adding missing strings to the relevant backing file

Are we using that feature anymore, with Steve's new system? @stephenmcconnel   I.e., are devs still finding the modified file in their localdata directory (or where it lives) and copying it into the code base, etc.
</blockquote></details>

I don't...don't even know whether it still works. Conversely, if we're also not using the code that uses reflection to update those localdata directories, does it matter whether we use GetString or GetDynamicString? Especially if we already checked that we have the string in our system?


<!-- Sent from Reviewable.io -->

2018-08-24 13:27 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 18 of 33 files reviewed, 10 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 287 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTEwzU7AupQH7-tmUM:-LKg616TDM4ozBPhOOVt:bf6yy82) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L287)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

That sounds right.
</blockquote></details>

I've attempted this...may well have missed something still.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 541 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTFhpEC9FhEFg3kQ4N:-LKg69T93sRPKpxSekEA:b-or5rck) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/Collection/CollectionSettingsDialog.cs#L541)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

At this point, we don't have another easy way (unless we share the spreadsheet around, which would still be less easy) for testers to activate a branding. I _think_ that was one reason...another may have been that you just wanted to keep the old until (field?) testing verifies that the new is really satisfactory?
And yes, this is an artifact of the ability to change the state of enterprise subscription from the C# side (i.e., by using the old combo). This particular thing is not a lot of bother, but the sum total of bother to keep two ways of doing the same thing in sync is not trivial. Of course, it's now done...but further bugs could of course emerge.
</blockquote></details>

We decided to get rid of the old control; this is now done.
___
*[src/BloomExe/web/I18NHandler.cs, line 87 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKTHB88DrZ4foyJY5Bs:-LKg6L5b7tHMRWlh0Mpi:b-djf94y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/a5c06c6bf41f2b00149849895636416624e09a60/src/BloomExe/web/I18NHandler.cs#L87)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's discuss options on this.
</blockquote></details>

I believe I have changed back to GetDynamicString for everything that doesn't pass a literal (and that I changed for this PR).


<!-- Sent from Reviewable.io -->

2018-08-24 14:23 UTC, hatton requested changes
> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 555 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKgHp8a0Z-TIsw3EeTf:-LKgHp8a0Z-TIsw3EeTg:b10kn3d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fce3bf5b5687a913ec301388e491567166c82492/src/BloomExe/Workspace/WorkspaceView.cs#L555)):*
> ```Smalltalk
> 			Application.Idle -= BringUpEnterpriseSettings;
> 			Program.CloseSplashScreen();
> 			CollectionSettingsApi.InvalidBranding = _collectionSettings.InvalidBranding;
> ```

I couldn't tell what ``InvalidBranding`` meant. I think it just means ``LegacyBranding``. Is that right? If so, I think that would be a lot clearer.
___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 557 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKgI11Q1_MvxbfnkLoc:-LKgI11Q1_MvxbfnkLod:bs6ea93) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fce3bf5b5687a913ec301388e491567166c82492/src/BloomExe/Workspace/WorkspaceView.cs#L557)):*
> ```Smalltalk
> 			CollectionSettingsApi.InvalidBranding = _collectionSettings.InvalidBranding;
> 			OnSettingsButton_Click(this, new EventArgs());
> 			CollectionSettingsApi.InvalidBranding = null;
> ```

I can't quite tell why this setting on the api is necessary. Instead, could the api just ask the collection settings?
___
*[src/BloomTests/web/controllers/CollectionSettingsApiTests.cs, line 15 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKgIJA69KdWoAz_31Pn:-LKgIJA69KdWoAz_31Po:b16w8gs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fce3bf5b5687a913ec301388e491567166c82492/src/BloomTests/web/controllers/CollectionSettingsApiTests.cs#L15)):*
> ```Smalltalk
> 		[TestCase("Acme-3506-487", 2019,2,10)]
> 		[TestCase("USAID-US-3098-2075", 2017,12,29)]
> 		[TestCase("SIL-LEAD-361769-2476", 3000,1, 1)]
> ```

Do you need to use real subscriber names here?


<!-- Sent from Reviewable.io -->

2018-08-24 14:52 UTC, hatton reviewed
![✂-1](https://files.reviewableusercontent.io/images/reviewable/8448/hpAZD4d4ti6tLQEAkTd308lU.png)

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-:-LKgPPj27bpGd2Au8QKa:blvmqkk)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)



<!-- Sent from Reviewable.io -->

2018-08-24 15:29 UTC, hatton reviewed
Note desired alignment:

![✂-1](https://files.reviewableusercontent.io/images/reviewable/8448/3JKH1pNV6OqvplDWPSMX8-wV.png)

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-:-LKgY7kr1hCf3c0Xruui:b1k57tb)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)



<!-- Sent from Reviewable.io -->

2018-08-24 15:32 UTC, hatton reviewed
Radio buttons should activate if you click their label.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-:-LKgYnpMDf6owZYMKKda:b-5mohe5)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)



<!-- Sent from Reviewable.io -->

2018-08-24 15:34 UTC, hatton reviewed
"Funded Local Community" copied the typo in the mockup. Should be "Funded by local community only".

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-:-LKgZ8Y60UykYG0a_Umb:br0m692)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton and @JohnThomson)



<!-- Sent from Reviewable.io -->

2018-08-24 20:05 UTC, hatton reviewed
![✂-1](https://files.reviewableusercontent.io/images/reviewable/8448/p-YkmODOrJqT35DBqC5203FP.png)

Let's introduce a state we can introduce where 

> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-:-LKgZrJU0U3_EVyYBHdL:bxk3s77)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2018-08-24 20:59 UTC, JohnThomson reviewed
I think I've dealt with all these except embedding the link in the label, which you offered to take on, and the 'obviously' incomplete code we shouldn't complain about, which was put off to version 2 of this UI.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-:-LKhehKNAxoJuCvTWK2Q:b22pkgt)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 555 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKgHp8a0Z-TIsw3EeTf:-LKh_KwB5J29WZWVFvE7:b-sb40b6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fce3bf5b5687a913ec301388e491567166c82492/src/BloomExe/Workspace/WorkspaceView.cs#L555)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I couldn't tell what ``InvalidBranding`` meant. I think it just means ``LegacyBranding``. Is that right? If so, I think that would be a lot clearer.
</blockquote></details>

It refers to any branding which is requested in the .bloomCollection file but not valid according to the current subscription code. This might be because it is a legacy subscription for which a code has not been entered, or because the code has expired. It _might_ even be because someone is trying to create his own branding.
___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 557 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKgI11Q1_MvxbfnkLoc:-LKh_pnkEKdaqpRKkOFo:b-7lel7w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fce3bf5b5687a913ec301388e491567166c82492/src/BloomExe/Workspace/WorkspaceView.cs#L557)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I can't quite tell why this setting on the api is necessary. Instead, could the api just ask the collection settings?
</blockquote></details>

It's tricky. CollectionSettings.Load() originally detects that the bloom collection file requests an invalid branding and sets a member property of the CollectionSettings object. But we don't want the behavior triggered by this every time the dialog comes up (i.e., starting out in the enterprise tab, with the extra message at the top). We only want that when we automatically launch the dialog as we open a collection. If we make the CollectionSettingsApi constructor take the collectionsettings and just read InvalidBranding from it, we'd have to do something else to stop it coming up that way every time, potentially even after the user fixed things.
Of course there are things we could do to fix that. We could for example allow the code that launches the dialog in this special way to clear the CollectionSettings.InvalidBranding property after the dialog closes. We could put a flag on CollectionSettingsDialog and have it pass it on to CollectionSettingsApi to tell it whether to use the CollectionSettings.InvalidBranding. Neither of those seemed obviously better to me, but perhaps one would be clearer. Essentially the CollectionSettingsApi.InvalidBranding is serving two purposes: a flag indicating that the special behavior is wanted, in a place accessible to both C# and JS, and the actual value of the desired branding which we display in the dialog.
I've added a comment which may help.
___
*[src/BloomTests/web/controllers/CollectionSettingsApiTests.cs, line 15 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKgIJA69KdWoAz_31Pn:-LKhebGN-dxvvcDEIY25:byejwuq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fce3bf5b5687a913ec301388e491567166c82492/src/BloomTests/web/controllers/CollectionSettingsApiTests.cs#L15)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Do you need to use real subscriber names here?
</blockquote></details>

Changed to all obvious fakes


<!-- Sent from Reviewable.io -->

2018-08-24 21:20 UTC, hatton requested changes
> Reviewed 2 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 32 of 36 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/Workspace/WorkspaceView.cs, line 555 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKgHp8a0Z-TIsw3EeTf:-LKhnMf1C-goztQvz8PM:b-ve0qdg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fce3bf5b5687a913ec301388e491567166c82492/src/BloomExe/Workspace/WorkspaceView.cs#L555)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It refers to any branding which is requested in the .bloomCollection file but not valid according to the current subscription code. This might be because it is a legacy subscription for which a code has not been entered, or because the code has expired. It _might_ even be because someone is trying to create his own branding.
</blockquote></details>

1) So wouldn't that be a "subscription", not a branding?
2) Why does that need to be stored in collection settings? I thought we were going to have the collectonSettings just store the current subscription code. Then at runtime we evaluate tha.


<!-- Sent from Reviewable.io -->

2018-08-24 21:24 UTC, hatton requested changes
> Reviewed 2 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 44 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685#-LKhoPov7D6TFTWbl0pm:-LKhoPov7D6TFTWbl0pn:b-wre3n7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d3594da72d9748939bb03302852e0c6df1b6da33/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L44)):*
> ```Smalltalk
> 		// in WorkspaceView that decides to run the dialog in this mode, the dialog itself, and the
> 		// React control that implements the behavior.
> 		public static string InvalidBranding { get; set; }
> ```

I don't understand why this is a property. I would expect it to be a function: 

    // determines if the current subscription code is good, expired, empty, or refers to a legacy, etc.
string SubscriptionStatus()


<!-- Sent from Reviewable.io -->

2018-08-24 21:26 UTC, hatton reviewed
> Reviewed 2 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/2685)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @hatton)



<!-- Sent from Reviewable.io -->

2018-08-24 22:22 UTC, hatton approved these changes

2018-08-24 22:40 UTC, merged