BL-7019 new comprehension question page using smart page
BloomBooks/BloomDesktop pull request #3119
Opened 2019-04-12 22:03 UTC by JohnThomson

2019-04-12 22:04 UTC, JohnThomson commented
Don't merge just yet...needs new version of bloom-player and tweak to add once it gets to npm

2019-04-16 19:09 UTC, andrew-polk requested changes
Generally looks good, but this is definitely a case where I think @hatton should have a look, too.

I did add a few comments.

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-:-LcbYHIw2xWpBHxlrw7m:b9f4rht)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LcbXF6T6WZNjeJPH6Oe:bh56zec) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
> ```
> quizv2
> ```
Any chance of this getting a semantic name?
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbX4CGBXAE1n1mzStj:-LcbX4CGBXAE1n1mzStk:b-nvq2tk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.pug#L70)):*
> ```
> Use for comprehension testing on devices.
> ```
Should this just be `Use for comprehension testing.`?
___
*[src/BloomExe/Book/Book.cs, line 2149 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbW3hSEsMLiVYoongn:-LcbW3hSEsMLiVYoongo:bc6rb26) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomExe/Book/Book.cs#L2149)):*
> ```Smalltalk
> 					continue;
> 				var destinationPath = Path.Combine(FolderPath, fileName);
> 				// Review: in other similar operations we don't overwrite an existing helper file.
> ```

Should we version our scripts with a number in the file name?


<!-- Sent from Reviewable.io -->

2019-04-24 21:02 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LdG6a0n2bqEzNLbXdAL:b-mp9049) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> quizv2
> ```
Any chance of this getting a semantic name?
</blockquote></details>

"reloaded" "back-for-more" "but-wait-theres-more"
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 5 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG7pk3An0RzlIkiHJL:-LdG7pk437no3Ju368-t:bbiulqn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L5)):*
> This is horribly unaccessible,

I think we should put the time into getting it accessible and... future-freindly-ish, since this is not UI that we can readily change. This is actual markup in the body of the book.
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 22 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG8LqDCEpzR4nYC-3U:-LdG8LqDCEpzR4nYC-3V:b2t6bqp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L22)):*
> ```Pug
> 		+standardStyles
> 			= '\n'
> 			| .quiz-style { font-size: 11pt !important;}
> ```

I don't know how these style things work and interact, but I'm surprised that the point-size would be "!important"... is that because this rule itself gets changed when the user customizes it?
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 44 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG8i05CMaFkW9ScxmU:-LdG8i05CMaFkW9ScxmV:b-6ap5ly) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L44)):*
> ```Pug
> 		//- Add Page dialog code insert localizations.
> 		//- Warning: be careful not to use the 'questions' class anywhere else! Bloom publishing expects pages whose class list contains
> 		//- 'questions' to be this one special type, and deletes them after extracting certain data to json.
> ```

Presumably it only deletes things when making some kind of backwards-compatible version of the book?


<!-- Sent from Reviewable.io -->

2019-04-24 23:57 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdGlpJD3KyPcwH7dqYx:-LdGlpJD3KyPcwH7dqYy:b-stv5gt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L45)):*
> ```Pug
> 		//- Warning: be careful not to use the 'questions' class anywhere else! Bloom publishing expects pages whose class list contains
> 		//- 'questions' to be this one special type, and deletes them after extracting certain data to json.
> 		+page('Bloom Reader Quiz', 'Use for comprehension testing.' ).questions.bloom-nonprinting#4140d100-e4c3-49c4-af05-dda5789e019b(data-page='extra').screen-only
> ```

Looks like this line got modified but not Special.less.


<!-- Sent from Reviewable.io -->

2019-04-25 13:26 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LdFG72fAHvAv10L6nXO:b-ty992x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

"reloaded" "back-for-more" "but-wait-theres-more"
</blockquote></details>

Do you mean that an abbreviation of "quiz version 2" is not sufficiently semantic to identify these new-style quiz pages, or that some of these rules  might apply to something more generic than these quiz pages, or something else? Any suggestion what name might be better?
This is the class we put on the whole new-style quiz page to restrict all the rules that are specific to it. I'm sorry but none of JohnH's suggestions make sense to me.
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbX4CGBXAE1n1mzStj:-LdFG_4Y76o_9t-OWGr4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.pug#L70)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Use for comprehension testing on devices.
> ```
Should this just be `Use for comprehension testing.`?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 5 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG7pk3An0RzlIkiHJL:-LdJf0d57zYaRATm-Lmh:b-vywklx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L5)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> This is horribly unaccessible,

I think we should put the time into getting it accessible and... future-freindly-ish, since this is not UI that we can readily change. This is actual markup in the body of the book.
</blockquote></details>

OK, back to drawing board...
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 22 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG8LqDCEpzR4nYC-3U:-LdJdADy-XDzhEKK0BHI:b4m8sej) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L22)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't know how these style things work and interact, but I'm surprised that the point-size would be "!important"... is that because this rule itself gets changed when the user customizes it?
</blockquote></details>

X-style rules are the implementation of the style that shows up as X in the cog style dialog. They are ALL ! important, to my sorrow...presumably the only way we could come up with to make sure what the user specifies in the dialog beats anything elsewhere in Bloom's various stylesheets.
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 44 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG8i05CMaFkW9ScxmU:-LdJdfdh8jB3qAbuSIMR:b-nsnao2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L44)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Presumably it only deletes things when making some kind of backwards-compatible version of the book?
</blockquote></details>

Unfortunately, no. This is existing behavior, part of the implementation of the old approach to quizzes. At least until Bloom 4.6 reaches release status and old-style quizzes are a thing of the past, pages with a class that contains 'questions' are going to get deleted in publication (and Bloom will try to turn them into json questions).
A bad decision (probably mine) but we are stuck with it for now.
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdGlpJD3KyPcwH7dqYx:-LdJe_txAb3ndSOFTyx3:b5uhhoo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L45)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this line got modified but not Special.less.
</blockquote></details>

I think you're misled by an intermediate version. This is the old-style quiz page, which in the initial commit was accidentally modified to use the new class, so I changed it back. The only change from the original is removing 'on devices' from the hint...since the new approach will allow these quizzes, too, to work in other places.
___
*[src/BloomExe/Book/Book.cs, line 2149 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbW3hSEsMLiVYoongn:-LdFH02Q6EmiQy0b9KW8:bki00v0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomExe/Book/Book.cs#L2149)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we version our scripts with a number in the file name?
</blockquote></details>

Well, that's another option. We'd at least need to check content, because we don't want a uniquely-named duplicate of the javascript every time we insert the page. The situation your strategy would benefit would be if a book already contains quiz pages with old javascript, now we add another with new JS, and the old quiz pages work better with the old javascript. Such a situation is easily handled by the maintainer of the quiz page, who can rename the javascript file if old versions of the page should keep using the old JS. On the other hand, if it's important for all versions of the page to use the updated JS, only overwriting it will work, and if we don't do that the page maintainer can't fix things.
Of course it's possible the maintainer of the quiz page didn't consider the possibility of old pages. Then the question becomes, is it more likely to work well with all using the latest code or each using the code current when it was inserted. I'm not sure of the answer, but I prefer to at least give the maintainer the possibility of achieving the desired result. So I think I still prefer the code as-is.


<!-- Sent from Reviewable.io -->

2019-04-25 14:23 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 44 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG8i05CMaFkW9ScxmU:-LdJraBpEJAAhzNXAesW:bo4oprp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L44)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Unfortunately, no. This is existing behavior, part of the implementation of the old approach to quizzes. At least until Bloom 4.6 reaches release status and old-style quizzes are a thing of the past, pages with a class that contains 'questions' are going to get deleted in publication (and Bloom will try to turn them into json questions).
A bad decision (probably mine) but we are stuck with it for now.
</blockquote></details>

This isn't making sense to me. There must be many approaches. Here are 2:
1) Include the json version, and mark the new version pages such that releases of BR 1.x can not show them.
2) Release BR 1.x so that it can recognize and convert the new version in the json it understands.


<!-- Sent from Reviewable.io -->

2019-04-25 15:32 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 44 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG8i05CMaFkW9ScxmU:-LdK76pi5oyskcpygNUh:bb2tm7m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L44)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This isn't making sense to me. There must be many approaches. Here are 2:
1) Include the json version, and mark the new version pages such that releases of BR 1.x can not show them.
2) Release BR 1.x so that it can recognize and convert the new version in the json it understands.
</blockquote></details>

ah ok, JT straightened me out here in conversation.


<!-- Sent from Reviewable.io -->

2019-04-25 15:35 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 44 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdG8i05CMaFkW9ScxmU:-LdK7nrX-4vmKgHOeviZ:b682rwb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c075e74eee1aa80cd9324e922908bac74c1c0197/src/BloomBrowserUI/templates/template books/Special/Special.pug#L44)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

ah ok, JT straightened me out here in conversation.
</blockquote></details>

3. Make BR 1.x be able to show and work with this page.


<!-- Sent from Reviewable.io -->

2019-04-25 16:16 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LdKGFMi-ADEfw4E2SCf:b-bivdl9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do you mean that an abbreviation of "quiz version 2" is not sufficiently semantic to identify these new-style quiz pages, or that some of these rules  might apply to something more generic than these quiz pages, or something else? Any suggestion what name might be better?
This is the class we put on the whole new-style quiz page to restrict all the rules that are specific to it. I'm sorry but none of JohnH's suggestions make sense to me.
</blockquote></details>

I guess I just don't like the idea of "quiz version 2" being around in code forever.
I was wondering if there was a way to name it descriptively like enhancedQuiz or customizableQuiz or something similar.


<!-- Sent from Reviewable.io -->

2019-04-25 16:28 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LdKIRbn7r6g69nXJZke:b-j07d0s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess I just don't like the idea of "quiz version 2" being around in code forever.
I was wondering if there was a way to name it descriptively like enhancedQuiz or customizableQuiz or something similar.
</blockquote></details>

Any name that doesn't contain 'question' is OK, I think even simply calling it 'quiz'. I'd be happier though with something that identified this specific type of quiz, in case there are others later.  Not knowing what it might contrast with makes it difficult. It's not significantly enhanced from the old one, except perhaps being easier to create. Nor is it very customizable, except I suppose things like font size and style. Maybe 'simple-quiz' or 'comprehension-quiz'? We can't use 'comprehension-question-quiz' because that contains 'question' and the page will get deleted.


<!-- Sent from Reviewable.io -->

2019-04-25 17:54 UTC, andrew-polk reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LdKbwoZDDU6gmMDoHyq:betz3uj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Any name that doesn't contain 'question' is OK, I think even simply calling it 'quiz'. I'd be happier though with something that identified this specific type of quiz, in case there are others later.  Not knowing what it might contrast with makes it difficult. It's not significantly enhanced from the old one, except perhaps being easier to create. Nor is it very customizable, except I suppose things like font size and style. Maybe 'simple-quiz' or 'comprehension-quiz'? We can't use 'comprehension-question-quiz' because that contains 'question' and the page will get deleted.
</blockquote></details>

Ok, you know the implications. If quizv2 is best, so be it. Not worth holding up the PR for any more.
But your description, "We can't use 'comprehension-question-quiz' because that contains 'question' and the page will get deleted." sounds like it is likely to cause problems in the future, just based on intuition...


<!-- Sent from Reviewable.io -->

2019-04-25 19:25 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LdKxL_LEYpzlGiaSzpu:brrth2z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, you know the implications. If quizv2 is best, so be it. Not worth holding up the PR for any more.
But your description, "We can't use 'comprehension-question-quiz' because that contains 'question' and the page will get deleted." sounds like it is likely to cause problems in the future, just based on intuition...
</blockquote></details>

Settled on simple-quiz


<!-- Sent from Reviewable.io -->

2019-04-25 19:31 UTC, andrew-polk approved these changes
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LdKyKRC8dAWQAg8RGHj:biu39ao) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Settled on simple-quiz
</blockquote></details>

Cool. Sorry to cause issues.

On the question causes delete thing, I see below that this is existing behavior you are working around.


<!-- Sent from Reviewable.io -->

2019-04-26 13:32 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.less, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LcbXF6T6WZNjeJPH6Od:-LdOq7UE75wchZ0YnrRb:b-51i7li) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5eebd603aa31d7c4b333791a46d7dd5f31083afa/src/BloomBrowserUI/templates/template books/Special/Special.less#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Cool. Sorry to cause issues.

On the question causes delete thing, I see below that this is existing behavior you are working around.
</blockquote></details>

np, I think your suggestion led to an improvement.


<!-- Sent from Reviewable.io -->

2019-04-26 14:10 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/quiz.js, line 1 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdOyhE62Da99trLEyQk:-LdOyhE75XZ87jL_nSaW:b-q7x0q3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dea7e913a99c2c4879911a253e675c147dc90b2e/src/BloomBrowserUI/templates/template books/Special/quiz.js#L1)):*
> ```JavaScript
> function init() {
> ```

I'm wondering, would it take much to stick with typescript for development and have the build process just plunk down the js here?


<!-- Sent from Reviewable.io -->

2019-04-26 14:18 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 3 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdOzsnl7mmNJQIy9S5v:-LdOzsnl7mmNJQIy9S5w:by2bns7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dea7e913a99c2c4879911a253e675c147dc90b2e/src/BloomBrowserUI/templates/template books/Special/Special.pug#L3)):*
> ```Pug
> include ../standard-page-mixins.pug
> 
> mixin answer
> ```

I think it would help to package all this more as a stand-alone component, rather than stuck in with other stuff under "special". But maybe we should go further, and make it a react thing... hmmm, will switch to flowdock for this.


<!-- Sent from Reviewable.io -->

2019-04-26 14:24 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 3 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdOzsnl7mmNJQIy9S5v:-LdP17vxErKdtDMtgdxb:b7tnk22) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dea7e913a99c2c4879911a253e675c147dc90b2e/src/BloomBrowserUI/templates/template books/Special/Special.pug#L3)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think it would help to package all this more as a stand-alone component, rather than stuck in with other stuff under "special". But maybe we should go further, and make it a react thing... hmmm, will switch to flowdock for this.
</blockquote></details>

Is there a limitation that things in the "special " book have to be in the same files?


<!-- Sent from Reviewable.io -->

2019-04-26 20:14 UTC, hatton reviewed
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 3 of 10 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/gulpfile.js, line 355 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQAmxID3Gl0MiV4Qfi:-LdQAmxID3Gl0MiV4Qfj:b-rrk215) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/gulpfile.js#L355)):*
> ```JavaScript
>             "markdownDistInfo"
>         ],
>         ["webpack", "translateHtmlFiles", "createXliffFiles", "specialTs"],
> ```

Wants a better name. Its neighbors here have nice verbNoun  names.
___
*[src/BloomBrowserUI/gulpfile.js, line 391 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQC_MxAacSPUJoCgim:-LdQC_MxAacSPUJoCgin:b-idbgji) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/gulpfile.js#L391)):*
> ```
>   .pipe(debug())
> ```
___
*[src/BloomBrowserUI/templates/template books/Special/quiz.pug, line 5 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQDCs60AmKeZQuT_mS:-LdQDCs60AmKeZQuT_mT:b-hlrsis) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/templates/template books/Special/quiz.pug#L5)):*
> ```Pug
> 		//- A div used as a check-box, because a regular input is hard to give the look we want.
> 		//- For accessibility, there is also a proper input element, whose value is kept in sync, but which is hidden.
> 		.quizCheck
> ```

I couldn't figure out what this empty div was supposed to do. This would help:

``
// JS intercepts clicks on this and sets the checkboxes (the custom .styleedCheckBox one AND the actual invisible input one. Notice that this works over a whole Bloom Field, not just the box itself, which is why it is a bit more complicated than checkbox-styling solutions which don't require JS.
.styled-checkbox-widget
    // This div is styled by CSS to look like a checkbox
    .styledCheckBox
    // this input widget is here for the benefit of screen readers. It is kept in sync by JS that we attach
    input...
``
___
*[src/BloomBrowserUI/templates/template books/Special/quiz.js, line 1 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdOyhE62Da99trLEyQk:-LdQGQTOD6rKu5Uteaps:b-prpjd1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dea7e913a99c2c4879911a253e675c147dc90b2e/src/BloomBrowserUI/templates/template books/Special/quiz.js#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm wondering, would it take much to stick with typescript for development and have the build process just plunk down the js here?
</blockquote></details>

this is done


<!-- Sent from Reviewable.io -->

2019-04-26 20:20 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 3 of 10 files reviewed, 7 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 2149 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQIJRpDU4CpstHWNuM:-LdQIJRpDU4CpstHWNuN:b-d5s5jv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomExe/Book/Book.cs#L2149)):*
> ```Smalltalk
> 					continue;
> 				var destinationPath = Path.Combine(FolderPath, fileName);
> 				// Review: in other similar operations we don't overwrite an existing helper file.
> ```

I think you can remove the "Review" part.

BTW, in what situation do we not "overwrite an existing helper file"?


<!-- Sent from Reviewable.io -->

2019-04-26 21:17 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 3 of 10 files reviewed, 9 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/quiz.ts, line 1 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQRe99Cp8Jxki9ACRF:-LdQRe99Cp8Jxki9ACRG:b-7ziq2m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/templates/template books/Special/quiz.ts#L1)):*
> ```XML
> function init() {
> ```

This file wants a more specific name (there will be many kinds of quizzes in the future). Maybe "SimpleComprehensionQuiz"?

Please write a file header explaining what's going on here, or that points to some other place that  you've done that. Here's what I'm guessing this does:

This file attaches to events of a SimpleComphrensionQuiz page. 
It manages the styled-checkbox-wigets, plays sounds, and sends analytics.
___
*[src/BloomBrowserUI/templates/template books/Special/quiz.ts, line 17 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQVPLS4_vX5qP47jk_:-LdQVPLS4_vX5qP47jka:b-wfudhq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/templates/template books/Special/quiz.ts#L17)):*
> ```XML
>             });
>         } else {
>             x!.parentElement!.addEventListener("click", evt => {
> ```

Would it make sense to factor out the handling of this widget, at a minimum, as its own function (if not own file)?


<!-- Sent from Reviewable.io -->

2019-04-26 21:48 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 2 of 11 files reviewed, 9 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/gulpfile.js, line 355 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQAmxID3Gl0MiV4Qfi:-LdQQavgAxOC2Z4ABBk_:bar8vio) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/gulpfile.js#L355)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Wants a better name. Its neighbors here have nice verbNoun  names.
</blockquote></details>

Changed to compileTemplateTypescript.
___
*[src/BloomBrowserUI/gulpfile.js, line 391 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQC_MxAacSPUJoCgim:-LdQQd3z2ugzxwG9Mm8J:b-hfpv0l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/gulpfile.js#L391)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> ```
>   .pipe(debug())
> ```

</blockquote></details>

removed
___
*[src/BloomBrowserUI/templates/template books/Special/quiz.pug, line 5 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQDCs60AmKeZQuT_mS:-LdQTRy95lX_axqKJ257:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/templates/template books/Special/quiz.pug#L5)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I couldn't figure out what this empty div was supposed to do. This would help:

``
// JS intercepts clicks on this and sets the checkboxes (the custom .styleedCheckBox one AND the actual invisible input one. Notice that this works over a whole Bloom Field, not just the box itself, which is why it is a bit more complicated than checkbox-styling solutions which don't require JS.
.styled-checkbox-widget
    // This div is styled by CSS to look like a checkbox
    .styledCheckBox
    // this input widget is here for the benefit of screen readers. It is kept in sync by JS that we attach
    input...
``
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/templates/template books/Special/Special.pug, line 3 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdOzsnl7mmNJQIy9S5v:-LdQUIRh0Ypmx8BnzgBf:b3jt0gd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dea7e913a99c2c4879911a253e675c147dc90b2e/src/BloomBrowserUI/templates/template books/Special/Special.pug#L3)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Is there a limitation that things in the "special " book have to be in the same files?
</blockquote></details>

I've extracted quiz.pug and quiz.less. Doing it with react sounds like a research project.
___
*[src/BloomExe/Book/Book.cs, line 2149 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQIJRpDU4CpstHWNuM:-LdQVAB77pf0Gla8j9CA:ba4vwmy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomExe/Book/Book.cs#L2149)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think you can remove the "Review" part.

BTW, in what situation do we not "overwrite an existing helper file"?
</blockquote></details>

Done. 'Helper' was perhaps not the most helpful word. In the immediately preceding code, we don't overwrite an existing image or css file that is found in a template but already present in the book.
___
*[src/BloomBrowserUI/templates/template books/Special/quiz.js, line 1 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdOyhE62Da99trLEyQk:-LdQTTnv5aFc9qKFr53-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dea7e913a99c2c4879911a253e675c147dc90b2e/src/BloomBrowserUI/templates/template books/Special/quiz.js#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

this is done
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-26 21:52 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 2 of 11 files reviewed, 8 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/gulpfile.js, line 402 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQcSoz7Z-IdT-LsVIx:-LdQcSoz7Z-IdT-LsVIy:b-t89gij) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3c0c3c96b5ad6b4f6a781c019b85ce8e0b81e137/src/BloomBrowserUI/gulpfile.js#L402)):*
> ```JavaScript
>         .src("./templates/template books/**/*.ts")
>         .pipe(tsProject())
>         .js.pipe(gulp.dest(outputDir + "/templates/template books"));
> ```

So this works to put the files in their original directories, without using the `base` parameter on `.src`, as in https://stackoverflow.com/a/44337370/723299?


<!-- Sent from Reviewable.io -->

2019-04-26 21:55 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 2 of 11 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 2149 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQIJRpDU4CpstHWNuM:-LdQd6rrEr7_pAmgxfDh:b-4vidp0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomExe/Book/Book.cs#L2149)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. 'Helper' was perhaps not the most helpful word. In the immediately preceding code, we don't overwrite an existing image or css file that is found in a template but already present in the book.
</blockquote></details>

Maybe life would be simpler for everyone if we did do that for all template files. I like your approach here. If you change some structure and don't want an auto-update, then add a number to the file name.


<!-- Sent from Reviewable.io -->

2019-04-26 22:22 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 2 of 11 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/gulpfile.js, line 402 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQcSoz7Z-IdT-LsVIx:-LdQj1bm5sbS1FHCsdNi:b-xmbrqx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3c0c3c96b5ad6b4f6a781c019b85ce8e0b81e137/src/BloomBrowserUI/gulpfile.js#L402)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So this works to put the files in their original directories, without using the `base` parameter on `.src`, as in https://stackoverflow.com/a/44337370/723299?
</blockquote></details>

Yes. I didn't realize it before, but it automatically keeps the part of the name that matches the asterisks.
___
*[src/BloomExe/Book/Book.cs, line 2149 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQIJRpDU4CpstHWNuM:-LdQjQNXD44QcbUSDM3S:bg9fi78) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomExe/Book/Book.cs#L2149)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe life would be simpler for everyone if we did do that for all template files. I like your approach here. If you change some structure and don't want an auto-update, then add a number to the file name.
</blockquote></details>

Probably makes sense. Maybe another card, though, so testing can concentrate on looking for any unexpected consequences?
___
*[src/BloomBrowserUI/templates/template books/Special/quiz.ts, line 1 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQRe99Cp8Jxki9ACRF:-LdQjB0MDQB34OH7hn7D:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/templates/template books/Special/quiz.ts#L1)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This file wants a more specific name (there will be many kinds of quizzes in the future). Maybe "SimpleComprehensionQuiz"?

Please write a file header explaining what's going on here, or that points to some other place that  you've done that. Here's what I'm guessing this does:

This file attaches to events of a SimpleComphrensionQuiz page. 
It manages the styled-checkbox-wigets, plays sounds, and sends analytics.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-04-29 16:07 UTC, hatton reviewed
> Reviewed 1 of 4 files at r3, 2 of 6 files at r5, 1 of 6 files at r6, 3 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomBrowserUI/gulpfile.js, line 389 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-Lddpi-o1cUqwl37SRdt:-Lddpi-o1cUqwl37SRdu:b8861b9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e60ec6f29121af02a8ec37e6544ef7e631aac2/src/BloomBrowserUI/gulpfile.js#L389)):*
> ```JavaScript
>     );
> });
> ```

John, will the normal webpack also try to pick up these files?


<!-- Sent from Reviewable.io -->

2019-04-29 16:27 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/templates/template books/Special/quiz.ts, line 17 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-LdQVPLS4_vX5qP47jk_:-LddqZLm2GScmn-V7A5j:b-ldkr9o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/842231b3c0898080c2fdef97d30b870a9a5c54fa/src/BloomBrowserUI/templates/template books/Special/quiz.ts#L17)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would it make sense to factor out the handling of this widget, at a minimum, as its own function (if not own file)?
</blockquote></details>

I've pulled the click handlers into their own named functions and divided the code into two sections, the code that figures out when to add the editMode class to <body> and the code related to the answer widget. I'm reluctant to separate them into distinct files. Almost all the code is in fact for the answer widget. And I don't want two js files to include from the final HTML, nor do I want to introduce the complexity of making the build process merge two files. Maybe it could be done with some sort of simple include? Still complicates things, the current  compileTemplateTypescript task will build both of them not just the master one. See what you think.


<!-- Sent from Reviewable.io -->

2019-04-29 17:37 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/gulpfile.js, line 389 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/3119#-Lddpi-o1cUqwl37SRdt:-Lde9rWeCgzlUErKaNXn:b-jtna8b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/59e60ec6f29121af02a8ec37e6544ef7e631aac2/src/BloomBrowserUI/gulpfile.js#L389)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

John, will the normal webpack also try to pick up these files?
</blockquote></details>

I don't believe so, as they aren't imported by any of the root modules.


<!-- Sent from Reviewable.io -->

2019-04-29 20:33 UTC, merged