Have Android depend on user settings for blind and sign language (BL-8995)
BloomBooks/BloomDesktop pull request #3978
Opened 2020-10-01 21:54 UTC by StephenMcConnel

Creating bloomd books through harvester were setting signLanguage as a
feature whenever a video exists in the book.  This was then getting set
in the parse table, and showing in next.blorg.  Blind and sign language
should be set only by the user when uploading.  (Talking book is still
being set automatically as a feature: it will be controlled by the user
allowing narration audio to be uploaded.)

2020-10-01 22:31 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, line 144 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978#-MIaGype9f5N14qGZ7CM:-MIaGypf-1U1z5MRY0zD:b-y9d8ea) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/729523119bcdf8f8c4951aa53a6b3fc4470f3a1f/src/BloomExe/Publish/Android/BloomReaderFileMaker.cs#L144)):*
> ```Smalltalk
> 			// See https://issues.bloomlibrary.org/youtrack/issue/BL-8995.
> 			modifiedBook.UpdateMetadataFeatures(
> 				isBlindEnabled: modifiedBook.BookInfo.MetaData.Feature_Blind,
> ```

Concerned about that this breaks the pathway for if an author has an accesible to blind book, but has never visited and has no plans to Publish to Web. He goes to Publish to BR.   We would set isBlindEnabled to false, I believe.

Steve mentioned there could be a UX solution to this (adding more checkboxes)


<!-- Sent from Reviewable.io -->

2020-10-01 22:31 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, line 144 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978#-MIaGype9f5N14qGZ7CM:-MIaHgQcAFoA1Jepv2Bi:bn623o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/729523119bcdf8f8c4951aa53a6b3fc4470f3a1f/src/BloomExe/Publish/Android/BloomReaderFileMaker.cs#L144)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Concerned about that this breaks the pathway for if an author has an accesible to blind book, but has never visited and has no plans to Publish to Web. He goes to Publish to BR.   We would set isBlindEnabled to false, I believe.

Steve mentioned there could be a UX solution to this (adding more checkboxes)
</blockquote></details>

I was wondering about checking IsHarvesterMode flag


<!-- Sent from Reviewable.io -->

2020-10-01 22:35 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, line 144 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978#-MIaGype9f5N14qGZ7CM:-MIaHxkb1W77ad9Bjg70:b-ws4l9p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/729523119bcdf8f8c4951aa53a6b3fc4470f3a1f/src/BloomExe/Publish/Android/BloomReaderFileMaker.cs#L144)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I was wondering about checking IsHarvesterMode flag
</blockquote></details>

This change is being made to a copy of meta.json created specifically for the BR book.
Whether we want to preserve the current behavior of the  code for local creation of BR books, or whether we want to provide UI on the Publish to Android screen to set the "Blind" and "Sign Language" features, or some other UI tweak are all good questions.


<!-- Sent from Reviewable.io -->

2020-10-02 16:10 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, line 144 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978#-MIaGype9f5N14qGZ7CM:-MIe3rkH2bgPuYP9RX6n:bux1qq5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/729523119bcdf8f8c4951aa53a6b3fc4470f3a1f/src/BloomExe/Publish/Android/BloomReaderFileMaker.cs#L144)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This change is being made to a copy of meta.json created specifically for the BR book.
Whether we want to preserve the current behavior of the  code for local creation of BR books, or whether we want to provide UI on the Publish to Android screen to set the "Blind" and "Sign Language" features, or some other UI tweak are all good questions.
</blockquote></details>

I've modified the code as requested.  I still think this whole area needs more work.


<!-- Sent from Reviewable.io -->

2020-10-02 16:41 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, line 144 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978#-MIaGype9f5N14qGZ7CM:-MIeAz3-Cf5zpv0u7u3M:bdo5ak) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/729523119bcdf8f8c4951aa53a6b3fc4470f3a1f/src/BloomExe/Publish/Android/BloomReaderFileMaker.cs#L144)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I've modified the code as requested.  I still think this whole area needs more work.
</blockquote></details>

I think we decided this morning that the sign language flag should NEVER be set automatically, only if the author tell us the book is sign language; and that we should make a new flag that IS set automatically to say the book contains video.


<!-- Sent from Reviewable.io -->

2020-10-02 16:44 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Publish/Android/BloomReaderFileMaker.cs, line 144 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978#-MIaGype9f5N14qGZ7CM:-MIeBRCP3czFRIu-SjNS:b-e3p8ai) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/729523119bcdf8f8c4951aa53a6b3fc4470f3a1f/src/BloomExe/Publish/Android/BloomReaderFileMaker.cs#L144)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think we decided this morning that the sign language flag should NEVER be set automatically, only if the author tell us the book is sign language; and that we should make a new flag that IS set automatically to say the book contains video.
</blockquote></details>

I agree with John, but I'm just trying to finish this issue off.  I have another issue (BL-9107) that will fix this by adding the proper UI to the Bloom Reader publish screen.  This code preserves current behaviour in the mean time.


<!-- Sent from Reviewable.io -->

2020-10-02 17:49 UTC, JohnThomson approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2020-10-02 17:49 UTC, JohnThomson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978#-:-MIeQg8T6OhMwJ5idTQA:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2020-10-02 17:50 UTC, JohnThomson approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2020-10-02 18:26 UTC, sujeffreyl approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/3978)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-02 18:26 UTC, merged