Improve error notification if UserAccessException occurs.
BloomBooks/BloomDesktop pull request #4059
Opened 2020-11-02 22:45 UTC by sujeffreyl

2020-11-03 16:27 UTC, JohnThomson reviewed
Couple of minor suggestions and one question...otherwise LGTM

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-:-MLDvqAU8tDKIIjACjDm:b-x7wcbp)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDh0gw1f-WoKh2xyBv:-MLDh0gw1f-WoKh2xyBw:bcut8gy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L58)):*
> ```Smalltalk
> 		}
> 
> 		// Assumption: Assumes that only assigned to by ShowProblemReport(), and that only one problem report happens at a time.
> ```

assigned...AFTER the thread checks and sets _showingProblemReport and thus establishes effectively locked access to it.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDhm17-nAM22dGYFBn:-MLDhm17-nAM22dGYFBo:blqv8x8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
> ```Smalltalk
> 			// This will help with not requiring locking (you only need to worry about whether this class interferes with itself and can ignore the rest of Bloom)
> 			// It also locks the reported values to their value at the time ShowProblemDialog() was invoked, which is also a nice-to-have.
> 			bool isSyncRequired = false;
> ```

Name suggests that sometimes it might not be. Maybe something like "const bool syncNotRequired = false"?
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 496 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDsO_AEn9p181m7PNk:-MLDsO_AEn9p181m7PNl:buoht4u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L496)):*
> ```Smalltalk
> 			catch (Exception error)
> 			{
> 				_takingScreenshotLock.Set();	// Release lock (Unblock others)
> ```

Is it possible for this Set and the one in the finally above to both happen? If so, is it a problem? e.g., possibly an extra Set() call subsequently allows two threads to Reset()? Or perhaps there's race condition if another thread gets in  after the first reset but before the second?


<!-- Sent from Reviewable.io -->

2020-11-03 17:21 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 58 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDh0gw1f-WoKh2xyBv:-MLE6g8VCq6_vbWsdK9j:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L58)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

assigned...AFTER the thread checks and sets _showingProblemReport and thus establishes effectively locked access to it.
</blockquote></details>

Done
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDhm17-nAM22dGYFBn:-MLE4SCc1wdb3Jznl8zH:b-9eyg0g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Name suggests that sometimes it might not be. Maybe something like "const bool syncNotRequired = false"?
</blockquote></details>

Yeah, I had a conundrum here... but I wouldn't want something like "bool syncNotRequired = false". That makes it easier to understand (maybe) at a glance when you see it passed as a function, but another view (a more accurate one) is that syncNotRequired is false, therefore sync IS required.
However, if it were clearly a const value, I could get behind it... something like "const bool kSyncNotRequired" or "const bool SYNC_NOT_REQUIRED"

Uh, with the first one, I feel like it should be a member var though, and then I need to move the comment further away from the other relevant code.

Thoughts?
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 496 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDsO_AEn9p181m7PNk:-MLE466l01lgODeVXSQi:b-j72cmq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L496)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it possible for this Set and the one in the finally above to both happen? If so, is it a problem? e.g., possibly an extra Set() call subsequently allows two threads to Reset()? Or perhaps there's race condition if another thread gets in  after the first reset but before the second?
</blockquote></details>

Looked it up. ManualResetEvents are either signaled or unsignalled... aka it's basically a boolean. There are other ones that user counter-like approaches, but ManualResetEvent is not one of them.


<!-- Sent from Reviewable.io -->

2020-11-03 18:03 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLEGLM61nLRdXqktgAA:-MLEGLM8E4H62FFFXfMX:b-jk5q7p) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L62)):*
> ```Smalltalk
> 				
> 		private static BookSelection _myBookSelection = null;
> 		private static /*readonly*/ BookSelection BookSelection
> ```

Oops, apparently changing collections calls the constructor again.  Previously, we had an instance readonly, which allows the constructor to modify it (and I guess you can call the constructor multiple times).


<!-- Sent from Reviewable.io -->

2020-11-03 18:40 UTC, JohnThomson reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 62 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLEGLM61nLRdXqktgAA:-MLEP51I2vBlIiQ-Ucx-:bnhlncn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L62)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Oops, apparently changing collections calls the constructor again.  Previously, we had an instance readonly, which allows the constructor to modify it (and I guess you can call the constructor multiple times).
</blockquote></details>

Glad you caught that.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDhm17-nAM22dGYFBn:-MLENvBk9g3qf5lZlCn2:b36667j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Yeah, I had a conundrum here... but I wouldn't want something like "bool syncNotRequired = false". That makes it easier to understand (maybe) at a glance when you see it passed as a function, but another view (a more accurate one) is that syncNotRequired is false, therefore sync IS required.
However, if it were clearly a const value, I could get behind it... something like "const bool kSyncNotRequired" or "const bool SYNC_NOT_REQUIRED"

Uh, with the first one, I feel like it should be a member var though, and then I need to move the comment further away from the other relevant code.

Thoughts?
</blockquote></details>

I like kSyncNotRequired.
Yet another option is to use named arguments where it's called, so each call explicitly says syncRequired=false. Proof tools don't like it when it's not required, but it makes the meaning clear. However, the definition of the constant could conveniently be put with the main comment that explains why every API MUST be kSyncNotRequired.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 496 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDsO_AEn9p181m7PNk:-MLEOWc05hedLwSI4Hvv:b-trkh5a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L496)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Looked it up. ManualResetEvents are either signaled or unsignalled... aka it's basically a boolean. There are other ones that user counter-like approaches, but ManualResetEvent is not one of them.
</blockquote></details>

That just leaves the race condition that the block running on the UI thread resets, then some other thread sets before that original thread catch resets. Since I can't see how an exception can happen in the original thread at all, much less after the UI thread completes, I suppose that's safe enough.


<!-- Sent from Reviewable.io -->

2020-11-03 21:13 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDhm17-nAM22dGYFBn:-MLEw8pb4cb7bHYUum9D:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I like kSyncNotRequired.
Yet another option is to use named arguments where it's called, so each call explicitly says syncRequired=false. Proof tools don't like it when it's not required, but it makes the meaning clear. However, the definition of the constant could conveniently be put with the main comment that explains why every API MUST be kSyncNotRequired.
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 496 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLDsO_AEn9p181m7PNk:-MLEwA1UDHGRG6cxmAD2:b-yujadr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5db290395522b245fa215686101a170bf28844d8/src/BloomExe/web/controllers/ProblemReportApi.cs#L496)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That just leaves the race condition that the block running on the UI thread resets, then some other thread sets before that original thread catch resets. Since I can't see how an exception can happen in the original thread at all, much less after the UI thread completes, I suppose that's safe enough.
</blockquote></details>

Hmm... part of your comment didn't make sense to me, so I was thinking about the code harder, and then realized 1) ShowProblemReport ought to wait before resetting and 2) I don't think this is the best synchronization class for it, cuz ResetEvetns are about "thread synchronization" but I think what I want is controlling access to a "shared resource", so I switched to Semaphore, and 3) theoretically it'd be better if the API call to get the screenshot prevented others from modifying it.


<!-- Sent from Reviewable.io -->

2020-11-03 21:19 UTC, JohnThomson reviewed
LGTM. Do you think @andrew-polk should also take a look?

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-:-MLEy_QxEPH6Ayele9Fo:b53ya4d)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-03 21:34 UTC, andrew-polk reviewed
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 65 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLEzT_GE2DEYmos8iJW:-MLEzT_GE2DEYmos8iJX:b-mu6gwa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/50101219e38d3b04b3b910ffe56217a45086e41f/src/BloomExe/web/controllers/ProblemReportApi.cs#L65)):*
> ```
> That's what will the ReportInfo class is here for
> ```
typo
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 68 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLEz_Cm26YWFfV6brKb:-MLEz_Cm26YWFfV6brKc:b-k7svm5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/50101219e38d3b04b3b910ffe56217a45086e41f/src/BloomExe/web/controllers/ProblemReportApi.cs#L68)):*
> ```Smalltalk
> 		// This will help with not requiring locking (you only need to worry about whether this class interferes with itself and can ignore the rest of Bloom)
> 		// It also locks the reported values to their value at the time ShowProblemDialog() was invoked, which is also a nice-to-have.
> 		const bool kSyncNotRequired = false;	// False value means that sync is not required.
> ```

This is too confusing.

How about either `kSyncRequired = false;` which you probably already decided against or something like
`kFalseValueForSyncRequired = false;`?
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 386 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLF-gsB7EjYTL0SfVlp:-MLF-gsB7EjYTL0SfVlq:b4j0wqr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/50101219e38d3b04b3b910ffe56217a45086e41f/src/BloomExe/web/controllers/ProblemReportApi.cs#L386)):*
> ```
> var bestBookName = _bookSelection.CurrentSelection?.TitleBestForUserDisplay;
> ```
var bestBookName = book?.TitleBestForUserDisplay;
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 563 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLF0PJ06eUrcczLwnFy:-MLF0PJ06eUrcczLwnFz:b-dyip4b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/50101219e38d3b04b3b910ffe56217a45086e41f/src/BloomExe/web/controllers/ProblemReportApi.cs#L563)):*
> ```Smalltalk
> 		private static string GetObfuscatedEmail(string userEmail = "")
> 		{
> 			var email = string.IsNullOrWhiteSpace(userEmail) ? userEmail : _reportInfo?.UserEmail;
> ```

This logic is backwards.


<!-- Sent from Reviewable.io -->

2020-11-05 18:33 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 65 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLEzT_GE2DEYmos8iJW:-MLF6UST86HFLFXk2cwZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/50101219e38d3b04b3b910ffe56217a45086e41f/src/BloomExe/web/controllers/ProblemReportApi.cs#L65)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> That's what will the ReportInfo class is here for
> ```
typo
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 68 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLEz_Cm26YWFfV6brKb:-MLF6uoIAzMV9CX4tKHB:b-rhqbwe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/50101219e38d3b04b3b910ffe56217a45086e41f/src/BloomExe/web/controllers/ProblemReportApi.cs#L68)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is too confusing.

How about either `kSyncRequired = false;` which you probably already decided against or something like
`kFalseValueForSyncRequired = false;`?
</blockquote></details>

It's supposed to be akin to defining const INFINITE = -1;
JT thinks the original way is confusing, but seems like you like the original convention better.

I think I just go for named parameters...
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 386 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLF-gsB7EjYTL0SfVlp:-MLF6Gw20D3WOOTU9RZR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/50101219e38d3b04b3b910ffe56217a45086e41f/src/BloomExe/web/controllers/ProblemReportApi.cs#L386)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> var bestBookName = _bookSelection.CurrentSelection?.TitleBestForUserDisplay;
> ```
var bestBookName = book?.TitleBestForUserDisplay;
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 563 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLF0PJ06eUrcczLwnFy:-MLF6Q7Q5jQNGjTfQJl1:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/50101219e38d3b04b3b910ffe56217a45086e41f/src/BloomExe/web/controllers/ProblemReportApi.cs#L563)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This logic is backwards.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-05 18:47 UTC, andrew-polk reviewed
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-10 23:22 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 4 of 13 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/Utils/BloomUnauthorizedAccessException.cs, line 7 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLoSp-NEaTLpHgJnrg3:-MLoSp-NEaTLpHgJnrg4:b-fnffd9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64ca34ba5d2953b98fd06db4c280c79edbd81e73/src/BloomExe/Utils/BloomUnauthorizedAccessException.cs#L7)):*
> ```Smalltalk
> using System.Security.AccessControl;
> 
> namespace Bloom.Utils
> ```

Open to feedback about the namespace (directory) it should go in.


<!-- Sent from Reviewable.io -->

2020-11-10 23:34 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/BloomServer.cs, line 1376 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLoUSQMBiOqBBnSqTxb:-MLoUSQMBiOqBBnSqTxc:bgwxg56) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e630302bc18cbad5c359d32c108149c9cd97c2/src/BloomExe/web/BloomServer.cs#L1376)):*
> ```Smalltalk
> 		/// the current thread is a server thread. This method will check for that.
> 		/// </summary>
> 		internal void RegisterThreadBlocking()
> ```

Wondering if "LeavingServerThreadPool" (and matching "RejoiningServerThreadPool") would capture what these do better? We're keeping track not exactly of blocking, but of being somehow no longer available in the pool of threads that can service BloomServer requests.


<!-- Sent from Reviewable.io -->

2020-11-11 19:00 UTC, andrew-polk requested changes
How did you decide when to do
`throw new BloomUnauthorizedAccessException(path, e);`
and when to do
`BookStorage.ShowAccessDeniedErrorReport(e);`
?

> Reviewed 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-:-MLsf4NW8JtRbco20LX7:b4q5u7u)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookStorage.cs, line 1783 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLsfL-o7VL8TLBX1ktN:-MLsfL-o7VL8TLBX1ktO:bbv31d5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64ca34ba5d2953b98fd06db4c280c79edbd81e73/src/BloomExe/Book/BookStorage.cs#L1783)):*
> ```Smalltalk
> 		}
> 
> 		internal static void ShowAccessDeniedErrorReport(UnauthorizedAccessException noAccessError)
> ```

Please add some comments helping future me know why I would choose this method vs ShowAccessDeniedErrorHtml.
___
*[src/BloomExe/Book/BookStorage.cs, line 1801 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLseddC8NM1ZSveIVAA:-MLseddC8NM1ZSveIVAB:b-adsk6e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64ca34ba5d2953b98fd06db4c280c79edbd81e73/src/BloomExe/Book/BookStorage.cs#L1801)):*
> ```
> showSendReport=false
> ```
Should be true, methinks.

Not sure of the implementation details here. How hard would it be to have a non MessageBox with no report button?


<!-- Sent from Reviewable.io -->

2020-11-12 14:44 UTC, sujeffreyl commented
@andrew-polk , I throw BloomUnauthorizedAccessException as close as possible to the method that directly causes the original exception. Basically, I'm just trying to replace the original exception with the wrapped exception. Code flow wise, it's not supposed to change much but the error message/stack trace.

ShowAccessDeniedErrorReport is placed where I would actually want to handle UnauthorizedAccessException (even if I hadn't wrapped it). This is usually at the conceptual level of a try/catch around Save, SavePage, that kind of thing.
(Uhm, I did also give some consideration to how many references each function had when going up the call stack). So, if a relevant function in the call stack has 57 references, but calls a submethod that only has a couple references, I would rather put it inside this function wrapping this submethod, rather than in this function's 57 callers wrapping this function.

2020-11-12 14:52 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 4 of 13 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/BloomServer.cs, line 1376 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLoUSQMBiOqBBnSqTxb:-MLwvsgA6IUv1RK0dfpP:blxocbu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e630302bc18cbad5c359d32c108149c9cd97c2/src/BloomExe/web/BloomServer.cs#L1376)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Wondering if "LeavingServerThreadPool" (and matching "RejoiningServerThreadPool") would capture what these do better? We're keeping track not exactly of blocking, but of being somehow no longer available in the pool of threads that can service BloomServer requests.
</blockquote></details>

We had some discussion about this. I do think that this is actually tracking blocking threads right now. However, my ruminations about thumbnail generation might not be (or might? See isRecursiveRequest... not sure if this recursive request is blocking cuz it needs to spin up a browser thing or just takes a while). But I figured I'd just delete my thumbnail generation ruminations, and then I think it is accurate to say that this tracks whether the thread is about to block or not.


<!-- Sent from Reviewable.io -->

2020-11-12 14:59 UTC, andrew-polk requested changes
> Reviewed 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 8 of 13 files reviewed, 4 unresolved discussions (waiting on @andrew-polk, @JohnThomson, and @sujeffreyl)



<!-- Sent from Reviewable.io -->

2020-11-12 15:02 UTC, sujeffreyl reviewed
I throw BloomUnauthorizedAccessException as close as possible to the method that directly causes the original exception. Basically, I'm just trying to replace the original exception with the wrapped exception. Code flow wise, it's not supposed to change much but the error message/stack trace.

ShowAccessDeniedErrorReport is placed where I would actually want to handle UnauthorizedAccessException (even if I hadn't wrapped it). This is usually at the conceptual level of a try/catch around Save, SavePage, that kind of thing.
(Uhm, I did also give some consideration to how many references each function had when going up the call stack). So, if a relevant function in the call stack has 57 references, but calls a submethod that only has a couple references, I would rather put it inside this function wrapping this submethod, rather than in this function's 57 callers wrapping this function.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-:-MLwyaOOCOcicUTNq6D8:b-z2f4mp)* status: 8 of 13 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 1783 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLsfL-o7VL8TLBX1ktN:-MLwyW-E4lMY3VANRmpT:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64ca34ba5d2953b98fd06db4c280c79edbd81e73/src/BloomExe/Book/BookStorage.cs#L1783)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Please add some comments helping future me know why I would choose this method vs ShowAccessDeniedErrorHtml.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookStorage.cs, line 1801 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLseddC8NM1ZSveIVAA:-MLwyTUh6IjORxpD79yp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64ca34ba5d2953b98fd06db4c280c79edbd81e73/src/BloomExe/Book/BookStorage.cs#L1801)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> showSendReport=false
> ```
Should be true, methinks.

Not sure of the implementation details here. How hard would it be to have a non MessageBox with no report button?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-12 15:03 UTC, andrew-polk requested changes
> Reviewed 5 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomExe/Book/BookStorage.cs, line 1801 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLseddC8NM1ZSveIVAA:-MLwyrWU64cGsj_s6NqZ:bd36wvt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64ca34ba5d2953b98fd06db4c280c79edbd81e73/src/BloomExe/Book/BookStorage.cs#L1801)):*
Probably because of the confusion I apparently created by not publishing my comments earlier, you missed responding to 
> Not sure of the implementation details here. How hard would it be to have a non MessageBox with no report button?


<!-- Sent from Reviewable.io -->

2020-11-12 16:26 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookStorage.cs, line 1801 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLseddC8NM1ZSveIVAA:-MLxGEtfCgPxM0yAzHdJ:b-slx4wy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/64ca34ba5d2953b98fd06db4c280c79edbd81e73/src/BloomExe/Book/BookStorage.cs#L1801)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably because of the confusion I apparently created by not publishing my comments earlier, you missed responding to 
> Not sure of the implementation details here. How hard would it be to have a non MessageBox with no report button?
</blockquote></details>

We discussed. This is ok until the winforms modal gets replaced.


<!-- Sent from Reviewable.io -->

2020-11-16 16:57 UTC, JohnThomson requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Utils/BloomUnauthorizedAccessException.cs, line 73 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGwqGy2deFEU7flvrM:-MMGwqGy2deFEU7flvrN:b-mf5n88) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/Utils/BloomUnauthorizedAccessException.cs#L73)):*
> ```Smalltalk
> 			{
> 				// Check its containing directory instead.
> 				string dirName = Path.GetDirectoryName(path);
> ```

Is it worth turning this into a loop? For example, perhaps we intended CreateDirectory to create several levels of subdirectory, which it will normally do, but the parent existing directory doesn't allow it.
___
*[src/BloomExe/web/BloomApiHandler.cs, line 174 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGxOSEAg38D08wGkyU:-MMGxOSEAg38D08wGkyV:bk3q0bj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/web/BloomApiHandler.cs#L174)):*
> ```Smalltalk
> 						try						
> 						{
> 							// Try to acquire lock
> ```

Worth adding "blocks until it either succeeds (lockAcquired will then always be true) or throws (lockAcquired will stay false)?
___
*[src/BloomExe/web/BloomServer.cs, line 1376 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MLoUSQMBiOqBBnSqTxb:-MMGxmuSDnECgcacP48V:b1t4z7b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/14e630302bc18cbad5c359d32c108149c9cd97c2/src/BloomExe/web/BloomServer.cs#L1376)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

We had some discussion about this. I do think that this is actually tracking blocking threads right now. However, my ruminations about thumbnail generation might not be (or might? See isRecursiveRequest... not sure if this recursive request is blocking cuz it needs to spin up a browser thing or just takes a while). But I figured I'd just delete my thumbnail generation ruminations, and then I think it is accurate to say that this tracks whether the thread is about to block or not.
</blockquote></details>

I can live with the existing names, since I failed to convince anyone mine are better :-)
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGyH3B0TXyf3tXOkiv:-MMGyH3CEVLdLDxkJdDJ:bh99alc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
> ```Smalltalk
> 				{
> 					request.ReplyWithText(_reportInfo.Heading ?? "");
> 				}, false, requiresSync: false);
> ```

Here's a new idea: how about giving BloomApiHandler a new method something like "RegisterWithApiHandlerUsedByOtherApiHandlers" which would call the existing one, but always with requiresSync false (so, it doesn't take that argument itself at all). It would pop up as an auto-suggest whenever looking for RegisterWithApiHandler, and possibly help remind people to use it if the API being registered could result in a recursive call?
Not required, just an idea to see if it appeals.


<!-- Sent from Reviewable.io -->

2020-11-16 22:51 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Utils/BloomUnauthorizedAccessException.cs, line 73 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGwqGy2deFEU7flvrM:-MMHWdj28miflaH3m5YD:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/Utils/BloomUnauthorizedAccessException.cs#L73)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it worth turning this into a loop? For example, perhaps we intended CreateDirectory to create several levels of subdirectory, which it will normally do, but the parent existing directory doesn't allow it.
</blockquote></details>

Done.
___
*[src/BloomExe/web/BloomApiHandler.cs, line 174 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGxOSEAg38D08wGkyU:-MMHXB5d7_5xhbOc-uMC:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/web/BloomApiHandler.cs#L174)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Worth adding "blocks until it either succeeds (lockAcquired will then always be true) or throws (lockAcquired will stay false)?
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGyH3B0TXyf3tXOkiv:-MMIFSvp7VERj0p_f1ly:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Here's a new idea: how about giving BloomApiHandler a new method something like "RegisterWithApiHandlerUsedByOtherApiHandlers" which would call the existing one, but always with requiresSync false (so, it doesn't take that argument itself at all). It would pop up as an auto-suggest whenever looking for RegisterWithApiHandler, and possibly help remind people to use it if the API being registered could result in a recursive call?
Not required, just an idea to see if it appeals.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-16 22:54 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGyH3B0TXyf3tXOkiv:-MMIG4AQ5iqKN4fOU4O_:bny5alq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done. You can see if you like it better than having requiresSync: false explicitly.


<!-- Sent from Reviewable.io -->

2020-11-16 23:32 UTC, andrew-polk approved these changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2020-11-16 23:46 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2020-11-17 20:20 UTC, JohnThomson approved these changes
LGTM...any further input from Andrew?

> Reviewed 1 of 4 files at r4, 4 of 9 files at r5, 5 of 5 files at r7, 1 of 3 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-:-MMMrG4t5y8EHDxh3XYu:b-1gidc9)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGyH3B0TXyf3tXOkiv:-MMMr-Qe6zkqU-9e0dLA:b-1m8t65) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Done. You can see if you like it better than having requiresSync: false explicitly.
</blockquote></details>

I think so...do you? How about @andrew-polk ?


<!-- Sent from Reviewable.io -->

2020-11-17 21:00 UTC, andrew-polk approved these changes
Nope. Thanks for all your help on this.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-:-MMN-T0702J7H2WudpOT:bjq1jhd)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 105 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-MMGyH3B0TXyf3tXOkiv:-MMN-PX77A72TDgbHype:bh943f3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/154a5a1f7c2c16bfe24d088e057a464e6a35314d/src/BloomExe/web/controllers/ProblemReportApi.cs#L105)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think so...do you? How about @andrew-polk ?
</blockquote></details>

Yes, looks good.


<!-- Sent from Reviewable.io -->

2020-11-17 21:01 UTC, andrew-polk approved these changes
Was going to merge but has a conflict.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-:-MMN-o3i-fklHDCNUbcB:bm8et1p)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2020-11-17 23:21 UTC, sujeffreyl reviewed
Rebased on top of master, fixed a merge conflict, and force pushed.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059#-:-MMNVt4zDXn5cojtaFWD:bxqfh9i)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)



<!-- Sent from Reviewable.io -->

2020-11-17 23:42 UTC, andrew-polk approved these changes
> Reviewed 3 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4059)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2020-11-17 23:42 UTC, merged