[4.9] BL-8073 regularize focus code
BloomBooks/BloomDesktop pull request #4107
Opened 2020-12-07 22:24 UTC by gmartin7

* box-header-off was causing the wrong text box
   to get focus
* Don't have Talking Book Tool hide source bubbles

2020-12-07 22:49 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 155 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107#-MNzMFh4BT6q3T_F-tS8:-MNzMFh4BT6q3T_F-tS9:b-61w8lo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/39e8e7ec51a9ad90ecdd2df93428bd2311f3008b/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L155)):*
> ```XML
>     }
> 
>     private focusFirstVisibleElement(activeElement: HTMLElement) {
> ```

Let's rename to focusFirstVisibleEditable instead of Element
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 222 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107#-MNzNihw9Kd1ZNq6LA8e:-MNzNihw9Kd1ZNq6LA8f:bbz3cyc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/39e8e7ec51a9ad90ecdd2df93428bd2311f3008b/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L222)):*
> ```
> } else {
> ```
Just wanted to double-check... this is necessary to fix some known case?

I'd rather not have this code here if possible, because it's slightly outside the scope of responsibility i'd like turnOnBubbleEditing to have.
If it is necessary, maybe we can change it to only call focus() if nothing is currently focused. I think it should be possible?


<!-- Sent from Reviewable.io -->

2020-12-07 23:04 UTC, andrew-polk reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2020-12-08 17:59 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 155 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107#-MNzMFh4BT6q3T_F-tS8:-MO2K_dV2zjnGaWs-9xd:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/39e8e7ec51a9ad90ecdd2df93428bd2311f3008b/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L155)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Let's rename to focusFirstVisibleEditable instead of Element
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 222 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107#-MNzNihw9Kd1ZNq6LA8e:-MO2UKiM4_6D5zjsFDJ9:b-bx1l3a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/39e8e7ec51a9ad90ecdd2df93428bd2311f3008b/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L222)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> } else {
> ```
Just wanted to double-check... this is necessary to fix some known case?

I'd rather not have this code here if possible, because it's slightly outside the scope of responsibility i'd like turnOnBubbleEditing to have.
If it is necessary, maybe we can change it to only call focus() if nothing is currently focused. I think it should be possible?
</blockquote></details>

Yes it's necessary. If Comic tool is open, and there are no textOverPicture elements on this page, we can end up with no text box focused. I tried checking for an `activeElement` before calling the focus code, but in this `else` path for some reason, the document's activeElement is set to the `body` element!


<!-- Sent from Reviewable.io -->

2020-12-08 18:11 UTC, sujeffreyl reviewed
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2020-12-08 18:12 UTC, sujeffreyl approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4107)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2020-12-08 18:12 UTC, merged