Get book languages from book itself, not the collection (BL-9449)
BloomBooks/BloomDesktop pull request #4166
Opened 2021-02-01 18:29 UTC by StephenMcConnel

This redirects accessing the book languages.  It does nothing about
setting the book languages apart from changing the collection settings.
That would be a separate issue.

2021-02-01 18:55 UTC, andrew-polk commented
___
*[src/BloomExe/Book/Book.cs, line 383 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSTwPYx9zY_8_CQOEQY:-MSTwPYx9zY_8_CQOEQZ:b-6lxajc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d175428253198a10be56269c87e9aef2c07acb40/src/BloomExe/Book/Book.cs#L383)):*
In the card, JH suggested this:
> Probably you will want to create another layer of wrapping that calls GetLanguage, so that you can just say
> ```
> TranslationGroupManager.UpdateContentLanguageClasses(dom.RawDom, CollectionSettings, Language1.Iso639Code, _bookData.MultilingualContentLanguage2,
> 													 _bookData.MultilingualContentLanguage3);
> BookInfo.IsRtl = Language1.IsRightToLeft;
> ```

Did you decide against that for some reason?


<!-- Sent from Reviewable.io -->

2021-02-01 19:05 UTC, andrew-polk commented
___
*[src/BloomExe/Book/Book.cs, line 383 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSTwPYx9zY_8_CQOEQY:-MSTz0RPCYxXLoI_qYdq:b-662fta) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d175428253198a10be56269c87e9aef2c07acb40/src/BloomExe/Book/Book.cs#L383)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In the card, JH suggested this:
> Probably you will want to create another layer of wrapping that calls GetLanguage, so that you can just say
> ```
> TranslationGroupManager.UpdateContentLanguageClasses(dom.RawDom, CollectionSettings, Language1.Iso639Code, _bookData.MultilingualContentLanguage2,
> 													 _bookData.MultilingualContentLanguage3);
> BookInfo.IsRtl = Language1.IsRightToLeft;
> ```

Did you decide against that for some reason?
</blockquote></details>

Seems like it would also be useful to have those props on BookData itself.


<!-- Sent from Reviewable.io -->

2021-02-01 22:56 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166)* status: 0 of 42 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Book/Book.cs, line 383 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSTwPYx9zY_8_CQOEQY:-MSUTRme6pERbDTJqvUo:b63zh5c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d175428253198a10be56269c87e9aef2c07acb40/src/BloomExe/Book/Book.cs#L383)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like it would also be useful to have those props on BookData itself.
</blockquote></details>

No, I just didn't notice the comment in the issue.  I'm adding these properties to BookData (using the => operator to invoke the proper call to GetLanguage).


<!-- Sent from Reviewable.io -->

2021-02-02 00:14 UTC, andrew-polk requested changes
> Reviewed 28 of 42 files at r1, 17 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166)* status: all files reviewed, 7 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomExe/Book/BookData.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSTxoRL7Rdjt3P5VqHa:-MSTxoRL7Rdjt3P5VqHb:b-yzo33o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d175428253198a10be56269c87e9aef2c07acb40/src/BloomExe/Book/BookData.cs#L77)):*
> ```Smalltalk
> 		/// data-xmatter-page="frontCover" data-backgroundaudio="SoundTrack0.mp3" data-backgroundaudiovolume="0.5717869999999999"
> 		/// lang=""&gt;
> 		/// </summary>
> ```

These changes in the summary seem unhelpful.
___
*[src/BloomExe/Book/BookData.cs, line 746 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSUzoL_72h6ZZHkcN-z:-MSUzoL_72h6ZZHkcN0-:b-8joz6m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/Book/BookData.cs#L746)):*
> ```Smalltalk
> 			var data = new DataSet();
> 
> 			// REVIEW BL-9449: still collect language settings from CollectionSettings originally?
> ```

I think I saw you added a bunch of notes in the card about places we still use collection settings. 
Do those notes cover all these REVIEW BL-9449 notes?
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 480 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV4ZJ71Kv0rX1_T4pe:-MSV4ZJ71Kv0rX1_T4pf:brls7c4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/CollectionTab/LibraryListView.cs#L480)):*
> ```Smalltalk
> 				// Maybe in this context we can rely on the collection settings for the languages?
> 				var bookData = new BookData(new HtmlDom("<html><body></body></html>"), _model.CollectionSettings, null);
> 				var bestTitle = bookInfo.GetBestTitleForUserDisplay(bookData);
> ```

I don't like this or the same code in ToolBoxView (creating a dummy dom).
Do we have any other options?
___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 88 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV04nyABcnqOz_EWA3:-MSV04nyABcnqOz_EWA4:bd1c3n1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/CollectionTab/LibraryModel.cs#L88)):*
> ```Smalltalk
> 		public string LanguageName
> 		{
> 			get { return _bookSelection.CurrentSelection.GetLanguage(LanguageSlot.Language1).Name; }
> ```

Maybe you've done some analysis I'm not seeing, but this seems wrong. 
Why would we want the collection model to give LanguageName of whichever book happens to be selected? What if no book is selected?
___
*[src/BloomExe/Edit/EditingModel.cs, line 395 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV0XZb11wadENGJysk:-MSV0XZb11wadENGJysl:biwi1qg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/Edit/EditingModel.cs#L395)):*
> ```Smalltalk
> 				if (_contentLanguages.Count() == 0)
> 				{
> 					_contentLanguages.Add(new ContentLanguage(_bookSelection.CurrentSelection.GetLanguage(LanguageSlot.Language1)) { Locked = true, Selected = true });
> ```

Is it worth adding the Language1, etc. shorthands on Book, too?
Or maybe just use Book.BookData.LanguageX for all these?
___
*[src/BloomTests/Book/BookStarterTests.cs, line 31 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV3HFGEcnibjShj0TX:-MSV3HFGEcnibjShj0TY:bsgp44o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomTests/Book/BookStarterTests.cs#L31)):*
> ```Smalltalk
> 		private TemporaryFolder _projectFolder;
> 		private CollectionSettings _librarySettings;
> 		private CollectionSettings _collectionSettings; // and a few tests need a real one
> ```

After making both of these "real" (not mock), I think we would benefit from better comments.
Particularly, why are there two with different values?


<!-- Sent from Reviewable.io -->

2021-02-02 17:29 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/BookData.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSTxoRL7Rdjt3P5VqHa:-MSYMOHh9nMCH_H05dWZ:bjvn9ly) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d175428253198a10be56269c87e9aef2c07acb40/src/BloomExe/Book/BookData.cs#L77)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These changes in the summary seem unhelpful.
</blockquote></details>

They may not be helpful in reading the comment directly in the code, but they're essential for Intellisense to display the summary comment.
___
*[src/BloomExe/Book/BookData.cs, line 746 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSUzoL_72h6ZZHkcN-z:-MSYRx0qDHRUzu8Non_H:b-rkxb75) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/Book/BookData.cs#L746)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think I saw you added a bunch of notes in the card about places we still use collection settings. 
Do those notes cover all these REVIEW BL-9449 notes?
</blockquote></details>

Done.  I added a couple of comments to the issue and removed all the REVIEW BL-9449 comments from the code.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 480 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV4ZJ71Kv0rX1_T4pe:-MSYYbAg2-eveOYjd6D4:b-2ymfux) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/CollectionTab/LibraryListView.cs#L480)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't like this or the same code in ToolBoxView (creating a dummy dom).
Do we have any other options?
</blockquote></details>

I'm not thrilled with this either, but without the dummy dom, null object exceptions get thrown.
I suppose we could go through BookData and handle having a null object, but that would be a rather major reworking of BookData since it assumes that _dataDiv either exists or can easily be created.  I'd rather explicitly create a dummy dom in the caller than inside the BookData code.  But I think we have to create a dummy dom in one location or the other.  If you prefer to do so in BookData.GetOrCreateDataDiv(), I can live with that.
___
*[src/BloomExe/CollectionTab/LibraryModel.cs, line 88 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV04nyABcnqOz_EWA3:-MSYaW3n8cP-4p2ywXxe:b-tjsjbv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/CollectionTab/LibraryModel.cs#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe you've done some analysis I'm not seeing, but this seems wrong. 
Why would we want the collection model to give LanguageName of whichever book happens to be selected? What if no book is selected?
</blockquote></details>

I think you're right that the collection tab / library model should still use the collection settings.
___
*[src/BloomExe/Edit/EditingModel.cs, line 395 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV0XZb11wadENGJysk:-MSYbUttE90N4vtB0pwH:byasepw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/Edit/EditingModel.cs#L395)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it worth adding the Language1, etc. shorthands on Book, too?
Or maybe just use Book.BookData.LanguageX for all these?
</blockquote></details>

I think I prefer having the shorthands on BookData.  I just missed these on my big edit yesterday.  It looks like I may have missed some other places as well.
___
*[src/BloomTests/Book/BookStarterTests.cs, line 31 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV3HFGEcnibjShj0TX:-MSYmUIe9q7Ih-IZhkZ5:b-y57qa0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomTests/Book/BookStarterTests.cs#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

After making both of these "real" (not mock), I think we would benefit from better comments.
Particularly, why are there two with different values?
</blockquote></details>

I added a couple of comments.  Whether they're totally satisfying is another question...


<!-- Sent from Reviewable.io -->

2021-02-02 17:55 UTC, andrew-polk requested changes
> Reviewed 15 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 480 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV4ZJ71Kv0rX1_T4pe:-MSYrFSC03FT1DUrjc5k:bw9ytqf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/CollectionTab/LibraryListView.cs#L480)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I'm not thrilled with this either, but without the dummy dom, null object exceptions get thrown.
I suppose we could go through BookData and handle having a null object, but that would be a rather major reworking of BookData since it assumes that _dataDiv either exists or can easily be created.  I'd rather explicitly create a dummy dom in the caller than inside the BookData code.  But I think we have to create a dummy dom in one location or the other.  If you prefer to do so in BookData.GetOrCreateDataDiv(), I can live with that.
</blockquote></details>

No, I don't like creating a BookData object with a null HtmlDom any better. One concern I have is that if you start creating these incomplete BookData objects just to be a container for language settings, someone will invariably try to use one of those incomplete objects for another reason and end up with odd bugs.

A full solution would be to extract an interface which gets passed in these places where all we really need are the language settings and have both BookData and some new simple object implement it. But that is probably overkill.

Thoughts, @stephenmcconnel?
Thoughts, @hatton?
___
*[src/BloomTests/Book/BookStarterTests.cs, line 31 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV3HFGEcnibjShj0TX:-MSYocsd28AlRsRY1oEo:b-jem1r3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomTests/Book/BookStarterTests.cs#L31)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I added a couple of comments.  Whether they're totally satisfying is another question...
</blockquote></details>

Thanks. How about removing `// and a few tests need a real one` from this line?
And can we now have better names for the variables?
_collectionSettings/_defaultCollectionSettings and _alternateCollectionSettings? or something else?


<!-- Sent from Reviewable.io -->

2021-02-02 18:09 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 480 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSV4ZJ71Kv0rX1_T4pe:-MSYv7O58qBfmWMpxKAm:bjhnw0e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7bb40f95976cb1272a67a9771c0398cefc53a0b1/src/BloomExe/CollectionTab/LibraryListView.cs#L480)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

No, I don't like creating a BookData object with a null HtmlDom any better. One concern I have is that if you start creating these incomplete BookData objects just to be a container for language settings, someone will invariably try to use one of those incomplete objects for another reason and end up with odd bugs.

A full solution would be to extract an interface which gets passed in these places where all we really need are the language settings and have both BookData and some new simple object implement it. But that is probably overkill.

Thoughts, @stephenmcconnel?
Thoughts, @hatton?
</blockquote></details>

I had thought of defining an interface implemented by both CollectionSettings and BookData for obtaining the set of languages.  An alternative simple class that can be initialized from an instance of CollectionSettings might be a better approach.


<!-- Sent from Reviewable.io -->

2021-02-02 23:03 UTC, JohnThomson requested changes
I've made some local comments. But globally, my main observation is that there are probably a dozen or more places where we do something along the lines X(lang1); if (lang2 exists and is different) X(lang2); if (lang3 exists and is different from both) X(lang3). This is going to be horrible when we add a few more (LanguageSlot.MainTitle; LanguageSlot.SecondaryTitle; LanguageSlot.Credits...). Could we give BookData one or two methods that return lists of all the book languages (without duplicates, and prioritized in whatever ways we need), and use them to simplify these bits of code now as well as removing the need to change them when we add more members to the enumeration?
Of course each needs some thought as to whether it really wants to use all the book's languages. But even if we turn out to be wrong, at least doing this we will be identifying, by using these methods, the places which currently loop over all the languages the book has, so it will be easy to consider whether they still should when there might be more.

My other general thought is that we should compare before and after unit-test runtimes, to see if we are paying a high price for making test BookData's with real HTML DOMs. If so, we might want to think about mocking them.

> Reviewed 11 of 42 files at r1, 12 of 17 files at r2, 14 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-:-MSZwzl93hCjjwtdmPEW:b-f4obb5)* status: all files reviewed, 22 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 234 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZwdgoB5mNvvNADfLt:-MSZwdgoB5mNvvNADfLu:b-g02p94) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/Book.cs#L234)):*
> ```Smalltalk
> 					if (!String.IsNullOrEmpty(bookData.Language3.Iso639Code))
> 						orderedPreferences.Add(bookData.Language3.Iso639Code);
> ```

all languages?
___
*[src/BloomExe/Book/Book.cs, line 838 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZwiIf0ctyanuHlW4p:-MSZwiIf0ctyanuHlW4q:b-g02p94) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/Book.cs#L838)):*
> ```Smalltalk
> 				if (!String.IsNullOrEmpty(lang3) && lang3 != lang2 && lang3 != lang1)
> 					TranslationGroupManager.FixDuplicateLanguageDivs(groupElement, lang3);
> 			}
> ```

all languages?
___
*[src/BloomExe/Book/Book.cs, line 978 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZwnka9tOae_AA9pOL:-MSZwnka9tOae_AA9pOM:b-srb716) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/Book.cs#L978)):*
> ```Smalltalk
> 			bookDom.Body.SetAttribute("data-L2", this._bookData.Language2.Iso639Code);
> 			bookDom.Body.SetAttribute("data-L3", this._bookData.Language3.Iso639Code );
> 		}
> ```

all languages? Or tag for attention when more?N
___
*[src/BloomExe/Book/Book.cs, line 1225 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZgfB8-XIxz0309ok2:-MSZgfB8-XIxz0309ok3:b-9sd4xp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/Book.cs#L1225)):*
> ```Smalltalk
> 			}
> 			// These settings will be saved to the meta.json file the next time the book itself is saved.
> 		}
> ```

Maybe this is premature. But eliminating duplicates is already messy, and we expect to add more LanguageSlot values, with increasing likelihood of duplicates. And I expect we want DisplayNames to contain one entry for each unique language the book cares about. Is there some way we can iterate over all the values of the LanguageSlot enumeration, make a set of the resulting languages to remove duplicates cleanly, and then just write them out? Incidentally, something like "All the languages the book is using" would probably be useful elsewhere.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 106 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZixKX84T7daN4skXV:-MSZixKX84T7daN4skXW:b-xkh0bm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookCopyrightAndLicense.cs#L106)):*
> ```Smalltalk
> 						bookData.Language1.Iso639Code,
> 						bookData.Language2.Iso639Code,
> 						bookData.Language3.Iso639Code,
> ```

This would also benefit from a BookData method that returned all the language codes, though in this case, they need to be prioritized.
___
*[src/BloomExe/Book/BookData.cs, line 1568 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZk8uf8OLitdNwPcmG:-MSZk8uf8OLitdNwPcmH:bamk4i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookData.cs#L1568)):*
> ```Smalltalk
> 					"en", "fr", "th", "pt", "*"
> 				};
> 			}
> ```

Again, probably good to try all the languages this book uses (from some common prioritized list)
___
*[src/BloomExe/Book/BookData.cs, line 1742 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZl5uw3VdJerd7uHku:-MSZl5uw3VdJerd7uHkv:bdkwq8u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookData.cs#L1742)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <returns>A prioritized enumerable of language codes</returns>
> 		public IEnumerable<string> GetLanguagePrioritiesForTranslatedTextOnPage(bool includeLang1 = true)
> ```

Do you mean, text that is not translated into a vernacular as part of making a new book, but translated by Bloom's localization mechanism, because for example we know the French for "Animal Stories"? How about a more specific GetLanguagePrioritiesForLocalizedTextOnPage?
___
*[src/BloomExe/Book/BookData.cs, line 1780 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZmTN_-FyBv9O8lIP7:-MSZmTN_-FyBv9O8lIP8:b9d02fw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookData.cs#L1780)):*
> ```Smalltalk
> 				if (pashtoLanguages.Contains(langCodes[i]))
> 				{
> 					langCodes.InsertRange(i + 1, tryTheseLanguageCodes.Where(lc => !lc.Equals(langCodes[i])));
> ```

Is there a problem here if the starting collection has more than one of the pashtoLanguages? Seems like we could get duplicates in the final list.
Here and for other cases, a class like OrderedSet (see https://stackoverflow.com/questions/27311617/any-existing-net-ordered-set) might help.
___
*[src/BloomExe/Book/BookData.cs, line 1799 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZntMK6pY9rae7ANqQ:-MSZntMK6pY9rae7ANqR:bgaxye2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookData.cs#L1799)):*
> ```Smalltalk
> 					name = Language2.Name;
> 				else if (code == Language3.Iso639Code)
> 					name = Language3.Name;
> ```

For future-proofing, can we iterate over the Book's languages or the members of the Enumeration?
___
*[src/BloomExe/Book/RuntimeInformationInjector.cs, line 48 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZodaV4javXQAhNeHc:-MSZodaV4javXQAhNeHd:b95x702) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/RuntimeInformationInjector.cs#L48)):*
> ```Smalltalk
> 			if (!String.IsNullOrEmpty(language3.Iso639Code))
> 				SafelyAddLanguage(d, language3.Iso639Code, language3.GetNameInLanguage(language3.Iso639Code));
> ```

Probably wants to add all the book's languages?
___
*[src/BloomExe/Book/TranslationGroupManager.cs, line 48 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZozlm9PGovj3G1IQ5:-MSZozlm9PGovj3G1IQ6:b-p7k231) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde3919 [...]

2021-02-02 23:04 UTC, JohnThomson reviewed
Note: this might be anticipating something that's meant to be the next issue. If so, fine.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-:-MSZzH3Z27ulRLRw54gV:b-4vgqvg)* status: all files reviewed, 22 unresolved discussions (waiting on @hatton and @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2021-02-03 23:50 UTC, StephenMcConnel reviewed
Test times are rather variable because some of the tests hit the internet.  My most recent run of all the tests on Linux on this revised branch reported taking 531 seconds to complete.  I recompiled with master and ran all the tests, and that run reported taking 590 seconds to complete.  I think the internet variability swamps any noticeable effect from the changes I made to the tests.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-:-MSchRcKDa6kkP-RCSsS:bynelsy)* status: 25 of 42 files reviewed, 22 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 234 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZwdgoB5mNvvNADfLt:-MS_HNWF5v9QopS5Ul-X:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/Book.cs#L234)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

all languages?
</blockquote></details>

Done.
___
*[src/BloomExe/Book/Book.cs, line 838 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZwiIf0ctyanuHlW4p:-MS_JitTA3gz3VjMbtLu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/Book.cs#L838)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

all languages?
</blockquote></details>

Done.
___
*[src/BloomExe/Book/Book.cs, line 978 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZwnka9tOae_AA9pOL:-MS_KIyTEtJ-SLFQBBxf:b-ink3tm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/Book.cs#L978)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

all languages? Or tag for attention when more?N
</blockquote></details>

I put in a TODO comment.  It's not clear to me what needs to be done here, or even what these attributes are ever used for.
___
*[src/BloomExe/Book/Book.cs, line 1225 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZgfB8-XIxz0309ok2:-MS_LBEc2sR2sSDxen3j:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/Book.cs#L1225)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe this is premature. But eliminating duplicates is already messy, and we expect to add more LanguageSlot values, with increasing likelihood of duplicates. And I expect we want DisplayNames to contain one entry for each unique language the book cares about. Is there some way we can iterate over all the values of the LanguageSlot enumeration, make a set of the resulting languages to remove duplicates cleanly, and then just write them out? Incidentally, something like "All the languages the book is using" would probably be useful elsewhere.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookCopyrightAndLicense.cs, line 106 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZixKX84T7daN4skXV:-MSd5XVx0P8WHUdmr3v9:b-k2olon) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookCopyrightAndLicense.cs#L106)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This would also benefit from a BookData method that returned all the language codes, though in this case, they need to be prioritized.
</blockquote></details>

Done.  The implemented method orders the languages in this way, although it also does not add duplicates.
___
*[src/BloomExe/Book/BookData.cs, line 1568 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZk8uf8OLitdNwPcmG:-MSd7m3O3aJSEq9U5uHy:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookData.cs#L1568)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again, probably good to try all the languages this book uses (from some common prioritized list)
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookData.cs, line 1742 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZl5uw3VdJerd7uHku:-MSdHHzF6aMno1a4aMlK:b-156f6r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookData.cs#L1742)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do you mean, text that is not translated into a vernacular as part of making a new book, but translated by Bloom's localization mechanism, because for example we know the French for "Animal Stories"? How about a more specific GetLanguagePrioritiesForLocalizedTextOnPage?
</blockquote></details>

Done.  I changed the method name.
___
*[src/BloomExe/Book/BookData.cs, line 1780 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZmTN_-FyBv9O8lIP7:-MSd9Lbo6VNRFXj0_TwN:b-7bmtyr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookData.cs#L1780)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is there a problem here if the starting collection has more than one of the pashtoLanguages? Seems like we could get duplicates in the final list.
Here and for other cases, a class like OrderedSet (see https://stackoverflow.com/questions/27311617/any-existing-net-ordered-set) might help.
</blockquote></details>

Note: this method is moved verbatim from CollectionSettings where it has lived for who know how long.  Any problems here are not original with this PR. :-)
But that doesn't mean the code shouldn't be improved.  I revised the .Where predicate to prevent duplication.
___
*[src/BloomExe/Book/BookData.cs, line 1799 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZntMK6pY9rae7ANqQ:-MSdZHYI76c6gjHiHxUJ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/BookData.cs#L1799)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

For future-proofing, can we iterate over the Book's languages or the members of the Enumeration?
</blockquote></details>

Done.
___
*[src/BloomExe/Book/RuntimeInformationInjector.cs, line 48 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZodaV4javXQAhNeHc:-MSd_ahHAKY2_b2lEjVn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/RuntimeInformationInjector.cs#L48)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Probably wants to add all the book's languages?
</blockquote></details>

Done.
___
*[src/BloomExe/Book/TranslationGroupManager.cs, line 48 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZozlm9PGovj3G1IQ5:-MSdc9q14Qk72PlZLQrv:b-ex50u3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/18ef0b9f7fde39191342637b2eaf3ae8a0f0a00e/src/BloomExe/Book/TranslationGroupManager.cs#L48)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe too soon to try to fix this, but could we at least tag things that seem to be doing something for all a book's languages?
A safe default is probably to make elements for all the book's languages; there might be some elements where some could be omitted.
</blockquote></details>

I fixed the preceding method to use GetBasicBookLanguageCodes and iterate over the returned list.
___
*[src/BloomExe/Book/TranslationGroupManager.cs, line 156 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166#-MSZpipI9YtsWKAX1e8K:-MSdlYJ43e6o1kaEio4k:b-896fix)  [...]

2021-02-04 00:00 UTC, JohnThomson approved these changes
> Reviewed 1 of 17 files at r2, 1 of 15 files at r3, 14 of 17 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4166)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)



<!-- Sent from Reviewable.io -->

2021-02-04 22:02 UTC, merged