Avoid saving PNG files from Image objects if possible (BL-9377)
BloomBooks/BloomDesktop pull request #4179
Opened 2021-02-09 17:09 UTC by StephenMcConnel

Writing PNG files turns out to be very slow, whether inside C# code
or with GraphicsMagick.  Setting the quality to 0 for GraphicsMagick
causes PNG saving to use Huffman encoding which is much faster, and
usually okay for image data compression.

2021-02-09 23:50 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Edit/EditingView.cs, line 1248 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MT8BbvY4996vp0bLaUz:-MT8BbvY4996vp0bLaV-:b-4a8n2f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b585db4ac94112fb1ec214014b865e6b627ad4cb/src/BloomExe/Edit/EditingView.cs#L1248)):*
> ```Smalltalk
> 			catch
> 			{
> 				// Ignore any errors.  We tried and failed...
> ```

How much do we anticipate this happening?
Should this be `TryGetOriginalImageDimension`?

Either way, we should probably pluralize `Dimensions` in the method name.


<!-- Sent from Reviewable.io -->

2021-02-10 16:23 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Edit/EditingView.cs, line 1248 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MT8BbvY4996vp0bLaUz:-MTBieTr7pCX1l5m8nQi:b1et6m4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b585db4ac94112fb1ec214014b865e6b627ad4cb/src/BloomExe/Edit/EditingView.cs#L1248)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How much do we anticipate this happening?
Should this be `TryGetOriginalImageDimension`?

Either way, we should probably pluralize `Dimensions` in the method name.
</blockquote></details>

I don't this this should happen, but I tend to be paranoid in my programming.
method renamed as suggested.


<!-- Sent from Reviewable.io -->

2021-02-10 16:26 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2021-02-10 20:34 UTC, JohnThomson requested changes
Mostly good...few small suggestions.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-:-MTCdnNr15YACAwAE8wO:b-o808qi)* status: all files reviewed, 10 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Edit/EditingView.cs, line 1156 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCXlBZ1XKK2c8BYRBl:-MTCXlBZ1XKK2c8BYRBm:bzdd30x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1156)):*
> ```Smalltalk
> 					var started = DateTime.Now;
> 					int height, width;
> 					TryGetOriginalImageDimensions(dlg.ImageInfo, out height, out width);
> ```

The name of this method implies that it might fail. I suppose if it does we'll just do the safer Save? (See comment below on the method.)
___
*[src/BloomExe/Edit/EditingView.cs, line 1158 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCY9wN9tbrDrEdMd_e:-MTCY9wN9tbrDrEdMd_f:bg3m0x7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1158)):*
> ```Smalltalk
> 					TryGetOriginalImageDimensions(dlg.ImageInfo, out height, out width);
> 					var copyOriginalImage = height == dlg.ImageInfo.Image.Height && width == dlg.ImageInfo.Image.Width;
> 					// Save the possibly modified (by cropping) image to a file before processing further.
> ```

Save or copy?
___
*[src/BloomExe/Edit/EditingView.cs, line 1173 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCXG5I6ymd1PqkKSbI:-MTCXG5I6ymd1PqkKSbJ:bov8quy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1173)):*
> ```Smalltalk
> 						// worry about the extension of newImagePath outside this block of code.)
> 						if (extension != ".jpg" && extension != ".jpeg")
> 							extension = ".png";
> ```

Don't we need to do a new Save (rather than copy) if we're converting from something else to PNG?
___
*[src/BloomExe/Edit/EditingView.cs, line 1202 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCYJmS65aXYh_HwLiG:-MTCYJmS65aXYh_HwLiH:bd6n665) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1202)):*
> ```Smalltalk
> 						}
> 						var finished = DateTime.Now;
> 						Debug.WriteLine($"total image preparation time = {finished - started}");
> ```

Maybe comment this out? Our debug output is very cluttered.
___
*[src/BloomExe/Edit/EditingView.cs, line 1230 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCYniD5whuvdEFR0sr:-MTCYniD5whuvdEFR0ss:bvz1nfi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1230)):*
> ```Smalltalk
> 		/// Get the original dimensions of the image if we can from the stored metadata.
> 		/// </summary>
> 		private void TryGetOriginalImageDimensions(PalasoImage palasoImage, out int height, out int width)
> ```

TryX is a very specific pattern in C# that always returns a boolean. I get that you're trying to warn any client that it may not always succeed, and that you don't actually need to know whether it did or not since the -1 outputs achieve the same thing, but I still don't like it.
I could live with GetOriginalImageDimensions and just a comment that it may fail and yield -1,-1, or you could actually return the boolean and include a test of the result in computing copyOriginalImage, or you could pass the current dimensions IN and recast this method as HasSameDimensions, simply returning false in the catch as well as if either is different.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 116 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCbwWqBhzm8VfQEIjm:-MTCbwWqBhzm8VfQEIjn:b-ld79an) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L116)):*
> ```Smalltalk
> 				bool isEncodedAsPng = !isEncodedAsJpeg && AppearsToBePng(imageInfo);
> 				string jpegFilePath = null;
> 				var shouldConvertToJpeg = !isEncodedAsJpeg && !HasTransparency(imageInfo.Image) && ShouldChangeFormatToJpeg(imageInfo, out jpegFilePath);
> ```

shouldConvertToJpeg -> convertedToJpeg?
Is this conversion common enough to make it tempting to pass in destinationPath so we write it directly there and avoid another file copy? Might need to be a ref param if we need to know the new destinationPath if it gets done.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 862 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCbR7JDh0XX3bUxN02:-MTCbR7JDh0XX3bUxN03:b71jg27) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L862)):*
> ```Smalltalk
> 		/// doing that if the size would be at least 50% less.
> 		/// </summary>
> 		public static bool ShouldChangeFormatToJpeg(PalasoImage image, out string jpegFilePath)
> ```

Wants a new name. TryConvertToJpeg()? It's now doing the job as well as deciding whether it should be done. But my name rather implies that failure means we couldn't, rather than just that we decided it wasn't helpful (enough). TryConvertToJpegIfHelpful?
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 888 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCb6m904hlmk6x2_9q:-MTCb6m904hlmk6x2_9r:bn75o68) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L888)):*
> ```Smalltalk
> 					else
> 					{
> 						LogGraphicsMagickFailure(proc);
> ```

LogGraphicsMagickMissing? Failure would seem to be more the exception handler below.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 895 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCaMRNB0usXYCxEJ83:-MTCaMRNB0usXYCxEJ84:bsrmxxk) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L895)):*
> ```Smalltalk
> 			catch (Exception e)
> 			{
> 				NonFatalProblem.Report(ModalIf.Alpha, PassiveIf.All,"Could not attempt conversion to jpeg.", "ref BL-3387", exception: e);
> ```

"Could not convert"? You attempted it!
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 1080 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCdAiqCICxJp22eyyu:-MTCdAirEtT8h4e7MIj7:b-td11ih) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L1080)):*
> ```Smalltalk
> 				_currentFilePaths.Remove(key);
> 			else if (_currentFilePaths.ContainsKey(key))
> 				_currentFilePaths[key] = filePath;
> ```

This line will add or replace as needed, so you don't need the test or the third case.


<!-- Sent from Reviewable.io -->

2021-02-10 20:44 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)* status: all files reviewed, 10 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/BloomExe/Edit/EditingView.cs, line 1230 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCYniD5whuvdEFR0sr:-MTCg0Z1-lsYfFk3wTlf:b-581p95) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1230)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

TryX is a very specific pattern in C# that always returns a boolean. I get that you're trying to warn any client that it may not always succeed, and that you don't actually need to know whether it did or not since the -1 outputs achieve the same thing, but I still don't like it.
I could live with GetOriginalImageDimensions and just a comment that it may fail and yield -1,-1, or you could actually return the boolean and include a test of the result in computing copyOriginalImage, or you could pass the current dimensions IN and recast this method as HasSameDimensions, simply returning false in the catch as well as if either is different.
</blockquote></details>

I had him change from GetOriginalImageDimensions to Try... but I did mean to infer that it should return the bool.


<!-- Sent from Reviewable.io -->

2021-02-10 22:49 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)* status: 0 of 3 files reviewed, 10 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Edit/EditingView.cs, line 1156 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCXlBZ1XKK2c8BYRBl:-MTCiZVjDv-Xk5SCRJjD:bb54k7d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1156)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The name of this method implies that it might fail. I suppose if it does we'll just do the safer Save? (See comment below on the method.)
</blockquote></details>

Yes, if it fails we do the (quite possibly slow) Image.Save operation.  I added the boolean output value as suggested below.
___
*[src/BloomExe/Edit/EditingView.cs, line 1158 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCY9wN9tbrDrEdMd_e:-MTCj27wCZ1z06xa5LxR:bcq2vye) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Save or copy?
</blockquote></details>

reworded the comment to reflect the new reality.
___
*[src/BloomExe/Edit/EditingView.cs, line 1173 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCXG5I6ymd1PqkKSbI:-MTCjoNW-uc1HyhSHIzA:b-i3co2x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1173)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Don't we need to do a new Save (rather than copy) if we're converting from something else to PNG?
</blockquote></details>

This happens later on if needed.  I added more commentary here to make that clear.
___
*[src/BloomExe/Edit/EditingView.cs, line 1202 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCYJmS65aXYh_HwLiG:-MTCk3zcDLG8Vt5EfwW_:bb4v4va) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1202)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe comment this out? Our debug output is very cluttered.
</blockquote></details>

Done.  (actually I deleted it since the timing is obvious enough code to create if we need it again)
___
*[src/BloomExe/Edit/EditingView.cs, line 1230 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCYniD5whuvdEFR0sr:-MTCpciJ8TmoF5tHYhar:b2unk0t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/Edit/EditingView.cs#L1230)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I had him change from GetOriginalImageDimensions to Try... but I did mean to infer that it should return the bool.
</blockquote></details>

changed to return the boolean success value.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 116 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCbwWqBhzm8VfQEIjm:-MTCuTeg4tNSXkm70pxM:brlyzwd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L116)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

shouldConvertToJpeg -> convertedToJpeg?
Is this conversion common enough to make it tempting to pass in destinationPath so we write it directly there and avoid another file copy? Might need to be a ref param if we need to know the new destinationPath if it gets done.
</blockquote></details>

Done.  (renamed variable)  also changed jpegFilePath to an input parameter so that we're through if the method is called and returns true.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 862 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCbR7JDh0XX3bUxN02:-MTD-zKfBFJm8JWsxiQU:bohfshs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L862)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Wants a new name. TryConvertToJpeg()? It's now doing the job as well as deciding whether it should be done. But my name rather implies that failure means we couldn't, rather than just that we decided it wasn't helpful (enough). TryConvertToJpegIfHelpful?
</blockquote></details>

Done.  renamed to TryConvertToJpegIfHelpful
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 888 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCb6m904hlmk6x2_9q:-MTD27C-9QquXGmwB3Sk:b1l7eq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L888)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

LogGraphicsMagickMissing? Failure would seem to be more the exception handler below.
</blockquote></details>

This "else" is for proc.ExitCode != 0, ie, a failure running the process.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 895 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCaMRNB0usXYCxEJ83:-MTD2WGAAPmXV6vldJhO:bjkjeaz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L895)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

"Could not convert"? You attempted it!
</blockquote></details>

Reworded.  I'm not sure this try-catch is really needed with the new code.
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 1080 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCdAiqCICxJp22eyyu:-MTD0Cqz2iPkLMrn_GVv:b3dfb1v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L1080)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This line will add or replace as needed, so you don't need the test or the third case.
</blockquote></details>

The original code just had Add, which liked to throw exceptions.  :-)
Fixed.


<!-- Sent from Reviewable.io -->

2021-02-10 23:14 UTC, JohnThomson requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 888 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTCb6m904hlmk6x2_9q:-MTDD0gqDlIEzTdwl8Sa:b-wtu3ag) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f7423115da6739af38353d9ffdc88655af12be24/src/BloomExe/ImageProcessing/ImageUtils.cs#L888)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This "else" is for proc.ExitCode != 0, ie, a failure running the process.
</blockquote></details>

oops! my bad
___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 855 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTDCleyDuV-TEcK3J1b:-MTDCleyDuV-TEcK3J1c:b-b7ucap) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a1d0e4c1837905154b65e69e5e8660c806a0f9/src/BloomExe/ImageProcessing/ImageUtils.cs#L855)):*
> ```Smalltalk
> 		/// So the idea here is just to try and detect that we should would be better off saving the image as a jpeg.
> 		/// Note that even at 100%, we're still going to lose some quality. So this method is only going to recommend
> 		/// doing that if the file size would be at least 50% smaller.
> ```

Sorry, missed this earlier, but the comment needs updating. It's not just detecting now!


<!-- Sent from Reviewable.io -->

2021-02-10 23:59 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/ImageProcessing/ImageUtils.cs, line 855 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179#-MTDCleyDuV-TEcK3J1b:-MTDF5QP4-CSyrnCvggL:bdycnkc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f6a1d0e4c1837905154b65e69e5e8660c806a0f9/src/BloomExe/ImageProcessing/ImageUtils.cs#L855)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sorry, missed this earlier, but the comment needs updating. It's not just detecting now!
</blockquote></details>

Done.  Comment updated (and expanded)


<!-- Sent from Reviewable.io -->

2021-02-11 00:15 UTC, JohnThomson approved these changes
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4179)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2021-02-11 00:15 UTC, merged