Fix duplicate audio ids added by earlier bug (BL-9503)
BloomBooks/BloomDesktop pull request #4183
Opened 2021-02-10 17:19 UTC by StephenMcConnel

2021-02-11 18:11 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 884 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTGemJS4D_N-LlSZar9:-MTGemJS4D_N-LlSZarA:br096nf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95efc42cb656ffc1a7c226ea6a0e56746e1c7920/src/BloomExe/Book/Book.cs#L884)):*
> ```Smalltalk
> 			{
> 				// Inform user of need to rerecord audio.
> 				var shortMsg = String.Format("Bloom fixed {0} duplicated audio id values.  You need to check the audio in this book and may need to record some pages again.", duplicateAudioIdsFixed);
> ```

I'm thinking "duplicated audio id values" will not mean much to the user.
Can we think of something more user-friendly?
What about
Bloom had to clean up some problematic audio information in this book. As a result, you need to review all your audio in the Talking Book Tool. You may need to record some text again.
?

Has there been any discussion on whether this should be localized?

@hatton 
___
*[src/BloomTests/Book/BookTests.cs, line 1976 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTHGmFE4IZuix6rXIHL:-MTHGmFE4IZuix6rXIHM:b-aclkir) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95efc42cb656ffc1a7c226ea6a0e56746e1c7920/src/BloomTests/Book/BookTests.cs#L1976)):*
> ```Smalltalk
> 				"//div[contains(@class,'audio-sentence') and @id='i07d27e74-f55e-4adf-b09e-16c3aae93789']", 2); // smallCoverCredits (same)
> 			AssertThatXmlIn.Dom(book.RawDom).HasSpecifiedNumberOfMatchesForXpath(
> 				"//div[contains(@class,'audio-sentence') and @id='i07d27e74-f55e-4adf-b09e-16c3aae93789']", 2); // funding (same)
> ```

Something's amiss here. You have the same ID on this line and the one above.
Probably just a copy/paste error.

But it actually brings up a question I was wondering about.
What if the user, in a buggy version, copied text from one xmatter field to another? Doesn't that mean they will still have errant duplicate ids after the current cleanup code?
___
*[src/BloomTests/Book/BookTests.cs, line 2141 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTHHB9LE3XaN4uOTnxH:-MTHHB9LE3XaN4uOTnxI:b982s6n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95efc42cb656ffc1a7c226ea6a0e56746e1c7920/src/BloomTests/Book/BookTests.cs#L2141)):*
> ```Smalltalk
> 			AssertThatXmlIn.Dom(book.RawDom).HasSpecifiedNumberOfMatchesForXpath(
> 				"//div[contains(@class,'audio-sentence') and @id='i90ccd522-5d20-4ff7-b9b3-b32a83f2abeb']", 1); // fixed!
> 		}
> ```

How much effort would it be to verify that the new ids were generated and we are generating new files for them which are copies of the originals?

Could be a new simpler test rather than adding that to the existing ones.


<!-- Sent from Reviewable.io -->

2021-02-12 17:51 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/Book/Book.cs, line 884 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTGemJS4D_N-LlSZar9:-MTHUooU5uSIdBQwkHTW:bti8yct) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95efc42cb656ffc1a7c226ea6a0e56746e1c7920/src/BloomExe/Book/Book.cs#L884)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm thinking "duplicated audio id values" will not mean much to the user.
Can we think of something more user-friendly?
What about
Bloom had to clean up some problematic audio information in this book. As a result, you need to review all your audio in the Talking Book Tool. You may need to record some text again.
?

Has there been any discussion on whether this should be localized?

@hatton 
</blockquote></details>

Done.  changed wording as suggested.  The detection code this was adapted from did not do any localization, but it would be easy to hook up if desired.
___
*[src/BloomTests/Book/BookTests.cs, line 1976 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTHGmFE4IZuix6rXIHL:-MTHWQDF1TmziIqwSjkP:b-d2sfrh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95efc42cb656ffc1a7c226ea6a0e56746e1c7920/src/BloomTests/Book/BookTests.cs#L1976)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Something's amiss here. You have the same ID on this line and the one above.
Probably just a copy/paste error.

But it actually brings up a question I was wondering about.
What if the user, in a buggy version, copied text from one xmatter field to another? Doesn't that mean they will still have errant duplicate ids after the current cleanup code?
</blockquote></details>

Fixed the copy/paste duplications.  Good eye.  :-)
I had thought about trying to handle problems with audio recorded in the xmatter.  Doing so will complicate the code a good bit.  (The current detection code probably misses such errors.)
I kept my changes in a separate commit for a change so that we can decide if they're worth it for 4.9.
___
*[src/BloomTests/Book/BookTests.cs, line 2141 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTHHB9LE3XaN4uOTnxH:-MTHWtdj5D3kQZLiwT_7:bkfq2pu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/95efc42cb656ffc1a7c226ea6a0e56746e1c7920/src/BloomTests/Book/BookTests.cs#L2141)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How much effort would it be to verify that the new ids were generated and we are generating new files for them which are copies of the originals?

Could be a new simpler test rather than adding that to the existing ones.
</blockquote></details>

I added a check to the existing tests that we end up with unique audio ids.  (except for the title, which is repeated in a couple of tests)
In the new test I wrote, I included checking for copying files.


<!-- Sent from Reviewable.io -->

2021-02-12 18:11 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @andrew-polk, @hatton, and @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 871 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTMPeaW9HI0Y8nSd4tP:-MTMPeaW9HI0Y8nSd4tQ:b-2un6ii) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/092cab632b7ccc0c7f9001a5d8ab98912ee4cd38/src/BloomExe/Book/Book.cs#L871)):*
How about

> There was a problem with recordings in this Talking Book, which was caused by a bug in an older version of Bloom. We have fixed the book, but now you will need to review all of your recordings in this book and see if you need to record some text again. We are very sorry for our mistake and the inconvenience this might cause you.


<!-- Sent from Reviewable.io -->

2021-02-12 20:14 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/Book/Book.cs, line 871 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTMPeaW9HI0Y8nSd4tP:-MTMsA9g3fWHW1c9EwFG:bg0ceqf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/092cab632b7ccc0c7f9001a5d8ab98912ee4cd38/src/BloomExe/Book/Book.cs#L871)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about

> There was a problem with recordings in this Talking Book, which was caused by a bug in an older version of Bloom. We have fixed the book, but now you will need to review all of your recordings in this book and see if you need to record some text again. We are very sorry for our mistake and the inconvenience this might cause you.
</blockquote></details>

Done.  (but changed "and see if" to "to see if".


<!-- Sent from Reviewable.io -->

2021-02-12 20:56 UTC, andrew-polk approved these changes
Approving but asking JT to look, too, since this is a scary 4.9 change.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-:-MTN0t1zEYxvGN-U-dSX:b-7wuaa5)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-02-12 23:50 UTC, JohnThomson requested changes
I've made a bunch of somewhat conflicting suggestions. The one I like best, which would make most of the others redundant, is on line 841: I think if we depend a little more on SynchronizeDataItemsThroughoutDOM(), we can simplify this to a single loop over the audio elements, just skipping any that occur in a data-book with a key we've already dealt with. Of course that assumes that any time we need to do this fix, we're sure to do SynchronizeDataItemsThroughoutDOM() soon after.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-:-MTNBHjG5IwkAEqG9-7G:bu3iol1)* status: all files reviewed, 17 unresolved discussions (waiting on @hatton and @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 841 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTN4GiR2ElhPCskI2CX:-MTN4GiR2ElhPCskI2CY:b4ia1ok) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L841)):*
> ```Smalltalk
> 			var idSet = new HashSet<string>();
> 			_duplicateAudioIdsFixed = 0;
> 			var xmatterIds = new Dictionary<string, Tuple<string, string>>();   // id => {data-book,lang}
> ```

Probably not worth changing now, but C#7 has a much nicer way of doing Tuples. Here, for example, I think you cold say new Dictionary<string, (string DataBook, string Lang)> and then use those names in place of Item1 and Item2. Worth starting to learn, I think. It also allows JS-like elegance of functions returning multiple values and deconstructing tuples in variable declarations.

More importantly, let's make the name and comment clearer. This is a map from the ID of an audio-sentence element that lives in a data-book to the (data-book, lang) pair that identify a data-book element in which it may legitimately occur. Something like audioIdToValidDataBookKey?

A third thought: would it clarify or simplify anything to merge idSet with this variable? Their function sort of overlaps. If we had audioIdToValidDataBookKey storing a null for any ID we found outside a data-book, and the appropriate key for any that we found inside, it would be unambiguous that each occurrence of an audio-sentence id is an error if it is already in the dictionary, it is in the same data-book zone as when it was seen before. I think I at least could more easily reason about the correctness of this code then.

Or another idea: perhaps all we need is a set audioIdsSeenBefore and another one dataBookKeysSeenBefore. As we process each audio-sentence, if it's not in a databook, fix it if it's in audioIdsSeenBefore. If it is in a data-book, and the data-book's key is not in dataBookKeysSeenBefore, we carry on through that data-book and then add its key to dataBookKeysSeenBefore. Ids we haven't seen before are obviously OK. Anything in a data div that isn't the first one with a given key will get overwritten later. (Of course, the test code would need to check the result after we also SynchronizeDataItemsThroughoutDOM()).
___
*[src/BloomExe/Book/Book.cs, line 842 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTNP2ExD8uxIODe4_JC:-MTNP2ExD8uxIODe4_JD:brzkxep) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L842)):*
> ```Smalltalk
> 			_duplicateAudioIdsFixed = 0;
> 			var xmatterIds = new Dictionary<string, Tuple<string, string>>();   // id => {data-book,lang}
> 			var fixedXmatter = new Dictionary<Tuple<string, string, string>, string>(); // {id,data-book,lang} => new id
> ```

How about, audioIdAndDataBookKeyToFixedId?
But also, do we need it at all? If we're always going to update data-book elements throughout the DOM after we do this fix, then we shouldn't need to fix any of the later copies. So once we have processed the data-div, we could just skip any node that IsNodePartOfDataBookOrDataCollection(node).
I suppose it's pathologically possible that such an element has a data-book/lang combination that is NOT in the data-div. If we're concerned about that, we could make a set of such combinations that we've seen, and if we encounter a new one later, pass it to a function created from the code inside the foreach of FixDuplicateAudioIdsInDataDiv.
___
*[src/BloomExe/Book/Book.cs, line 844 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTN9fAt7ixIfhhJrMs5:-MTN9fAt7ixIfhhJrMs6:bepxv2k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L844)):*
> ```Smalltalk
> 			var fixedXmatter = new Dictionary<Tuple<string, string, string>, string>(); // {id,data-book,lang} => new id
> 			FixDuplicateAudioIdsInDataDiv(bookDOM, idSet, xmatterIds, fixedXmatter);
> 			foreach (var contentPage in bookDOM.GetPageElements())
> ```

maybe just 'page'? contentPage suggests, incorrectly, that  xmatter pages are excluded.
___
*[src/BloomExe/Book/Book.cs, line 902 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTNKOw_DwjHHq3aZvwq:-MTNKOw_DwjHHq3aZvwr:b-rs18f6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L902)):*
> ```Smalltalk
> 				{
> 					var id = (audioElement as XmlElement).GetOptionalStringAttribute("id", null);
> 					if (id != null)
> ```

It must have an ID...that was required to match the xpath.
___
*[src/BloomExe/Book/Book.cs, line 907 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTN6V242ubbSH7OXzXQ:-MTN6V242ubbSH7OXzXR:b-d1glur) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L907)):*
> ```Smalltalk
> 						var dataBook = (div as XmlElement).GetStringAttribute("data-book");
> 						var lang = (div as XmlElement).GetStringAttribute("lang");
> 						var checkValue = new Tuple<string, string>(dataBook, lang);
> ```

Even for old style Tuples, it's shorter to say Tuple.Create(dataBook, lang) which infers the type. With the new syntax, I thin it's just checkValue = (dataBook, lang).
___
*[src/BloomExe/Book/Book.cs, line 915 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTNL48k9ecxTLk0CKI5:-MTNL48k9ecxTLk0CKI6:b-fx7mqq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L915)):*
> ```Smalltalk
> 							var newId = FixDuplicateAudioId(audioElement, id);
> 							if (xmatterIds[id] == checkValue)
> 							{
> ```

So, here we've found an audio id we've seen before in the data div. But the data-book element it's part of has the same data-book/lang key as when we saw it last. So either (a) the data-div contains two data-book elements with the same key, or (b) a single data-book element contains two audio-sentences with the same ID. The former would be a different bug, which we're not trying to fix. In the latter case, we've made a new ID (and recording) for the duplicate. But what should we do when we find a copy of this data-book elsewhere? It will have two elements with the old ID. Both will match the expected key for that ID which is already in xmatterIds. So we won't do yet another de-duplication, but this fixup process will leave the second one wrong. However, the data-div copy is right, and will shortly be copied over all the others.
(All that took me a while to figure out...I think a longer comment along the lines above might be helpful. Then again, as discussed above, maybe we can simplify to where we don't need this special case?)
I suppose we always do update book-data stuff throughout the DOM AFTER we do this?
___
*[src/BloomExe/Book/Book.cs, line 934 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTNDly_AQB6ORKHAtG-:-MTNDlya-bKyRJ3_gfPd:bq617p7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L934)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// If the  [...]

2021-02-15 22:36 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: 0 of 3 files reviewed, 17 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 841 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTN4GiR2ElhPCskI2CX:-MTb5wA6-lFklgPTlJAz:b-oo2nla) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L841)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Probably not worth changing now, but C#7 has a much nicer way of doing Tuples. Here, for example, I think you cold say new Dictionary<string, (string DataBook, string Lang)> and then use those names in place of Item1 and Item2. Worth starting to learn, I think. It also allows JS-like elegance of functions returning multiple values and deconstructing tuples in variable declarations.

More importantly, let's make the name and comment clearer. This is a map from the ID of an audio-sentence element that lives in a data-book to the (data-book, lang) pair that identify a data-book element in which it may legitimately occur. Something like audioIdToValidDataBookKey?

A third thought: would it clarify or simplify anything to merge idSet with this variable? Their function sort of overlaps. If we had audioIdToValidDataBookKey storing a null for any ID we found outside a data-book, and the appropriate key for any that we found inside, it would be unambiguous that each occurrence of an audio-sentence id is an error if it is already in the dictionary, it is in the same data-book zone as when it was seen before. I think I at least could more easily reason about the correctness of this code then.

Or another idea: perhaps all we need is a set audioIdsSeenBefore and another one dataBookKeysSeenBefore. As we process each audio-sentence, if it's not in a databook, fix it if it's in audioIdsSeenBefore. If it is in a data-book, and the data-book's key is not in dataBookKeysSeenBefore, we carry on through that data-book and then add its key to dataBookKeysSeenBefore. Ids we haven't seen before are obviously OK. Anything in a data div that isn't the first one with a given key will get overwritten later. (Of course, the test code would need to check the result after we also SynchronizeDataItemsThroughoutDOM()).
</blockquote></details>

this dictionary is no longer used.  It isn't needed if we use _bookData.SynchronizeDataItemsThroughoutDOM() as suggested.
___
*[src/BloomExe/Book/Book.cs, line 842 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTNP2ExD8uxIODe4_JC:-MTb5rg06lkJ1GBmeLz2:b-r5vg28) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L842)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How about, audioIdAndDataBookKeyToFixedId?
But also, do we need it at all? If we're always going to update data-book elements throughout the DOM after we do this fix, then we shouldn't need to fix any of the later copies. So once we have processed the data-div, we could just skip any node that IsNodePartOfDataBookOrDataCollection(node).
I suppose it's pathologically possible that such an element has a data-book/lang combination that is NOT in the data-div. If we're concerned about that, we could make a set of such combinations that we've seen, and if we encounter a new one later, pass it to a function created from the code inside the foreach of FixDuplicateAudioIdsInDataDiv.
</blockquote></details>

this dictionary is no longer used.
___
*[src/BloomExe/Book/Book.cs, line 844 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTN9fAt7ixIfhhJrMs5:-MTb5-Dt0TuYKKRWbAuc:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L844)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

maybe just 'page'? contentPage suggests, incorrectly, that  xmatter pages are excluded.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/Book.cs, line 902 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTNKOw_DwjHHq3aZvwq:-MTb51oT9IJWyTjuzDYz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L902)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It must have an ID...that was required to match the xpath.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/Book.cs, line 907 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTN6V242ubbSH7OXzXQ:-MTb5GewARnC2mZLJBgD:bf5fjdn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L907)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Even for old style Tuples, it's shorter to say Tuple.Create(dataBook, lang) which infers the type. With the new syntax, I thin it's just checkValue = (dataBook, lang).
</blockquote></details>

no longer used.  But thanks for the pointer.
___
*[src/BloomExe/Book/Book.cs, line 915 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTNL48k9ecxTLk0CKI5:-MTb54mLDvIpoqGBZSfD:bqw6n6b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L915)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So, here we've found an audio id we've seen before in the data div. But the data-book element it's part of has the same data-book/lang key as when we saw it last. So either (a) the data-div contains two data-book elements with the same key, or (b) a single data-book element contains two audio-sentences with the same ID. The former would be a different bug, which we're not trying to fix. In the latter case, we've made a new ID (and recording) for the duplicate. But what should we do when we find a copy of this data-book elsewhere? It will have two elements with the old ID. Both will match the expected key for that ID which is already in xmatterIds. So we won't do yet another de-duplication, but this fixup process will leave the second one wrong. However, the data-div copy is right, and will shortly be copied over all the others.
(All that took me a while to figure out...I think a longer comment along the lines above might be helpful. Then again, as discussed above, maybe we can simplify to where we don't need this special case?)
I suppose we always do update book-data stuff throughout the DOM AFTER we do this?
</blockquote></details>

This code is greatly simplified to take advantage of _bookData.SynchronizeDataItemsThroughoutDOM() as suggested.
___
*[src/BloomExe/Book/Book.cs, line 934 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTNDly_AQB6ORKHAtG-:-MTb5UkZ7AXSYJJYmfys:b81razc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6d4da0499a83ef43437f02ae25d5c6241b518129/src/BloomExe/Book/Book.cs#L934)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is wrong, and confusing. We're not concerned about the node containing children with duplicate audio ids...rather, it is known that node itself has the specified audio-id and is an audio-sentence itself, and we want to make sure that node itself is not a problem duplicate. Because it's part of the data-book system, it may be a legitimate duplicate, in that the previous occurrences were in data-book elements with matching data-book and lang attrs. If so, nothing to do. It may be that it's a truly new duplicate, in which case we have to fix it. And the third option is that we already encountered this ID as a problem duplicate in another element contai [...]

2021-02-16 19:42 UTC, JohnThomson approved these changes
Looks good. I particularly like that you just synchronize at once if there are data-div issues, and don't need to worry about that otherwise. Makes it much easier to be confident the solution works.
I didn't look again at the tests, except your reponses.
This is changed (and important) enough that maybe Andrew should take another look too?

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-:-MTgLNFY3_TuU9tVITph:b9pvmxt)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2021-02-16 21:20 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/BookData.cs, line 1385 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTgglQ23Wgp9ZYgbp6x:-MTgglQ23Wgp9ZYgbp6y:b-nv6wpo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d8cb9e47e7629075901572cf3a9a0143c175ece9/src/BloomExe/Book/BookData.cs#L1385)):*
> ```Smalltalk
> 						if (Char.IsDigit(newId[0]))
> 							newId = "i" + newId;
> 						node.Attributes["id"].Value = newId;
> ```

I don't see a particular problem with this, but I thought we agreed this morning it would be better just to remove the ids and let Bloom add them in due course.


<!-- Sent from Reviewable.io -->

2021-02-16 23:57 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 1385 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTgglQ23Wgp9ZYgbp6x:-MThGK1S3KGoZcXKGNm_:b-wh5c8j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d8cb9e47e7629075901572cf3a9a0143c175ece9/src/BloomExe/Book/BookData.cs#L1385)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't see a particular problem with this, but I thought we agreed this morning it would be better just to remove the ids and let Bloom add them in due course.
</blockquote></details>

That was my understanding.  I don't think the code is "simpler" if we try to remove the span as the revised code does.


<!-- Sent from Reviewable.io -->

2021-02-17 00:10 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 1385 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTgglQ23Wgp9ZYgbp6x:-MThJ1azBhAlSMU5g0Yy:b-8va7xl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d8cb9e47e7629075901572cf3a9a0143c175ece9/src/BloomExe/Book/BookData.cs#L1385)):*
> I don't think the code is "simpler" if we try to remove the span as the revised code does.

Sigh. Yes, I have to agree.
This requires specific knowledge of all the pieces we might add/remove, and the list could grow in the future without getting modified here.
I also have concerns about the safety of replacing any span/div which doesn't have attributes with its children. span seems pretty safe, but I'm dubious about divs.

@johnthomson, thoughts?

@stephenmcconnel, is this testable? (don't add tests until we decide if we want this code or the previous...)


<!-- Sent from Reviewable.io -->

2021-02-17 14:06 UTC, JohnThomson reviewed
Had  a couple of thoughts. Not sure what's best to do about fixing the copied text. Maybe the three of us should talk?

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-:-MTkInji4Lk0WsjEomuq:b-uzusj0)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/BloomExe/Book/BookData.cs, line 1385 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTgglQ23Wgp9ZYgbp6x:-MTkF1GpCIqJvFgDK93L:b3q48ec) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d8cb9e47e7629075901572cf3a9a0143c175ece9/src/BloomExe/Book/BookData.cs#L1385)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> I don't think the code is "simpler" if we try to remove the span as the revised code does.

Sigh. Yes, I have to agree.
This requires specific knowledge of all the pieces we might add/remove, and the list could grow in the future without getting modified here.
I also have concerns about the safety of replacing any span/div which doesn't have attributes with its children. span seems pretty safe, but I'm dubious about divs.

@johnthomson, thoughts?

@stephenmcconnel, is this testable? (don't add tests until we decide if we want this code or the previous...)
</blockquote></details>

It sounds easier to remove the audio-sentence markup, but clearly it isn't.  Doing so involves distinctly more code and more knowledge of how audio markup is done. It will save a tiny amount of space in the document if the copy is never recorded, but it will just have to be re-created if we ever do. Something of a toss-up, but I find myself leaning towards the original version. It's all a bit of an edge case...if the user cares enough about this block to think of recording it, they will hopefully replace it with something in the right language, and markup will get redone.
___
*[src/BloomExe/Book/BookData.cs, line 1373 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTkGxPk98TzqATJNLlo:-MTkGxPk98TzqATJNLlp:b-s73pws) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3e7a45bc7e11ef83325cc85336f63b1af6b30599/src/BloomExe/Book/BookData.cs#L1373)):*
> ```Smalltalk
> 								 */
> 			if (!String.IsNullOrEmpty(s) && s.StartsWith("<") && s.EndsWith(">"))
> 			{
> ```

How certain is it that s will start and end with these characters if it contains audio markup? For example, could it start or end with white space? Could there be punctuation before or after the spans? Could there be whole chunks of text outside the audio spans, if the user edited the source since last opening it in the talking book tool?

Leaves me wondering a bit if we should just use a regular expression to replace anything that looks like an id attribute. After all, we're duplicating this content. ANY duplicate ID in a document is technically invalid.


<!-- Sent from Reviewable.io -->

2021-02-17 15:21 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 1373 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTkGxPk98TzqATJNLlo:-MTkZyIU8mXRIDghVaRq:b-tujqxe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3e7a45bc7e11ef83325cc85336f63b1af6b30599/src/BloomExe/Book/BookData.cs#L1373)):*
> Leaves me wondering a bit if we should just use a regular expression to replace anything that looks like an id attribute. 

I came here to say something similar. 1) if we find `<span id='123'>hello</span>` is it actually a problem to leave it as `<span>hello></span`? If not, a regex over the string would do the trick to remove any `id` attributes.


<!-- Sent from Reviewable.io -->

2021-02-17 16:13 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/BloomExe/Book/BookData.cs, line 1385 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTgglQ23Wgp9ZYgbp6x:-MTkkl1-64f8cdaP_-9f:bn5d4a1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d8cb9e47e7629075901572cf3a9a0143c175ece9/src/BloomExe/Book/BookData.cs#L1385)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It sounds easier to remove the audio-sentence markup, but clearly it isn't.  Doing so involves distinctly more code and more knowledge of how audio markup is done. It will save a tiny amount of space in the document if the copy is never recorded, but it will just have to be re-created if we ever do. Something of a toss-up, but I find myself leaning towards the original version. It's all a bit of an edge case...if the user cares enough about this block to think of recording it, they will hopefully replace it with something in the right language, and markup will get redone.
</blockquote></details>

We decided in discussion this morning that we should have a separate method (probably living in HTMLDom) which takes a string and replaces the ids with new ones.

That method, at least, should be easily unit-testable, even if this isn't.


<!-- Sent from Reviewable.io -->

2021-02-17 17:15 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 1385 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTgglQ23Wgp9ZYgbp6x:-MTkzEZu8MbFiYYusZfJ:bsutcup) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d8cb9e47e7629075901572cf3a9a0143c175ece9/src/BloomExe/Book/BookData.cs#L1385)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We decided in discussion this morning that we should have a separate method (probably living in HTMLDom) which takes a string and replaces the ids with new ones.

That method, at least, should be easily unit-testable, even if this isn't.
</blockquote></details>

The code now uses a static method in HtmlDom to set a new id attribute value.
___
*[src/BloomExe/Book/BookData.cs, line 1373 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTkGxPk98TzqATJNLlo:-MTkz83eAdbINau7D-hI:b54z6xn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3e7a45bc7e11ef83325cc85336f63b1af6b30599/src/BloomExe/Book/BookData.cs#L1373)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> Leaves me wondering a bit if we should just use a regular expression to replace anything that looks like an id attribute. 

I came here to say something similar. 1) if we find `<span id='123'>hello</span>` is it actually a problem to leave it as `<span>hello></span`? If not, a regex over the string would do the trick to remove any `id` attributes.
</blockquote></details>

The code no longer checks for the opening/closing markers.


<!-- Sent from Reviewable.io -->

2021-02-17 17:37 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @StephenMcConnel)

___
*[src/BloomExe/Book/BookData.cs, line 1385 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTgglQ23Wgp9ZYgbp6x:-MTl2Jtz7uJDow19iakU:bde9812) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d8cb9e47e7629075901572cf3a9a0143c175ece9/src/BloomExe/Book/BookData.cs#L1385)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The code now uses a static method in HtmlDom to set a new id attribute value.
</blockquote></details>

I thought the plan was to move all this logic to HTMLDom.
I.e., a new method which does: given a string which is assumed to be html, replace all IDs with new ones.

Please unit test that method. (And a relevant pass through this one if feasible.)
___
*[src/BloomExe/Book/HtmlDom.cs, line 130 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTl2qDTAiOHGAXhlWNO:-MTl2qDTAiOHGAXhlWNP:boird3f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e6a9c3f8a6db6b8af6a4f2b81d98a329126c142/src/BloomExe/Book/HtmlDom.cs#L130)):*
> ```Smalltalk
> 				newId = "i" + newId;
> 			element.SetAttribute("id", newId);
> 		}
> ```

Seems like it would be beneficial to have this return the new id.


<!-- Sent from Reviewable.io -->

2021-02-18 19:01 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Book/BookData.cs, line 1385 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTgglQ23Wgp9ZYgbp6x:-MTm3pEl3s_JLGHvvj9A:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d8cb9e47e7629075901572cf3a9a0143c175ece9/src/BloomExe/Book/BookData.cs#L1385)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought the plan was to move all this logic to HTMLDom.
I.e., a new method which does: given a string which is assumed to be html, replace all IDs with new ones.

Please unit test that method. (And a relevant pass through this one if feasible.)
</blockquote></details>

Done.
___
*[src/BloomExe/Book/HtmlDom.cs, line 130 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183#-MTl2qDTAiOHGAXhlWNO:-MTlNwW2D-MT_yr1e7xz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6e6a9c3f8a6db6b8af6a4f2b81d98a329126c142/src/BloomExe/Book/HtmlDom.cs#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like it would be beneficial to have this return the new id.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-18 21:28 UTC, andrew-polk approved these changes
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2021-02-18 21:30 UTC, andrew-polk approved these changes
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-02-19 19:15 UTC, JohnThomson approved these changes
> Reviewed 1 of 2 files at r5, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4183)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-02-23 17:58 UTC, merged