New NotifyUserOfProblem dialog (BL-9102)
BloomBooks/BloomDesktop pull request #4188
Opened 2021-02-10 21:45 UTC by sujeffreyl

2021-02-10 23:34 UTC, andrew-polk requested changes
Submitting partial review in case you want to act on what I've commented on so far.

> Reviewed 15 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-:-MTDHzbi230sqwcK63SZ:b-fwfaih)* status: 15 of 30 files reviewed, 13 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTD7DnHBOyaV6rsobpC:-MTD7DnHBOyaV6rsobpD:bmdtqfv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L42)):*
> ```
> ReportDialog
> ```
So... not that I want to say this, but if we are changing this, shouldn't we change the file and folder name, etc.?
___
*[src/BloomBrowserUI/utils/bloomApi.ts, line 216 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTD4sPF2v0X5c1GVRoV:-MTD4sPGEkcRmzh69q0p:bt7f2am) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomBrowserUI/utils/bloomApi.ts#L216)):*
> ```XML
>     }
> 
>     public static useApiStringIf(
> ```

Deserves a function comment.

But can't you combine this with the above function and a conditional condition?
___
*[src/BloomExe/Edit/EditingModel.cs, line 611 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDCPVyAl11JQwOjVt1:-MTDCPVyAl11JQwOjVt2:b-godkd5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/Edit/EditingModel.cs#L611)):*
> ```Smalltalk
> 		private void CheckForFakeTestErrorsIfNotRealUser()
> 		{
> 			// A real user is defined as one using a Release build and with feedback enabled.
> ```

I'm unsure about this.
Though there probably aren't many, we might have a few real users out there who have found out how and opted out of analytics for security reasons.
How about checking for the useSandbox env var instead?

On the other hand, the titles are soooo unlikely, it probably doesn't matter.
___
*[src/BloomExe/ErrorReporter/CompositeErrorReporter.cs, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDE0hc4aPgORyIm9MD:-MTDE0hc4aPgORyIm9ME:bxygte5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/CompositeErrorReporter.cs#L23)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="primaryReporter">The primaryReporter will be executed first. If an interface method has a return value, the composite will return the value that the primary returns</param>
> 		/// <param name="secondaryReporters">1 or more error reporters, ordered in the order you want them to run.</param>
> ```

The params in the comment don't match the code.
Also, I think there is some inconsistency in comments/code with regard to if the primary happens first or only if it is first in the list of reporters.
___
*[src/BloomExe/ErrorReporter/ErrorReportUtils.cs, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDEl8x3AhK4d-FQNE4:-MTDEl8x3AhK4d-FQNE5:bo2u3u2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/ErrorReportUtils.cs#L10)):*
> ```
> particuarly
> ```
sic
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 90 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDG9Ae89smDQ1F_USQ:-MTDG9Ae89smDQ1F_USR:bxytm9j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L90)):*
> ```
> beofre
> ```
sic
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 90 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDGEEe0G0lPmia6Omh:-MTDGEEe0G0lPmia6Omi:bsatdzw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L90)):*
> ```
> As a result, we work around that by having class instance variables that you set beofre invoking NotifyUserOfProblem
> ```
Wants a period at the end
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDGIuKBcHTyMs_-aLG:-MTDGIuKBcHTyMs_-aLH:bhp5x9e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L91)):*
> ```
> ///··
> ```
Extraneous

But wants a period at the end of the sentence.


Similar issues with the next method's comments.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 110 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDGhlR-RejNMcf01Z4:-MTDGhlR-RejNMcf01Z5:bx7a6ib) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L110)):*
> ```
> Auto-Invoke
> ```
Manual-Invoke?
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 188 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDH4KY7Oq3rbK0rqes:-MTDH4KY7Oq3rbK0rqet:bvkcszg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L188)):*
> ```Smalltalk
> 			}
> 
> 			ErrorReport.NotifyUserOfProblem(policy, error, message, args);
> ```

Probably useful to have the previous method's comment here and in the next method regarding why ErrorReporter.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 290 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDHeBc9KjOWcnZN_hb:-MTDHeBc9KjOWcnZN_hc:blwxm5r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L290)):*
> ```
> Each thread needs to make sure it calls Exit() the same number of times as it calls Enter()
> ```
We conditionally called Enter but unconditionally call Exit. Is that a problem?
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDHZopCfPuD8l5iz0M:-MTDHZopCfPuD8l5iz0N:b3xx1ff) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L291)):*
> ```
> ock
> ```
sic
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 295 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDHwTZ2sC-jCaaYjO4:-MTDHwTZ2sC-jCaaYjO5:b-5gr4p3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L295)):*
> ```Smalltalk
> 			}
> 		}
> ```

Note to self: I got this far in this file.


<!-- Sent from Reviewable.io -->

2021-02-11 15:25 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 8 of 31 files reviewed, 13 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/problemDialog/ProblemDialog.tsx, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTD7DnHBOyaV6rsobpC:-MTGWwVGD5SQaZk70Bzy:b-yrtrvp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L42)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> ReportDialog
> ```
So... not that I want to say this, but if we are changing this, shouldn't we change the file and folder name, etc.?
</blockquote></details>

My thinking is that ReportDialog and NotifyDialog are both types of problem dialogs. So, I think the folder name is good as ProblemReport. I split out the ReportDialog class into its own file now though.
___
*[src/BloomBrowserUI/utils/bloomApi.ts, line 216 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTD4sPF2v0X5c1GVRoV:-MTGSqoA0S3P2QVZNxZE:b8602l6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomBrowserUI/utils/bloomApi.ts#L216)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Deserves a function comment.

But can't you combine this with the above function and a conditional condition?
</blockquote></details>

Combined the two into 1 function with an optional parameter.
___
*[src/BloomExe/Edit/EditingModel.cs, line 611 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDCPVyAl11JQwOjVt1:-MTGgdvIBXM9YqpEbuHX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/Edit/EditingModel.cs#L611)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm unsure about this.
Though there probably aren't many, we might have a few real users out there who have found out how and opted out of analytics for security reasons.
How about checking for the useSandbox env var instead?

On the other hand, the titles are soooo unlikely, it probably doesn't matter.
</blockquote></details>

Done.
___
*[src/BloomExe/ErrorReporter/CompositeErrorReporter.cs, line 23 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDE0hc4aPgORyIm9MD:-MTGTkepB45CV2eFPyPE:b-iy116a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/CompositeErrorReporter.cs#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The params in the comment don't match the code.
Also, I think there is some inconsistency in comments/code with regard to if the primary happens first or only if it is first in the list of reporters.
</blockquote></details>

Done.

(FYI, primary does not need to be first)
___
*[src/BloomExe/ErrorReporter/ErrorReportUtils.cs, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDEl8x3AhK4d-FQNE4:-MTGUDgwDKleqOK5QOGt:bi79dq6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/ErrorReportUtils.cs#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> particuarly
> ```
sic
</blockquote></details>

Fixed.
Fun fact, sic actually means like "thus it was written", indicating that it was copied verbatim (typo and all), and doesn't literally mean typo
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 90 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDG9Ae89smDQ1F_USQ:-MTGUSNB61JAmPa69ITR:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L90)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> beofre
> ```
sic
</blockquote></details>

Done.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 90 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDGEEe0G0lPmia6Omh:-MTGUUWY0UNPAPoFpvlP:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L90)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> As a result, we work around that by having class instance variables that you set beofre invoking NotifyUserOfProblem
> ```
Wants a period at the end
</blockquote></details>

Done.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 91 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDGIuKBcHTyMs_-aLG:-MTGU_to3-FVEVk0hb2U:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L91)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> ///··
> ```
Extraneous

But wants a period at the end of the sentence.


Similar issues with the next method's comments.
</blockquote></details>

Done.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 110 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDGhlR-RejNMcf01Z4:-MTGUgpME57b1TGMdBwp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Auto-Invoke
> ```
Manual-Invoke?
</blockquote></details>

Done.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 188 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDH4KY7Oq3rbK0rqes:-MTGUrgKEw61EQI_C1ca:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L188)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably useful to have the previous method's comment here and in the next method regarding why ErrorReporter.
</blockquote></details>

Done.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 290 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDHeBc9KjOWcnZN_hb:-MTGUxF91MjhUzljYCvp:bru8d5h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L290)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Each thread needs to make sure it calls Exit() the same number of times as it calls Enter()
> ```
We conditionally called Enter but unconditionally call Exit. Is that a problem?
</blockquote></details>

We don't call Enter() if it's already entered, which is supposed to imply (for us) that Enter() has been called once to this point. That means we only need to call Exit() once here.   (the previous caller of Enter() doesn't exit() unless it encounters a problem prior to calling this function.

Hmm, on the other hand, I guess I could make it so that whichever function calls Enter() also has the responsibility of calling Exit(). Hmm... that sounds easier to keep straight. Let me do that.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDHZopCfPuD8l5iz0M:-MTGUwep9c1YEpthHFZn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L291)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> ock
> ```
sic
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-15 16:31 UTC, andrew-polk requested changes
> Reviewed 12 of 30 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 30 of 31 files reviewed, 8 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 47 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaJ1GF0xqbTAv2TB1A:-MTaJ1GF0xqbTAv2TB1B:b-aiq43z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L47)):*
> ```XML
>                 //fullWidth={true}
>                 maxWidth={"md"}
>                 fullScreen={true}
> ```

I started asking for clarifications on the previous 4 lines but then saw you just copied from the other dialog.
___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 196 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaSSvq46-Es8KdOhS_:-MTaSSvq46-Es8KdOhSa:bdja792) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L196)):*
> ```XML
> // 1) HTML-encoded (so, theoretically safe to pass into InnerHTML)
> // 2) newlines and carriage returns are converted into <br> elements.
> function formatForHtml(unsafeText: string): string {
> ```

Is there a better, common place to put this bit of code?
Seems like at least problemDialog, but maybe even higher?
___
*[src/BloomExe/Edit/EditingModel.cs, line 611 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDCPVyAl11JQwOjVt1:-MTGvq7S1uOwjr-0n7Xw:b-dwep24) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/Edit/EditingModel.cs#L611)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. Comment needs updating.
___
*[src/BloomExe/ErrorReporter/ErrorReportUtils.cs, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDEl8x3AhK4d-FQNE4:-MTGttV644sTn8AegAh2:b-3nen79) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/ErrorReporter/ErrorReportUtils.cs#L10)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Fixed.
Fun fact, sic actually means like "thus it was written", indicating that it was copied verbatim (typo and all), and doesn't literally mean typo
</blockquote></details>

Ah, thanks. I kind of suspected I was misusing that but that it would be understood anyway. I was right on both accounts!
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 304 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaTHjT2c6_u10DEM-P:-MTaTHjT2c6_u10DEM-Q:b-69awri) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L304)):*
> ```
> need
> ```
needed
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 313 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaTRuAD4P9giK4lB_U:-MTaTRuAD4P9giK4lB_V:b-wzqzxj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L313)):*
> ```
> insetad
> ```
instead
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 321 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaTu8969a9HHZQmg0y:-MTaTu8969a9HHZQmg0z:b-ypkk65) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L321)):*
> ```
> // REVIEW: Is GetControlToUse() logic OK for getting which form to use?
> ```
I don't know of a way to improve it.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 444 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaVQ8r2XNqRozfaKqI:-MTaVQ8r2XNqRozfaKqJ:bodahz9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L444)):*
> ```
> fllow
> ```
follow

Out of curiosity, is your IDE showing these typos? Mine seems to be configured to show typos in comments.
___
*[src/BloomExe/MiscUI/BrowserDialog.cs, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaDjd-82Aot0EkUZ17:-MTaDjd-82Aot0EkUZ18:bhu1qk0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/MiscUI/BrowserDialog.cs#L9)):*
> ```
> interfaces
> ```
interface
___
*[src/BloomTests/DataBuilders/HtmlErrorReporterBuilder.cs, line 10 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTNBwwbAWCzBNet8R4w:-MTNBwwbAWCzBNet8R4x:b-7aindz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomTests/DataBuilders/HtmlErrorReporterBuilder.cs#L10)):*
> ```
> facilatate 
> ```
facilitate


<!-- Sent from Reviewable.io -->

2021-02-15 16:39 UTC, andrew-polk requested changes
> Reviewed 1 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 9 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomTests/ErrorReporter/HtmlErrorReporterTests.cs, line 69 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaXT2i6Hds9vMD64gE:-MTaXT2j0xpRY1549ria:bvihhey) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomTests/ErrorReporter/HtmlErrorReporterTests.cs#L69)):*
> ```
> fheck
> ```
check


<!-- Sent from Reviewable.io -->

2021-02-17 17:34 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 25 of 32 files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 196 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaSSvq46-Es8KdOhS_:-MTknfmJ8v7CR6jxn0p2:b1imtj4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L196)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is there a better, common place to put this bit of code?
Seems like at least problemDialog, but maybe even higher?
</blockquote></details>

I was trying to dodge responsibility for ensuring that it works safely for every scenario haha.
I created a file utils/encodingUtils.ts and put it there (as a  simple function export)
___
*[src/BloomExe/Edit/EditingModel.cs, line 611 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTDCPVyAl11JQwOjVt1:-MTko2_82fdAgqptmLKp:b-886gsx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1cc991d45b6abba58a4f4cc026366d85c7ea9d56/src/BloomExe/Edit/EditingModel.cs#L611)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. Comment needs updating.
</blockquote></details>

Fixed
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 304 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaTHjT2c6_u10DEM-P:-MTkqJDGEvMage9cEDH0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L304)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> need
> ```
needed
</blockquote></details>

Done.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 313 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaTRuAD4P9giK4lB_U:-MTkqM6n81boGf1-krbr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L313)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> insetad
> ```
instead
</blockquote></details>

Done.
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 444 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaVQ8r2XNqRozfaKqI:-MTkqxRQ4axUWSwyL_wz:b-vrv9qp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L444)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> fllow
> ```
follow

Out of curiosity, is your IDE showing these typos? Mine seems to be configured to show typos in comments.
</blockquote></details>

No. I just installed some spell check extensions... although, then I realized I'll need to do it again later when I'm back on my desktop.
___
*[src/BloomExe/MiscUI/BrowserDialog.cs, line 9 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaDjd-82Aot0EkUZ17:-MTkrwahBJ4uZFnziDh3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomExe/MiscUI/BrowserDialog.cs#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> interfaces
> ```
interface
</blockquote></details>

Done.
___
*[src/BloomTests/DataBuilders/HtmlErrorReporterBuilder.cs, line 10 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTNBwwbAWCzBNet8R4w:-MTks9B45xicb2MQbkuu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomTests/DataBuilders/HtmlErrorReporterBuilder.cs#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> facilatate 
> ```
facilitate
</blockquote></details>

Done.
___
*[src/BloomTests/ErrorReporter/HtmlErrorReporterTests.cs, line 69 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MTaXT2i6Hds9vMD64gE:-MTksEF_4wQ_zI14Eoc-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/fd00e3edc4f58703b1eba8c711f30253bc5929d2/src/BloomTests/ErrorReporter/HtmlErrorReporterTests.cs#L69)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> fheck
> ```
check
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-17 17:43 UTC, andrew-polk approved these changes
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-02-17 20:41 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-02-26 21:53 UTC, hatton requested changes
> Reviewed 7 of 30 files at r1, 5 of 10 files at r2, 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[src/BloomExe/Edit/EditingModel.cs, line 612 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVKCDo-JQZ0SIhzFeH:-MUVKCDo-JQZ0SIhzFeI:b-58pxzi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/Edit/EditingModel.cs#L612)):*
> ```Smalltalk
> 		private void CheckForFakeTestErrorsIfNotRealUser()
> 		{
> 			// A real user is defined as one using a Release build and not using Sandbox mode.
> ```

It seems dangerous to have different code paths for Release vs. Beta?


<!-- Sent from Reviewable.io -->

2021-02-26 22:11 UTC, hatton requested changes
> Reviewed 4 of 30 files at r1, 2 of 10 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Edit/EditingModel.cs, line 610 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVKRdN6kzV-xuPVW8N:-MUVKRdN6kzV-xuPVW8O:b-5symx9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/Edit/EditingModel.cs#L610)):*
> ```Smalltalk
> 		}
> 
> 		private void CheckForFakeTestErrorsIfNotRealUser()
> ```

It's unfortunate that this much code, unrelated to what the EditingModel does, lives in that code file?
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 322 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVMUlt2sXimau30cyw:-MUVMUlt2sXimau30cyx:b-v8metb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L322)):*
> ```Smalltalk
> 		{
> 			var message = String.Format(messageFormat, args);
> 			ProblemReportApi.ShowProblemDialog(GetControlToUse(), error, message , ProblemLevel.kNonFatal);
> ```

You didn't do this, I did. But that won't stop me from expressing how grumpy it makes me to see that we have UI code in SOMETHING NAMED "...API".  I should be fired.
___
*[src/BloomExe/web/RequestInfo.cs, line 54 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVOIZt8mjiqHHb1f7R:-MUVOIZu5slvOSfnAs0B:bkn0ppt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/RequestInfo.cs#L54)):*
> ```Smalltalk
> 
> 		// Gets the Content Type of the REQUEST
> 		public string RequestContentType
> ```

I don't understand why we have a `RequestContentType` for getting, and a `ContentType` for setting?


<!-- Sent from Reviewable.io -->

2021-02-26 22:27 UTC, hatton commented on src/BloomBrowserUI/problemDialog/ProblemDialog.tsx
> +    Notify = "Notify",
Please ignore, this is a test

2021-02-26 22:47 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 6 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/ApiRequest.cs, line 224 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVVI2E-lZpnNC26fCw:-MUVVI2F33Z741Jp-UuG:ba5i718) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/ApiRequest.cs#L224)):*
> ```Smalltalk
> 		}
> 
> 		public string GetContentType() => _requestInfo.RequestContentType;
> ```

Ah so now we have 3 variations: `RequestContentType` & `ContentType` in `RequestInfo.cs`, and here `GetContentType`  :-)
___
*[src/BloomExe/web/controllers/ApiRequest.cs, line 253 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVVq1aBWxYNfE3p0Rk:-MUVVq1aBWxYNfE3p0Rl:bd1dzga) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/ApiRequest.cs#L253)):*
> ```Smalltalk
> 		/// <returns>If the request's content type is "application/json", returns the data as a JSON string
> 		/// If the request's content type is not "application/json", returns null instead</returns>
> 		public string OptionalPostJson()
> ```

This follows the pattern set by `RequiredPostString()`, but I tripped over it mightily. How about `GetPostJsonOrNull` ?


<!-- Sent from Reviewable.io -->

2021-02-26 22:53 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 7 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 12 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVXDOP7Cia6s4xnxaD:-MUVXDOP7Cia6s4xnxaE:b-p2mllt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/BrowserDialogApi.cs#L12)):*
> ```Smalltalk
> 		// Consumers that read LastCloseSource should make sure to reset LastCloseSource prior to showing the BrowserDialog.
> 		// If the uses closes the dialog uses the WinForms X close button, this class's dialog/close handler will not be invoked.
> 		static internal string LastCloseSource { get; set; }
> ```

 I think this means "some static place to put some text that remembers for you which control (or keyboard?) the user used to dismiss the dialog"? But that's feeling vauge?

 I know I'm supposed to reset it (that's unfortunate, I suppose this has to be static for some reason?) What are examples of `CloseSource`s? 


<!-- Sent from Reviewable.io -->

2021-02-26 22:57 UTC, hatton reviewed
> Reviewed 1 of 30 files at r1, 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 7 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/RequestInfo.cs, line 54 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVOIZt8mjiqHHb1f7R:-MUVYf-75F2MOls-2tCg:b-4fk0il) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/RequestInfo.cs#L54)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't understand why we have a `RequestContentType` for getting, and a `ContentType` for setting?
</blockquote></details>

Oh, ok an hour later I see it. So should we rename `ContentType` as `ResponseContentType`?


<!-- Sent from Reviewable.io -->

2021-02-26 22:58 UTC, hatton reviewed
> Reviewed 2 of 30 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 8 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomTests/PretendRequestInfo.cs, line 43 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVZ4k43BCwCNSo3Qki:-MUVZ4k43BCwCNSo3Qkj:bns4vke) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomTests/PretendRequestInfo.cs#L43)):*
> ```Smalltalk
> 
> 		public string RequestContentType { get; }
> 		public string ContentType { private get; set; }
> ```

Should this become `ResponseContentType` ?


<!-- Sent from Reviewable.io -->

2021-02-26 23:02 UTC, hatton reviewed
> Reviewed 4 of 30 files at r1, 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 9 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 417 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVZLjJ4CeOEkgVtUvX:-MUVZLjJ4CeOEkgVtUvY:bj2skfd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/ProblemReportApi.cs#L417)):*
> ```Smalltalk
> 				try
> 				{
> 					var query = $"?level={levelOfProblem}";
> ```

I'm curious, why use the url to  pass some parameters when the react component is going to turn around and use this api to get information anyhow? 


<!-- Sent from Reviewable.io -->

2021-02-26 23:02 UTC, hatton reviewed
> Reviewed 2 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 9 unresolved discussions (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-03-01 23:30 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 24 of 32 files reviewed, 9 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/Edit/EditingModel.cs, line 610 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVKRdN6kzV-xuPVW8N:-MUjz0n4Abz-UfkDQKzb:b-rpxkm7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/Edit/EditingModel.cs#L610)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's unfortunate that this much code, unrelated to what the EditingModel does, lives in that code file?
</blockquote></details>

Moved to its own file
___
*[src/BloomExe/Edit/EditingModel.cs, line 612 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVKCDo-JQZ0SIhzFeH:-MUjz5J62qVhCQHtZL5m:b15ka3d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/Edit/EditingModel.cs#L612)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It seems dangerous to have different code paths for Release vs. Beta?
</blockquote></details>

This is about Release vs Debug builds, not Release vs Beta builds. Bloom Release, Bloom Beta, and Bloom Alpha are both built under the Release configuration as far as msbuild or Visual Studio are concerned.
Do you also have a concern about Release vs Debug?  (We would automatically find out if there's a build error because the TC build would compile under Release.)
___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 322 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVMUlt2sXimau30cyw:-MUk-7wG4WnkYRsumE4a:b1vvh2m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L322)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

You didn't do this, I did. But that won't stop me from expressing how grumpy it makes me to see that we have UI code in SOMETHING NAMED "...API".  I should be fired.
</blockquote></details>

Ahh yeah... I was thinking it would make better sense here in HtmlErrorReporter, but then I abandoned doing that right away after I spent a long time working on this...
___
*[src/BloomExe/web/RequestInfo.cs, line 54 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVOIZt8mjiqHHb1f7R:-MUk-J85DfwmYVQxYSOu:b-an8802) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/RequestInfo.cs#L54)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Oh, ok an hour later I see it. So should we rename `ContentType` as `ResponseContentType`?
</blockquote></details>

I would prefer that.
___
*[src/BloomExe/web/controllers/ApiRequest.cs, line 224 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVVI2E-lZpnNC26fCw:-MUk05pK1L2Se6OrBr__:b-bj7hv0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/ApiRequest.cs#L224)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Ah so now we have 3 variations: `RequestContentType` & `ContentType` in `RequestInfo.cs`, and here `GetContentType`  :-)
</blockquote></details>

Ah, well I started here and this was an ApiRequest so there wasn't a need to distinguish which one.  I can just make it match RequestContentType though.
___
*[src/BloomExe/web/controllers/ApiRequest.cs, line 253 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVVq1aBWxYNfE3p0Rk:-MUk0gwT6E5z7vwgVBlt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/ApiRequest.cs#L253)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

This follows the pattern set by `RequiredPostString()`, but I tripped over it mightily. How about `GetPostJsonOrNull` ?
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 12 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVXDOP7Cia6s4xnxaD:-MUk19586Su7xs9Wk1pA:b4ncsl5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/BrowserDialogApi.cs#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

 I think this means "some static place to put some text that remembers for you which control (or keyboard?) the user used to dismiss the dialog"? But that's feeling vauge?

 I know I'm supposed to reset it (that's unfortunate, I suppose this has to be static for some reason?) What are examples of `CloseSource`s? 
</blockquote></details>

Yes, that's pretty much right.
Regarding vagueness: I guess since I put it in BrowserDialog, it needs to be vague enough to be generic for any BrowserDialog.  Another option I had is that I could put a more specific API in ProblemReportApi, like SetLastCloseSource.   For the JS code, before closing the dialog, it would need to also call SetLastCloseSource and wait for it to return.

Does it have to be static?  Well, TECHNICALLY since I think we only construct one instance of BrowserDialogApi so technically it could be instance, but that wouldn't really help the issue that the Bloom program as a whole shares the same variable.
One thought about auto-resetting it... We could put have BrowserDialog's constructor automatically reset it. As long as we don't have multiple BrowserDialogs up at once, it should work.

Examples: Right now, "report" or "alternate" (As in this hypothetical Secondary/Alternate Action button that could be like "Retry")
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 417 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVZLjJ4CeOEkgVtUvX:-MUk3bVe1aZnf-nH072g:b-5boy77) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/ProblemReportApi.cs#L417)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm curious, why use the url to  pass some parameters when the react component is going to turn around and use this api to get information anyhow? 
</blockquote></details>

This isn't new, so your question is about the original code.

Two minor benefits I see though:
* I guess the React component can probably start rendering faster by just doing some string processing in JS land compared to making an API localhsot call before deciding which component to even start with?
* Personally I prefer to develop / debug with a complete URL. I like that I can easily see what it's supposed to be doing. If you go all the way with it (like the new Notify code does), then you don't even need Bloom to be in a specific situation... it just needs to be open and you can enter in the appropriate URL and see what it looks like. You can also change parameters this way with less setup.  (Of course, in this part of ProblemReportApi, you require both the URL parameters and the Bloom API, so... maybe a lose-lose).
___
*[src/BloomTests/PretendRequestInfo.cs, line 43 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVZ4k43BCwCNSo3Qki:-MUk4uWz3A0e9eQ9Mwqu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomTests/PretendRequestInfo.cs#L43)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Should this become `ResponseContentType` ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-02 19:14 UTC, andrew-polk approved these changes
> Reviewed 8 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 9 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-03-03 22:43 UTC, andrew-polk approved these changes
> Reviewed 4 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 9 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-03-04 22:21 UTC, hatton requested changes
> Reviewed 1 of 8 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[src/BloomExe/Edit/EditingModel.cs, line 612 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVKCDo-JQZ0SIhzFeH:-MUzFYHM9MGaq3RmsiG0:bnlasfd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/Edit/EditingModel.cs#L612)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This is about Release vs Debug builds, not Release vs Beta builds. Bloom Release, Bloom Beta, and Bloom Alpha are both built under the Release configuration as far as msbuild or Visual Studio are concerned.
Do you also have a concern about Release vs Debug?  (We would automatically find out if there's a build error because the TC build would compile under Release.)
</blockquote></details>

OK Thx.
___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 12 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVXDOP7Cia6s4xnxaD:-MUzGL-I6kluUwS7NE_Z:b-5a9zn3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/BrowserDialogApi.cs#L12)):*
> We could put have BrowserDialog's constructor automatically reset it.

I guess resetting doesn't actually do us any good? The real problem is that you can close the dialog without providing this parameter? So I think we're good here and I'll make a comment a few lines down...
___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 23 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUzHEh-AptUDsV3Dplr:-MUzHEh-AptUDsV3Dpls:boaxx5o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/910e13f97036e7611dea3a27498f4d143b773f39/src/BloomExe/web/controllers/BrowserDialogApi.cs#L23)):*
> ```Smalltalk
> 
> 					LastCloseSource = null;	// First reset the source, in case of any parsing errors
> 					var postData = ParseCloseData(request);
> ```

How about we simplify all this with, on the web side, `BloomApi.postString(.., "something or empty if you don't care")` and here in c#,`LastCloseSource = request.RequiredPostString();`. 
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 417 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVZLjJ4CeOEkgVtUvX:-MUzK8N40Syf2-guItfV:b-dwl9pj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/ProblemReportApi.cs#L417)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This isn't new, so your question is about the original code.

Two minor benefits I see though:
* I guess the React component can probably start rendering faster by just doing some string processing in JS land compared to making an API localhsot call before deciding which component to even start with?
* Personally I prefer to develop / debug with a complete URL. I like that I can easily see what it's supposed to be doing. If you go all the way with it (like the new Notify code does), then you don't even need Bloom to be in a specific situation... it just needs to be open and you can enter in the appropriate URL and see what it looks like. You can also change parameters this way with less setup.  (Of course, in this part of ProblemReportApi, you require both the URL parameters and the Bloom API, so... maybe a lose-lose).
</blockquote></details>

OK thanks.  Good reasons (especially #2).


<!-- Sent from Reviewable.io -->

2021-03-05 22:42 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 30 of 33 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 12 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUVXDOP7Cia6s4xnxaD:-MV3VTzn7r6qo3B_-wP2:brfhftr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9355da31004f25d65c7b7967ca83a425f632f450/src/BloomExe/web/controllers/BrowserDialogApi.cs#L12)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> We could put have BrowserDialog's constructor automatically reset it.

I guess resetting doesn't actually do us any good? The real problem is that you can close the dialog without providing this parameter? So I think we're good here and I'll make a comment a few lines down...
</blockquote></details>

Yes, the real problem is closing the dialog via the WinForms x doesn't provide the parameter.
___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 23 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUzHEh-AptUDsV3Dplr:-MV3VOi02b4VyKtedhH6:b6zqpco) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/910e13f97036e7611dea3a27498f4d143b773f39/src/BloomExe/web/controllers/BrowserDialogApi.cs#L23)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

How about we simplify all this with, on the web side, `BloomApi.postString(.., "something or empty if you don't care")` and here in c#,`LastCloseSource = request.RequiredPostString();`. 
</blockquote></details>

Done, more magic values though...


<!-- Sent from Reviewable.io -->

2021-03-05 23:00 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 30 of 33 files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @hatton, and @sujeffreyl)

___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 23 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUzHEh-AptUDsV3Dplr:-MV3bZnv4Nz5NyOmYc46:bauuebm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/910e13f97036e7611dea3a27498f4d143b773f39/src/BloomExe/web/controllers/BrowserDialogApi.cs#L23)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Done, more magic values though...
</blockquote></details>

Say more.... what's the magic ? 


<!-- Sent from Reviewable.io -->

2021-03-05 23:23 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 30 of 33 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 23 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUzHEh-AptUDsV3Dplr:-MV3gnnB6geAn7XmQAM9:b-fkyvh0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/910e13f97036e7611dea3a27498f4d143b773f39/src/BloomExe/web/controllers/BrowserDialogApi.cs#L23)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Say more.... what's the magic ? 
</blockquote></details>

I mean the JS code just has a random string literal, at least before it was annotated with a field name to somewhat explain it.


<!-- Sent from Reviewable.io -->

2021-03-05 23:25 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 162 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MV3gql93iZE9mU8mbPu:-MV3gqlA64dN7wRsuAWa:b-e9jxuh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6eba092ec74c99e32b99b7692ca2df6b6b545d4e/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L162)):*
> ```
> BloomApi.postString("dialog/close", "report"); // The value is the close source
> ```
Since you wrote this code, we have two new handlers:
```
 			// At this point we open dialogs from c# code; if we opened dialog from javascript, we wouldn't need this
			// api to do it. We just need a way to close a c#-opened dialog from javascript (e.g. the Close button of the dialog).
			apiHandler.RegisterEndpointHandler("common/closeReactDialog", request =>
			{
				CurrentDialog?.Close();
				request.PostSucceeded();
			}, true);

			// TODO: move to the new App API (BL-9635)
			apiHandler.RegisterEndpointHandler("common/reloadCollection", HandleReloadCollection, true);
```
Helpful?


<!-- Sent from Reviewable.io -->

2021-03-05 23:26 UTC, andrew-polk commented
___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 162 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MV3gql93iZE9mU8mbPu:-MV3hcuO41z3MuJpEfCt:bgrctdb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6eba092ec74c99e32b99b7692ca2df6b6b545d4e/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L162)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BloomApi.postString("dialog/close", "report"); // The value is the close source
> ```
Since you wrote this code, we have two new handlers:
```
 			// At this point we open dialogs from c# code; if we opened dialog from javascript, we wouldn't need this
			// api to do it. We just need a way to close a c#-opened dialog from javascript (e.g. the Close button of the dialog).
			apiHandler.RegisterEndpointHandler("common/closeReactDialog", request =>
			{
				CurrentDialog?.Close();
				request.PostSucceeded();
			}, true);

			// TODO: move to the new App API (BL-9635)
			apiHandler.RegisterEndpointHandler("common/reloadCollection", HandleReloadCollection, true);
```
Helpful?
</blockquote></details>

Oops. Ignore that second one.


<!-- Sent from Reviewable.io -->

2021-03-05 23:41 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 23 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUzHEh-AptUDsV3Dplr:-MV3kHGH6pR3DSuczCZz:b-jbpbdu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/910e13f97036e7611dea3a27498f4d143b773f39/src/BloomExe/web/controllers/BrowserDialogApi.cs#L23)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I mean the JS code just has a random string literal, at least before it was annotated with a field name to somewhat explain it.
</blockquote></details>

Maybe I misread or maybe we had a misunderstanding... as I recall, it was always just a string, not an enum or whatever. What I asked for was going from a json object with a single element plus code to produce and then parse that object, to simply the one value, by itself.

I actually can't tell in reviewable here that the code changed, but you said "Done".  By now I know not to trust what I see here. So I'm confused.


<!-- Sent from Reviewable.io -->

2021-03-05 23:47 UTC, hatton approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 23 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUzHEh-AptUDsV3Dplr:-MV3lZwV1XKTxULFw_G0:bq47onx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/910e13f97036e7611dea3a27498f4d143b773f39/src/BloomExe/web/controllers/BrowserDialogApi.cs#L23)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Maybe I misread or maybe we had a misunderstanding... as I recall, it was always just a string, not an enum or whatever. What I asked for was going from a json object with a single element plus code to produce and then parse that object, to simply the one value, by itself.

I actually can't tell in reviewable here that the code changed, but you said "Done".  By now I know not to trust what I see here. So I'm confused.
</blockquote></details>

Ahah! After clicking randomly around reviewable I see the change.  So now were back to me not understanding what is more magic about the current state. Didn't the original code also have a random string literal?


<!-- Sent from Reviewable.io -->

2021-03-06 00:16 UTC, andrew-polk reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 23 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUzHEh-AptUDsV3Dplr:-MV3sctu8ys9sv0ZSMEQ:b-cgdchr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/910e13f97036e7611dea3a27498f4d143b773f39/src/BloomExe/web/controllers/BrowserDialogApi.cs#L23)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Ahah! After clicking randomly around reviewable I see the change.  So now were back to me not understanding what is more magic about the current state. Didn't the original code also have a random string literal?
</blockquote></details>

I think Jeffrey's saying that before the json payload was 
 ```
                                 {
                                     source: "report"
                                 }
 ```
but now it is `report`.
So we lost the context of `source` telling us what it is.
But that's probably worth the simplicity, imo.


<!-- Sent from Reviewable.io -->

2021-03-06 18:21 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 162 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MV3gql93iZE9mU8mbPu:-MV7jY626JVWSuyeSkxZ:b-eyqvxc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6eba092ec74c99e32b99b7692ca2df6b6b545d4e/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L162)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Oops. Ignore that second one.
</blockquote></details>

Well, that is for ReactDialog not BrowserDialog, which I think was written after I started working on this.   (dialog/close predates common/closeReactDialog).  It won't work out of the box for this.  They don't hit the same static variables.  (Also, closeReactDialog doesn't have any concept of close source yet, so that wouldn't be any different for solving the Sending-The-Close-Source value problem)

However, there are probably multiple cases (including right here) where BrowserDialog could be replaced by ReactDialog.  If we want to bundle that work together then... I mean sure, I can convert the existing ProblemReportDialog to use ReactDialog instead, and then I can make closeReactDialog look for the close source instead of BrowserDialog.  I'd say that's moving where something happens (equivalent) and then doing some future follow-up now instead of later, so in terms of overall I think it's equivalent but not any easier or harder.


<!-- Sent from Reviewable.io -->

2021-03-06 18:21 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/web/controllers/BrowserDialogApi.cs, line 23 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MUzHEh-AptUDsV3Dplr:-MV7lT_I5wNJ22o_b66r:b-81la7d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/910e13f97036e7611dea3a27498f4d143b773f39/src/BloomExe/web/controllers/BrowserDialogApi.cs#L23)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think Jeffrey's saying that before the json payload was 
 ```
                                 {
                                     source: "report"
                                 }
 ```
but now it is `report`.
So we lost the context of `source` telling us what it is.
But that's probably worth the simplicity, imo.
</blockquote></details>

Right


<!-- Sent from Reviewable.io -->

2021-03-08 19:09 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 162 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MV3gql93iZE9mU8mbPu:-MVIEPk44mbcruI_nyVP:b-lhrdwz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6eba092ec74c99e32b99b7692ca2df6b6b545d4e/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L162)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Well, that is for ReactDialog not BrowserDialog, which I think was written after I started working on this.   (dialog/close predates common/closeReactDialog).  It won't work out of the box for this.  They don't hit the same static variables.  (Also, closeReactDialog doesn't have any concept of close source yet, so that wouldn't be any different for solving the Sending-The-Close-Source value problem)

However, there are probably multiple cases (including right here) where BrowserDialog could be replaced by ReactDialog.  If we want to bundle that work together then... I mean sure, I can convert the existing ProblemReportDialog to use ReactDialog instead, and then I can make closeReactDialog look for the close source instead of BrowserDialog.  I'd say that's moving where something happens (equivalent) and then doing some future follow-up now instead of later, so in terms of overall I think it's equivalent but not any easier or harder.
</blockquote></details>

If we can, without undue problems, make use of ReactDialog now that we have it, I think we should. Open to discussion.


<!-- Sent from Reviewable.io -->

2021-03-10 21:41 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 13 of 39 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 162 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MV3gql93iZE9mU8mbPu:-MVT3z3t8fid7TDJMruy:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6eba092ec74c99e32b99b7692ca2df6b6b545d4e/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L162)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If we can, without undue problems, make use of ReactDialog now that we have it, I think we should. Open to discussion.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-10 22:17 UTC, andrew-polk approved these changes
> Reviewed 26 of 26 files at r9.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/problemDialog/NotifyDialog.tsx, line 162 at r7](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MV3gql93iZE9mU8mbPu:-MVTCkam1oRmqXd0-6SI:b-iz03xr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/6eba092ec74c99e32b99b7692ca2df6b6b545d4e/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L162)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. That was a lot of work, but I think worth it going forward!


<!-- Sent from Reviewable.io -->

2021-03-11 15:23 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: 39 of 41 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/CollectionTab/LibraryView.cs, line 91 at r10](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188#-MVWsX6H9F09romy4qXm:-MVWsX6H9F09romy4qXn:bttuwyx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e956c75bc6458dd0c7b64109bb6aa16c0bd82304/src/BloomExe/CollectionTab/LibraryView.cs#L91)):*
> ```Smalltalk
> 				// Later we may implement some efficient way to scroll through them.
> 				// tcManager.CurrentCollection?.MessageLog?.LoadSavedMessages();
> 				using (var dlg = new ReactDialog("teamCollectionSettingsBundle.js", "TeamCollectionDialog"))
> ```

Even though one of the John's didn't dispose of it, but from looking at it I think it ought to be disposed?


<!-- Sent from Reviewable.io -->

2021-03-14 00:38 UTC, hatton approved these changes
> Reviewed 5 of 8 files at r5, 1 of 4 files at r6, 1 of 3 files at r7, 26 of 26 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-03-14 00:38 UTC, hatton approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4188)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-03-14 00:40 UTC, merged