Team Collections - Add checkout status icon over book list
BloomBooks/BloomDesktop pull request #4235
Opened 2021-02-24 23:28 UTC by sujeffreyl

2021-02-25 14:19 UTC, JohnThomson requested changes
We need unit tests verifying that changed files result in sending the new events.
I think we will eventually want something to push these events into a queue, and all substantial work (like copying files to local and updating UI) will be done by an idle task that pulls from the queue in the UI thread. Doing that isn't necessarily part of this task, but if going ahead with it makes it easier to deal with any of the points I raised, you could consider doing so.
Overall this is a nice bit of work. I've made quite a few comments but I think they are mostly minor improvements.

> Reviewed 20 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-:-MUOWKY1-1pmDO8EkjFM:bczod3e)* status: all files reviewed, 15 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Event.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUODg7DBAg8xtH2eZFk:-MUODg7DBAg8xtH2eZFl:b-cp36f4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/Event.cs#L253)):*
> ```Smalltalk
> 	}
> 
> 	public class TeamCollectionCheckoutStatusChangeEvent : Event<CheckoutStatusChangeEventArgs>
> ```

Name suggests to me that the whole TC is being checked out. TeamCollectionBookCheckoutStatusChangeEvent is very long...what would you think of just BookCheckoutStatusChangeEvent?
Anything useful to say by way of class comment? I know it's very small...
___
*[src/BloomExe/Collection/BookCollection.cs, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOEWbED1O-D5jllK19:-MUOEWbED1O-D5jllK1A:bm3mzyx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/Collection/BookCollection.cs#L33)):*
> ```Smalltalk
> 		public BookCollection()
> 		{
> 			_bookInfos = null;
> ```

This would be the default anyway?
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1091 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOFEHfCygmtLy5OowC:-MUOFEHfCygmtLy5OowD:bohju8g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1091)):*
> ```Smalltalk
> 			if (IsPrimaryCollectionAddingButtons())
> 			{
> 				Task.Delay(100).ContinueWith(unused =>					
> ```

trailing white space
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1116 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOG0pTBVFhNIqs9V0T:-MUOG0pTBVFhNIqs9V0U:bngaymu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1116)):*
> ```Smalltalk
> 			var bookInfos = _primaryCollection.GetBookInfos();
> 			// QuickTitle relies just on the folder name, so I think that should align better with eventArgs.BookName than {bookInfo.Title} would.
> 			var targetBookInfo = bookInfos.Where(bookInfo => bookInfo.QuickTitleUserDisplay == eventArgs.BookName).FirstOrDefault();
> ```

You're right that QuickTitleUserDisplay does exactly what you want for finding the right book. But that's not what its name suggests, and if I one day found a way to come up with a better (say, UI-language dependent) way to generate better titles to display for the user, I wouldn't expect to break display of checkout icons. I think it would be better to either just extract the file name from bookInfo.FolderPath here, or give BookInfo a new method FolderName that this and QuickTitleUserDisplay both use.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1121 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOH-Iy-1opon5gSgB5:-MUOH-Iy-1opon5gSgB6:b-y92jvv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1121)):*
> ```Smalltalk
> 			// A new book can actually cause both a Created and a Changed file system event to be raised.
> 			// While we attempt to filter out the spurious change, it's not a sure thing... especially if network latency is involved.
> 			// In those cases, it's totally fine to just ignore this event and exit early.
> ```

So, you're saying it IS certain that ONE of the events will happen after the button is created? Otherwise it seems we might want to re-raise the event with a delay.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1125 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOHRyUErYIWLLW3T6o:-MUOHRyUErYIWLLW3T6p:b-344c98) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1125)):*
> ```Smalltalk
> 				return;
> 
> 			var targetButton = FindBookButton(targetBookInfo);
> ```

It's certain that if bookInfos contains the bookInfo we want, then FindBookButton will find a button? Even with a newly created book and multiple threads working?
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1130 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOHv5L97lGeLdDvOv1:-MUOHv5L97lGeLdDvOv2:b37ybao) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1130)):*
> ```Smalltalk
> 		}
> 
> 		private void UpdateTCCheckoutStatusIcon(Button parentButton, CheckedOutBy checkedOutByWhom)
> ```

How about 'bookButton'? I found myself wondering what it's the parent of, and how that relates to the book.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1178 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOK35C3rPYx5aMHj2B:-MUOK35C3rPYx5aMHj2C:bk0myyf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1178)):*
> ```Smalltalk
> 			var desiredControls = originalControls.Where(control => control.GetType() != type);
> 			controlCollection.Clear();
> 			controlCollection.AddRange(desiredControls.ToArray());
> ```

Why not just use Remove() on the control you want to remove? Seems simpler, and perhaps less prone to flicker if there really were other children.
Also: shouldn't the removed control be disposed?
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1190 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOKQlrD1C35JOfcpQp:-MUOKQlrD1C35JOfcpQq:b-t1vniz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1190)):*
> ```Smalltalk
> 			{
> 				var label = iconLabels.First();
> 				button.Controls.Remove(label);
> ```

Dispose?
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 353 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOUYXnBE1Qv5eLudpv:-MUOUYXoEI4X0VJHgZyL:bsbgoh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L353)):*
> ```Smalltalk
> 			_watcher.DebounceChanged(OnChanged, kDebouncePeriodInMs);
> 			_watcher.DebounceCreated(OnCreated, kDebouncePeriodInMs);
> 			_watcher.DebounceRenamed(OnRenamed, kDebouncePeriodInMs);
> ```

I think we would gain in reliability and reduce complexity here by using _watcher.DebounceAnyEvent configured to watch for all three. The handler can use the ChangeType of the EventArgs to call one of the existing methods, but I believe the debounce code would then itself guarantee we only get one event for a create/modify sequence, and we could remove our own handling of that. And unlike our own handling, the debounce code is ready to handle multiple overlapping change sequences to different files.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 411 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOM2k63ckqZoPGkHpg:-MUOM2k63ckqZoP [...]

2021-02-26 16:39 UTC, sujeffreyl reviewed
Added a basic unit test, but not as thorough as it could be. Setting the state up correctly is proving quite tricky!

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-:-MUUCBF5ExguKlSuPURi:bmmhd9p)* status: 7 of 21 files reviewed, 15 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Event.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUODg7DBAg8xtH2eZFk:-MUOuYJf5L8bDg3ykfpr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/Event.cs#L253)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Name suggests to me that the whole TC is being checked out. TeamCollectionBookCheckoutStatusChangeEvent is very long...what would you think of just BookCheckoutStatusChangeEvent?
Anything useful to say by way of class comment? I know it's very small...
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/BookCollection.cs, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOEWbED1O-D5jllK19:-MUOy_vv9AGlP4fs6E1U:b-v3tq9t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/Collection/BookCollection.cs#L33)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This would be the default anyway?
</blockquote></details>

Whoops! you're right.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1091 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOFEHfCygmtLy5OowC:-MUP3lZR5rSZSM1f1Ojr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1091)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

trailing white space
</blockquote></details>

Done.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1116 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOG0pTBVFhNIqs9V0T:-MUPm_Cy0e23QZrbp8io:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1116)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

You're right that QuickTitleUserDisplay does exactly what you want for finding the right book. But that's not what its name suggests, and if I one day found a way to come up with a better (say, UI-language dependent) way to generate better titles to display for the user, I wouldn't expect to break display of checkout icons. I think it would be better to either just extract the file name from bookInfo.FolderPath here, or give BookInfo a new method FolderName that this and QuickTitleUserDisplay both use.
</blockquote></details>

Done.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1121 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOH-Iy-1opon5gSgB5:-MUPmpdX0cg627Sw8oIO:b5t9z2l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1121)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

So, you're saying it IS certain that ONE of the events will happen after the button is created? Otherwise it seems we might want to re-raise the event with a delay.
</blockquote></details>

No, we don't ever create a button in this case.  I can see how the comments don't make that clear though.  I updated the comments.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1125 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOHRyUErYIWLLW3T6o:-MUPnuxP9-BW98qtmRbN:blnijnd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1125)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's certain that if bookInfos contains the bookInfo we want, then FindBookButton will find a button? Even with a newly created book and multiple threads working?
</blockquote></details>

hmm... yes, it's expected to find the button.  Newly created book isn't relevant.  I don't think multiple threads is generally relevant as far as I can think of, the buttons/button info isn't really changing after ManageButtonsAtIdle finishes its thing.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1130 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOHv5L97lGeLdDvOv1:-MUP4Ktq9uhJot9xw1mr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1130)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How about 'bookButton'? I found myself wondering what it's the parent of, and how that relates to the book.
</blockquote></details>

Done.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1178 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOK35C3rPYx5aMHj2B:-MUP5bZQBn6xi4Tx9z_R:b-3wv30m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1178)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why not just use Remove() on the control you want to remove? Seems simpler, and perhaps less prone to flicker if there really were other children.
Also: shouldn't the removed control be disposed?
</blockquote></details>

Oh, didn't realize it should be disposed of. Guess so.

Ok, so some conflicting thoughts...
1) I didn't directly Remove() because since controlCollections implements IList, I hypothesize that deleting in a loop would be O(n^2). My solution is O(n).
2) But, since I also have the constraint that a button can only have one label, n shouldn't get above 1, so could just delete it the easy way?
3) Another thought is that now that we added the debouncing, we're way less likely to get duplicate labels.

Hmm, well, OK i think i've talked myself into just implementing it the straightforward instead of the O(n) way. Let me know if you think differently.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1190 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOKQlrD1C35JOfcpQp:-MUP5BZd6joAeA9L5G1R:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1190)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Dispose?
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 353 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOUYXnBE1Qv5eLudpv:-MUPBYXH9ZV9od44UUWc:btapgsg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L353)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think we would gain in reliability and reduce complexity here by using _watcher.DebounceAnyEvent configured to watch for all three. The handler can use the ChangeType of the EventArgs to call one of the existing methods, but I believe the debounce code would then itself guarantee we only get one event for a create/modify sequence, and we could remove our own handling of that. And unlike our own handling, the debounce code is ready to handle multiple overlapping change sequences to different files.
</blockquote></details>

One issue though is that when a new book is added, if we get a Create followed by a Change, _watcher.Debounce* will let the  [...]

2021-02-26 16:41 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235)* status: 7 of 21 files reviewed, 15 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1125 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOHRyUErYIWLLW3T6o:-MUUC_gD4-BOmEBE9-Yi:b-r850f4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1125)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

hmm... yes, it's expected to find the button.  Newly created book isn't relevant.  I don't think multiple threads is generally relevant as far as I can think of, the buttons/button info isn't really changing after ManageButtonsAtIdle finishes its thing.
</blockquote></details>

But I figured might as well add a null check anyway.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 696 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOQQKb1Ea7dybEIuHm:-MUUCrV53JIVA0JzbWtY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/TeamCollection/TeamCollection.cs#L696)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think I'll leave that for later.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-26 17:25 UTC, JohnThomson requested changes
Picked up a couple more minor things

> Reviewed 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-:-MUUMuTK7uQm0w-blTAa:b-5zsy58)* status: all files reviewed, 6 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1178 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOK35C3rPYx5aMHj2B:-MUUD_Y7-rw_EKQ7XgvM:b2f7ciq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/CollectionTab/LibraryListView.cs#L1178)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Oh, didn't realize it should be disposed of. Guess so.

Ok, so some conflicting thoughts...
1) I didn't directly Remove() because since controlCollections implements IList, I hypothesize that deleting in a loop would be O(n^2). My solution is O(n).
2) But, since I also have the constraint that a button can only have one label, n shouldn't get above 1, so could just delete it the easy way?
3) Another thought is that now that we added the debouncing, we're way less likely to get duplicate labels.

Hmm, well, OK i think i've talked myself into just implementing it the straightforward instead of the O(n) way. Let me know if you think differently.
</blockquote></details>

I think it's highly unlikely that we'd be removing enough controls for the performance hit to be noticeable. And if removing and reinserting them caused a display refresh, I suspect that would cost a lot more, anyway. what you have is good.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1098 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUUJxSA5z55_5RwKCEw:-MUUJxSB6x9FTAZ67OBY:b-7qgf6w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e9d420376b91851a2354c9384be706bce09d299c/src/BloomExe/CollectionTab/LibraryListView.cs#L1098)):*
> ```Smalltalk
> 				// Now we have the incorrect state :(
> 				// However, I think this scenario is not likely enough to be worth fixing. I think it would require a book being changed in the repo
> 				// as Bloom is starting up.
> ```

The easy way to fix this would be to NOT pass the current checkout status in the event. Instead, have the library fetch the current status when it handles the event. Then whatever order the events get handled, the last handler sets the current state. But I don't think it's worth making that big a change at this point. Maybe later.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1189 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUUDw7t1nxOT0to58RW:-MUUDw7t1nxOT0to58RX:b-u6twav) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e9d420376b91851a2354c9384be706bce09d299c/src/BloomExe/CollectionTab/LibraryListView.cs#L1189)):*
> ```Smalltalk
> 
> 		// Modifies controlCollection to not have any controls of the specified {type}
> 		private static void RemoveControlsOfType(ControlCollection controlCollection, Type type)
> ```

RemoveAndDisposeControlsOfType? Since the convention seems to be that Remove methods are NOT responsible for Dispose().
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 353 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOUYXnBE1Qv5eLudpv:-MUUEeVIEulibl1nkvzI:b4iwdti) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L353)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

One issue though is that when a new book is added, if we get a Create followed by a Change, _watcher.Debounce* will let the last one (Change) win, when we'd really prefer Create to win.
IDK, I guess I could like modify the Debounce code to have some more smarts...
</blockquote></details>

Since you are now tracking lastCreateTime separately for each file, I don't think we need to explore this option further.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 696 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOQQKb1Ea7dybEIuHm:-MUUIpMF6g9vtuSw6385:b4yptso) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/TeamCollection/TeamCollection.cs#L696)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't actually see any new error handling around or in UpdateCheckoutStatusIcon. That's OK, there's lots of ways we need to improve handling of errors, especially ones that might be caused by remote/local race conditions. But just in case you did something and it didn't make it to the PR, I thought I'd point it out.
___
*[src/BloomTests/TeamCollection/TeamCollectionTests.cs, line 67 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUULscN8Nd8Js-tYalo:-MUULscN8Nd8Js-tYalp:b-6o3oex) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e9d420376b91851a2354c9384be706bce09d299c/src/BloomTests/TeamCollection/TeamCollectionTests.cs#L67)):*
> ```Smalltalk
> 		public void HandleModifiedFile_GivenModifiedToCheckedIn_RaisesCheckedOutByNone()
> 		{
> 			TeamCollectionManager._overrideCurrentUser = null;
> ```

I gather that it is a change to 'none' because an event says the book changed but it not now checked out? It doesn't appear that the test ever put it into a checked-out state, so commenting why that isn't needed might be helpful.
I'm also puzzled by why you're messing with _overrideCurrentUser. It doesn't seem to contribute to making the right thing happen?
___
*[src/BloomTests/TeamCollection/TeamCollectionTests.cs, line 78 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUULQvd2f1cDk-CGui-:-MUULQvd2f1cDk-CGui0:bwymfds) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e9d420376b91851a2354c9384be706bce09d299c/src/BloomTests/TeamCollection/TeamCollectionTests.cs#L78)):*
> ```Smalltalk
> 
> 			// System Under Test //
> 			_collection.HandleModifiedFile(new BookStateChangeEventArgs() { BookName = $"{bookFolderName}.bloom" } );
> ```

Looking at this made me realize something I missed before: this is another case where BookFileName would be better than BookName.


<!-- Sent from Reviewable.io -->

2021-02-26 18:00 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235)* status: 16 of 22 files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1098 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUUJxSA5z55_5RwKCEw:-MUUOJvT0Y9OO_JbWosE:bsle7y8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e9d420376b91851a2354c9384be706bce09d299c/src/BloomExe/CollectionTab/LibraryListView.cs#L1098)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The easy way to fix this would be to NOT pass the current checkout status in the event. Instead, have the library fetch the current status when it handles the event. Then whatever order the events get handled, the last handler sets the current state. But I don't think it's worth making that big a change at this point. Maybe later.
</blockquote></details>

Oh, i see. Right, that makes sense.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1189 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUUDw7t1nxOT0to58RW:-MUUOYFf3GIFMJ-0pX47:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e9d420376b91851a2354c9384be706bce09d299c/src/BloomExe/CollectionTab/LibraryListView.cs#L1189)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

RemoveAndDisposeControlsOfType? Since the convention seems to be that Remove methods are NOT responsible for Dispose().
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/TeamCollection.cs, line 696 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUOQQKb1Ea7dybEIuHm:-MUUPH3r152sPw4_jP7D:b1dks8x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/78bfa8d729d207ea244b93402e3e54b52c9225c1/src/BloomExe/TeamCollection/TeamCollection.cs#L696)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't actually see any new error handling around or in UpdateCheckoutStatusIcon. That's OK, there's lots of ways we need to improve handling of errors, especially ones that might be caused by remote/local race conditions. But just in case you did something and it didn't make it to the PR, I thought I'd point it out.
</blockquote></details>

Sorry, I just meant that in the sense that I was changing it to not blocking, not that I actually wrote any code for it.
___
*[src/BloomTests/TeamCollection/TeamCollectionTests.cs, line 67 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUULscN8Nd8Js-tYalo:-MUUSUB605HDvaaXf578:bct635a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e9d420376b91851a2354c9384be706bce09d299c/src/BloomTests/TeamCollection/TeamCollectionTests.cs#L67)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I gather that it is a change to 'none' because an event says the book changed but it not now checked out? It doesn't appear that the test ever put it into a checked-out state, so commenting why that isn't needed might be helpful.
I'm also puzzled by why you're messing with _overrideCurrentUser. It doesn't seem to contribute to making the right thing happen?
</blockquote></details>

Added a comment to try to explain.

Uhm, at one point it was needed because the system under test invokes stuff like IsCheckedOutByHere / etc. And also that the other unit tests (which are now commented out) were interfering with it. But seems like it's not needed anymore. I took it out.
___
*[src/BloomTests/TeamCollection/TeamCollectionTests.cs, line 78 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-MUULQvd2f1cDk-CGui-:-MUUTGth4lN1NN7e6bV9:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e9d420376b91851a2354c9384be706bce09d299c/src/BloomTests/TeamCollection/TeamCollectionTests.cs#L78)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Looking at this made me realize something I missed before: this is another case where BookFileName would be better than BookName.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-02-26 18:04 UTC, JohnThomson reviewed
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-02-26 18:05 UTC, JohnThomson approved these changes

2021-02-26 19:10 UTC, JohnThomson reviewed
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-02-26 19:10 UTC, JohnThomson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4235#-:-MUUjzwN8qxHPdJydI_f:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-02-26 19:10 UTC, merged