Fix missing audio ids (BL-9599)
BloomBooks/BloomDesktop pull request #4239
Opened 2021-02-25 20:59 UTC by StephenMcConnel

Also fine-tune the message displayed for fixing duplicate audio ids.  In
many (most?) cases, this results in no message being displayed. (BL-9503)

2021-02-25 23:52 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Book/Book.cs, line 852 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239#-MUQMuvx0Me9Q4d2MhZI:-MUQ_OvA7fuJPKqyQ6D3:bcgvrlx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/702a793e5461089dd2f92441ebe32b3218b9a874/src/BloomExe/Book/Book.cs#L852)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> _autoCopiedAudioId == _duplicateAudioIdsFixed
> ```
This doesn't seem quite right.
For example, what if there was one auto-copied but no mp3 file. And one non-auto-copied with an mp3 file?


</blockquote></details>

If there's one auto-copied without mp3 and one user-copied with mp3, then _autoCopiedAudioId != _duplicateAudioIdsFixed.  Maybe I should rename the first variable here...  I'm sure the logic is correct.


<!-- Sent from Reviewable.io -->

2021-02-26 00:03 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 852 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239#-MUQMuvx0Me9Q4d2MhZI:-MUQbh5715Ldmsbnb9AL:b-vshgd8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/702a793e5461089dd2f92441ebe32b3218b9a874/src/BloomExe/Book/Book.cs#L852)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

If there's one auto-copied without mp3 and one user-copied with mp3, then _autoCopiedAudioId != _duplicateAudioIdsFixed.  Maybe I should rename the first variable here...  I'm sure the logic is correct.
</blockquote></details>

Oops! I read it wrong. Somehow I got it in my head that we were comparing autocopied fixes with files copied.


<!-- Sent from Reviewable.io -->

2021-02-26 00:04 UTC, andrew-polk approved these changes
Again, since this is a change to 4.9 and data, I would like @johnthomson to take a look.
Don't wait for my re-review if I'm out.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239#-:-MUQdUtr8DLpmCYEhncL:b-mxx5hv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2021-03-02 17:19 UTC, JohnThomson requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/Book/Book.cs, line 852 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239#-MUnvMez3_H1bYJBkMmC:-MUnvMez3_H1bYJBkMmD:b-r12zef) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b3247b3bc5d26554e62d558e6c3e0470c8e9fda0/src/BloomExe/Book/Book.cs#L852)):*
> ```Smalltalk
> 				// If the only fixes were in spans Bloom copied in the data-div because we told it to, then restrict the message for where to rerecord.
> 				var shortMsg = "There was a problem with recordings in this Talking Book, which was caused by a bug in an older version of Bloom." +
> 					((_autoCopiedAudioIdsFixed == _duplicateAudioIdsFixed) ?
> ```

Would a better test for this message be to count whether any audio files were copied during FixDuplicateAudioIdInBookPages()? If not, only the xmatter pages need be reviewed. I'm not sure whether there would ever be an actual difference, but it's more obviously correct, and perhaps easier to calculate...just note _audioFilesCopiedForDuplication before calling the method and compare with the value after.
(If instead you decide to keep _duplicateAudioIdsFixed...since we're only counting ones in the data-div, I think the name should reflect that somehow.)


<!-- Sent from Reviewable.io -->

2021-03-02 19:06 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 852 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239#-MUnvMez3_H1bYJBkMmC:-MUoItf7CR2EMmIP8c1K:bj9wzva) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b3247b3bc5d26554e62d558e6c3e0470c8e9fda0/src/BloomExe/Book/Book.cs#L852)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Would a better test for this message be to count whether any audio files were copied during FixDuplicateAudioIdInBookPages()? If not, only the xmatter pages need be reviewed. I'm not sure whether there would ever be an actual difference, but it's more obviously correct, and perhaps easier to calculate...just note _audioFilesCopiedForDuplication before calling the method and compare with the value after.
(If instead you decide to keep _duplicateAudioIdsFixed...since we're only counting ones in the data-div, I think the name should reflect that somehow.)
</blockquote></details>

Done.  I adjusted the comment to include Cover along with Title and Credits pages.


<!-- Sent from Reviewable.io -->

2021-03-02 19:16 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2021-03-02 19:20 UTC, JohnThomson approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4239)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2021-03-02 19:20 UTC, merged