Always reload the top page in the edit view when switching
BloomBooks/BloomDesktop pull request #4287
Opened 2021-03-17 17:57 UTC by JohnThomson

This is a partial cure for memory leaks.
Code is present, but disabled, to only do it when short of memory.

2021-03-17 18:06 UTC, andrew-polk requested changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Edit/EditingView.cs, line 581 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287#-MW0MD2O7NTAJ5U5b2kO:-MW0MD2O7NTAJ5U5b2kP:bl7j9rq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/be41751a2744fb1b1461fe8015f560450d7723b1/src/BloomExe/Edit/EditingView.cs#L581)):*
> ```Smalltalk
> 
> 		// A crude way of measuring when we might be short enough of memory to need a full reload.
> 		private bool SystemIsShortOfMemory()
> ```

My only comment is that this and GetPrivateBytes don't belong here, but as we aren't using them.... I'm not sure it matters.
Still, if they are being introduced into the code base, might as well put them somewhere they make sense. My guess is that is some new MemoryUtils or similar.


<!-- Sent from Reviewable.io -->

2021-03-17 19:24 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Edit/EditingView.cs, line 581 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287#-MW0MD2O7NTAJ5U5b2kO:-MW0dPFpDCXABaUdbVwn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/be41751a2744fb1b1461fe8015f560450d7723b1/src/BloomExe/Edit/EditingView.cs#L581)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

My only comment is that this and GetPrivateBytes don't belong here, but as we aren't using them.... I'm not sure it matters.
Still, if they are being introduced into the code base, might as well put them somewhere they make sense. My guess is that is some new MemoryUtils or similar.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-17 20:08 UTC, andrew-polk approved these changes
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2021-03-18 15:30 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Utils/MemoryUtils.cs, line 26 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287#-MW4wsx183bIthn_xrQq:-MW4wsx183bIthn_xrQr:b-v39szv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1c18704761d34b40a5f40fbe2cffdd7dc77556a5/src/BloomExe/Utils/MemoryUtils.cs#L26)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <returns></returns>
> 		public static long GetPrivateBytes()
> ```

I think this value is in KB.  I suggest appending KB to the end. (Otherwise, the call in SystemIsShortOfMemory is really confusing). Alternatively, could just add a comment clarifying the units, but I think this is more error-prone.


<!-- Sent from Reviewable.io -->

2021-03-18 15:54 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomExe/Utils/MemoryUtils.cs, line 26 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287#-MW4wsx183bIthn_xrQq:-MW51oa_5yda_ru83VS_:b-uxwh92) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1c18704761d34b40a5f40fbe2cffdd7dc77556a5/src/BloomExe/Utils/MemoryUtils.cs#L26)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I think this value is in KB.  I suggest appending KB to the end. (Otherwise, the call in SystemIsShortOfMemory is really confusing). Alternatively, could just add a comment clarifying the units, but I think this is more error-prone.
</blockquote></details>

I decided instead to just make it give the answer in bytes.


<!-- Sent from Reviewable.io -->

2021-03-18 15:56 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-03-18 15:59 UTC, sujeffreyl approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4287)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2021-03-18 15:59 UTC, merged