Center text box with background color (BL-9654)
BloomBooks/BloomDesktop pull request #4375
Opened 2021-04-16 20:05 UTC by JohnThomson

2021-04-16 22:47 UTC, andrew-polk requested changes

2021-04-16 22:47 UTC, andrew-polk commented on src/BloomBrowserUI/bookLayout/bubble.less
> +    .bloom-textOverPicture[data-bubble]:not([data-bubble*="`backgroundColors`:[`transparent`]"]) {
```
 The ones we don't want to do it
 ...
 data-bubble="...`style`:`none`..." and don't specify a background color at all.
```
But then you are doing it to 
> anything without backgroundColors at all
```
.bloom-textOverPicture[data-bubble]:not([data-bubble*="backgroundColors"])
```
I blame Friday code review brain, but I can't make this work in my head.

2021-04-19 13:10 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4375)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookLayout/bubble.less, line 295 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4375#-MYRHPaUaKz814-9lVwe-r1-295:-MYe6CPe4xZA02gnpmhr:b-9jf2zs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2ce950052c096013162c26e021d90a0b77b3fb91/src/BloomBrowserUI/bookLayout/bubble.less#L295)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

```
 The ones we don't want to do it
 ...
 data-bubble="...`style`:`none`..." and don't specify a background color at all.
```
But then you are doing it to 
> anything without backgroundColors at all
```
.bloom-textOverPicture[data-bubble]:not([data-bubble*="backgroundColors"])
```
I blame Friday code review brain, but I can't make this work in my head.
</blockquote></details>

You were right to be concerned. Actually the problem is not the second rule, which is harmless but useless. The problem is that the third rule incorrectly applies the vertical centering to bubbles (if there are any) that have no backgroundColor at all.
I think I finally got it right. At least, the current two rules center text in a box with a green background color and style none, and don't do so in one that is transparent or has no backgroundColor.


<!-- Sent from Reviewable.io -->

2021-04-19 16:37 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4375)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2021-04-19 16:37 UTC, merged