Readers skip pages that don't print or have nonvernacular text (BL-9876)
BloomBooks/BloomDesktop pull request #4418
Opened 2021-04-30 17:34 UTC by StephenMcConnel

They also skip pages that don't have any places to put vernacular text.

2021-04-30 17:55 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[src/BloomExe/web/ReadersApi.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZYuVpxC-PhQMBdxkzf:-MZYuVpxC-PhQMBdxkzg:b1myvi6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bae298099c0401911a818c1c201c9b6859bd58e1/src/BloomExe/web/ReadersApi.cs#L253)):*
> ```Smalltalk
> 			foreach (var page in pages)
> 			{
> 				// Skip pages that contain non-vernacular text.
> ```

This comment seems to imply that it will skip pages that contain ANY non-vernacular text, but the code below skips pages that contain ONLY non-vernacular text.
From what I understand, I think the comment is in error (somewhat misleading) and the code is right. 


<!-- Sent from Reviewable.io -->

2021-04-30 22:57 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/ReadersApi.cs, line 237 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZYvUXZBABZuQAB0MRF:-MZ_-4IY7kAAe4PL0lxC:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bae298099c0401911a818c1c201c9b6859bd58e1/src/BloomExe/web/ReadersApi.cs#L237)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I know ReaderApiTest is pretty basic right now, but I think (at least I hope) it wouldn't be too hard to add a unit test for this?  Just need to load the book from an HTML string, which we've done in other places.  After that I think it'd be straightforward to test the changed behavior.
</blockquote></details>

Done.
___
*[src/BloomExe/web/ReadersApi.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZYuVpxC-PhQMBdxkzf:-MZYwCkMAeLTPQYr5Fnn:bxjkv78) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bae298099c0401911a818c1c201c9b6859bd58e1/src/BloomExe/web/ReadersApi.cs#L253)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This comment seems to imply that it will skip pages that contain ANY non-vernacular text, but the code below skips pages that contain ONLY non-vernacular text.
From what I understand, I think the comment is in error (somewhat misleading) and the code is right. 
</blockquote></details>

I think the code is right, but the commenting could be (has been) improved.


<!-- Sent from Reviewable.io -->

2021-05-03 16:24 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/web/ReadersApi.cs, line 237 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZYvUXZBABZuQAB0MRF:-MZmsFgnA2qDqbuhFiiC:b8loo2f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bae298099c0401911a818c1c201c9b6859bd58e1/src/BloomExe/web/ReadersApi.cs#L237)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yikes, looks a lot harder than I was hoping with all the storage shenangians needed. Thanks for doing it.
___
*[src/BloomExe/web/ReadersApi.cs, line 253 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZYuVpxC-PhQMBdxkzf:-MZmuNrp6R8rAA6WxPnk:bkpj0vm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bae298099c0401911a818c1c201c9b6859bd58e1/src/BloomExe/web/ReadersApi.cs#L253)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I think the code is right, but the commenting could be (has been) improved.
</blockquote></details>

Thanks for clearing that up
___
*[src/BloomExe/web/ReadersApi.cs, line 235 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZmyrd43AhiG2MWtpyN:-MZmyrd43AhiG2MWtpyO:b-s616tf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fc564b9086ae87a4283e35c7ab7c7b56be0b2d4/src/BloomExe/web/ReadersApi.cs#L235)):*
> ```Smalltalk
> 		/// <summary>
> 		/// Return a json string with the page guid and the visible bloom-content1 text of each content page
> 		/// that contains only bloom-content1 text and that will be printed.
> ```

After reading the card, I was still confused about what the desired behavior should be if a page contains both L1 text and L3 text.  Would appreciate JH's input on this.
___
*[src/BloomTests/web/controllers/ReadersApiTests.cs, line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZmqucY8q1BSrlz4kM2:-MZmqucZ0NRV5jj_-Nq1:b-3paa7s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fc564b9086ae87a4283e35c7ab7c7b56be0b2d4/src/BloomTests/web/controllers/ReadersApiTests.cs#L45)):*
> ```Smalltalk
> 		public void GetTextOfContentPagesAsJson_OmitsUnwantedPages()
> 		{
> 			var htmlLeveledReader = $@"<html><head><meta charset='UTF-8'></meta></head>
> ```

Let's make this HTML a pretty short HTML with just enough HTML/pages to repro what is desired, with as much fluff removed as reasonably possible.
In this case, I think even just one content page would suffice, unless there are multiple combinations of box setups that you're trying to test.  (Or optionally, ideally maybe you would have multiple tests, each with 1 page, so it's clearer what's going on if something fails)


<!-- Sent from Reviewable.io -->

2021-05-03 16:54 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/web/ReadersApi.cs, line 235 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZmyrd43AhiG2MWtpyN:-MZn8Y3iALMS3rErPcBy:b9196nz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fc564b9086ae87a4283e35c7ab7c7b56be0b2d4/src/BloomExe/web/ReadersApi.cs#L235)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

After reading the card, I was still confused about what the desired behavior should be if a page contains both L1 text and L3 text.  Would appreciate JH's input on this.
</blockquote></details>

JH's response: Exclude if has class (bloom-frontMatter ||  bloom-backMatter || bloom-nonprinting || bloom-ignoreForReaderStats)  or lacks any text in L1


<!-- Sent from Reviewable.io -->

2021-05-03 17:52 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/ReadersApi.cs, line 235 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZmyrd43AhiG2MWtpyN:-MZnM1iE3wpfIFug0s_3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fc564b9086ae87a4283e35c7ab7c7b56be0b2d4/src/BloomExe/web/ReadersApi.cs#L235)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

JH's response: Exclude if has class (bloom-frontMatter ||  bloom-backMatter || bloom-nonprinting || bloom-ignoreForReaderStats)  or lacks any text in L1
</blockquote></details>

Done.
___
*[src/BloomTests/web/controllers/ReadersApiTests.cs, line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZmqucY8q1BSrlz4kM2:-MZnLq1z1bp-TmBmFLoC:b-vko47y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fc564b9086ae87a4283e35c7ab7c7b56be0b2d4/src/BloomTests/web/controllers/ReadersApiTests.cs#L45)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Let's make this HTML a pretty short HTML with just enough HTML/pages to repro what is desired, with as much fluff removed as reasonably possible.
In this case, I think even just one content page would suffice, unless there are multiple combinations of box setups that you're trying to test.  (Or optionally, ideally maybe you would have multiple tests, each with 1 page, so it's clearer what's going on if something fails)
</blockquote></details>

I tried to shorten it some, and added comments at the beginning of  each page what it was testing.


<!-- Sent from Reviewable.io -->

2021-05-03 19:01 UTC, sujeffreyl approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[src/BloomTests/web/controllers/ReadersApiTests.cs, line 45 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4418#-MZmqucY8q1BSrlz4kM2:-MZnaa7eAd_wRjI2Hloo:b-lns2u5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2fc564b9086ae87a4283e35c7ab7c7b56be0b2d4/src/BloomTests/web/controllers/ReadersApiTests.cs#L45)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I tried to shorten it some, and added comments at the beginning of  each page what it was testing.
</blockquote></details>

Ah yes, those comments are very handy!


<!-- Sent from Reviewable.io -->

2021-05-03 19:02 UTC, merged