[5.0] BL-9844 Fix ePub xmatter
BloomBooks/BloomDesktop pull request #4431
Opened 2021-05-05 19:52 UTC by gmartin7

* simplifies Kyrgyzstan xmatter and allows brandings and
   other parts of xmatter to layout better when xmatter css
   is included in ePub.

2021-05-05 19:55 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MZy5BL415iulssoLJmU:-MZy5BL541YFnuN4ECMW:b7saeai) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8395a276441b7ac280b3399f55d0db6efc186ffb/src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less#L115)):*
> ```Less
> .bloom-page,
> .marginBox {
>     height: 100%;
> ```

The way I read this selector, this change would affect all bloom-pages and all margin boxes. That's what the comma means.


<!-- Sent from Reviewable.io -->

2021-05-05 20:00 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MZy5BL415iulssoLJmU:-MZy6POd-AUx4vnO9H4P:b-azjlqc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8395a276441b7ac280b3399f55d0db6efc186ffb/src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less#L115)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

The way I read this selector, this change would affect all bloom-pages and all margin boxes. That's what the comma means.
</blockquote></details>

true, but this file only gets included in epub generation.


<!-- Sent from Reviewable.io -->

2021-05-05 20:01 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MZy5BL415iulssoLJmU:-MZy6YxRBAeWFL3t2LU2:b-ko5jvv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8395a276441b7ac280b3399f55d0db6efc186ffb/src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less#L115)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

true, but this file only gets included in epub generation.
</blockquote></details>

The problem exists on all pages, but only shows on xmatter where we have multiple parts, some going to the bottom of the page, etc.


<!-- Sent from Reviewable.io -->

2021-05-05 21:28 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MZy5BL415iulssoLJmU:-MZyPnZ8E4Kvo-o8xWsm:bvlnz5q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8395a276441b7ac280b3399f55d0db6efc186ffb/src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less#L115)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

The problem exists on all pages, but only shows on xmatter where we have multiple parts, some going to the bottom of the page, etc.
</blockquote></details>

If you can you limit the selector to the xmatter problems are that you are trying to solve, then we can probably merge. Otherwise we'll have to come up with some plan for evaluating and testing the change, probably when JT comes back.

Also, in you comment, can you add information about what is different in epub that requires this special rule. Thx.


<!-- Sent from Reviewable.io -->

2021-05-06 18:04 UTC, gmartin7 commented
I should have done this on 4.9 in the first place. I will close this PR and open a different one. Just switching the base branch didn't want to work.

2021-05-06 18:18 UTC, gmartin7 commented
opening again...
Grr... we did something less in 4.9 to NOT include all xmatter css there, just the Kyrgyzstan ones. So we'll need to get this fixed up and merged and then pull in something different for 4.9 again.

2021-05-06 19:30 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MZy5BL415iulssoLJmU:-M_1ujjDEiNjibCdeZM4:b41vonh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8395a276441b7ac280b3399f55d0db6efc186ffb/src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less#L115)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

If you can you limit the selector to the xmatter problems are that you are trying to solve, then we can probably merge. Otherwise we'll have to come up with some plan for evaluating and testing the change, probably when JT comes back.

Also, in you comment, can you add information about what is different in epub that requires this special rule. Thx.
</blockquote></details>

Done as much as possible.
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 444 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-M_1uLeqBHTcHPRqO9uE:-M_1uLeqBHTcHPRqO9uF:b-5p3cb8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ea1227339d8f6ddaeb2dcb854b0ae46ffbed9361/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L444)):*
> ```Less
>     .bloom-backMatter {
>         height: 100%; // these height 100% are needed to make the cover color flow to the bottom
>     }
> ```

These changes that I've moved to `baseEPUB.less` will need to move back to Kyrg xmatter files for `4.9`, but I have confidence they will work there (and I'll test 'em too).


<!-- Sent from Reviewable.io -->

2021-05-07 21:20 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-05-25 18:29 UTC, andrew-polk requested changes
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk, @gmartin7, and @hatton)

___
*[src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MZy5BL415iulssoLJmU:-MaZmLVfEXYYRUlwDLeD:bggoyfx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8395a276441b7ac280b3399f55d0db6efc186ffb/src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less#L115)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done as much as possible.
</blockquote></details>

I think each rule below would benefit from more explicit comments. Think... when I come back to this in 3 years and want to know if I can remove or change this rule, what would I need to make sure still works?
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 469 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MaZlpGR2xN4sYfggDT_:-MaZlpGR2xN4sYfggDTa:b-cfdsit) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/40700510367e6c24791a19367e3818bb38d3c2a7/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L469)):*
> ```Less
>         }
>     }
> }
> ```

With this PR, I was expecting to find this file and baseEPUB.less in the following state:

Everything in Kyrgyz.less `.epub {...}` is either still there in 5.0 or extracted to baseEPUB.less for cases where we decided it should apply to all xmatters.

But that doesn't seem to be the case. What am I am missing or assuming incorrectly?


<!-- Sent from Reviewable.io -->

2021-05-25 20:38 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less, line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MZy5BL415iulssoLJmU:-Ma_EPJqDg_mmvq2MQZv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8395a276441b7ac280b3399f55d0db6efc186ffb/src/BloomBrowserUI/publish/ePUBPublish/baseEPUB.less#L115)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think each rule below would benefit from more explicit comments. Think... when I come back to this in 3 years and want to know if I can remove or change this rule, what would I need to make sure still works?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less, line 469 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431#-MaZlpGR2xN4sYfggDT_:-Ma_ERtl3RGUaDTDoApS:bs8buak) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/40700510367e6c24791a19367e3818bb38d3c2a7/src/BloomBrowserUI/templates/xMatter/Kyrgyzstan2020-XMatter/Kyrgyzstan2020-XMatter.less#L469)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

With this PR, I was expecting to find this file and baseEPUB.less in the following state:

Everything in Kyrgyz.less `.epub {...}` is either still there in 5.0 or extracted to baseEPUB.less for cases where we decided it should apply to all xmatters.

But that doesn't seem to be the case. What am I am missing or assuming incorrectly?
</blockquote></details>

I've done a better job of including Kyrgyz.less epub rules from the final 4.9 version. Most of them are copies of rules that would apply if the user had explicitly set the Edit page layout to `Device 16x9Portrait`.


<!-- Sent from Reviewable.io -->

2021-05-25 21:06 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4431)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-05-25 21:07 UTC, merged