Handle more cases of joining an existing TC (BL-9864)
BloomBooks/BloomDesktop pull request #4454
Opened 2021-05-12 21:37 UTC by JohnThomson

- Many changes to dialog messages
- If we've already joined, just open (without normal merge behavior of committing new local books)
- If the existing local collection is already a TC but NOT the one we're joining, prevent the join
(Some of this work was done by Gordon)

2021-05-12 22:47 UTC, hatton requested changes
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 245 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_XjuyW-vz5T2sF3QHx:-M_XjuyW-vz5T2sF3QHy:bkokzdc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L245)):*
> ```XML
> 
>     function getBodyOfDialogByState(): JSX.Element {
>         switch (dialogState) {
> ```

I'm surprised that this much code and a state approach was needed, since there is no actual state (in the sense that it does not change), but rather just a series of flags delivered by props, and each element of the dialog is visible or not depending on the value of the flags.  But not worth re-writing over.
___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 272 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_XjPcgAymNZxWRN92F:-M_XjPcgAymNZxWRN92G:b-6ru32f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L272)):*
> ```XML
>             <DialogBottomButtons>
>                 {wantReportButton && (
>                     <BloomButton
> ```

Probably this wants to be factored out as a re-usable REPORT button like we have for close and cancel
___
*[src/BloomExe/Collection/CollectionSettings.cs, line 349 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_XkkGNDJEjpwlP-kT8:-M_XkkGNDJEjpwlP-kT9:bl3okey) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomExe/Collection/CollectionSettings.cs#L349)):*
> ```Smalltalk
> 				var settingsFilePath = Path.Combine(collectionFolder,
> 					Path.ChangeExtension(Path.GetFileName(collectionFolder), "bloomCollection"));
> 				if (!File.Exists(settingsFilePath))
> ```

`RobustFile.____`
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 727 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_Xj2PRCMGjmIxs6eZo:-M_Xj2PRCMGjmIxs6eZp:bpvv9hj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L727)):*
> ```Smalltalk
> 			var localCollectionFolder =
> 				Path.Combine(NewCollectionWizard.DefaultParentDirectoryForCollections, collectionName);
> 			var isExistingCollection = Directory.Exists(localCollectionFolder);
> ```

`RobustFile.___`
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 730 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_Xj22P0WqCUIezFAx5:-M_Xj22P0WqCUIezFAx6:bpvv9hj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L730)):*
> ```Smalltalk
> 			var tcLinkPath = TeamCollectionManager.GetTcLinkPathFromLcPath(localCollectionFolder);
> 			var isAlreadyTcCollection = isExistingCollection &&
> 			                            File.Exists(tcLinkPath);
> ```

`RobustFile.___`
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 776 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_Xiwu50lF8roo2ZTtj:-M_Xiwu50lF8roo2ZTtk:bpvv9hj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L776)):*
> ```Smalltalk
> 			var localCollectionFolder =
> 				Path.Combine(NewCollectionWizard.DefaultParentDirectoryForCollections, collectionName);
> 			var firstTimeJoin = !Directory.Exists(localCollectionFolder) || !File.Exists(TeamCollectionManager.GetTcLinkPathFromLcPath(localCollectionFolder));
> ```

`RobustFile.___`


<!-- Sent from Reviewable.io -->

2021-05-13 15:54 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 245 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_XjuyW-vz5T2sF3QHx:-M_aQ6yJ5zLB9ErPSHCz:b23ulj5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L245)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I'm surprised that this much code and a state approach was needed, since there is no actual state (in the sense that it does not change), but rather just a series of flags delivered by props, and each element of the dialog is visible or not depending on the value of the flags.  But not worth re-writing over.
</blockquote></details>

Yes, Gordon started it this way and I went along. I like that this makes clear that the various booleans resolve to five possible layouts and that it makes pretty clear what is common and different. It would be interesting to see what it looked like as a single layout with a separate calculation of whether each component should appear. But I think I agree it's not worth redoing.
___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 272 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_XjPcgAymNZxWRN92F:-M_a7aOS3DkTSKOuAcks:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L272)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Probably this wants to be factored out as a re-usable REPORT button like we have for close and cancel
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/CollectionSettings.cs, line 349 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_XkkGNDJEjpwlP-kT8:-M_a7wkmEI9jwpljkpor:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomExe/Collection/CollectionSettings.cs#L349)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`RobustFile.____`
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 727 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_Xj2PRCMGjmIxs6eZo:-M_a8HTU35gfHzM5GpR4:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L727)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`RobustFile.___`
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 730 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_Xj22P0WqCUIezFAx5:-M_a8HrLCetkTmOvGxn-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L730)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`RobustFile.___`
</blockquote></details>

Done.
___
*[src/BloomExe/TeamCollection/FolderTeamCollection.cs, line 776 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_Xiwu50lF8roo2ZTtj:-M_a8IZ06YzbutHQhVW0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e3336267a74d333b4f36d5aba99b49e0a69af16d/src/BloomExe/TeamCollection/FolderTeamCollection.cs#L776)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`RobustFile.___`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-13 16:05 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454)* status: 6 of 10 files reviewed, 6 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 274 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_aSHdS1hefwUgY_rna:-M_aSHdS1hefwUgY_rnb:b5jwz25) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8ae1ccd8ffc28a10b95111a227608d8f3046db/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L274)):*
> ```XML
>                 {wantReportButton && (
>                     <DialogReportButton
>                         // margin-left counteracts Material-UI padding. The padding is used for hover effects,
> ```

It looks like we can move most of this into `DialogReportButton`, including the css and the onclick handler. Instead of the onclick, I think we can supply the message? Not clear if that should be a string or a function that returns a string (i.e. maybe it's expensive sometimes to produce the report and a waste to do it on every render or complicate the component by making a memo or whatever?). I think I've talked myself into a string. `reportContents={()=>"the sky did fall"}`.  If *did* eventually supply an OnClick as well, then I suppose we could define that it overrides the default behavior.


<!-- Sent from Reviewable.io -->

2021-05-13 16:47 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 274 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_aSHdS1hefwUgY_rna:-M_ac0kL9ICPX-xzxRRj:b-vc6a7d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8ae1ccd8ffc28a10b95111a227608d8f3046db/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L274)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It looks like we can move most of this into `DialogReportButton`, including the css and the onclick handler. Instead of the onclick, I think we can supply the message? Not clear if that should be a string or a function that returns a string (i.e. maybe it's expensive sometimes to produce the report and a waste to do it on every render or complicate the component by making a memo or whatever?). I think I've talked myself into a string. `reportContents={()=>"the sky did fall"}`.  If *did* eventually supply an OnClick as well, then I suppose we could define that it overrides the default behavior.
</blockquote></details>

I think I've done what you wanted.


<!-- Sent from Reviewable.io -->

2021-05-13 22:30 UTC, hatton approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454)* status: 6 of 10 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx, line 274 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4454#-M_aSHdS1hefwUgY_rna:-M_ah3j8AnSh50EfRVQA:ba8qgad) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ff8ae1ccd8ffc28a10b95111a227608d8f3046db/src/BloomBrowserUI/teamCollection/JoinTeamCollectionDialog.tsx#L274)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think I've done what you wanted.
</blockquote></details>

Drat, reviewable is still showing me the old stuff.


<!-- Sent from Reviewable.io -->

2021-05-13 22:30 UTC, merged