Allow error reporting if opening collection fails (BL-9916)
BloomBooks/BloomDesktop pull request #4509
Opened 2021-05-26 20:45 UTC by sujeffreyl

* Add the "Report" button to the Ui dialog opened
* Re-factoring of fallback reporting
* Add mechanism to submit reports including the problematic .bloomCollection file

2021-05-27 19:30 UTC, StephenMcConnel requested changes
This might benefit from someone else taking a look.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-:-MajIYmpDv_J90wLqEVf:b-qja8my)* status: all files reviewed, 3 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 222 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajDh3PC6UmqkbEFvrx:-MajDh3PC6UmqkbEFvry:b9suabi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L222)):*
> ```Smalltalk
> 					}
> 					catch (Exception e)
> 					{
> ```

Is this strange indentation for real?
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 447 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajDz8xDB6FOh64xLgp:-MajDz8y-8tsX1RLAGpM:b-m0j6an) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L447)):*
> ```Smalltalk
> 				// We got an error really early, before we can use HTML dialogs. Report using the old dialog.
> 				// Hopefully we're still on the one main thread.
> 				HtmlErrorReporter.ShowFallbackProblemDialog(levelOfProblem, exception, detailedMessage, shortUserLevelMessage, isShortMessagePreEncoded);
> ```

Is the comment obsolete?  How can we use HtmlErrorReporter when we can't yet use HTML dialogs?
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 465 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajEH3T1JcUzkRIQTJs:-MajEH3T1JcUzkRIQTJt:beg9t3t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L465)):*
> ```Smalltalk
> 					{
> 						// We can't use the react dialog!
> 						HtmlErrorReporter.ShowFallbackProblemDialog(levelOfProblem, exception, detailedMessage, shortUserLevelMessage, isShortMessagePreEncoded);
> ```

Is the comment still valid?  Does it make sense?


<!-- Sent from Reviewable.io -->

2021-05-27 20:56 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 222 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajDh3PC6UmqkbEFvrx:-MajawSLAlH8EgveXMCF:b9o8t5e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L222)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is this strange indentation for real?
</blockquote></details>

Hmm... yeah it looks awful in Reviewable and doesn't seem to make sense even after I started at it for a long time. I'm not sure why reviewable makes it look so strange, but it looks much better in my IDE.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 447 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajDz8xDB6FOh64xLgp:-Majb3EC8Gu2CvFj2Y3A:buwfnys) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L447)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is the comment obsolete?  How can we use HtmlErrorReporter when we can't yet use HTML dialogs?
</blockquote></details>

We're using the HTMLErrorReporter's fallback, which is actually WinFormsErrorReporter
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 465 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajEH3T1JcUzkRIQTJs:-MajbHtr8L-YyFWEdM3i:b-9d7igh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L465)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Is the comment still valid?  Does it make sense?
</blockquote></details>

It calls the Fallback dialog instead of the React dialog.


<!-- Sent from Reviewable.io -->

2021-05-27 21:08 UTC, JohnThomson requested changes
Looks basically good to me, but I only moderately understand this code, and it looks like a really scary change to make to error reporting code, considering that it is hard to test, at the end of a release cycle after we did our main test pass. But likely the problem it addresses really needs to be fixed. @andrew-polk has been looking hard at error reporting recently; I think a third review might be worth it.

> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-:-MajdVupC2S4TY1oSpdd:b-s9h09m)* status: all files reviewed, 5 unresolved discussions (waiting on @StephenMcConnel and @sujeffreyl)

___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 412 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajbUSG1Q957AhAuIYj:-MajbUSG1Q957AhAuIYk:b-rrktay) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L412)):*
> ```Smalltalk
> 
> 						// Note: HtmlErrorReporter supports up to 3 buttons (OK, Report, and [Secondary action]), but the fallback reporter only supports a max of two.
> 						// Well, just gong to have to drop the secondary action.
> ```

gong -> going (if you're fixing something else)
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 557 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-Majd5eW3XYZlGfwmmNW:-Majd5eW3XYZlGfwmmNX:b-lgpxvl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L557)):*
> ```Smalltalk
> 				if (issueLink.StartsWith("failed"))
> 				{
> 					MessageBox.Show("Failed to report issue. Please email Bloom team manually.");
> ```

@hatton usually objects to using MessageBox. Maybe there's no reasonable alternative here though?


<!-- Sent from Reviewable.io -->

2021-05-27 21:09 UTC, JohnThomson reviewed
Sorry, didn't mean to block this, I don't think any of the points I made needs to stop it. But I'd like to wait for responses from JohnH and Andrew.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-:-Maje8QhB3tMoqkjYYF6:b-blwqym)* status: all files reviewed, 5 unresolved discussions (waiting on @StephenMcConnel and @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-05-27 22:26 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: 3 of 5 files reviewed, 5 unresolved discussions (waiting on @hatton, @JohnThomson, and @StephenMcConnel)

___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 412 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajbUSG1Q957AhAuIYj:-MajrdiKAN7-McUgKdTG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L412)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

gong -> going (if you're fixing something else)
</blockquote></details>

Done.
___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 557 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-Majd5eW3XYZlGfwmmNW:-Majvk8V69BVX8TkShjX:b7gmf4h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L557)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

@hatton usually objects to using MessageBox. Maybe there's no reasonable alternative here though?
</blockquote></details>

Now it'll bring up a notify.
(In this scenario, the notify will use WinFormsErrorReporter).


<!-- Sent from Reviewable.io -->

2021-05-28 21:53 UTC, andrew-polk requested changes
> Reviewed 2 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 569 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MaouWOW6xGgN1ickK6m:-MaouWOW6xGgN1ickK6n:b-kfm97l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9c9ff76be8abed4b0451b47435fc12c51178d436/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L569)):*
> ```Smalltalk
> 				return null;
> 			}
> 			else if (levelOfProblem == ProblemLevel.kNonFatal || levelOfProblem == ProblemLevel.kUser)
> ```

In what scenario would we get here with kUser?
Worth a comment explaining why it should take this path. (And if you just picked one because you had to pick one, you can say that in a comment.)


<!-- Sent from Reviewable.io -->

2021-05-28 22:04 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 222 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajDh3PC6UmqkbEFvrx:-Map-7eW-Q1xRHq-CWCp:b18q3hw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L222)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Hmm... yeah it looks awful in Reviewable and doesn't seem to make sense even after I started at it for a long time. I'm not sure why reviewable makes it look so strange, but it looks much better in my IDE.
</blockquote></details>

I pulled this into VS myself to try to see what was going on. It definitely does have some indentation issues which need to be fixed.
If you delete and re-add the closing brace on 270, it will fix it up.


<!-- Sent from Reviewable.io -->

2021-05-31 14:30 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, @JohnThomson, and @StephenMcConnel)

___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 569 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MaouWOW6xGgN1ickK6m:-Mb1nQWUCS9JvKdliL0F:b-lxm85) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9c9ff76be8abed4b0451b47435fc12c51178d436/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L569)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In what scenario would we get here with kUser?
Worth a comment explaining why it should take this path. (And if you just picked one because you had to pick one, you can say that in a comment.)
</blockquote></details>

Is your question when is kUser set? kUser happens if the user clicks the ? in the top right and selects "Report a Problem"
Is your question why is kUser both set and a fallback dialog needed? IDK, beats me, maybe if the bloom server is never able to start up and the user wants to report that?
Does that guide what kind of comment you're looking for?


<!-- Sent from Reviewable.io -->

2021-05-31 14:31 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, @JohnThomson, and @StephenMcConnel)

___
*[src/BloomExe/web/controllers/ProblemReportApi.cs, line 222 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MajDh3PC6UmqkbEFvrx:-Mb1pWSoAlhoPTzpyJum:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d9065ec027130fbfeb76223a9ca75a9eaad35084/src/BloomExe/web/controllers/ProblemReportApi.cs#L222)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I pulled this into VS myself to try to see what was going on. It definitely does have some indentation issues which need to be fixed.
If you delete and re-add the closing brace on 270, it will fix it up.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-01 17:28 UTC, andrew-polk requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton, @JohnThomson, @StephenMcConnel, and @sujeffreyl)

___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 569 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MaouWOW6xGgN1ickK6m:-Mb7asqD2Xr9DZfz3wwn:b-4epq0u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9c9ff76be8abed4b0451b47435fc12c51178d436/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L569)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Is your question when is kUser set? kUser happens if the user clicks the ? in the top right and selects "Report a Problem"
Is your question why is kUser both set and a fallback dialog needed? IDK, beats me, maybe if the bloom server is never able to start up and the user wants to report that?
Does that guide what kind of comment you're looking for?

</blockquote></details>

Yeah, I was just surprised that we would get into the fallback by having the user initiate the dialog.
And then wondering if it really makes sense to do this if we do.
I see why you picked to make it like the nonfatal option. It makes more sense than fatal or notify. But still seems like it would be a pretty odd ux for the user.
i.e.
Something bad happened. Let me report it. Click. Bloom tells me something is wrong and I should report it. Yeah, that's what I was trying to do.

Anyway, it is probably the best we can do easily/reasonably. So I'm fine with it. Maybe just a comment saying while unexpected and not ideal, this is the best we can do for the user report scenario. (or something along those lines)


<!-- Sent from Reviewable.io -->

2021-06-01 21:18 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @hatton, @JohnThomson, and @StephenMcConnel)

___
*[src/BloomExe/ErrorReporter/HtmlErrorReporter.cs, line 569 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509#-MaouWOW6xGgN1ickK6m:-Mb8RDnO7VvlTTu-ARBQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9c9ff76be8abed4b0451b47435fc12c51178d436/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L569)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yeah, I was just surprised that we would get into the fallback by having the user initiate the dialog.
And then wondering if it really makes sense to do this if we do.
I see why you picked to make it like the nonfatal option. It makes more sense than fatal or notify. But still seems like it would be a pretty odd ux for the user.
i.e.
Something bad happened. Let me report it. Click. Bloom tells me something is wrong and I should report it. Yeah, that's what I was trying to do.

Anyway, it is probably the best we can do easily/reasonably. So I'm fine with it. Maybe just a comment saying while unexpected and not ideal, this is the best we can do for the user report scenario. (or something along those lines)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-01 21:20 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: all files reviewed, 5 unresolved discussions (waiting on @hatton, @JohnThomson, and @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2021-06-01 21:22 UTC, andrew-polk approved these changes
> Dismissed @JohnThomson and @StephenMcConnel from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2021-06-01 21:23 UTC, andrew-polk approved these changes
> Dismissed @StephenMcConnel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-06-01 21:23 UTC, merged