Allow user to choose a default bookshelf for uploads (BL-10020)
BloomBooks/BloomDesktop pull request #4524
Opened 2021-06-01 22:24 UTC by JohnThomson

2021-06-01 23:24 UTC, hatton requested changes
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: 1 of 11 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/contentful/ContentfulContext.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8s0GyE7q-TIP4s5RN:-Mb8s0GyE7q-TIP4s5RO:b-2cf8wi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/contentful/ContentfulContext.tsx#L10)):*
> ```XML
> });
> 
> // using the preview key, we can access draft materials for easy previewing while working on content
> ```

Do we need have a use for preview in this context?
___
*[src/BloomBrowserUI/contentful/UseContentful.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8sjFf-spgn1zcPi3f:-Mb8sjFf-spgn1zcPi3g:b2j8rut) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/contentful/UseContentful.tsx#L13)):*
> ```XML
> // Bloom probably doesn't much need this (yet, at least) but I copied most of this code
> // from BloomLibrary2 and it's easiest to keep it as little changed as possible,
> // especially w.r.t. things we might want one day.
> ```

What do you think? My intuition is that it is better to strip down to what we are actually using, which is some simple code. Then, if we wanted the full power, then we should factor out to some shared code. But this in-between state leaves me uncomfortable.


<!-- Sent from Reviewable.io -->

2021-06-01 23:27 UTC, hatton requested changes
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8tKCm0o2ALOvAiZkY:-Mb8tKCm0o2ALOvAiZkZ:b-ictwwi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L29)):*
> ```XML
>     // to retrieve the actual contentful ID of the Enterprise Subscription
>     // object to which the collections we want refer. The third retrives the
>     // collections that refer to that object in their enterpriseSubscriptions
> ```

In the comments, we have

![image.png](https://files.reviewableusercontent.io/images/reviewable/8448/u9--Mos5iKmQsNC9w57mHOkV/image.png)

So I didn't expect to see you doing 2 queries. Maybe you don't want to bother changing, now, though?


<!-- Sent from Reviewable.io -->

2021-06-01 23:48 UTC, hatton requested changes
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: 5 of 11 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8ug3503uB6CMSPbAY:-Mb8ug3503uB6CMSPbAZ:b-uk75s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L59)):*
> ```XML
>     // or we haven't yet retrieved the project, no query will run.)
>     const {
>         loading: loadingES,
> ```

I don't understand these "ES" things. `loading` and `error` seem to actually be `boolean`, and result seems to actually be a `string`
___
*[src/BloomExe/Collection/CollectionSettings.cs, line 461 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8ww-X611fsV_68IcK:-Mb8ww-Y0xb6iIl4G546:bayg351) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomExe/Collection/CollectionSettings.cs#L461)):*
> ```Smalltalk
> 				Administrators=ReadString(xml, "Administrators", "")
> 					.Split(new[] {","}, StringSplitOptions.RemoveEmptyEntries);
> 				var defaultTags = ReadString(xml, "DefaultBookTags", "").Split(';');
> ```

Do you prefer semi-colon over Comma-delimited here?
___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8y10L8Wb5bJ2bm3hZ:-Mb8y10L8Wb5bJ2bm3h_:b-f03d00) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L38)):*
> 		// here, it feels awkward to have a static reference to a very temporary object like
		// a dialog. This API is designed specifically to support that dialog, so a bit of

I think it feels *way more awkward* to see it here. It triggers me! And in the dialog, I would recommend naming it something like `PendingDefaultBookshelf`


<!-- Sent from Reviewable.io -->

2021-06-01 23:50 UTC, andrew-polk requested changes
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 18 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomBrowserUI/contentful/UseContentful.tsx, line 173 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8i2cr6Yiu6KQ5fSIh:-Mb8i2cr6Yiu6KQ5fSIi:bqllryy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/contentful/UseContentful.tsx#L173)):*
> ```XML
> //     // eslint-disable-next-line no-unreachable
> //     return tempLocalesCache;
> // }
> ```

How about replacing all these comment with a comment at the top saying if we ever need localized content, see relevant code in BloomLibrary2?
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8oI5dChMh4sdPrGWg:-Mb8oI5dChMh4sdPrGWh:b-4dzyhs) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L28)):*
> ```
> retrives
> ```
retrieves
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8oATx4pI3os_F--Il:-Mb8oATx4pI3os_F--Im:biyt9y0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L38)):*
> ```
>     // The currentShelf retrieved from the settings/bookShelfData API, or 'none'
>     // currentShelf is falsy. Using 'none' as the value here in this control
> ```
or 'none' **if** currentShelf is falsy
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8qwqa0gX763FjDJwo:-Mb8qwqa0gX763FjDJwp:bfdof52) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L43)):*
> ```XML
>     // in our API which does not allow an empty string as the value of a
>     // required string value.
>     const [currentShelf, setCurrentShelf] = useState("");
> ```

Just a thought... would this provide more consistency with the C# side if we called it defaultBookshelf?
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8oees5GC42IiGtG_C:-Mb8oees5GC42IiGtG_D:b-6j51gn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L57)):*
> ```XML
>     // Preliminary query to get the ID of the indicated enterpriseSubscription
>     // (assuming we have a project...if the project is not an enterprise one,
>     // or we haven't yet retrieved the project, no query will run.)
> ```

In the high-level description, you listed "three" queries as first, second, and third. Then you refer to them here as "first", "preliminary", and "main". I found the latter confusing after already having three in my mental model.
Here, how about first, second, third; or local, preliminary contentful, and main contentful?
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 134 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8rLup9mLZdyG2Hh9V:-Mb8rLup9mLZdyG2Hh9W:b-n7sn5i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L134)):*
> ```
> max-height is close than usual to 100%
> ```
I think there's a typo here, but I can't parse it.
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 140 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8rWHo0jjhyQRoiHZq:-Mb8rWHo0jjhyQRoiHZr:bhcre97) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L140)):*
> ```
>     // ... Reduced padding makes the menu and items take up more
>     // the usual Windows amount of space.
> ```
I don't understand this sentence. If you're trying to make it look like Windows, why are we doing something to make it take up more than Windows?
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 152 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8s2sa4oLYIUzFaDs1:-Mb8s2sa4oLYIUzFaDs2:b-upbham) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L152)):*
> ```
> fontFamily: "Segoe UI",
> ```
Do we really have to set this even though the outer div has this font-family? That's annoying!
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 201 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8s_zICIDcjqSJjihY:-Mb8s_zICIDcjqSJjihZ:b-rh7ie0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L201)):*
> ```
> don'e
> ```
don't
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 264 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8z1ok80tiptoka6YP:-Mb8z1ok80tiptoka6YQ:b-e7li16) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L264)):*
> ```XML
>                         `}
>                         l10nKey="CollectionSettingsDialog.DefaultBookshelfDescription"
>                         temporarilyDisableI18nWarning={true}
> ```

I'm not sure what the advantage is to delaying i18n.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8jbCJ00FgYEVlnAdt:-Mb8jbCKA-0Jjhq4k8Af:bc20zu8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomExe/Collection/CollectionSettingsDialog.cs#L55)):*
> ```Smalltalk
> 			_language2FontLabel.UseMnemonic = false;
> 			_language3FontLabel.UseMnemonic = false;
> 			CollectionSettingsApi.DefaultBookshelf = collectionSettings.DefaultBookshelf;
> ```

How do you feel about setting something like `pendingDefaultBookshelf` in collection settings so that the view doesn't need to reference the api?

Hm. But as I look further... 
CollectionSettingsApi.DefaultBookshelf is never read. So this line can go away. And I think you can just set _collecitonSetings.DefaultBookshelf directly in the API instead of setting this intermediary.
Unless I missing somethign.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 425 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8lBcL9dHEPp9q139I:-Mb8lBcL9dHEPp9q139J:bd8g8te) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L425)):*
> ```Smalltalk
> 				// change that, so that the list of tags uploaded will be decisive
> 				// Suspicion: Bloom editor only handles the topic tag and loses any others;
> 				// BL was made to retain bookshelf to overcome that problem.
> ```

I think this comment is confusing after a couple iterations/updates. And I think is not completely accurate?
Maybe just kind of start over/simplify with the current state of things?

For example, harvester maintains tag info so we don't lose librarian-set data. But since we are about to change that, this comment probably doesn't need to say anything about it anyway.


<!-- Sent from Reviewable.io -->

2021-06-01 23:51 UTC, hatton requested changes
> Reviewed 5 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 19 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 415 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8z49hET5Uj2RL6iQU:-Mb8z49hET5Uj2RL6iQV:bda6bjd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L415)):*
> ```Smalltalk
> #endif
> 				metadata.DownloadSource = s3BookId;
> 				// If the collection has a default book shelf, make sure the book has that tag.
> ```

Yeah if I'm thinking correctly, then for now this should simply be 

`metadata.Tags = collectionStettings.DefaultBookshelf`


<!-- Sent from Reviewable.io -->

2021-06-01 23:51 UTC, hatton reviewed
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 19 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2021-06-01 23:54 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 19 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 264 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8z1ok80tiptoka6YP:-Mb8zfMFC5285bN3EMDc:bfk2iro) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L264)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure what the advantage is to delaying i18n.
</blockquote></details>

Seems good to me. I fear the ever growing "l10 load". I wish we could specify priorities.


<!-- Sent from Reviewable.io -->

2021-06-01 23:57 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 19 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 264 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8z1ok80tiptoka6YP:-Mb9-GG60tgpR5D8b5np:b-5z7iw6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L264)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Seems good to me. I fear the ever growing "l10 load". I wish we could specify priorities.
</blockquote></details>

Still not seeing the advantage of delaying. Maybe it makes sense to say we don't think we will localize this. But then we probably want to introduce a new prop which would mean that.

But we do have BloomLowPriority.


<!-- Sent from Reviewable.io -->

2021-06-02 16:51 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: 4 of 11 files reviewed, 19 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/contentful/ContentfulContext.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8s0GyE7q-TIP4s5RN:-MbBrIs0EEwNsebzDZu2:ba3dfob) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/contentful/ContentfulContext.tsx#L10)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Do we need have a use for preview in this context?
</blockquote></details>

Removed
___
*[src/BloomBrowserUI/contentful/UseContentful.tsx, line 13 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8sjFf-spgn1zcPi3f:-MbBtvHp9Dt_oKQ0qU6h:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/contentful/UseContentful.tsx#L13)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What do you think? My intuition is that it is better to strip down to what we are actually using, which is some simple code. Then, if we wanted the full power, then we should factor out to some shared code. But this in-between state leaves me uncomfortable.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/contentful/UseContentful.tsx, line 173 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8i2cr6Yiu6KQ5fSIh:-MbBtuVIASqNJlYtWYHd:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/contentful/UseContentful.tsx#L173)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How about replacing all these comment with a comment at the top saying if we ever need localized content, see relevant code in BloomLibrary2?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 28 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8oI5dChMh4sdPrGWg:-MbBu9In8MW91U4HtsR3:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L28)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> retrives
> ```
retrieves
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 29 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8tKCm0o2ALOvAiZkY:-MbBuBzW50tvkCjNqMcg:b-dbjmlv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L29)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

In the comments, we have

![image.png](https://files.reviewableusercontent.io/images/reviewable/8448/u9--Mos5iKmQsNC9w57mHOkV/image.png)

So I didn't expect to see you doing 2 queries. Maybe you don't want to bother changing, now, though?
</blockquote></details>

Didn't want to change unless the other model is actually a better model. We decided that it is, so I've made the change. It definitely simplified things.
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8oATx4pI3os_F--Il:-MbBvJ7h5pVazJPt-O57:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L38)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     // The currentShelf retrieved from the settings/bookShelfData API, or 'none'
>     // currentShelf is falsy. Using 'none' as the value here in this control
> ```
or 'none' **if** currentShelf is falsy
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8qwqa0gX763FjDJwo:-MbBvXoRAdvjH9vmY8Cv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Just a thought... would this provide more consistency with the C# side if we called it defaultBookshelf?
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 57 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8oees5GC42IiGtG_C:-MbBvjlZCF1PYM0ZLitj:b-4u9yg4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In the high-level description, you listed "three" queries as first, second, and third. Then you refer to them here as "first", "preliminary", and "main". I found the latter confusing after already having three in my mental model.
Here, how about first, second, third; or local, preliminary contentful, and main contentful?
</blockquote></details>

Done. (Well, we're now down to first an second.)
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8ug3503uB6CMSPbAY:-MbBvnzC1YTAaCzlKd3r:b-fckn8r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L59)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I don't understand these "ES" things. `loading` and `error` seem to actually be `boolean`, and result seems to actually be a `string`
</blockquote></details>

These look like type declarations, but they are not. This is a destructor. useContentful returns an object with properties loading:boolean, result: any[], and error:boolean. Those three values are assigned to three new const variables loadingES, resultES, and errorES (to distinguish them from the similar values returned in what I think of as the main query below). I added a comment.
However, we're now down to one contentful query, so we don't need two sets of names, and these are gone.
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 134 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8rLup9mLZdyG2Hh9V:-MbBxByh8UOtcXk6UOKZ:b-47z0yh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L134)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> max-height is close than usual to 100%
> ```
I think there's a typo here, but I can't parse it.
</blockquote></details>

Hopefully better
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 140 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8rWHo0jjhyQRoiHZq:-MbBxU2l9MvopsNh3Vb4:b3bvum1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L140)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
>     // ... Reduced padding makes the menu and items take up more
>     // the usual Windows amount of space.
> ```
I don't understand this sentence. If you're trying to make it look like Windows, why are we doing something to make it take up more than Windows?
</blockquote></details>

Badly worded. It is (just) possible to p [...]

2021-06-02 16:55 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: 4 of 11 files reviewed, 16 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8qwqa0gX763FjDJwo:-MbCdZ7a2m8KPwrhZgOf:b-w7xexu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L43)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@johnthomson I don't see the full change yet. Andrew suggested "defaultBookshelf"


<!-- Sent from Reviewable.io -->

2021-06-02 17:01 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: 4 of 11 files reviewed, 16 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8ug3503uB6CMSPbAY:-MbCdtpF6UuciVSsNRVc:blvm22d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L59)):*
> This is a destructor

Ah, yes.
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 264 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8z1ok80tiptoka6YP:-MbCe8H2BxM8OV0qZDtg:bazelas) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L264)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

My thinking was (a) this is used by Enterprise users, maybe they know enough English? (b) Maybe we will reword things after testers try it out? (c) maybe a good time to internationalize is as things move from beta to release, like we seem to be planning for TC?
</blockquote></details>

(Point taken, Andrew)
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 421 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-MbCecpB82Ef5j32uKsH:-MbCecpB82Ef5j32uKsI:b-xg2hwv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cf24de6b55c0d6c5948c0e9055204bbaee213130/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L421)):*
> ```Smalltalk
> 				if (!string.IsNullOrEmpty(collectionSettings?.DefaultBookshelf))
> 				{
> 					tags = tags.Concat(new [] {"bookshelf:" + collectionSettings.DefaultBookshelf});
> ```

What keeps this from accruing a new copy of the bookshelf tag each time? Probably worth a comment or I'll wonder again some day. FWIW it's likely that we will have a follow-on feature where you can select the bookshelf for the individual book.


<!-- Sent from Reviewable.io -->

2021-06-02 17:16 UTC, andrew-polk approved these changes
> Reviewed 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 140 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8rWHo0jjhyQRoiHZq:-MbCeVBS0cef7w2uMic0:bg2exyr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L140)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Badly worded. It is (just) possible to parse "more the usual" as "more like the usual", at least in my dialect. Reworded.
</blockquote></details>

Ah. I inserted a word when reading it. Thanks for clarifying.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8jbCJ00FgYEVlnAdt:-MbChasE1298UaonRcKA:b-4yp4s3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomExe/Collection/CollectionSettingsDialog.cs#L55)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Afraid you did. There's a line _collectionSettings.DefaultBookshelf = CollectionSettingsApi.DefaultBookshelf; in the OK code of CollectionSettingsDialog.
I don't much like giving CollectionSettings a bunch of variables that are only used while something is editing it. (It's not just this one, there's a family of values, such as all the enterprise setting stuff, that is handled the same way. Eventually every aspect of CollectionSettings that is edited from HTML controls, I expect.)
If I were going to refactor, it would probably be in the direction of giving the API a reference to the dialog object, which is the logical place to store the temporary results. But it's slightly weird for a long-lifetime object to have a reference to such a short-lifetime object. I don't muc h like any of the approaches I've found.
However, in another comment JohnH strongly preferred to give the API a reference to the dialog, so that's what I've done.
</blockquote></details>

I think it would make for better separation if the model housed the staged changes somehow. But since this will all get "fixed" once the tab is react, it would be more effort than it is worth, probably.


<!-- Sent from Reviewable.io -->

2021-06-02 18:20 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8qwqa0gX763FjDJwo:-MbCwGzbDx6v4XYddB5p:b-m8effh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L43)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

@johnthomson I don't see the full change yet. Andrew suggested "defaultBookshelf"
</blockquote></details>

It's there. For some reason Reviewable seemed to think the new changes were 'provisional'?
___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8ug3503uB6CMSPbAY:-MbCwOSh5gg_qLcG7A2w:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L59)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> This is a destructor

Ah, yes.
</blockquote></details>

Done.
___
*[src/BloomExe/Collection/CollectionSettingsDialog.cs, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8jbCJ00FgYEVlnAdt:-MbCwiinE9LUnify2JC9:b-zvuj5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomExe/Collection/CollectionSettingsDialog.cs#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it would make for better separation if the model housed the staged changes somehow. But since this will all get "fixed" once the tab is react, it would be more effort than it is worth, probably.
</blockquote></details>

If we wanted to, we could have a model of the state of the dialog. But that's not the same thing as the model of the collection's settings.
___
*[src/BloomExe/WebLibraryIntegration/BookTransfer.cs, line 421 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-MbCecpB82Ef5j32uKsH:-MbCveh0BYRaYUh9-DvK:b-9vaxjd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/cf24de6b55c0d6c5948c0e9055204bbaee213130/src/BloomExe/WebLibraryIntegration/BookTransfer.cs#L421)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What keeps this from accruing a new copy of the bookshelf tag each time? Probably worth a comment or I'll wonder again some day. FWIW it's likely that we will have a follow-on feature where you can select the bookshelf for the individual book.
</blockquote></details>

Ah...the previous line of code, which removed all bookshelf: tags?


<!-- Sent from Reviewable.io -->

2021-06-02 19:51 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8qwqa0gX763FjDJwo:-MbDGpl07ygbFwvCarJS:b-p5qq2h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L43)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's there. For some reason Reviewable seemed to think the new changes were 'provisional'?
</blockquote></details>

If I'm not mistaken, JH is referring to the difference between "defaultShelf" and "defaultBookshelf"


<!-- Sent from Reviewable.io -->

2021-06-03 18:02 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8qwqa0gX763FjDJwo:-MbI1JvX6UP56-84kCsQ:bncypd6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I'm not mistaken, JH is referring to the difference between "defaultShelf" and "defaultBookshelf"
</blockquote></details>

Done. Sorry.


<!-- Sent from Reviewable.io -->

2021-06-03 22:21 UTC, hatton requested changes
> Reviewed 3 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8qwqa0gX763FjDJwo:-MbIxhbR3TIimfEJbnfm:b-zd29h9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L43)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. Sorry.
</blockquote></details>

@johnthomson I'm not seeing the change yet. Reviewable is showing me 

` const [defaultShelf, setDefaultShelf] = useState("");`

when I expect to see

` const [defaultBookShelf, setDefaultBookShelf] = useState("");`
___
*[src/BloomExe/web/controllers/CollectionSettingsApi.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8y10L8Wb5bJ2bm3hZ:-MbIxVE61UhLuP2BDp4R:bymei6k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L38)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. (Note, there are lots of other pre-existing statics just like this that should be fixed too. But I think better to fix them in a separate PR, probably targeting master.)
</blockquote></details>

Yeah and I complain about people putting state in APIs every time I see it (unless of course, *I* did it :-)   ).


<!-- Sent from Reviewable.io -->

2021-06-04 13:55 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx, line 43 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524#-Mb8qwqa0gX763FjDJwo:-MbMIf8fED0NLAmUE-Lh:b9egtts) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4137e4235e1541a3585eba313e4baa6db104630b/src/BloomBrowserUI/react_components/DefaultBookshelfControl.tsx#L43)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

@johnthomson I'm not seeing the change yet. Reviewable is showing me 

` const [defaultShelf, setDefaultShelf] = useState("");`

when I expect to see

` const [defaultBookShelf, setDefaultBookShelf] = useState("");`
</blockquote></details>

Sorry. Somehow the latest changes didn't get pushed.


<!-- Sent from Reviewable.io -->

2021-06-04 15:41 UTC, hatton reviewed
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4524)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2021-06-04 15:41 UTC, merged