Let C# handle mailto and external links in ReactControl (BL-10050)
BloomBooks/BloomDesktop pull request #4536
Opened 2021-06-04 20:36 UTC by JohnThomson

2021-06-04 21:38 UTC, andrew-polk requested changes

2021-06-04 21:38 UTC, andrew-polk commented on src/BloomExe/web/ReactControl.cs
> +			browser.OnBrowserClick += Browser.HandleExternalLinkClick;
We don't need to unsubscribe?

2021-06-04 21:51 UTC, hatton approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4536)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/web/ReactControl.cs, line 97 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4536#-MbNzOND70PUv4xdcxGO:-MbNzOND70PUv4xdcxGP:bvmijj9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b9cdc6b63c997f30001cb3954ec21ded73b42a8f/src/BloomExe/web/ReactControl.cs#L97)):*
> ```Smalltalk
> 				
> 			};
> 			// This is mainly so that the mailTo: link in the Team Collection settings panel
> ```

One has to go read `HandleExernalLinkClick` to decided that this is not a bug :-) But what's a better name? Hard. Something like `InterceptIfThisIsAnExternalLinkClick`?


<!-- Sent from Reviewable.io -->

2021-06-07 14:28 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4536)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/web/ReactControl.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4536#-MbNjYaChvCpEAtfZSLx-r1-104:-MbaruIv2vGSEgn-WcMY:bp0shtz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b9cdc6b63c997f30001cb3954ec21ded73b42a8f/src/BloomExe/web/ReactControl.cs#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We don't need to unsubscribe?
</blockquote></details>

Don't see any reason to. We want this handler in place for the life of the browser. Other places where we set this up don't.


<!-- Sent from Reviewable.io -->

2021-06-07 14:29 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4536)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/web/ReactControl.cs, line 97 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4536#-MbNzOND70PUv4xdcxGO:-Mbas6Lb0vRgBe3h5qmf:b-77eo8r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b9cdc6b63c997f30001cb3954ec21ded73b42a8f/src/BloomExe/web/ReactControl.cs#L97)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

One has to go read `HandleExernalLinkClick` to decided that this is not a bug :-) But what's a better name? Hard. Something like `InterceptIfThisIsAnExternalLinkClick`?
</blockquote></details>

I can change it if you want. But I agree, it's hard to come up with a clearly better name.


<!-- Sent from Reviewable.io -->

2021-06-07 15:36 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4536)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-06-07 20:16 UTC, merged