Spreadsheet import/export stage 1 (BL-9897)
BloomBooks/BloomDesktop pull request #4550
Opened 2021-06-15 15:36 UTC by JohnThomson

2021-06-15 18:30 UTC, andrew-polk requested changes
I'm not done reviewing, but I added some comments so I figured I would go ahead and publish.

> Reviewed 16 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-:-McFvvoI7VgWEns0F5oy:b-xe8sud)* status: 16 of 20 files reviewed, 11 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/HtmlDom.cs, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFthc17rZGq8T9x2YE:-McFthc28YTm3bfBrQkh:bdxpbsi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Book/HtmlDom.cs#L53)):*
> ```
> _dom.PreserveWhitespace = true;
> ```
Is there any risk to this?
___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFYi-y8Ej48BCed3eY:-McFYi-y8Ej48BCed3eZ:bei8hof) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L49)):*
> ```
> book
> ```
folder or htm file?
___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFYmcnAMpF7ODgJb2F:-McFYmcnAMpF7ODgJb2G:b-zhurj0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L52)):*
> ```
> file 
> ```
must be an xlsx file?
___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFYzkS8p0FizgcMgvL:-McFYzkS8p0FizgcMgvM:bsp8h90) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L55)):*
> ```
> file containing parameters
> ```
Worth saying anything here about extension or format?
Or maybe the help text here or for the verb should have a link to some documentation? (not sure what the documentation plan is... but certainly this is not enough to get started on your own)

Similar issues for the import command to the ones I've put here in export.
___
*[src/BloomExe/Spreadsheet/HeaderRow.cs, line 9 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFbzsR4FrdfcdnAW2s:-McFbzsR4FrdfcdnAW2t:b3sj7wy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/HeaderRow.cs#L9)):*
> ```Smalltalk
> namespace Bloom.Spreadsheet
> {
> 	public class HeaderRow: SpreadsheetRow
> ```

class comment
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFqq1c5j5HWQIX3OH7:-McFqq1c5j5HWQIX3OH8:bu8nggz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L21)):*
> ```
> TextGroupLabel
> ```
Don't we usually prepend these with `k`?
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 76 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFrqVW8MbZTjS4Hckl:-McFrqVW8MbZTjS4Hckm:bs06jgh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L76)):*
> ```
> AllRows
> ```
Seems like we should either have all GetX (like GetContentRows) or none.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExportParams.cs, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFdMac5eUBZWnT85Ko:-McFdMac5eUBZWnT85Kp:bvlxwi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetExportParams.cs#L12)):*
> ```
> SpreadsheetImporter
> ```
SpreadsheetExporter
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 26 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFu5bk2XB6aEvwsoZG:-McFu5bk2XB6aEvwsoZH:b-8p6blu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L26)):*
> ```
> it's easiest to just do it here
> ```
static constructor would work, too.
Then you wouldn't need it in two places or need to remember to add it to future public static methods.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFv-N277mKOJ5U6OSp:-McFv-N277mKOJ5U6OSq:bbomhkz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L49)):*
> ```
> RobustFile.Delete(path);
> ```
I'm pretty sure this will fail if the user has the spreadsheet open.  Should we try to helpfully tell them it might be open?
I think we will also fail to read if the file is open. That will be a pretty typical occurrence, methinks.
___
*[src/BloomExe/Spreadsheet/SpreadsheetRow.cs, line 38 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFcrGeDRRKPVWJwVuE:-McFcrGf1hpMEjSKZJJM:bln0de0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetRow.cs#L38)):*
> ```
> Cell
> ```
GetCell?


<!-- Sent from Reviewable.io -->

2021-06-15 22:04 UTC, andrew-polk requested changes
> Reviewed 2 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550)* status: 18 of 20 files reviewed, 22 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McG9I8H7EMjw7uvHzFX:-McG9I8H7EMjw7uvHzFY:b-34ftmt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L98)):*
> ```
> SortTranslationGroups
> ```
I think this wants to be in another class. Probably TranslationGroupManager?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 88 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGdYXx0l9EdcwQdSm5:-McGdYXx0l9EdcwQdSm6:b-kah7lt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L88)):*
> ```
> indexOfRightPage
> ```
Since we can have right/left pages, this is confusing.
How about indexOfCorrectPage or indexOfTargetPage?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 145 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGeDB06o_e9ItYgf7M:-McGeDB06o_e9ItYgf7N:b-pi29bx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L145)):*
> ```
> NumberOfPage
> ```
Belongs in HtmlDom?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGegJL6MyzLj1R97y0:-McGegJL6MyzLj1R97y1:b-1465k3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L169)):*
> ```
> bool GetNextGroup()
> ```
I was going to suggest this be TryGetNextGroup, but then I saw that nothing uses the return value.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 195 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGf3ab0gAFzrqXSuAD:-McGf3ab0gAFzrqXSuAE:b-ejbnjr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L195)):*
> ```
> GroupsOnPage
> ```

Should this be TranslationGroupManager::GetSortedGroupsOnPage()?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 225 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGfVCa0t4pAR7xVZau:-McGfVCa0t4pAR7xVZav:bv5h9hf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L225)):*
> ```
> // todo
> ```
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 231 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGfYU23bu3GpyG7oW6:-McGfYU23bu3GpyG7oW7:bbjmd73) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L231)):*
> ```Smalltalk
> 				}
> 
> 				
> ```

Strange indentation below here.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 256 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGgEgLDRjG1BvXRFul:-McGgEgLDRjG1BvXRFum:b-rzrjqh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L256)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 				foreach (var editable in group.ChildNodes.Cast<XmlNode>()
> 					.Where(x => x is XmlElement e
> 						&& (e.Attributes["class"]?.Value ?? "").Contains("bloom-editable"))
> 					.Cast<XmlElement>().ToList())
> ```
</details>

Seems like this logic does or should exist in HtmlDom (or is there a better class)?

And actually maybe the whole block in `if (RemoveOtherLanguages)` wants to be a method there?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 284 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGfvOQ9n1htYw8X72C:-McGfvOQ9n1htYw8X72D:b-el1aks) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L284)):*
> ```
> NoMarkup
> ```
HasNoMarkup?
Or reverse it to HasMarkup?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 286 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGfq6w7ip47ghKoFY2:-McGfq6w7ip47ghKoFY3:b-1dp8uh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L286)):*
> ```
> wedges
> ```
I don't have this sense in my idiolect. How about `angle brackets`?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 292 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGgqVl-6Oau9ion1fB:-McGgqVm8d1HTcW-jWzS:b13pg94) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L292)):*
> ```
> EditableChildInLang
> ```
Again, I think this wants to be in HtmlDom or another class.
Probably with a `Get` prefix.


<!-- Sent from Reviewable.io -->

2021-06-15 22:04 UTC, andrew-polk reviewed
Ok, I've reviewed everything but tests. I'm just not up to that right now...
But you can take a look at what I've commented so far.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-:-McGh2v6C7WrHTZvCyyU:b-b5gbgf)* status: 18 of 20 files reviewed, 22 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2021-06-16 16:25 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550)* status: 18 of 20 files reviewed, 23 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/packages.config, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McKcsq53HWa1vZR5rte:-McKcsq53HWa1vZR5rtf:b1zjq8t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/packages.config#L30)):*
> ```XML
>   <package id="Microsoft.DotNet.PlatformAbstractions" version="3.1.6" targetFramework="net461" />
>   <package id="Microsoft.Extensions.DependencyModel" version="3.1.6" targetFramework="net461" />
>   <package id="Microsoft.Web.Xdt" version="3.1.0" targetFramework="net461" />
> ```

It appears we also need 
`  <package id="Microsoft.IO.RecyclableMemoryStream" version="1.4.1" targetFramework="net461" />`

(I wanted to try out this cool new feature, but I couldn't get it to run. I uninstalled and reinstalled EPPlus from the Nuget package manager, and it added this.)


<!-- Sent from Reviewable.io -->

2021-06-16 18:14 UTC, andrew-polk requested changes
> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550)* status: 19 of 20 files reviewed, 26 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 42 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McL-K0815CsZ-NP89Da:-McL-K0815CsZ-NP89Db:bhh0pm5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L42)):*
> ```Smalltalk
> 		protected virtual void InitializeImporter(SpreadsheetImporter importer)
> 		{ 
> 		}
> ```

I would have found it helpful if this had a comment like
// Base implementation currently does nothing
or 
// Subclasses can provide extra initialization steps
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McKzEwq-lBvzaSFqe9X:-McKzEwq-lBvzaSFqe9Y:bbcxagi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L53)):*
> ```
> Subclass with RemoveOtherLanguages overrides
> ```
Is this a todo? You were going to run this again with the import parameters different?

As is, I think this wants to be called simply `GermanKept`?

Later... 
Actually, it looks like you did this below to test that behavior? So you can remove this comment and clean up both method names?
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 77 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McKzzEz3tXUOxAJZL5Q:-McKzzEz3tXUOxAJZL5R:bc6rfbw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L77)):*
> ```Smalltalk
> 			// Now, did it put things in the right places? "This elephant is running amok." which we put in the first row
> 			// should be placed into the SECOND translation grou
> ```

Looks like this test didn't get finished


<!-- Sent from Reviewable.io -->

2021-06-16 20:01 UTC, andrew-polk requested changes
Ok, all done with initial review.

> Reviewed 1 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-:-McLPTejEkqjtH_fnSqB:b2fv1m2)* status: all files reviewed, 28 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomTests/Spreadsheet/SpreadsheetTests.cs, line 161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McLNVBT52EMWHsbxMWa:-McLNVBT52EMWHsbxMWb:b7g68qx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomTests/Spreadsheet/SpreadsheetTests.cs#L161)):*
> ```
> _sheetXml, _rowsXml or _sheetFile, _rowsFile
> ```
Looks like you changed these variable names but not the comment
___
*[src/BloomTests/Spreadsheet/SpreadsheetTests.cs, line 363 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McLPCwMAMK-p61ksIv9:-McLPCwMAMK-p61ksIvA:b8k1r9f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomTests/Spreadsheet/SpreadsheetTests.cs#L363)):*
> ```Smalltalk
> 
> 		[Test]
> 		public void SortTranslationGroups_YieldsExpectedOrder()
> ```

A reminder that this needs to move if you end up moving the target method.


<!-- Sent from Reviewable.io -->

2021-06-17 15:54 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550)* status: 6 of 21 files reviewed, 28 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/packages.config, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McKcsq53HWa1vZR5rte:-McPEePR-fy0BeQR4Cnv:b-gdfgt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/packages.config#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It appears we also need 
`  <package id="Microsoft.IO.RecyclableMemoryStream" version="1.4.1" targetFramework="net461" />`

(I wanted to try out this cool new feature, but I couldn't get it to run. I uninstalled and reinstalled EPPlus from the Nuget package manager, and it added this.)
</blockquote></details>

Done. (In the course of trying to repair the mess package manager made, I think I reverted all changes and then just put in what I thought was the one new line I needed.)
___
*[src/BloomExe/Book/HtmlDom.cs, line 53 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFthc17rZGq8T9x2YE:-McPElKRAuU1FSZHvUls:b-j1civv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Book/HtmlDom.cs#L53)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> _dom.PreserveWhitespace = true;
> ```
Is there any risk to this?
</blockquote></details>

I don't think so. I'm very surprised that the lack of it hasn't caused problems before this. Without it, for example, the white space between two sentence spans simply gets dropped. I can only assume this constructor isn't used much.
___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 49 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFYi-y8Ej48BCed3eY:-McPFjXy1G6QhMKSvGc0:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> book
> ```
folder or htm file?
</blockquote></details>

Done.
___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFYmcnAMpF7ODgJb2F:-McPFyUaCOM0ln4I03om:b4ocu1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> file 
> ```
must be an xlsx file?
</blockquote></details>

Done. (Actually, it had better be an xlsx that pretty closely follows the organization we've designed.)
___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFYzkS8p0FizgcMgvL:-McPKTLh6icW3gILWdt_:b-lwfm7b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> file containing parameters
> ```
Worth saying anything here about extension or format?
Or maybe the help text here or for the verb should have a link to some documentation? (not sure what the documentation plan is... but certainly this is not enough to get started on your own)

Similar issues for the import command to the ones I've put here in export.
</blockquote></details>

Done. (There's not much yet, but I added a link to what we do have.)
___
*[src/BloomExe/Spreadsheet/HeaderRow.cs, line 9 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFbzsR4FrdfcdnAW2s:-McPKwZMAI8POU8e98is:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/HeaderRow.cs#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

class comment
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFqq1c5j5HWQIX3OH7:-McPL0yoDPtGdquZG5zh:b8dxb68) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> TextGroupLabel
> ```
Don't we usually prepend these with `k`?
</blockquote></details>

According to whatever tool complains about name formatting on my system...maybe Resharper?...not when they are public.
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 76 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFrqVW8MbZTjS4Hckl:-McPLZfg8ISlc8CPTNGj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L76)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> AllRows
> ```
Seems like we should either have all GetX (like GetContentRows) or none.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 98 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McG9I8H7EMjw7uvHzFX:-McPUlnCAn5hxYZQVSkY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> SortTranslationGroups
> ```
I think this wants to be in another class. Probably TranslationGroupManager?
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExportParams.cs, line 12 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFdMac5eUBZWnT85Ko:-McPUuxX-BP0dMlOA31r:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetExportParams.cs#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> SpreadsheetImporter
> ```
SpreadsheetExporter
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 88 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGdYXx0l9EdcwQdSm5:-McPVN925DjpHCoZlQC-:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> indexOfRightPage
> ```
Since we can have right/left pages, this is confusing.
How about indexOfCorrectPage or indexOfTargetPage?
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 145 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGeDB06o_e9ItYgf7M:-McPVbcmBmWKeJ02K7i6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L145)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> NumberOfPage
> ```
Belongs in HtmlDom?
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 169 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McGegJL6MyzLj1R97y0:-McPVrGOCiBFRsy2Rp7Z:ba3o3s1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L169)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> bool GetNextGroup()
> ```
I was going to suggest this be TryGetNextGroup, but then I saw that nothing uses the return value.
</blockquote></detai [...]

2021-06-17 16:41 UTC, andrew-polk requested changes
> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFYmcnAMpF7ODgJb2F:-McPnlkl7jMyKqHSxPwW:b-755ew2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L52)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. (Actually, it had better be an xlsx that pretty closely follows the organization we've designed.)
</blockquote></details>

"xlsx" got added to the import command but not the export command
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 93 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McPpRyYB12jLT-E8c2l:-McPpRyYB12jLT-E8c2m:blwr1ee) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2ffa3a7897549c2b2d8340ac0829eca274a166dc/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L93)):*
> ```
> test subclass
> ```
I'm probably just missing something, but I don't see an advantage to making a virtual/override test method. And it is kind of confusing.
Can't we just make the base class test 
`public void GermanKept`
and this one
`public void GermanRemoved`
?


<!-- Sent from Reviewable.io -->

2021-06-17 19:30 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550)* status: 19 of 21 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/CLI/SpreadsheetExportCommand.cs, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McFYmcnAMpF7ODgJb2F:-McQRnsf1oyKzHQyv5ea:b-jlx3y0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/0c33ebb137b5abb56214baf8c7bfec53c5d440b3/src/BloomExe/CLI/SpreadsheetExportCommand.cs#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

"xlsx" got added to the import command but not the export command
</blockquote></details>

I thought it less necessary for the export command, but I suppose it's helpful to be reminded what extension to use. Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 93 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McPpRyYB12jLT-E8c2l:-McQRYpo0HdJSFRi8sRJ:bfzedau) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2ffa3a7897549c2b2d8340ac0829eca274a166dc/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L93)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> test subclass
> ```
I'm probably just missing something, but I don't see an advantage to making a virtual/override test method. And it is kind of confusing.
Can't we just make the base class test 
`public void GermanKept`
and this one
`public void GermanRemoved`
?
</blockquote></details>

We need some override to prevent the inherited GermanKept() test from running and failing. I tried another approach...see what you think.


<!-- Sent from Reviewable.io -->

2021-06-17 20:45 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 93 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4550#-McPpRyYB12jLT-E8c2l:-McQhjPL4pJGFLdrEwm0:b-pipt75) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2ffa3a7897549c2b2d8340ac0829eca274a166dc/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L93)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We need some override to prevent the inherited GermanKept() test from running and failing. I tried another approach...see what you think.
</blockquote></details>

Interesting. I didn't know that's how inheritance worked with NUnit.
I suppose another way would be an abstract class with two implementations. But not worth any more effort.


<!-- Sent from Reviewable.io -->

2021-06-17 20:45 UTC, merged