export images to spreadsheet, refactor
BloomBooks/BloomDesktop pull request #4609
Opened 2021-07-21 22:49 UTC by nabalone

2021-07-22 16:19 UTC, JohnThomson requested changes
Good work!

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-:-MfE-wFh78rgIC3DbSxn:b-onzvv2)* status: all files reviewed, 20 unresolved discussions (waiting on @nabalone)

___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDUpiWC_D9aZFPLjVU:-MfDUpiX5UohvF3opEuz:b-yx4ei9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L33)):*
> ```Smalltalk
> 		{
> 			MetadataKeyLabel, // what kind of data is in the row; might be book-data key or [textgroup] or [image]
> 			PageNumberLabel, // for textgroups, value from data-page-number of bloom-page
> ```

I hope images have pageNumber, too, so comment needs adjusting
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 35 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDUyAT9ZA81nnEJocD:-MfDUyAT9ZA81nnEJocE:b96hyan) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L35)):*
> ```Smalltalk
> 			PageNumberLabel, // for textgroups, value from data-page-number of bloom-page
> 			// Todo: [page layout], // something that indicates the template for the page
> 			ImageIndexOnPageLabel, // for textgroups, its index in reading order
> ```

for images? and images won't be in 'reading' order, just in document order.
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDV43w49uBVYQ99GEC:-MfDV43x4M__L9RvL_m5:b-knrjf9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L36)):*
> ```Smalltalk
> 			// Todo: [page layout], // something that indicates the template for the page
> 			ImageIndexOnPageLabel, // for textgroups, its index in reading order
> 			ImageSourceLabel, // where the image comes from, especially for [image] rows
> ```

let's be more specific, at this point, it's the full path to the image, and only on image rows, right?
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 65 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDVbq72WOEsdIxUnkR:-MfDVbq72WOEsdIxUnkS:b-4w56z0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L65)):*
> ```Smalltalk
> 		}
> 
> 		public InternalSpreadsheet(bool populateHeader=true)
> ```

I don't much like the false option in the public constructor. If we don't create a header row at all, or don't populate the standard columns, ColumnForTag will not work properly.
I think we only need this for the ReadFromFile method, so how about making this constructor private and adding a public one with no argument that calls this with populateHeader true? (I think you will have to remove the default...the same result is achieved by calling the no-argument constructor).

In C# it would look like
public InternalSpreadsheet() : this(true) {}
private InternalSpreadsheet(bool populateHeader) {...
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 26 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfD_f_N4EJImK-WOQmT:-MfD_f_N4EJImK-WOQmU:bj5fqo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L26)):*
> ```Smalltalk
> 			foreach (var page in pages)
> 			{
> 				//First get images
> ```

Comment should move down to the new block. (First we are getting the page number!)
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfD_tMM70wuD0_Leq64:-MfD_tMM70wuD0_Leq65:biq30eg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L45)):*
> ```Smalltalk
> 				// which eventually needs to be handled by exporting data-book items.
> 				if (pageNumber == "")
> 					continue;
> ```

We don't need to repeat the previous 4 lines.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 69 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDosZRALksw31MY83I:-MfDosZRALksw31MY83J:b-avbcoa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L69)):*
> ```Smalltalk
> 				var row = new ContentRow(_spreadsheet);
> 				row.SetCell(InternalSpreadsheet.MetadataKeyLabel, InternalSpreadsheet.ImageKeyLabel);
> 				row.SetCell(InternalSpreadsheet.ImageIndexOnPageLabel, imageIndex.ToString(CultureInfo.InvariantCulture));
> ```

Let's have the page number on these rows, too.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDaO742AjeUGlCNMOH:-MfDaO742AjeUGlCNMOI:b-205s57) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L72)):*
> ```Smalltalk
> 				string imagePath = Path.Combine(imagesFolderPath, image.GetAttribute("src"));
> 				var encodedImageSrc = UrlPathString.CreateFromUrlEncodedString(imagePath);
> 				var decodedImageSrc = encodedImageSrc.NotEncoded;
> ```

The imagesFolderPath will not be encoded. It's remotely possible it might contain something that decoding would change. So it would be better to do something like
var imageSrc = UrlPathString.CreateFromUrlEncodedString(image.GetAttribute("src"));
var imagePath = Path.Combine(imagesFolderPath, imageSrc.NotEncoded);
And then stick imagePath into the cell.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 93 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDpxIc1Jx4rmtsRdAa:-MfDpxIc1Jx4rmtsRdAb:brd34se) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L93)):*
> ```Smalltalk
> 						using (System.Drawing.Image image = System.Drawing.Image.FromFile(imageSrcPath))
> 						{
> 							string imageName = imageSrcPath;
> ```

I'm not sure exactly how Excel uses this name, but I'm thinking maybe just the file name would be better if it's a pop-up label or something like that?
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 100 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDqJWXAdT_4IQSvKHk:-MfDqJWXAdT_4IQSvKHl:b-my84x1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L100)):*
> ```Smalltalk
> 							int finalWidth = defaultImageWidth;
> 							int finalHeight = (int)(finalWidth * origImageHeight / origImageWidth);
> 							excelImage.SetSize(finalWidth, finalHeight);
> ```

This could well be a research project after we merge this, since what you have is already very useful. But one of our goals is that in making the images small, they shouldn't contribute a lot to the spreadsheet size. So we may want to do something to reduce the pixel count of the image to the size we actually want.
Or maybe Excel does that in SetSize? If so, it would be worth commenting. Can you at least try and see whether a huge image file results in a similarly huge spreadsheet?
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDt26k8XE8uZGIK9OI:-MfDt26l8A2HpssLJ3Wx:b-a7avih) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L32)):*
> ```Smalltalk
> 			_sheet = exporter.Export(_dom, "fakeImagesFolderpath");
> 			var indexDe = _sheet.Colu [...]

2021-07-22 18:45 UTC, JohnThomson requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609)* status: all files reviewed, 21 unresolved discussions (waiting on @nabalone)

___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 35 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfEWdbNBEVW2EpAlKj7:-MfEWdbNBEVW2EpAlKj8:bg5rupg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L35)):*
> ```Smalltalk
> 			var engColumn = _sheet.ColumnForLang("en");
> 			_sheet.ContentRows.First(row => row.GetCell(engColumn).Content == "This elephant is running amok. Causing much damage.")
> 				.SetCell(engColumn, "<p>This elephant is running amok.</p>");
> ```

We could further improve this by adding a variable for the result of the "First" search, changing it to FirstOrDefault (which is allowed to answer null) and asserting it is not null, with a helpful description (third arg to Assert.That) like "Did not find the cell that OneTimeSetup was expecting to modify". Check that if you change the text it is looking for, the tests fail in a helpful way.


<!-- Sent from Reviewable.io -->

2021-07-22 22:07 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609)* status: 4 of 13 files reviewed, 21 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 33 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDUpiWC_D9aZFPLjVU:-MfFCv0b1fpnnwimghYo:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L33)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I hope images have pageNumber, too, so comment needs adjusting
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 35 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDUyAT9ZA81nnEJocD:-MfFCz1r0Uce_jeEzriv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L35)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

for images? and images won't be in 'reading' order, just in document order.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 36 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDV43w49uBVYQ99GEC:-MfFD2f757FdejYLKv7Y:bfizxld) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L36)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

let's be more specific, at this point, it's the full path to the image, and only on image rows, right?
</blockquote></details>

Is this good?
___
*[src/BloomExe/Spreadsheet/InternalSpreadsheet.cs, line 65 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDVbq72WOEsdIxUnkR:-MfFDapyB52OfyvYSSOr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L65)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't much like the false option in the public constructor. If we don't create a header row at all, or don't populate the standard columns, ColumnForTag will not work properly.
I think we only need this for the ReadFromFile method, so how about making this constructor private and adding a public one with no argument that calls this with populateHeader true? (I think you will have to remove the default...the same result is achieved by calling the no-argument constructor).

In C# it would look like
public InternalSpreadsheet() : this(true) {}
private InternalSpreadsheet(bool populateHeader) {...
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 26 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfD_f_N4EJImK-WOQmT:-MfFDd_300a6KQpYxXVs:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L26)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Comment should move down to the new block. (First we are getting the page number!)
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 45 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfD_tMM70wuD0_Leq64:-MfFDeWEB9rfd13N3kvM:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L45)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We don't need to repeat the previous 4 lines.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 69 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDosZRALksw31MY83I:-MfFDh8jDLOop6rRNitp:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L69)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's have the page number on these rows, too.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 72 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDaO742AjeUGlCNMOH:-MfFDkgv3uJ_3gXZd7xH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L72)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The imagesFolderPath will not be encoded. It's remotely possible it might contain something that decoding would change. So it would be better to do something like
var imageSrc = UrlPathString.CreateFromUrlEncodedString(image.GetAttribute("src"));
var imagePath = Path.Combine(imagesFolderPath, imageSrc.NotEncoded);
And then stick imagePath into the cell.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 93 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDpxIc1Jx4rmtsRdAa:-MfFDmAs8PXodKxRFqdO:b-9a6mfn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L93)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not sure exactly how Excel uses this name, but I'm thinking maybe just the file name would be better if it's a pop-up label or something like that?
</blockquote></details>

I'm guessing we don't want the file extension on the name?
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 100 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDqJWXAdT_4IQSvKHk:-MfFDtzZ0yRg509pLAFn:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L100)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This could well be a research project after we merge this, since what you have is already very useful. But one of our goals is that in making the images small, they shouldn't contribute a lot to the spreadsheet size. So we may want to do something to reduce the pixel count of the image to the size we actually want.
Or maybe Excel does that in SetSize? If so, it would be worth commenting. Can you at least try and see whether a huge image file results in a similarly huge spreadsheet?
</blockquote></details>

Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDt26k8XE8uZGIK9OI:-MfFE6oJ3pfTq9bhvYjZ:b-txnaed) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L32)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's add a comment here (which I should have written originally):
"The tests in this class all check the results of importing what export produced, but with a couple of changes. Here we locate the cells produced from two particular bloom-editable elements in the kSimpleTwoPageBook DOM and replace them with different text. The import should update those bloom-editables to these changed values."
</blockquote></details>

Did I put the comment in the right place? Its above "var exporter = new SpreadsheetExporter();"
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 35 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfEWdbNBEVW2EpAlKj7:-MfFF4dkA0O3YAfyOV [...]

2021-07-22 22:27 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609)* status: 4 of 13 files reviewed, 21 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 35 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfEWdbNBEVW2EpAlKj7:-MfFK6-y8cuCyCiCeMhv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L35)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-26 14:00 UTC, JohnThomson requested changes
Looks good. Two small remaining suggestions (one of them my fault)

> Reviewed 8 of 9 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-:-MfY6P9H5GFc8jOkAMhc:b-kstie2)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 93 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDpxIc1Jx4rmtsRdAa:-MfY37L60KlLmdk9r2dI:b-4wunir) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L93)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

I'm guessing we don't want the file extension on the name?
</blockquote></details>

I'm guessing a bit too, because I still don't really know how this shows up in Excel. But we've got the full path with extension elsewhere, so I think what you have is good.
___
*[src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs, line 17 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfY3iCV51XRx4aDODYo:-MfY3iCV51XRx4aDODYp:bymwmt0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/27294cd2a7e5fa0cd3a61881eea7f6a2aa955503/src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs#L17)):*
> ```Smalltalk
> namespace BloomTests.Spreadsheet
> {
> 	//TODO
> ```

Yes, this should be done :-)
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDt26k8XE8uZGIK9OI:-MfY4xPj0xDfJunA5NkA:b1148gr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L32)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Did I put the comment in the right place? Its above "var exporter = new SpreadsheetExporter();"
</blockquote></details>

Hmm, looking at it again in that context, I want to improve it some more. The first sentence is good where you have it, but there is another important change that isn't mentioned.
Let's
1. In the first sentence, change " a couple of " to "some".
2. Move the other two sentences to here (just above where we search for the two cells)
3. Add another comment above the declaration for indexDe: "Changing this header will cause all the data that was originally tagged as German to be imported as Tok Pisin."


<!-- Sent from Reviewable.io -->

2021-07-26 15:30 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs, line 17 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfY3iCV51XRx4aDODYo:-MfYR5xP65XbFoBZX5gG:b-a4wcvi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/27294cd2a7e5fa0cd3a61881eea7f6a2aa955503/src/BloomTests/Spreadsheet/SpreadsheetImagesTests.cs#L17)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, this should be done :-)
</blockquote></details>

Oops. Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs, line 32 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609#-MfDt26k8XE8uZGIK9OI:-MfYR9dH2u4VVP07BTRP:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/71833d7c85a16c631141c8614d370d7f4bd7ac26/src/BloomTests/Spreadsheet/SpreadsheetImporterTests.cs#L32)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Hmm, looking at it again in that context, I want to improve it some more. The first sentence is good where you have it, but there is another important change that isn't mentioned.
Let's
1. In the first sentence, change " a couple of " to "some".
2. Move the other two sentences to here (just above where we search for the two cells)
3. Add another comment above the declaration for indexDe: "Changing this header will cause all the data that was originally tagged as German to be imported as Tok Pisin."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-26 19:54 UTC, JohnThomson reviewed
> Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2021-07-26 19:55 UTC, JohnThomson approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4609)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2021-07-26 19:55 UTC, merged