BL-9976 Third section of tweaks, one UI bit to go
BloomBooks/BloomDesktop pull request #4626
Opened 2021-07-29 21:42 UTC by gmartin7

* fix hiding of image buttons for nested imageContainers
* use video container constant
* take off video .bloom-selected when entering comicTool
* add hover background color for video container
* give picture and video over picture elements the blue
   border when selected that Just Text bubbles have
* keep video placeholders from automatically jumping to
   the sign language tool when clicked
* match size on duplicate picture/video on picture

2021-08-02 21:05 UTC, andrew-polk requested changes
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7cd_yBe51SW5tmC7K:-Mg7cd_zCDv-NxRXk3fe:balwqcj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/css/editMode.less#L162)):*
> ```Less
>     &.hoverUp {
>         background-color: @ImageHoverOverlay !important;
>     }
> ```

Generally speaking, uses of !important deserve a comment since we try to avoid it whenever possible.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1712 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7ehYw0hlmXmveKJdt:-Mg7ehYw0hlmXmveKJdu:bhf9490) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1712)):*
> ```XML
>         }
>         return false;
>     }
> ```

Probably worth extracting all this logic to something like
`isOverPictureElementWithClass(string class) { logic }`
and each of these just calling that with the right class.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7f_yM23kKQhvl0-TU:-Mg7f_yM23kKQhvl0-TV:bkz1gw3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2161)):*
> ```XML
>         // If this is needed for correct duplication somewhere else, we will need to try
>         // something different.
>         //this.safelyRemoveAttribute(element, "tabindex");
> ```

Isn't this how we do talking book order? 


<!-- Sent from Reviewable.io -->

2021-08-03 19:02 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/css/editMode.less, line 162 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7cd_yBe51SW5tmC7K:-MgCCRzcCOsC3NlaHrLW:b195zhy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/css/editMode.less#L162)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Generally speaking, uses of !important deserve a comment since we try to avoid it whenever possible.
</blockquote></details>

Better version with comment.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 1712 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7ehYw0hlmXmveKJdt:-MgC9nBB61BshOm3F9RZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L1712)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably worth extracting all this logic to something like
`isOverPictureElementWithClass(string class) { logic }`
and each of these just calling that with the right class.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7f_yM23kKQhvl0-TU:-MgCNwEe4hL14bcTMTBO:b8v7ubb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2161)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't this how we do talking book order? 
</blockquote></details>

Umm... yes. But the context here is duplicating a comic bubble, so at worst we'd have 2 with the same tabindex. Should I remove the tabindex unless it's zero?


<!-- Sent from Reviewable.io -->

2021-08-03 19:23 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7f_yM23kKQhvl0-TU:-MgCRHYb1dTGmrRiPBvz:bjheqri) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2161)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Umm... yes. But the context here is duplicating a comic bubble, so at worst we'd have 2 with the same tabindex. Should I remove the tabindex unless it's zero?
</blockquote></details>

I'm not sure. I don't feel like I have a good grasp on the implications, not fully knowing how the ordering logic works.

I have questions like:
Does a bubble with no tabindex go to the end by default? 
Does one with tabindex 0 go to the beginning initially and then get "fixed up" when the user changes order?
How would it handle -1 which should allow for focus but, in a normal web scenario, would not get "tabbed" to?
Particularly, does this code modification result in a change for the default order of a duplicate bubble? Does that then get "cleaned up" when the user makes an order change?

Not necessarily looking for explicit answers to all these questions, but I think these kinds of questions need to factor in to the solution.


Going back up to the higher-level idea/solution...
Why does video container need an explicit tabindex to allow focus when image container doesn't?


Probably easier to discuss all this than comment back and forth... let me know.


<!-- Sent from Reviewable.io -->

2021-08-03 19:24 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7f_yM23kKQhvl0-TU:-MgCTJiB4OZZRGqJ8bw9:b-qmkhgt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2161)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure. I don't feel like I have a good grasp on the implications, not fully knowing how the ordering logic works.

I have questions like:
Does a bubble with no tabindex go to the end by default? 
Does one with tabindex 0 go to the beginning initially and then get "fixed up" when the user changes order?
How would it handle -1 which should allow for focus but, in a normal web scenario, would not get "tabbed" to?
Particularly, does this code modification result in a change for the default order of a duplicate bubble? Does that then get "cleaned up" when the user makes an order change?

Not necessarily looking for explicit answers to all these questions, but I think these kinds of questions need to factor in to the solution.


Going back up to the higher-level idea/solution...
Why does video container need an explicit tabindex to allow focus when image container doesn't?


Probably easier to discuss all this than comment back and forth... let me know.
</blockquote></details>

It's the imageContainer that needs it. Apparently an HTML video element can be focused by default.


<!-- Sent from Reviewable.io -->

2021-08-03 21:09 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/bookEdit/js/bubbleManager.ts, line 2161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626#-Mg7f_yM23kKQhvl0-TU:-MgCn7STBlpCzD_YqT56:bvm1iuo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b4c2f71038872234e43324b2d3316c4a66a50e75/src/BloomBrowserUI/bookEdit/js/bubbleManager.ts#L2161)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

It's the imageContainer that needs it. Apparently an HTML video element can be focused by default.
</blockquote></details>

After discussion we decided to only remove positive tabindex.


<!-- Sent from Reviewable.io -->

2021-08-03 21:47 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4626)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2021-08-03 21:47 UTC, merged