Import from spreadsheet
BloomBooks/BloomDesktop pull request #4642
Opened 2021-08-06 19:54 UTC by nabalone

2021-08-06 22:13 UTC, JohnThomson requested changes
I haven't looked at the tests yet, but there are a few things you can work on if you get time before I get back to it.

> Reviewed 12 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-:-MgSWktU1WhQuEmFnoiZ:bdcka4w)* status: 12 of 20 files reviewed, 8 unresolved discussions (waiting on @nabalone)

___
*[src/BloomExe/CLI/SpreadsheetImportCommand.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSHFNe93QTwtJEGc67:-MgSHFNe93QTwtJEGc68:brrmobi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CLI/SpreadsheetImportCommand.cs#L22)):*
> ```Smalltalk
> 			try
> 			{
> 				string folderPath = Directory.GetParent(options.BookPath).FullName;
> ```

This backup code is pretty much duplicated in LibraryListView, and doesn't feel much at home to me in either place. How about a static method on BookStorage? I think all it needs is a path to the folder to back up.
(You might comment on that method that it won't actually cause the new book to appear.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1883 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSIoxC9-MO9Qj3iLE6:-MgSIoxC9-MO9Qj3iLE7:b-7lavh3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CollectionTab/LibraryListView.cs#L1883)):*
> ```Smalltalk
> 				backupBook.Save();
> 
> 				//If we want to reename the book htm file in the backup copy.
> ```

Let's do this (in the new shared method). Most of Bloom will cope with the file and folder names not matching, but I'm pretty sure some things have slipped through the craks.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1889 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSKPkO-d6yAsi7WJ9o:-MgSKPkO-d6yAsi7WJ9p:bartld4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CollectionTab/LibraryListView.cs#L1889)):*
> ```Smalltalk
> 				//RobustFile.Move(Path.Combine(newFolderPath, origHtmlFileName), Path.Combine(newFolderPath, newCopyHtmlFileName));
> 
> 				var sheet = InternalSpreadsheet.ReadFromFile(inputFilepath);
> ```

I think we can do better here (something I should have seen earlier). Book.currentSelection.Dom will give you the current DOM, already in memory, and we can apply the importer directly to that, then just tell the book to Save. It may not make a lot of difference, but it saves reading the whole HTML file a couple of times. Worth a try, at least. (The original SpreadsheetImportCommand can't do this because in that case we don't have an existing Book object that already has a DOM.)
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1894 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSJBl96aOrtfIRfg1h:-MgSJBl96aOrtfIRfg1i:btj4fr8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CollectionTab/LibraryListView.cs#L1894)):*
> ```Smalltalk
> 
> 				var messages = importer.Import();
> 				foreach (var message in messages)
> ```

Let's do one NonFatalProblem, concatenating the strings...something like String.Join(messages, "\r\n"). If something gets out of whack in a long book we might get hundreds of messages, and the user will be clicking OK for ages if each puts up a dialog. Moreover, if we decided to allow the user to report the problem, we'd like to get all the errors in one Youtrack issue.
I think there's an overload of NonFatalProblem that has an argument like "detailedDescription" so it would probably be good to let the main message be just "Import failed" and put the details in the other argument.
___
*[src/BloomExe/Spreadsheet/MarkedUpText.cs, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSLvzX0O4dIDZJ0RIG:-MgSLvzX0O4dIDZJ0RIH:b-6fhd3q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/MarkedUpText.cs#L167)):*
> ```Smalltalk
> 				// A bloom-linebreak span created by ctrl+enter will leave an invisible 0xfeff character after it.
> 				// Remove these, since we are converting linebreaks to new paragrpahs for now
> 				string text = node.InnerText.Replace("\xfeff", "");
> ```

Sounds like this is our answer for round-tripping bloom-linebreak spans. If we get a newline followed immediately by a \xfeff, we can just create a bloom-linebreak span instead of stopping a paragraph and starting a new one.
If that doesn't work out, I think it would be better to remove these on export, where we still have the bloom-linebreak spans and can delete \xfeff only immediately after them. There are situations where the user might actually use \xfeff in his data (it has an obsolete use as a non-breaking zero-width space).
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 183 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSS1Sv3CJtYzOJ_h2E:-MgSS1Sw3CRr2HMLP-Sm:b2sqzbp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L183)):*
> ```Smalltalk
> 				// Enhance: eventually we should detect any rows that are not ContentRows,
> 				// and either drop them or make plain SpreadsheetRows.
> 				spreadsheet.Header.Spreadsheet = spreadsheet;
> ```

I'm puzzled why spreadsheet.Header isn't null, since I think we create the InternalSpreadsheet in ReadFromFile, which does populateHeader(false). But that must somehow be OK...though you might want to test the command-line import one more time.
However, it feels wrong that the code here has to set the Spreadsheet field of the header like this. Could we move the constructor logic on ContentRow down into the base class, so all rows are created with Spreadsheet initialized and added to the spreadsheet?
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 218 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSTsWECletKGKBhunf:-MgSTsWECletKGKBhung:b-y2bsnm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L218)):*
> ```Smalltalk
> 			while (match.Success)
> 			{
> 				string x = match.Value.Substring(2, 4);
> ```

I'm not sure it's better in this simple case, but it's worth being aware that if you make a group in the pattern with parens..."_x([0-9A-F]{4})_"...you can access it's content here with match.Groups(1).
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 242 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSUmII79coKySPDN5Q:-MgSUmII79coKySPDN5R:b-9kuk7o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L242)):*
> ```Smalltalk
> 			}
> 
> 			StringBuilder MarkedupStringBuilder = new StringBuilder();
> ```

It's conventional in C# to start local variables with a lower case


<!-- Sent from Reviewable.io -->

2021-08-09 16:51 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642)* status: 8 of 20 files reviewed, 8 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[src/BloomExe/CLI/SpreadsheetImportCommand.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSHFNe93QTwtJEGc67:-MgfnLJYDOZeusTjnkp5:b-5eyz4l) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CLI/SpreadsheetImportCommand.cs#L22)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This backup code is pretty much duplicated in LibraryListView, and doesn't feel much at home to me in either place. How about a static method on BookStorage? I think all it needs is a path to the folder to back up.
(You might comment on that method that it won't actually cause the new book to appear.
</blockquote></details>

I noticed that the book shown in the right panel of Bloom Collections tab was not changing when I clicked between a book and its backup copy made during an import, which is pretty confusing. I also found this duplicate function: https://github.com/BloomBooks/BloomDesktop/blob/0ceb3f8accada723c65c05ddb818293e822562c7/src/BloomExe/Book/BookStorage.cs#L2440
Can I modify and reuse that function instead, passing in a different regex? Would that help bloom properly treat the backup book as a separate book?


<!-- Sent from Reviewable.io -->

2021-08-09 22:05 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642)* status: 6 of 23 files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1883 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSIoxC9-MO9Qj3iLE6:-MgfqVhe8zRpXB_j_XVw:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CollectionTab/LibraryListView.cs#L1883)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's do this (in the new shared method). Most of Bloom will cope with the file and folder names not matching, but I'm pretty sure some things have slipped through the craks.
</blockquote></details>

Done.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1889 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSKPkO-d6yAsi7WJ9o:-MgfqUdm6GodgbImREq_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CollectionTab/LibraryListView.cs#L1889)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think we can do better here (something I should have seen earlier). Book.currentSelection.Dom will give you the current DOM, already in memory, and we can apply the importer directly to that, then just tell the book to Save. It may not make a lot of difference, but it saves reading the whole HTML file a couple of times. Worth a try, at least. (The original SpreadsheetImportCommand can't do this because in that case we don't have an existing Book object that already has a DOM.)
</blockquote></details>

Done.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1894 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSJBl96aOrtfIRfg1h:-MgfrtnE2JZQCPdMWSvX:b1ietxy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CollectionTab/LibraryListView.cs#L1894)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's do one NonFatalProblem, concatenating the strings...something like String.Join(messages, "\r\n"). If something gets out of whack in a long book we might get hundreds of messages, and the user will be clicking OK for ages if each puts up a dialog. Moreover, if we decided to allow the user to report the problem, we'd like to get all the errors in one Youtrack issue.
I think there's an overload of NonFatalProblem that has an argument like "detailedDescription" so it would probably be good to let the main message be just "Import failed" and put the details in the other argument.
</blockquote></details>

Ok. Should this be showSendReport:false? We will hit this with a lot of user errors e.g. user selecting the wrong spreadsheet, adding bad rows or otherwise messing up the spreadsheet-book correspondence before import. 

Also, I realized the import might not have necessarily "failed", it looks like it imports what it can and leaves the rest, so depending on what happened the book may have completely imported as the user wanted or it may be completely the old version or something in between. Should I say "Import warning:" as the main message?

Here's a screenshot of when I made the change and selected the wrong spreadsheet (had sendShowReport:false)
![image.png](https://files.reviewableusercontent.io/images/reviewable/22460975/BdVxGc8tQ1U0Uup76Oep7EFU/image.png)
___
*[src/BloomExe/Spreadsheet/MarkedUpText.cs, line 167 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSLvzX0O4dIDZJ0RIG:-MggR63-DOOVgsr7I-6S:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/MarkedUpText.cs#L167)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Sounds like this is our answer for round-tripping bloom-linebreak spans. If we get a newline followed immediately by a \xfeff, we can just create a bloom-linebreak span instead of stopping a paragraph and starting a new one.
If that doesn't work out, I think it would be better to remove these on export, where we still have the bloom-linebreak spans and can delete \xfeff only immediately after them. There are situations where the user might actually use \xfeff in his data (it has an obsolete use as a non-breaking zero-width space).
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 183 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSS1Sv3CJtYzOJ_h2E:-MggsxE0BHivVu6VEUX9:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L183)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm puzzled why spreadsheet.Header isn't null, since I think we create the InternalSpreadsheet in ReadFromFile, which does populateHeader(false). But that must somehow be OK...though you might want to test the command-line import one more time.
However, it feels wrong that the code here has to set the Spreadsheet field of the header like this. Could we move the constructor logic on ContentRow down into the base class, so all rows are created with Spreadsheet initialized and added to the spreadsheet?
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 218 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSTsWECletKGKBhunf:-MggwPuoD1vOlVx9KZ4x:bw2sksx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L218)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not sure it's better in this simple case, but it's worth being aware that if you make a group in the pattern with parens..."_x([0-9A-F]{4})_"...you can access it's content here with match.Groups(1).
</blockquote></details>

Ooh cool! I like it and did it.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 242 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSUmII79coKySPDN5Q:-MggtHYK7GdIUa-lp73Z:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L242)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's conventional in C# to start local variables with a lower case
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 23:15 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642)* status: 5 of 23 files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/CLI/SpreadsheetImportCommand.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSHFNe93QTwtJEGc67:-Mgh67MlA8UAt1Pb1gxx:b-39w50x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CLI/SpreadsheetImportCommand.cs#L22)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

I noticed that the book shown in the right panel of Bloom Collections tab was not changing when I clicked between a book and its backup copy made during an import, which is pretty confusing. I also found this duplicate function: https://github.com/BloomBooks/BloomDesktop/blob/0ceb3f8accada723c65c05ddb818293e822562c7/src/BloomExe/Book/BookStorage.cs#L2440
Can I modify and reuse that function instead, passing in a different regex? Would that help bloom properly treat the backup book as a separate book?


</blockquote></details>

Actually I take that back, you said we don't want to rename the backup book .htm file, maybe it's not worth reusing. I used the copying files logic from that "Duplicate" function to create a new book InstanceID in the new method in BookStorage, and that fixed the problem of the book display not updating. 

Do we want to follow the "Duplicate" function's naming logic, so that if you backup a book called "Cupcakes (before import overwrite-5)", the result is called "Cupcakes (before import overwrite-6)" instead of "Cupcakes (before import overwrite-5) (before import overwrite)"? 


<!-- Sent from Reviewable.io -->

2021-08-10 18:18 UTC, JohnThomson requested changes
Looking good. Mostly very small things now. We need to do that backup a different way...not your fault...I'll talk to you about it.

> Reviewed 6 of 20 files at r1, 7 of 10 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-:-MglH2iy-CCZwpLE_RM-:b-xeejsr)* status: all files reviewed, 11 unresolved discussions (waiting on @nabalone)

___
*[src/BloomExe/Book/BookStorage.cs, line 2748 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-Mgkqj_z04YCw6XjKU29:-Mgkqja-0qQD3Jx-xNaA:b-f2fziu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomExe/Book/BookStorage.cs#L2748)):*
> ```Smalltalk
> 				{
> 					//TODO should we use RobustFile.Delete instead? Would that also be recursive though?
> 					Directory.Delete(newFolderPath, true);
> ```

The function you want is SIL.RobustIO.DeleteDirectory(newFolderPath, true). (It's not RobustFile, because it's a directory operation. Note, confusingly, there are two RobustIO classes used in Bloom, so you have to spell out SIL.RobustIO.)
___
*[src/BloomExe/CLI/SpreadsheetImportCommand.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSHFNe93QTwtJEGc67:-MgkriPJ15EZinDjb3pm:bc93dxr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CLI/SpreadsheetImportCommand.cs#L22)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Actually I take that back, you said we don't want to rename the backup book .htm file, maybe it's not worth reusing. I used the copying files logic from that "Duplicate" function to create a new book InstanceID in the new method in BookStorage, and that fixed the problem of the book display not updating. 

Do we want to follow the "Duplicate" function's naming logic, so that if you backup a book called "Cupcakes (before import overwrite-5)", the result is called "Cupcakes (before import overwrite-6)" instead of "Cupcakes (before import overwrite-5) (before import overwrite)"? 
</blockquote></details>

Well done figuring out we need a new book instance ID!! Unfortunately that revealed a design flaw (my fault and John's). Changing the instance ID is necessary for the reasons you found, but also unacceptable because if the backup gets restored, we need to get the original instanceID back too. We're going to have to do something else about backups. Sorry. I'll come talk to you about it.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1894 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSJBl96aOrtfIRfg1h:-Mgl071m2XWwJ6wcBIb_:b-3y48ob) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CollectionTab/LibraryListView.cs#L1894)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Ok. Should this be showSendReport:false? We will hit this with a lot of user errors e.g. user selecting the wrong spreadsheet, adding bad rows or otherwise messing up the spreadsheet-book correspondence before import. 

Also, I realized the import might not have necessarily "failed", it looks like it imports what it can and leaves the rest, so depending on what happened the book may have completely imported as the user wanted or it may be completely the old version or something in between. Should I say "Import warning:" as the main message?

Here's a screenshot of when I made the change and selected the wrong spreadsheet (had sendShowReport:false)
![image.png](https://files.reviewableusercontent.io/images/reviewable/22460975/BdVxGc8tQ1U0Uup76Oep7EFU/image.png)

</blockquote></details>

Good idea. showSendReport is a toss-up. Let's leave it false for now.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 218 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSTsWECletKGKBhunf:-Mgl0rjvARD8kzZb4kPP:b-are21j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L218)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Ooh cool! I like it and did it.
</blockquote></details>

Let's drop the commented out old version
___
*[src/BloomTests/Spreadsheet/SpreadsheetFormattingTests.cs, line 199 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-Mgl3fh4DQdynqE45rj1:-Mgl3fh4DQdynqE45rj2:b5poszi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetFormattingTests.cs#L199)):*
> ```Smalltalk
> 			ExcelRange thirdCell = _worksheet.Cells[3, 3];
> 			string xmlString = SpreadsheetIO.BuildXmlString(thirdCell);
> 			Assert.That(Regex.IsMatch(xmlString, "<p><\\/p><p><strong>Apples<\\/strong><\\/p><p><strong>Bananas.*"));
> ```

I'm not clear what's going on here. Why not just a single Assert on the whole value of the string?
By the way...C# has a nice syntactic trick where if you put an @ at the beginning of a string, it won't interpret backslash escapes, so you don't have to double them. (Of course, if you need something like \xfeff, you can't use the @ syntax)
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 13 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-Mgl9Lz17wDQuUGJplt5:-Mgl9Lz17wDQuUGJplt6:b-yzkzvm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L13)):*
> ```Smalltalk
> {
> 	/// <summary>
> 	/// This class tests roundtripping a book with formatted text to and from a spreadsheet
> ```

I think it would be worth saying somewhere, and here might be good, something like "Note that formatting is now round-tripped whether or not retainMarkup is true, though the representation in the spreadsheet is completely different. The tests here save it both ways and expect the same results in both cases."
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 202 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglAKB0C2KvFa9XVDOJ:-MglAKB0C2KvFa9XVDOK:bolx6dq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L202)):*
> ```Smalltalk
> 			Assert.That(FormatNodeContainsText("//div[@id='simpleFormattingTest']//sup", "4"));
> 
> 			Assert.That(!FormatNodeContainsText("//div[@id='simpleFormattingTest']//strong", "dog"));
> ```

Could we change these to Assert.That(FormatNodeContainsText(...), Is.False)? It's very easy to miss that exclamation point, and then the reader is puzzled.
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 233 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglCI230x3bOFIyWfCS:-MglCI230x3bOFIyWfCT:b-l727x0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L233)):*
> ```Smalltalk
> 
> 		//Remove the whitespace between <p> tags that was originally there just for readability
> 		private void RemoveOuterWhitespace(XmlNode node)
> ```

Maybe RemoveTopLevelWhiteSpace()? I was expecting this to remove only white space before the first p and after the last.
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 236 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglAyD_B2tCMBQbh5Tu:-MglAyD_B2tCMBQbh5Tv:b8r9sls) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L236)):*
> ```Smalltalk
> 		{
> 			var nodeList = new List<XmlNode>();
> 			foreach (XmlNode childnode in node.ChildNodes)
> ```

A shorter way to do this is
foreach (XmlNode childNode in node.ChildNodes.Cast<XmlNode>(). [...]

2021-08-10 21:35 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642)* status: 17 of 26 files reviewed, 11 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[src/BloomExe/Book/BookStorage.cs, line 2748 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-Mgkqj_z04YCw6XjKU29:-Mgl_bPnClCMVZla8Mx8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomExe/Book/BookStorage.cs#L2748)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The function you want is SIL.RobustIO.DeleteDirectory(newFolderPath, true). (It's not RobustFile, because it's a directory operation. Note, confusingly, there are two RobustIO classes used in Bloom, so you have to spell out SIL.RobustIO.)
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 218 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSTsWECletKGKBhunf:-Mgl_osfCbgIiJHux_Gm:bw10jn4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L218)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's drop the commented out old version
</blockquote></details>

Oops, done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetFormattingTests.cs, line 199 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-Mgl3fh4DQdynqE45rj1:-Mglb-ZHA9Kq_HVdFlhZ:bupal97) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetFormattingTests.cs#L199)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not clear what's going on here. Why not just a single Assert on the whole value of the string?
By the way...C# has a nice syntactic trick where if you put an @ at the beginning of a string, it won't interpret backslash escapes, so you don't have to double them. (Of course, if you need something like \xfeff, you can't use the @ syntax)
</blockquote></details>

Oops, I think I was debugging and forgot to restore it. Fixed.
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 13 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-Mgl9Lz17wDQuUGJplt5:-MglbJde9mWl0Rlpj4Kg:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L13)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think it would be worth saying somewhere, and here might be good, something like "Note that formatting is now round-tripped whether or not retainMarkup is true, though the representation in the spreadsheet is completely different. The tests here save it both ways and expect the same results in both cases."
</blockquote></details>

Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 202 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglAKB0C2KvFa9XVDOJ:-MglbXPyDud0Pm6oqo4Z:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L202)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Could we change these to Assert.That(FormatNodeContainsText(...), Is.False)? It's very easy to miss that exclamation point, and then the reader is puzzled.
</blockquote></details>

Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 233 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglCI230x3bOFIyWfCS:-Mglbh8z3LGP155WT_Yk:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L233)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe RemoveTopLevelWhiteSpace()? I was expecting this to remove only white space before the first p and after the last.
</blockquote></details>

Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 236 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglAyD_B2tCMBQbh5Tu:-Mgldyr-AaFEpOIFHfUX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L236)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A shorter way to do this is
foreach (XmlNode childNode in node.ChildNodes.Cast<XmlNode>().ToArray()
  if (...)
   node.removeChild(childNode).
The ToArray makes a snapshot of the original Childnodes so the list isn't getting modified while working through the enumeration, so you can delete immediately. (The cast is there to work around a weird type incompatibility from C#'s history.)
</blockquote></details>

Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs, line 270 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglCdFk7ddky6m2z_x2:-Mgle2v5B0o9zG49rY9v:bhdz46z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetRoundTripTests.cs#L270)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't see how this can pass. One assert says that children[4] is a string with a \xfeff, the next that it's not there.
</blockquote></details>

The second one had the actual invisible zero-width space character in it. I just wanted to check that it worked, make sure my escaping was right. But I now see how this is extremely confusing and am removing the second one.
___
*[src/BloomTests/Spreadsheet/SpreadsheetTests.cs, line 329 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglGKpx0kNKyU9XE3yP:-MgltjXb2euimJ2vsiiz:b-1cpayq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetTests.cs#L329)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not clear why it might be in any one of four cells. Deserves a comment if we can't pin it down better.
</blockquote></details>

Is this better?


<!-- Sent from Reviewable.io -->

2021-08-11 18:54 UTC, JohnThomson approved these changes
> Reviewed 7 of 9 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[src/BloomExe/CLI/SpreadsheetImportCommand.cs, line 22 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSHFNe93QTwtJEGc67:-MgqYhpv03hlLnZLzqIA:b-n68qs8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CLI/SpreadsheetImportCommand.cs#L22)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Well done figuring out we need a new book instance ID!! Unfortunately that revealed a design flaw (my fault and John's). Changing the instance ID is necessary for the reasons you found, but also unacceptable because if the backup gets restored, we need to get the original instanceID back too. We're going to have to do something else about backups. Sorry. I'll come talk to you about it.
</blockquote></details>

We decided to just leave this for now.
___
*[src/BloomTests/Spreadsheet/SpreadsheetTests.cs, line 329 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglGKpx0kNKyU9XE3yP:-MgqWFK_0-fgRww-AD2H:b-xqkpr6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetTests.cs#L329)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Is this better?
</blockquote></details>

It's much clearer, thanks. I'm a little sorry that we'll no longer fail if it somehow doesn't find any TextGroupLabels. But I suppose plenty of other tests would fail.
A one-line fix would be to remove the "r < rowCount" from the for, and add an initial Assert.That(r, Is.LessThan(rowCount), "did not find expected TextGroup row").
Another option would be to change the 'break' to 'return' and add an assert after the for loop. But that causes problems if we later want to add another assertion.
Your original idea of a flag that is set when we find it and tested after the for loop works, too.
I'll leave it to you. I'm happy to merge as-is if you think the possibility of not finding the TextGroup is covered adequately elsewhere.


<!-- Sent from Reviewable.io -->

2021-08-12 20:49 UTC, nabalone reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-:-Mgw78fy6VtSqP1ZRr70:bnfp4nl)* status: 25 of 26 files reviewed, 3 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1894 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MgSJBl96aOrtfIRfg1h:-MgvwaYf6aAofAotgjGH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e0368034a74782c67adf7ea181b7c76fbab365ea/src/BloomExe/CollectionTab/LibraryListView.cs#L1894)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Good idea. showSendReport is a toss-up. Let's leave it false for now.
</blockquote></details>

Done.
___
*[src/BloomTests/Spreadsheet/SpreadsheetTests.cs, line 329 at r5](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642#-MglGKpx0kNKyU9XE3yP:-Mgw71bPAeH5s5i665na:buf0ag5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/8ad34cb96a67c9cf3bd369edde4df1f1555be20e/src/BloomTests/Spreadsheet/SpreadsheetTests.cs#L329)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's much clearer, thanks. I'm a little sorry that we'll no longer fail if it somehow doesn't find any TextGroupLabels. But I suppose plenty of other tests would fail.
A one-line fix would be to remove the "r < rowCount" from the for, and add an initial Assert.That(r, Is.LessThan(rowCount), "did not find expected TextGroup row").
Another option would be to change the 'break' to 'return' and add an assert after the for loop. But that causes problems if we later want to add another assertion.
Your original idea of a flag that is set when we find it and tested after the for loop works, too.
I'll leave it to you. I'm happy to merge as-is if you think the possibility of not finding the TextGroup is covered adequately elsewhere.
</blockquote></details>

Done. Added the Assert.That(r, Is.LessThan(rowCount)


<!-- Sent from Reviewable.io -->

2021-08-13 20:52 UTC, JohnThomson reviewed
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2021-08-13 21:27 UTC, JohnThomson approved these changes
> Reviewed 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4642)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2021-08-13 21:27 UTC, merged