Xmatter to spreadsheet
BloomBooks/BloomDesktop pull request #4666
Opened 2021-08-18 17:05 UTC by nabalone

2021-08-18 17:09 UTC, nabalone commented on src/BloomExe/Spreadsheet/SpreadsheetExporter.cs
> +						"Export warning: Found multiple elements for image element " + dataBookLabel + ". Only the first will be exported.");
Should I do something different in this case? Will there be multiple branding image elements with the same name? Right now the importer won't import multiple images for the same element. I guess I would have to make multiple rows with the same "metadata key" but different content?

2021-08-18 20:55 UTC, JohnThomson requested changes
Very good work overall.
One general comment:  I would be happier if we changed most occurrences of XMatter to DataDiv. All this code is basically about exporting and importing the bloomDataDiv. It's true that the bloomDataDiv is mainly used to store data that is used in XMatter, but it doesn't have to be...it can also store keys that are used on content pages, though we haven't used that capability much.
This is my fault...I'm pretty sure we described this task as importing and exporting xmatter. So if it feels like too much work, or you find that various renames are not giving good readable results, feel free to say "no".

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-:-MhQ-UZ4B4YScBVQjcMh:b4f9z4b)* status: 9 of 10 files reviewed, 21 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPnivsEUASdzE8Nq_3:-MhPnivsEUASdzE8Nq_4:babw0o3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L14)):*
> ```Smalltalk
> 	public class SpreadsheetExporter
> 	{
> 		InternalSpreadsheet _spreadsheet = new InternalSpreadsheet();
> ```

Let's explain a bit..."a list of values which, if they occur in the data-book attribute of an element in the bloomDataDiv, indicate that the element content should be treated as an image, even though the element doesn't have a src attribute nor actually contain an img element"
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPqQOsEfMr72xXfjAW:-MhPqQOsEfMr72xXfjAX:b-5iblb4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L15)):*
> ```Smalltalk
> 	{
> 		InternalSpreadsheet _spreadsheet = new InternalSpreadsheet();
> 		public static List<string> _xmatterImagesWithNoSrcAttributes = new List<string>() { "licenseImage" };
> ```

A public static would usually have a name starting in upper case and without an underscore.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPgsbN8l6_0QgFJ1f1:-MhPgsbN8l6_0QgFJ1f2:bw9ttef) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L59)):*
> ```Smalltalk
> 		}
> 
> 		private XmlElement[] GetXMatterDataDiv(HtmlDom elementOrDom)
> ```

This can just return one element, and save you a loop. There should never be more than one.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPi_Rh-0wUo33otxeC:-MhPi_Rh-0wUo33otxeD:b4p3oql) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L104)):*
> ```Smalltalk
> 		}
> 
> 		private void AddXmatterDataRow(XmlNode node, string imagesFolderPath)
> ```

AddXMatterDataRows? The current name suggests that it adds only one.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 107 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPiLQ_9nq8kLL5QSvo:-MhPiLQ_9nq8kLL5QSvp:bngvlhd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L107)):*
> ```Smalltalk
> 		{
> 			var dataBookNodeList = node.SafeSelectNodes("./div[@data-book]").Cast<XmlElement>().ToList();
> 			dataBookNodeList.Sort((a, b) => a.GetAttribute("data-book").CompareTo(b.GetAttribute("data-book")));
> ```

Think this deserves a comment..."Bring the ones with the same data-book value together so we can easily make a single row for each data-book value"
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 109 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPiiuY0N68pDUBQxbX:-MhPiiuY0N68pDUBQxbY:b4y09yj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L109)):*
> ```Smalltalk
> 			dataBookNodeList.Sort((a, b) => a.GetAttribute("data-book").CompareTo(b.GetAttribute("data-book")));
> 			string prevDataBookLabel = null;
> 			SpreadsheetRow row = _spreadsheet.Header;
> ```

Maybe start with it null? I don't think you make any use of it being initially the header.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPj04v0XTyTcWWX7d2:-MhPj04v0XTyTcWWX7d3:bc3zovh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L118)):*
> ```Smalltalk
> 				{
> 					row = new ContentRow(_spreadsheet);
> 					row.SetCell(InternalSpreadsheet.MetadataKeyLabel, dataBookLabel.Trim());
> ```

We want to surround this with []. (The idea is that import only pays attention to rows with [] in this column. So users can make other rows as needed and have them ignored.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 123 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPlizS0xp1bOCwHSNZ:-MhPlizS0xp1bOCwHSN_:bqzye4u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L123)):*
> ```Smalltalk
> 
> 					if (IsImageXmatterElement(dataBookElement, dataBookLabel))
> 					{
> ```

I think it's worth noting, "Some data-book items redundantly store the src of the image which they capture in both their content and src attribute. We haven't yet found any case in which they are different, so are only storing one in the spreadsheet. This test is to make sure that we notice if we come across a case where it might be necessary to save both."
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 131 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPjp-ECBPzSHjl-Uol:-MhPjp-ECBPzSHjl-Uom:bkebk7c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L131)):*
> ```Smalltalk
> 								"Export warning: Found differing 'src' attribute and element text for xmatter element " + dataBookLabel
> 								+ ". The 'src' attribute will be ignored.");
> 							NonFatalProblem.Report(ModalIf.All, PassiveIf.None, msg, showSendReport: true);
> ```

I suppose there are currently only a couple of unlikely messages that Export can currently produce? If we get a few more, or ones likely to happen several times, it would be worth having the process gather them and make a single report at the end.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPkjOWAtt5Nj3AJtSA:-MhPkjOWAtt5Nj3AJtSB:bz1d07v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L137)):*
> ```Smalltalk
> 						if (FirstChildIsImageWithSource(dataBookElement))
> 						{
> 							if (! dataBookElement.Name.Contains("branding"))
> ```

I don't see how this works. dataBookElement is an XmlElement, right, which means its Name will almost always be "div". Isn't it the dataBookLabel that should contain "branding"?
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 148 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPlH891GAI36Bu6VT9:-MhPlH891GAI36Bu6VTA:bk1pxst) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L148)):*
> ```Smalltalk
> 		 [...]

2021-08-23 15:22 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666)* status: 4 of 12 files reviewed, 21 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 14 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPnivsEUASdzE8Nq_3:-MhQ7flr8GUTIZ8iV6qH:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L14)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's explain a bit..."a list of values which, if they occur in the data-book attribute of an element in the bloomDataDiv, indicate that the element content should be treated as an image, even though the element doesn't have a src attribute nor actually contain an img element"
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 15 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPqQOsEfMr72xXfjAW:-Mh_XK7x9grvRKPKrDiJ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A public static would usually have a name starting in upper case and without an underscore.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPgsbN8l6_0QgFJ1f1:-MhQKgqJERoQhwUmuCsX:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L59)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This can just return one element, and save you a loop. There should never be more than one.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 104 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPi_Rh-0wUo33otxeC:-MhQKhIf8rw_zdjuOG-a:b-2gwqec) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L104)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

AddXMatterDataRows? The current name suggests that it adds only one.
</blockquote></details>

You're right, I got confused
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 107 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPiLQ_9nq8kLL5QSvo:-MhQKps65KxtgmNOgM-0:bz3vudb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L107)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Think this deserves a comment..."Bring the ones with the same data-book value together so we can easily make a single row for each data-book value"
</blockquote></details>

Makes sense! Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 109 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPiiuY0N68pDUBQxbX:-MhQNNoe2epLLIIdps7L:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L109)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe start with it null? I don't think you make any use of it being initially the header.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 118 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPj04v0XTyTcWWX7d2:-MhQOealD7C0P38IJ0TQ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L118)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We want to surround this with []. (The idea is that import only pays attention to rows with [] in this column. So users can make other rows as needed and have them ignored.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 123 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPlizS0xp1bOCwHSNZ:-MhQQ6WE9rwPC7x6IymK:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L123)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think it's worth noting, "Some data-book items redundantly store the src of the image which they capture in both their content and src attribute. We haven't yet found any case in which they are different, so are only storing one in the spreadsheet. This test is to make sure that we notice if we come across a case where it might be necessary to save both."
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 131 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPjp-ECBPzSHjl-Uol:-MhQQLgA7pExR0o14-Bl:b-dekbfa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L131)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose there are currently only a couple of unlikely messages that Export can currently produce? If we get a few more, or ones likely to happen several times, it would be worth having the process gather them and make a single report at the end.
</blockquote></details>

That's what I was thinking. There are currently only 3 and the only would occur in unforeseen situations
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 137 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPkjOWAtt5Nj3AJtSA:-MhQQZAU44W1rDtFjJ92:bdjvci) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L137)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't see how this works. dataBookElement is an XmlElement, right, which means its Name will almost always be "div". Isn't it the dataBookLabel that should contain "branding"?
</blockquote></details>

You are right, this is one of the bugs I fixed in the next commit
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 148 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPlH891GAI36Bu6VT9:-MhQQtvH4ubiJftetGSb:b-avieft) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L148)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's capture in a comment "We determined that whether or not a data-book div has a src attribute, it is the innerText of the  item that is used to set the src of the image in the actual pages of the document. So that's what we want to capture in the spreadsheet."
</blockquote></details>

Ok. At least that's true for coverImage and licenseImage, and if there are other possible tags I haven't seen yet where src attribute and innerText differ and src wins, at least we should get the warning toast. 
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 168 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPoDt23MI2N7QB4LGL:-MhQSBcu9ADjaXrssRcP:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L168)) [...]

2021-08-23 15:33 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666)* status: 4 of 12 files reviewed, 21 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 245 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPvIqyB_pszvYqSclV:-MhncRjmCM-g9PuQsQzl:b-joktev) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L245)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

^^ Actually please disregard that comment, that is completely wrong and I forgot to delete it
</blockquote></details>

I tried to fix up the logic of the now UpdateDataDiv method. Current approach is:
//For each xmatter row in the spreadsheet,
//	For each langauge column:
//		If there is content in that cell,
//			If there is a node of the same language, replace content
//			Else Create a new node with that content.
//					(Using a clone of a node of the same book-data but different language if not,
//					and using a blank div node if that fails too? In order to try to preserve other attributes).
//				Remove the old node
//		else delete if present that langs node
//
//Then if removeOtherLanguages, remove all cells of languages not in sheet.


Also, the RemoveOtherLanguagesInDataDiv logic is very similar to this method which gets called elsewhere in the importer, should I try to use it instead or combine them? https://github.com/BloomBooks/BloomDesktop/blob/master/src/BloomExe/Book/HtmlDom.cs#L2807


<!-- Sent from Reviewable.io -->

2021-08-23 16:51 UTC, JohnThomson requested changes
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666)* status: all files reviewed, 5 unresolved discussions (waiting on @nabalone)

___
*[src/BloomExe/Book/BookStorage.cs, line 2719 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhnbNCrB5qy0l_0h0ae:-MhnkC3B3UQd_4iTsMBo:b-53aik1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c24523e77a4d89924ca8695f3d321e7b0579b76e/src/BloomExe/Book/BookStorage.cs#L2719)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

I was getting path too long errors for some titles with multiple (before import overwrites) after them from importing into a backup. Is this an okay way to fix it?
</blockquote></details>

Looks good. It will get trickier if we decide to allow "before import overwrite" to be localized, especially if the current importer is using a different locale than the previous one. But it will do for now. We already have a quite different 'revisions' system in mind which might replace this before we need to localize.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 184 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPooIP6Gk6x1rbvKRK:-MhnmJqe9Uc6blC_5JHI:bx9ia1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L184)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

I changed it, found it more useful to return the string, how does this look? Should I just check the first Xmlelement child in case there are multiple children, with one of them being an img? But what order would they be in?
</blockquote></details>

Returning the value of the src attribute is a good idea. I don't know of any case where there would be an img element that isn't the first thing. But if it happened, we'd probably be glad to capture the image in the appropriate spreadsheet columns, and the element lists aren't likely to be long enough that the time taken to search the whole list is significant. I think what you have can stand.
___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 182 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhnlnGBAZuce1qgjJfr:-MhnlnGBAZuce1qgjJfs:b-as8a3n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c24523e77a4d89924ca8695f3d321e7b0579b76e/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L182)):*
> ```Smalltalk
> 		{
> 			var imageSrc = dataBookElement.GetAttribute("src").Trim();
> 			//Unfortunately, in the current state of Bloom, we have at least three ways of representing in the bloom-data - div things that are
> ```

Some extra white space has made my mistake even worse. It's actually bloomDataDiv.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 245 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPvIqyB_pszvYqSclV:-MhnrBmFE6dm0DzMOVwA:b-d5l1z8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L245)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

I tried to fix up the logic of the now UpdateDataDiv method. Current approach is:
//For each xmatter row in the spreadsheet,
//	For each langauge column:
//		If there is content in that cell,
//			If there is a node of the same language, replace content
//			Else Create a new node with that content.
//					(Using a clone of a node of the same book-data but different language if not,
//					and using a blank div node if that fails too? In order to try to preserve other attributes).
//				Remove the old node
//		else delete if present that langs node
//
//Then if removeOtherLanguages, remove all cells of languages not in sheet.


Also, the RemoveOtherLanguagesInDataDiv logic is very similar to this method which gets called elsewhere in the importer, should I try to use it instead or combine them? https://github.com/BloomBooks/BloomDesktop/blob/master/src/BloomExe/Book/HtmlDom.cs#L2807

</blockquote></details>

Good question. One of these cases where two methods are similar enough to make the duplication annoying but different enough to make reusing the code difficult. Here, for example, the nodes we want to possibly delete are not all .bloom-editable. But, the method you found is doing a similar task: removing nodes that don't have a lang in a certain list. And, looking at it reminded me of a special case we want here too: we should not delete the item in lang 'z' (which is not a real language, but used to mark a prototype for use in adding languages).
How about we refactor HtmlDom.RemoveOtherLanguages by giving it an overload where the first argument is simply a list of elements to consider deleting? (Roughly the second half of the current method.) Then we can use that here also. (And maybe in the old importer code for non-data-div stuff, too?)
I think it would be worth adding a test case to confirm that it doesn't delete lang="z"
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 241 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhnopMt1oDfkqMRO1Ew:-MhnopMt1oDfkqMRO1Ex:b-u0n59h) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c24523e77a4d89924ca8695f3d321e7b0579b76e/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L241)):*
> ```Smalltalk
> 					else  //Spreadsheet cell for this row and language is empty. Remove the corresponding node if present.
> 					{
> 						foreach (XmlNode n in langMatchingNodes)
> ```

Technically this is problematic. langMatchingNodes is an iterator working over the DOM. You are not supposed to modify the DOM, especially in ways that would affect the results of the iteration, while looping through the iteration. In this case, you probably get away with it as it is highly unlikely that langMatchingNodes contains more than one item. But let's not count on that. The proper fix is (either here or above where langMatchingNodes is declared) to append ToArray() or ToList() so the iteration is done once (creating an independent collection) before you start modifying the DOM.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 267 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhnqM8K3BqffXMSs1o2:-MhnqM8K3BqffXMSs1o3:bo2icqu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c24523e77a4d89924ca8695f3d321e7b0579b76e/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L267)):*
> ```Smalltalk
> 		private void RemoveOtherLanguagesInDataDiv(XmlNodeList matchingNodes)
> 		{
> 			foreach (XmlElement n in matchingNodes.Cast<XmlNode>())
> ```

Again you need a .ToArray() or similar either here or where the matchingNodes is created.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 186 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPwA2D7R95WA2ji-M-:-MhntsgjCQ8YyX0WG9-5:b-mkrjcu) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L186)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Hmm, is this okay? Please do suggest any better names for the function and set. And good idea to  format the book title.
</blockquote></details>

I like yours better than any of mine.


<!-- Sent from Reviewable.io -->

2021-08-23 19:26 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666)* status: 8 of 13 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetExporter.cs, line 182 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhnlnGBAZuce1qgjJfr:-Mhnz-de2aqfhHSfNQ43:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c24523e77a4d89924ca8695f3d321e7b0579b76e/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L182)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Some extra white space has made my mistake even worse. It's actually bloomDataDiv.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 245 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPvIqyB_pszvYqSclV:-MhoPS7l6_Tzx95mihOI:b-x9ba83) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L245)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Good question. One of these cases where two methods are similar enough to make the duplication annoying but different enough to make reusing the code difficult. Here, for example, the nodes we want to possibly delete are not all .bloom-editable. But, the method you found is doing a similar task: removing nodes that don't have a lang in a certain list. And, looking at it reminded me of a special case we want here too: we should not delete the item in lang 'z' (which is not a real language, but used to mark a prototype for use in adding languages).
How about we refactor HtmlDom.RemoveOtherLanguages by giving it an overload where the first argument is simply a list of elements to consider deleting? (Roughly the second half of the current method.) Then we can use that here also. (And maybe in the old importer code for non-data-div stuff, too?)
I think it would be worth adding a test case to confirm that it doesn't delete lang="z"
</blockquote></details>

Like this?
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 241 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhnopMt1oDfkqMRO1Ew:-MhnzzE954zTI40DGH5k:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c24523e77a4d89924ca8695f3d321e7b0579b76e/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L241)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Technically this is problematic. langMatchingNodes is an iterator working over the DOM. You are not supposed to modify the DOM, especially in ways that would affect the results of the iteration, while looping through the iteration. In this case, you probably get away with it as it is highly unlikely that langMatchingNodes contains more than one item. But let's not count on that. The proper fix is (either here or above where langMatchingNodes is declared) to append ToArray() or ToList() so the iteration is done once (creating an independent collection) before you start modifying the DOM.
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 267 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhnqM8K3BqffXMSs1o2:-MhoPiaR648kn1ruIPsb:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c24523e77a4d89924ca8695f3d321e7b0579b76e/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L267)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again you need a .ToArray() or similar either here or where the matchingNodes is created.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-24 14:26 UTC, JohnThomson approved these changes
LGTM. Just want to check you ran the HtmlDom unit tests. Assuming those pass, I think this is ready to merge.

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-:-MhsYN1X-GAGcphwJNEJ:b-lu7tgj)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 245 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPvIqyB_pszvYqSclV:-MhsY5428X8uICEpTXji:b-frpm7f) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L245)):*
<details><summary><i>Previously, nabalone wrote…</i></summary><blockquote>

Like this?
</blockquote></details>

Yes, exactly. (To make sure nothing got broken, please run the HtmlDom unit tests.)


<!-- Sent from Reviewable.io -->

2021-08-24 21:03 UTC, JohnThomson requested changes
> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 158 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhtxqAzE7Emsn3XDa_p:-MhtxqAzE7Emsn3XDa_q:b-7x1udf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b01df3c74ef0d319282d165d33e9731c5c1f52e/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L158)):*
> ```Smalltalk
> 							errorText = "Missing";
> 						}
> 						else if (Path.GetExtension(imageSrcPath).Equals(".svg"))
> ```

Let's insert .ToLowerInvariant() before .Equals (unless something elsewhere is ensuring imageSrcPath is all lower case?)


<!-- Sent from Reviewable.io -->

2021-08-25 14:22 UTC, nabalone reviewed
Passed

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-:-Mhxg19o0NKlCzvV-gTd:bxoupqt)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/BloomExe/Spreadsheet/SpreadsheetImporter.cs, line 245 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhPvIqyB_pszvYqSclV:-MhxYtwgAPc7fLZS-KwY:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/160fa313d6708e15bd44a845d34f8b48dbf49c69/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L245)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, exactly. (To make sure nothing got broken, please run the HtmlDom unit tests.)
</blockquote></details>

Done.
___
*[src/BloomExe/Spreadsheet/SpreadsheetIO.cs, line 158 at r6](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666#-MhtxqAzE7Emsn3XDa_p:-MhxZTCq27psmlnfojsF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/3b01df3c74ef0d319282d165d33e9731c5c1f52e/src/BloomExe/Spreadsheet/SpreadsheetIO.cs#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's insert .ToLowerInvariant() before .Equals (unless something elsewhere is ensuring imageSrcPath is all lower case?)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-25 16:38 UTC, JohnThomson approved these changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2021-08-25 16:40 UTC, merged