Fix some problems with renaming things in team Collection
BloomBooks/BloomDesktop pull request #4784
Opened 2021-10-08 20:36 UTC by JohnThomson

Remotely renamed book not yet reloaded allowed user to try to check out (BL-10528)
BringBookUpToDate could rename a not-checked-out book, with various nasty consequence (BL-10529)

2021-10-08 21:39 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 3536 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-MlWoYJR8QRA6intGyTT:-MlWoYJR8QRA6intGyTU:b-bb79fe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72fe174c2d352e233dd57a4198b45ced727748f8/src/BloomExe/Book/Book.cs#L3536)):*
> ```Smalltalk
> 				// in BringBookUpToDate, and it is disastrous to change the folder name of a book
> 				// that is not checked out.
> 				var tcm = TeamCollectionManager.TheOneInstance;
> ```

It would be good if we could avoid this kind of connection between this low-level thing (a book) and this high level thing (collection manager). Each individual connection like this is harmless, but they add up in such a big program.

Not the total solution, but a little bit better would be to just use `IsEditable` here, and then tie the editability to the checkout status. A step better than that would be for the book to query its collection for its editability (which in turn could know about the TCOL)?


<!-- Sent from Reviewable.io -->

2021-10-08 22:22 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 3536 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-MlWoYJR8QRA6intGyTT:-MlWziW-36M-2OgCJhyi:b-j1jjp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72fe174c2d352e233dd57a4198b45ced727748f8/src/BloomExe/Book/Book.cs#L3536)):*
> but a little bit better would be to just use IsEditable here, 

That's what I said but what I was *thinking* was that this function could go way and `Save()` should just, well, not ever do anything if the books `IsEditable == false`.


<!-- Sent from Reviewable.io -->

2021-10-08 22:26 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @hatton and @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 3536 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-MlWoYJR8QRA6intGyTT:-MlX-SUH1-LlM_agb9QF:b3nc35i) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72fe174c2d352e233dd57a4198b45ced727748f8/src/BloomExe/Book/Book.cs#L3536)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> but a little bit better would be to just use IsEditable here, 

That's what I said but what I was *thinking* was that this function could go way and `Save()` should just, well, not ever do anything if the books `IsEditable == false`.
</blockquote></details>

Would take (at least) 2 steps:
1) BookCollection.AddBookInfo, when it creates the BookInfo, would query for checkout status and include that in determination.
2) When a book is checked out or in, that editability would need to be updated.

As a result, all the places that check for editability via IsEditable would just continue to work, but now implicitly be controlled by the Team Collection, without explicit appeals to it.


<!-- Sent from Reviewable.io -->

2021-10-13 17:25 UTC, andrew-polk requested changes
> Reviewed 23 of 23 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 76 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-Mlubi6m2Ab_-ajzFxxJ:-Mlubi6m2Ab_-ajzFxxK:b-z0i05o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/Book.cs#L76)):*
> ```
> // This constructor is used only for testing and should assume savability
> ```
I think we should add the Guard like the previous constructor if that's the case.
___
*[src/BloomExe/Book/Book.cs, line 89 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-Mlubqfz5vDbz9i0bq7m:-Mlubqfz5vDbz9i0bq7n:b-t4gpg2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/Book.cs#L89)):*
> ```Smalltalk
> 			BookInfo = info;
> 			// This constructor is used often for testing and should assume savability in such cases
> 			_saveContext = context ?? new AlwaysEditSaveContext();
> ```

I think this is the place I was thinking of earlier where I'm a bit uncomfortable with the idea of defaulting to savable.
If it really is too much of a pain to set the parameter in all the test code, we could at least Guard (or is debug.assert better in this case?) for context == null.
___
*[src/BloomExe/Book/Book.cs, line 3547 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-Mluce1q1b7Uih-aY-gR:-Mluce1q1b7Uih-aY-gS:b-sniid5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/Book.cs#L3547)):*
> ```Smalltalk
> 				if (!IsSaveable)
> 					return false;
> 				return true;
> ```

Doesn't really matter, but if you're making changes elsewhere, this would cleaner as simply `return IsSaveable` now (after the first if).
___
*[src/BloomExe/Book/BookInfo.cs, line 55 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-MludLWJ0HEjXeWq57s9:-MludLWJ0HEjXeWq57sA:b6sqayq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/BookInfo.cs#L55)):*
> ```Smalltalk
> 			// By default (especially for many, many test cases), BookInfo's should assume savability
> 			// unless not editable
> 			_saveContext = saveContext ?? (isEditable ? new AlwaysEditSaveContext() : new NoEditSaveContext() as ISaveContext);
> ```

This still makes me slightly uncomfortable.
It maintains existing behavior, sure, but what about future callers? Usually it seems better to force devs to make a decision.

I'm definitely open to pushback, but it would be a shame to have less careful code just because unit tests are hindering us.
___
*[src/BloomExe/Book/SaveContext.cs, line 22 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-MlueMVE7EKJVGxWLMAe:-MlueMVE7EKJVGxWLMAf:b-h26apd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/SaveContext.cs#L22)):*
> ```
> allows
> ```
allowed


<!-- Sent from Reviewable.io -->

2021-10-13 19:36 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784)* status: 16 of 23 files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[src/BloomExe/Book/Book.cs, line 3536 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-MlWoYJR8QRA6intGyTT:-MluyVizCY18qOIaABUb:b-eo4cjq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72fe174c2d352e233dd57a4198b45ced727748f8/src/BloomExe/Book/Book.cs#L3536)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Would take (at least) 2 steps:
1) BookCollection.AddBookInfo, when it creates the BookInfo, would query for checkout status and include that in determination.
2) When a book is checked out or in, that editability would need to be updated.

As a result, all the places that check for editability via IsEditable would just continue to work, but now implicitly be controlled by the Team Collection, without explicit appeals to it.
</blockquote></details>

I think what I ended up doing is roughly what you had in mind, refined by our subsequent discussions.
___
*[src/BloomExe/Book/Book.cs, line 76 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-Mlubi6m2Ab_-ajzFxxJ:-Mluy2mh3_VrNGaqw6_2:b-q132dy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/Book.cs#L76)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // This constructor is used only for testing and should assume savability
> ```
I think we should add the Guard like the previous constructor if that's the case.
</blockquote></details>

This is a piece I neglected to clean out from the previous approach. There is now no reason for Book to have its own ISaveContext, either in its constructors or member variables.
___
*[src/BloomExe/Book/Book.cs, line 89 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-Mlubqfz5vDbz9i0bq7m:-MluyGKf5kRUOB8qB_RJ:b-gqwhz2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/Book.cs#L89)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this is the place I was thinking of earlier where I'm a bit uncomfortable with the idea of defaulting to savable.
If it really is too much of a pain to set the parameter in all the test code, we could at least Guard (or is debug.assert better in this case?) for context == null.
</blockquote></details>

The defaults are now in BookInfo and depend on editability.
___
*[src/BloomExe/Book/Book.cs, line 3547 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-Mluce1q1b7Uih-aY-gR:-MluyuS_9BFgdeK0toTh:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/Book.cs#L3547)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Doesn't really matter, but if you're making changes elsewhere, this would cleaner as simply `return IsSaveable` now (after the first if).
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookInfo.cs, line 55 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-MludLWJ0HEjXeWq57s9:-Mlv5ylw0S2TGa3m105f:b-ebsloz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/BookInfo.cs#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This still makes me slightly uncomfortable.
It maintains existing behavior, sure, but what about future callers? Usually it seems better to force devs to make a decision.

I'm definitely open to pushback, but it would be a shame to have less careful code just because unit tests are hindering us.
</blockquote></details>

Take a look at what I did. Basically it is to allow leaving it out when isEditable is false, or when running unit tests, but not otherwise.
___
*[src/BloomExe/Book/SaveContext.cs, line 22 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784#-MlueMVE7EKJVGxWLMAe:-Mlv6SMd1y4lM_0y2Q8P:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b8e92652952fbc5c4abda621b1313783efa36454/src/BloomExe/Book/SaveContext.cs#L22)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> allows
> ```
allowed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-10-13 20:34 UTC, andrew-polk approved these changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-10-13 20:34 UTC, andrew-polk approved these changes
> Dismissed @hatton from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)



<!-- Sent from Reviewable.io -->

2021-10-13 20:35 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4784)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)



<!-- Sent from Reviewable.io -->

2021-10-13 20:35 UTC, merged