Remove SideBySide and SplitAcrossPages
BloomBooks/BloomDesktop pull request #4815
Opened 2021-11-02 16:42 UTC by hatton

These were used before we had page layouts. Nowadays, we keep "layouts" separate from "page size/orientation".

2021-11-02 17:06 UTC, andrew-polk requested changes
Do we need to do anything with books which are already set to side-by-side?

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815#-:-MnWar3F3_io-Ro6JMkn:bku19qa)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, line 89 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815#-MnWZwu3BKHaLR96wts1:-MnWZwu3BKHaLR96wts2:be6kpau) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/618a488c752aed8c192bdc4cef62c3cad2fa2239/src/BloomBrowserUI/templates/template%20books/Basic%20Book/Basic%20Book.less#L89)):*
> ```
> &.layout-style-SplitAcrossPages
> ```
Can this section be removed?
___
*[src/BloomExe/Edit/EditingView.cs, line 1500 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815#-MnW_hVbEy6ewy4RAyWg:-MnW_hVbEy6ewy4RAyWh:be8zikm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/618a488c752aed8c192bdc4cef62c3cad2fa2239/src/BloomExe/Edit/EditingView.cs#L1500)):*
> ```Smalltalk
> 
> 						continue;
> 					}
> ```

I'm not understanding why we need this if/continue.
Can't we just get rid of `Book.Layout.ElementDistributionChoices.SplitAcrossPages`?
Or do we need it to handle existing books which are already set to this?

Is this a good time to rename things like `GetLayoutChoices` to `GetSizeAndOrientationChoices`?
___
*[src/BloomExe/Edit/EditingView.cs, line 1505 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815#-MnW_emW3pvQphSlPnG8:-MnW_emW3pvQphSlPnG9:b-p55tay) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/618a488c752aed8c192bdc4cef62c3cad2fa2239/src/BloomExe/Edit/EditingView.cs#L1505)):*
> ```
> //we don't allow the split options here
> ```
This comment wants to go away, too.


<!-- Sent from Reviewable.io -->

2021-11-02 19:56 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, line 89 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815#-MnWZwu3BKHaLR96wts1:-MnXCXTJAfGej8TIQdHe:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/618a488c752aed8c192bdc4cef62c3cad2fa2239/src/BloomBrowserUI/templates/template%20books/Basic%20Book/Basic%20Book.less#L89)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> &.layout-style-SplitAcrossPages
> ```
Can this section be removed?
</blockquote></details>

Done.
___
*[src/BloomExe/Edit/EditingView.cs, line 1500 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815#-MnW_hVbEy6ewy4RAyWg:-MnXCe3Y51ebHqFNuC9z:bd6egjr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/618a488c752aed8c192bdc4cef62c3cad2fa2239/src/BloomExe/Edit/EditingView.cs#L1500)):*
> I'm not understanding why we need this if/continue.

We don't. That wasn't supposed to be in this commit, just the previous one.

> Is this a good time to rename things like GetLayoutChoices to GetSizeAndOrientationChoices?

Agreed. But there's a bit of renaming to do around that.... probably wiser for me to leave that for someone. We can put this back into the Ready For Work for that.
___
*[src/BloomExe/Edit/EditingView.cs, line 1505 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815#-MnW_emW3pvQphSlPnG8:-MnXCoqp3ZsB9D0W4gD7:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/618a488c752aed8c192bdc4cef62c3cad2fa2239/src/BloomExe/Edit/EditingView.cs#L1505)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> //we don't allow the split options here
> ```
This comment wants to go away, too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-02 21:19 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomBrowserUI/templates/template books/Basic Book/Basic Book.less, line 239 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815#-MnXVxHk3KFnTQwC_LhG:-MnXVxHk3KFnTQwC_LhH:bi10h1u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/618a488c752aed8c192bdc4cef62c3cad2fa2239/src/BloomBrowserUI/templates/template%20books/Basic%20Book/Basic%20Book.less#L239)):*
> ```Less
>         }
>     }
>     // ----- Text Boxes ------
> ```

I might be parsing it incorrectly, but I think everything from `// ----- Text Boxes ------` down should remain.


<!-- Sent from Reviewable.io -->

2021-12-10 15:11 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4815)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)



<!-- Sent from Reviewable.io -->

2021-12-10 15:11 UTC, merged