BL-10507 new upload collision dialog
BloomBooks/BloomDesktop pull request #4822
Opened 2021-11-04 21:50 UTC by gmartin7

* remove old C# version
* create BookInfoCard component
* create new ReactDialog
* add icon
* work on spacing
* correct color for Ask For Help button
* add some l10n strings
* convert langPointers to language names
* get thumbnail to work
BL-10507

* finish wiring up new api
* setup way to change the book instance ID, if the user says
   the book's are different.

2021-11-04 21:51 UTC, gmartin7 commented
I need to test some more tomorrow. There may be a problem with the bit that changes the id and uploads.

2021-11-05 16:57 UTC, andrew-polk reviewed
> Reviewed 13 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: 13 of 20 files reviewed, 10 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 4261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkuQqQ4ltrgyWnCzom:-MnkuQqQ4ltrgyWnCzon:bnw0jsd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4261)):*
> ```
> Ask for help
> ```
You added this string twice with two different IDs
___
*[DistFiles/localization/en/Bloom.xlf, line 4307 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkvrVi9n71Rw7Njrc5:-MnkvrVi9n71Rw7Njrc6:b-tnj3ht) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4307)):*
> ```XML
>         <note>ID: PublishTab.UploadCollisionDialog.Uploading</note>
>         <note>This is the header for the book that is about to be uploaded.</note>
>       </trans-unit>
> ```

There are several strings where which I think would be better with more general IDs because I think it is likely we could reuse them in the future. 
e.g. Upload, Uploading, What caused this problem?
Actually, I was surprised we don't have Upload/Uploading already.

Maybe we should have a team discussion about this. 
IDs used to be much more helpful in the old system for providing the context in which a string was used. But with Crowdin and screenshots, that usefulness is much much less. We may want to consider moving toward IDs simply reflecting the string itself.
___
*[src/BloomBrowserUI/react_components/stories.tsx, line 26 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkxHKYBCn6V3oKz3Sg:-MnkxHKYBCn6V3oKz3Sh:b-iqp382) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/react_components/stories.tsx#L26)):*
> ```XML
>     IUploadCollisionDlgProps
> } from "../publish/LibraryPublish/uploadCollisionDlg";
> import { normalDialogEnvironmentForStorybook } from "./BloomDialog/BloomDialog";
> ```

Looks like you pulled in several imports you're not using.
___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 506 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mnl08TP2ZOCR8eGcFUr:-Mnl08TP2ZOCR8eGcFUs:biw94kh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L506)):*
> ```Smalltalk
> 					dlg.ControlBox = false;
> 					dlg.ShowDialog();
> 				}
> ```

If just for my sanity, could you move the creation and showing of this dialog to a new method? Thanks!
___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 520 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mnl0zpo8nVQvXHSjtgi:-Mnl0zpo8nVQvXHSjtgj:bvidcay) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L520)):*
> ```Smalltalk
> 
> 		}
> ```

Note to self: I was looking at this thumbnail stuff when I had to take a break from this review... pick up here.
___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 545 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mnl0k9r0eHiM6kEz6gr:-Mnl0k9r0eHiM6kEz6gs:bouugz4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L545)):*
> ```Smalltalk
> 			{
> 				return null;
> 			}
> ```

We'll have to look at it, but I'm pretty sure we can simplify this now. I think all non-failed books have been harvested since that date.
If not, we should include the comments here from blorg2 code stating why we do this.
___
*[src/BloomExe/WebLibraryIntegration/BloomParseClient.cs, line 154 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkynlDBCYaRucDYdtc:-MnkynlDBCYaRucDYdtd:b-8xq9ob) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/WebLibraryIntegration/BloomParseClient.cs#L154)):*
> ```Smalltalk
> 		}
> 
> 		public IRestResponse GetBookRecordsByQuery(string query, bool includeLanguageInfo)
> ```

Probably worth a comment here indicating the result of setting includeLanguageInfo to true and why to or not to.
___
*[src/BloomExe/WebLibraryIntegration/BookUpload.cs, line 403 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mnkz2vi0151ug3mJwAr:-Mnkz2vi0151ug3mJwAs:b-fztlzc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L403)):*
> ```Smalltalk
> 		/// </summary>
> 		/// <param name="bookPath"></param>
> 		/// <returns></returns>
> ```

I find empty params and returns to be unnecessary noise.
___
*[src/BloomExe/WebLibraryIntegration/BookUpload.cs, line 404 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkzSZN2LA17YJb55F3:-MnkzSZN2LA17YJb55F4:b-4yg4kr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L404)):*
> ```
> GetConflictingServerBookInfo
> ```
I think this would be better with a more general name, such as `GetBookOnServer`
___
*[src/BloomExe/web/controllers/WebPublishApi.cs, line 6 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkxwZO8zL4K01G4Npy:-MnkxwZO8zL4K01G4Npz:b8y0w41) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/web/controllers/WebPublishApi.cs#L6)):*
> ```
> WebPublishApi
> ```
Curious how you chose this name. The ts side uses LibraryPublish currently. Should we make them consistent?


<!-- Sent from Reviewable.io -->

2021-11-05 18:38 UTC, andrew-polk requested changes
> Reviewed 7 of 20 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: all files reviewed, 17 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 60 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlL4-h3JsNCOS92D6y:-MnlL4-h3JsNCOS92D6z:bs4lxjz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L60)):*
> ```
> "This is the dialog subtitle",
> ```
Should add what the {0} is.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlLkM_7Ac4HUjooWqy:-MnlLkM_7Ac4HUjooWqz:b-3u2nrq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L70)):*
> ```
> uploading
> ```
Can we rename some of these to better indicate they are just a localized string?
When looking through the use of them below, it is confusing not knowing what they are.
I guess something as simple as `existingCardHeader` and `uploadingCardHeader` or similar.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 76 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlLPDB4eiRqFRXzSlA:-MnlLPDC98Kl7K0W2Ji2:byq011s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L76)):*
> ```
> // Normally we prefer the Emotion CSS, but I can't get it to work in the case we need here.
> ```
What's the issue? Happy to look at it with you
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlNOm-8fbUUdl3MFJ0:-MnlNOm-8fbUUdl3MFJ1:b56tw12) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L161)):*
> ```XML
>                     `}
>                 >
>                     <div
> ```

I haven't evaluated enough whether it is worth it or not, but all this repetition makes me wonder if we should pull out each div-Radio to a separate component.
Even if we don't think it will be reused beyond this context, it might still make sense to create it as a separate component in this file.
See what you think.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 257 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlN92B0Vh0CX5rAXgr:-MnlN92B0Vh0CX5rAXgs:b-5r7uud) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L257)):*
> ```XML
>                                 color="textPrimary"
>                             >
>                                 What caused this problem?
> ```

Let's find out what this is supposed to do so it doesn't get lost.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 278 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlN0A2CTwuhsxZHnhO:-MnlN0A2CTwuhsxZHnhP:bz04rpo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L278)):*
> ```XML
>                         enabled={true}
>                     >
>                         Ask For Help
> ```

I guess this is probably supposed to launch a report a problem dialog?
Let's clarify so this doesn't get lost.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 287 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlMnQ15jHwWaDglL2v:-MnlMnQ2DfcynUbZW8ra:brmtgfz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L287)):*
> ```
> // We need a new api maybe that has a ref to the upload control object.
> ```
I don't understand this comment. Is it still relevant?
___
*[src/BloomExe/Book/BookStorage.cs, line 2536 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlK27k2mtvKN_Sdrrd:-MnlK27k2mtvKN_Sdrre:b-nd5n11) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Book/BookStorage.cs#L2536)):*
> ```Smalltalk
> 		}
> 
> 		public void ChangeInstanceId(string metaDataPath)
> ```

The original code you are reusing here is in the context of creating a new book.
I think we may need to do some other things when doing it for an existing book.
Look at BookInfo::InstallFreshGuidInternal() where we also do
```
 				Save();
				RobustFile.Delete(BookOrderPath(FolderPath));
				RobustFile.Delete(BookMetaData.BackupFilePath(FolderPath));
```

Maybe instead of calling something in BookStorage, we should instead be calling that logic in BookInfo and just make the error message more generic?


<!-- Sent from Reviewable.io -->

2021-11-05 22:21 UTC, gmartin7 commented
My recently pushed changes mostly address JH's UI review in the issue. I may have handled some of Andrew's review on the way. I still need to process Andrew's review that I just saw at the end of Friday.

2021-11-05 22:37 UTC, andrew-polk reviewed
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: all files reviewed, 17 unresolved discussions (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 4261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkuQqQ4ltrgyWnCzom:-MnmD3x_6DbQ9_jlAVKI:b67oi9j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> Ask for help
> ```
You added this string twice with two different IDs
</blockquote></details>

You didn't remove the `PublishTab.OverwriteWarning.AskForHelpButton` one, so there are still two.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 310 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnmEYVF90vjyQeP3XcI:-MnmEYVF90vjyQeP3XcJ:bmta6se) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2794aacb6114a58dc9b555e48cb7226bef50a04a/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L310)):*
> ```
> temporarilyDisableI18nWarning={true}
> ```
Did you mistakenly leave this in from a copy/paste?


<!-- Sent from Reviewable.io -->

2021-11-09 21:03 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: 8 of 21 files reviewed, 17 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 4261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkuQqQ4ltrgyWnCzom:-Mo-R1za0CqFHUhtQc9C:by5rxny) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You didn't remove the `PublishTab.OverwriteWarning.AskForHelpButton` one, so there are still two.
</blockquote></details>

Updated code just has Common.AskForHelp and the above AskForHelpButton is now marked "obsolete".
___
*[DistFiles/localization/en/Bloom.xlf, line 4307 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkvrVi9n71Rw7Njrc5:-Mo5VZx15ei_VUHTB7xH:b-5wji9x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4307)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There are several strings where which I think would be better with more general IDs because I think it is likely we could reuse them in the future. 
e.g. Upload, Uploading, What caused this problem?
Actually, I was surprised we don't have Upload/Uploading already.

Maybe we should have a team discussion about this. 
IDs used to be much more helpful in the old system for providing the context in which a string was used. But with Crowdin and screenshots, that usefulness is much much less. We may want to consider moving toward IDs simply reflecting the string itself.
</blockquote></details>

I'd be glad to have such a discussion.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 60 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlL4-h3JsNCOS92D6y:-Mo-RyE37xd0Ieakp8VZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L60)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> "This is the dialog subtitle",
> ```
Should add what the {0} is.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 70 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlLkM_7Ac4HUjooWqy:-Mo-SDPc3lkIjW3DW9n1:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L70)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> uploading
> ```
Can we rename some of these to better indicate they are just a localized string?
When looking through the use of them below, it is confusing not knowing what they are.
I guess something as simple as `existingCardHeader` and `uploadingCardHeader` or similar.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 76 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlLPDB4eiRqFRXzSlA:-Mo-SLhu5JqxPJ7-3TLk:b-16bdys) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L76)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // Normally we prefer the Emotion CSS, but I can't get it to work in the case we need here.
> ```
What's the issue? Happy to look at it with you
</blockquote></details>

Figured it out w/Emotion! Done.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 161 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlNOm-8fbUUdl3MFJ0:-Mo0_ONP-w6jE7cn4GWm:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L161)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I haven't evaluated enough whether it is worth it or not, but all this repetition makes me wonder if we should pull out each div-Radio to a separate component.
Even if we don't think it will be reused beyond this context, it might still make sense to create it as a separate component in this file.
See what you think.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 257 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlN92B0Vh0CX5rAXgr:-Mo0_SuE5pU5UontA-Mv:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L257)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's find out what this is supposed to do so it doesn't get lost.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 278 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlN0A2CTwuhsxZHnhO:-Mo-UEmj1jCTuvjVm50l:b603xa0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L278)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I guess this is probably supposed to launch a report a problem dialog?
Let's clarify so this doesn't get lost.
</blockquote></details>

You are right. Before I saw this comment, I noticed on the Figma mockup that the component is called a Report Button. That headed me down the direction we have in this next iteration.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 287 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlMnQ15jHwWaDglL2v:-Mo-UrBm-pyl8ulzIbgv:bxavmxx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L287)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> // We need a new api maybe that has a ref to the upload control object.
> ```
I don't understand this comment. Is it still relevant?
</blockquote></details>

Nope. Good catch. Removed.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 310 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnmEYVF90vjyQeP3XcI:-Mo-Tjmy6gXAZIOYyPcx:b-drvkq7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2794aacb6114a58dc9b555e48cb7226bef50a04a/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L310)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> temporarilyDisableI18nWarning={true}
> ```
Did you mistakenly leave this in from a copy/paste?
</blockquote></details>

Removed. I think I'm less than clear on when to use that, but yeah, probably not needed here.
___
*[src/BloomBrowserUI/react_components/stories.tsx, line 26 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkxHKYBCn6V3oKz3Sg:-Mo-Vzs116Vd-UVrGb_z:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomBrowserUI/react_components/stories.tsx#L26)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like you pulled in several imports you're not using.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookStorage.cs, line 2536 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlK27k2mtvKN_Sdrrd:-Mo5UbJ9Ey_YSTiUXxfV:b-7m33bl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4 [...]

2021-11-09 21:58 UTC, andrew-polk requested changes
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: all files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 4261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkuQqQ4ltrgyWnCzom:-Mo5Xxy1AR_p5rtpNk5-:b3bewb9) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4261)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Updated code just has Common.AskForHelp and the above AskForHelpButton is now marked "obsolete".
</blockquote></details>

But you added the obsolete one in this PR. So we can just remove it.
___
*[src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx, line 310 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnmEYVF90vjyQeP3XcI:-Mo5bR9g1YbS19NB3JFX:b-u5pu6b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/2794aacb6114a58dc9b555e48cb7226bef50a04a/src/BloomBrowserUI/publish/LibraryPublish/uploadCollisionDlg.tsx#L310)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Removed. I think I'm less than clear on when to use that, but yeah, probably not needed here.
</blockquote></details>

I think the only place we've used it for production code so far is for Team Collections where the decision was made not to internationalize anything yet.
___
*[src/BloomExe/Book/BookInfo.cs, line 620 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mo5cS1vB-_KeCGMZLy7:-Mo5cS1vB-_KeCGMZLy8:b7e7kw6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dec810e407c78b49319700388b5011ab96e87058/src/BloomExe/Book/BookInfo.cs#L620)):*
> ```
> internal for testing
> ```
Not anymore. Probably just make it public now to be more consistent with how we use public/internal usually.
___
*[src/BloomExe/Book/BookInfo.cs, line 644 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mo5c_-W3rCQjmVimwkb:-Mo5c_-W3rCQjmVimwkc:b-ad8j22) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dec810e407c78b49319700388b5011ab96e87058/src/BloomExe/Book/BookInfo.cs#L644)):*
> ```
> failed to repair duplicate id
> ```
I think we should make this message (and the short version) more generic.
___
*[src/BloomExe/Book/BookStorage.cs, line 2536 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnlK27k2mtvKN_Sdrrd:-Mo5cg3wCTzAMuvaYlDg:bqzy5xy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Book/BookStorage.cs#L2536)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

You're right. In fact, exploring your comment here led me to what my problem with changing the Id was (it was still uploading to the same S3 ID). Fixed now.
</blockquote></details>

Great!
I've moved the comment about generic error message to BookInfo to hopefully be more clear.
___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 545 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mnl0k9r0eHiM6kEz6gr:-Mo5dSbxD7epkV9oJApH:bdx8xza) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L545)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Have we determined a better way, yet?
</blockquote></details>

Just checked; some books were harvested before Feb 12, 2020 which is what the comment has in blorg2. So we do need the more complicated code.
So we should include the explanatory comment from blorg2.
And ideally, we need to test a book harvested before that date.


<!-- Sent from Reviewable.io -->

2021-11-10 18:00 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: all files reviewed, 5 unresolved discussions (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 4307 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkvrVi9n71Rw7Njrc5:-MoA-MB5CJ8fFjtOkXb1:bacokql) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4307)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I'd be glad to have such a discussion.
</blockquote></details>

Decided to make those three `Common.` for now.


<!-- Sent from Reviewable.io -->

2021-11-10 19:42 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: 17 of 22 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 4261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkuQqQ4ltrgyWnCzom:-Mo9Yi8A6S7-a-PbRiRl:b-eexd1k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

But you added the obsolete one in this PR. So we can just remove it.
</blockquote></details>

Well silly me! You're right. Removed.
___
*[DistFiles/localization/en/Bloom.xlf, line 4307 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MnkvrVi9n71Rw7Njrc5:-MoA-fk2-Dlrhy8Qp3HZ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/DistFiles/localization/en/Bloom.xlf#L4307)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Decided to make those three `Common.` for now.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookInfo.cs, line 620 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mo5cS1vB-_KeCGMZLy7:-Mo9lMg98BBbqKIDN8zU:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dec810e407c78b49319700388b5011ab96e87058/src/BloomExe/Book/BookInfo.cs#L620)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> internal for testing
> ```
Not anymore. Probably just make it public now to be more consistent with how we use public/internal usually.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookInfo.cs, line 644 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mo5c_-W3rCQjmVimwkb:-MoA-Wyx8Mr5FNgDBFEU:bfgjmpi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/dec810e407c78b49319700388b5011ab96e87058/src/BloomExe/Book/BookInfo.cs#L644)):*
> ```
> Failed to repair duplicate id
> ```
Decided to leave this as is.
___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 545 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mnl0k9r0eHiM6kEz6gr:-MoAHrWhA4z4zp5N2f-Y:b-exr4ag) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L545)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Just checked; some books were harvested before Feb 12, 2020 which is what the comment has in blorg2. So we do need the more complicated code.
So we should include the explanatory comment from blorg2.
And ideally, we need to test a book harvested before that date.
</blockquote></details>

Done. Spent some time trying to figure out how to test a book harvested before that date... that would be ideal, but I'm not sure how to do it. :(


<!-- Sent from Reviewable.io -->

2021-11-10 21:17 UTC, andrew-polk requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[DistFiles/localization/en/Bloom.xlf, line 3802 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MoAfRpp6JzrNYylqG01:-MoAfRpqDnzfH88d1DmJ:b7nr1ad) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03b14a6f2fd84107088db69f8aaaed02f54484a1/DistFiles/localization/en/Bloom.xlf#L3802)):*
> ```XML
>         <source xml:lang="en">Replace Existing</source>
>         <note>ID: PublishTab.OverwriteWarning.ReplaceExistingButton</note>
>         <note>obsolete</note>
> ```

The convention is to include the version number so we know when we can remove it.
So you'll see `<note>Obsolete for Bloom 5.1 and later</note>` and `<note>Obsolete as of Bloom 5.0</note>` elsewhere in this file. Might as well go with the text in the former (but 5.2, of course) since the latter will be removed sooner.

Same below.
___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 545 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mnl0k9r0eHiM6kEz6gr:-MoAguVs2qHmHyTLjiLR:b4qlz38) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L545)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done. Spent some time trying to figure out how to test a book harvested before that date... that would be ideal, but I'm not sure how to do it. :(
</blockquote></details>

Well, it looks like I messed up. 
I went to find a book you could test with (I think you just need to set your local book to the same ID. Or copy it down and copy the book folder to your collection). But then I discovered if you filter out books which aren't in circulation the oldest successful harvest date is Nov 2020.
So we don't need the complication in the code after all. It can just assume the url to the harvester thumbnail is always valid and not try to fall back to the legacy version.

Sorry.


<!-- Sent from Reviewable.io -->

2021-11-11 18:00 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: 20 of 22 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[DistFiles/localization/en/Bloom.xlf, line 3802 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-MoAfRpp6JzrNYylqG01:-MoEydPU50bIhTascCis:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/03b14a6f2fd84107088db69f8aaaed02f54484a1/DistFiles/localization/en/Bloom.xlf#L3802)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The convention is to include the version number so we know when we can remove it.
So you'll see `<note>Obsolete for Bloom 5.1 and later</note>` and `<note>Obsolete as of Bloom 5.0</note>` elsewhere in this file. Might as well go with the text in the former (but 5.2, of course) since the latter will be removed sooner.

Same below.
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 545 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-Mnl0k9r0eHiM6kEz6gr:-MoF7toR86-z74KU2-rt:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/f64cea6ce6d732e32b0bde3768dd4b5f28a475da/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L545)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Well, it looks like I messed up. 
I went to find a book you could test with (I think you just need to set your local book to the same ID. Or copy it down and copy the book folder to your collection). But then I discovered if you filter out books which aren't in circulation the oldest successful harvest date is Nov 2020.
So we don't need the complication in the code after all. It can just assume the url to the harvester thumbnail is always valid and not try to fall back to the legacy version.

Sorry.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-11 18:11 UTC, andrew-polk approved these changes
Approving but not merging due to the comment in the card about checking for missing items.

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-:-MoFB_w0EPXTukDsRLK1:be4sxdh)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2021-11-11 23:06 UTC, gmartin7 reviewed
Added the existing book title link and made some more minor tweaks to the various links.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822#-:-MoGEx0qBXCnTJ_4Ih1x:b-rfce7r)* status: 18 of 22 files reviewed, all discussions resolved (waiting on @andrew-polk)



<!-- Sent from Reviewable.io -->

2021-11-12 00:01 UTC, andrew-polk approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2021-11-12 14:49 UTC, merged