BL-8956 switch BookCompressor from black to whitelist
BloomBooks/BloomDesktop pull request #4843
Opened 2021-11-30 21:35 UTC by gmartin7

* whitelists file extensions for book level and audio and video folders
* whitelists an activities folder (Widgets) and any contents

2021-12-01 17:49 UTC, sujeffreyl requested changes
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[src/BloomExe/Book/BookCompressor.cs, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-MpqzKMg90D6SjU4swr2:-MpqzKMh2qkmBs2he9YL:bii37tq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91e861f5460478b3a092572f688a55866c6ceb90/src/BloomExe/Book/BookCompressor.cs#L30)):*
> ```
> jpg"
> ```
The proposal called for jpeg as well. Is that still supposed to be included?
___
*[src/BloomExe/Book/BookCompressor.cs, line 185 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpr-3mCEOFwmM-Enwgk:-Mpr-3mCEOFwmM-Enwgl:b-pd7jau) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91e861f5460478b3a092572f688a55866c6ceb90/src/BloomExe/Book/BookCompressor.cs#L185)):*
> ```
> Path.GetExtension(filePath.ToLowerInvariant())
> ```
You could do Path.GetExtension(filePath).ToLowerInvariant() instead, cuz only the extension needs to be lowercased.
___
*[src/BloomExe/Book/BookCompressor.cs, line 310 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpr-zNx2x_61-RWabpY:-Mpr-zNx2x_61-RWabpZ:b-c0igc2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91e861f5460478b3a092572f688a55866c6ceb90/src/BloomExe/Book/BookCompressor.cs#L310)):*
> ```
> 			// We only check depth 2, because 1 is not a subfolder and farther down, if we are going there,
> 			// we want everything.
> ```
Is this (we want everything if depth >= 3 because any invalid sub-subfolders are already filtered out?
If so, maybe we could make that even clearer in the comment.
___
*[src/BloomTests/Book/BookCompressorTests.cs, line 143 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpr6Kks4edQZGcIBXQC:-Mpr6Kks4edQZGcIBXQD:b5qvdzd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91e861f5460478b3a092572f688a55866c6ceb90/src/BloomTests/Book/BookCompressorTests.cs#L143)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 					string audioDir = Path.Combine(folderPath, "audio");
> 					Directory.CreateDirectory(audioDir);
> 					File.WriteAllText(Path.Combine(audioDir, "musicfile.ogg"), "dummy ogg content");
> 
> 					string videoDir = Path.Combine(folderPath, "video");
> 					Directory.CreateDirectory(videoDir);
> 					File.WriteAllText(Path.Combine(videoDir, "signlanguageVid.mp4"), "dummy video content");
> ```
</details>

How about extensions not in the whitelist in the audio/video folders?


<!-- Sent from Reviewable.io -->

2021-12-01 21:58 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookCompressor.cs, line 30 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-MpqzKMg90D6SjU4swr2:-MprLwG003iuQftQnWZm:b35wj2g) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91e861f5460478b3a092572f688a55866c6ceb90/src/BloomExe/Book/BookCompressor.cs#L30)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> jpg"
> ```
The proposal called for jpeg as well. Is that still supposed to be included?
</blockquote></details>

Done. Good point.
___
*[src/BloomExe/Book/BookCompressor.cs, line 185 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpr-3mCEOFwmM-Enwgk:-MprMX6j6yR0Nf3ewMPV:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91e861f5460478b3a092572f688a55866c6ceb90/src/BloomExe/Book/BookCompressor.cs#L185)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> Path.GetExtension(filePath.ToLowerInvariant())
> ```
You could do Path.GetExtension(filePath).ToLowerInvariant() instead, cuz only the extension needs to be lowercased.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookCompressor.cs, line 310 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpr-zNx2x_61-RWabpY:-MprxipLBEEn4yk1sf29:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91e861f5460478b3a092572f688a55866c6ceb90/src/BloomExe/Book/BookCompressor.cs#L310)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> 			// We only check depth 2, because 1 is not a subfolder and farther down, if we are going there,
> 			// we want everything.
> ```
Is this (we want everything if depth >= 3 because any invalid sub-subfolders are already filtered out?
If so, maybe we could make that even clearer in the comment.
</blockquote></details>

Done.
___
*[src/BloomTests/Book/BookCompressorTests.cs, line 143 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpr6Kks4edQZGcIBXQC:-MprzMGk82HX5GSm5P2o:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/91e861f5460478b3a092572f688a55866c6ceb90/src/BloomTests/Book/BookCompressorTests.cs#L143)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> 					string audioDir = Path.Combine(folderPath, "audio");
> 					Directory.CreateDirectory(audioDir);
> 					File.WriteAllText(Path.Combine(audioDir, "musicfile.ogg"), "dummy ogg content");
> 
> 					string videoDir = Path.Combine(folderPath, "video");
> 					Directory.CreateDirectory(videoDir);
> 					File.WriteAllText(Path.Combine(videoDir, "signlanguageVid.mp4"), "dummy video content");
> ```
How about extensions not in the whitelist in the audio/video folders?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 19:22 UTC, sujeffreyl requested changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomExe/Book/BookCompressor.cs, line 313 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpwa65b5sajeizRlukD:-Mpwa65b5sajeizRlukE:b-kk59m0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ec8d1a19b0eee33e6cc761d315fe4962589757a/src/BloomExe/Book/BookCompressor.cs#L313)):*
> ```
>  Review
> ```
TODO: let's try to resolve this before merging
___
*[src/BloomTests/Book/BookCompressorTests.cs, line 145 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpw_w07-TupuMHysImF:-Mpw_w07-TupuMHysImG:bz5oe1d) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ec8d1a19b0eee33e6cc761d315fe4962589757a/src/BloomTests/Book/BookCompressorTests.cs#L145)):*
> ```
> included
> ```
maybe add "because their extensions are not whitelisted" or something to that effect here or anywhere else you like in this function.


<!-- Sent from Reviewable.io -->

2021-12-02 23:58 UTC, gmartin7 reviewed
The whitelisting mechanism has been reworked. It now only allows audio file types in the 'audio' subfolder and only allows video file types in the 'video' subfolder and the whitelist for the main book folder does NOT contain AudioVisual files.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-:-Mpx_8n07KBpxWzYQZgj:b-ijb80z)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookCompressor.cs, line 313 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpwa65b5sajeizRlukD:-Mpx_5TJC8-xAFn33Pd6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ec8d1a19b0eee33e6cc761d315fe4962589757a/src/BloomExe/Book/BookCompressor.cs#L313)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
>  Review
> ```
TODO: let's try to resolve this before merging
</blockquote></details>

Done.
___
*[src/BloomTests/Book/BookCompressorTests.cs, line 145 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpw_w07-TupuMHysImF:-MpwwnDv-_kYATV6aQhj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ec8d1a19b0eee33e6cc761d315fe4962589757a/src/BloomTests/Book/BookCompressorTests.cs#L145)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> included
> ```
maybe add "because their extensions are not whitelisted" or something to that effect here or anywhere else you like in this function.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 23:59 UTC, gmartin7 reviewed
I also added comments where we will find them if we upgrade Bloom to use other audio or video file types.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-:-Mpx_YC58cvy8WVcjF3i:b-cwltdu)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2021-12-03 05:01 UTC, sujeffreyl reviewed
> Reviewed 3 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookCompressor.cs, line 313 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-Mpwa65b5sajeizRlukD:-MpyeY5N7DRZ9SnGzGbi:b-5wvuhb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/5ec8d1a19b0eee33e6cc761d315fe4962589757a/src/BloomExe/Book/BookCompressor.cs#L313)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ok, you can delete this comment then


<!-- Sent from Reviewable.io -->

2021-12-07 15:47 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @gmartin7 and @sujeffreyl)

___
*[src/BloomExe/Book/BookCompressor.cs, line 316 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-MqKYlBR4RG3a5K75DEF:-MqKYlBU5by2uiLOhRmK:bpzl57w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fdaea228ebe8a784489c6cfbf99723cd5dbc3bc/src/BloomExe/Book/BookCompressor.cs#L316)):*
> ```
> FileIsNotWhitelisted
> ```
I think this will be easier to grok by reversing the logic, i.e. having a function FileIsWhitelisted
___
*[src/BloomExe/Book/BookCompressor.cs, line 351 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-MqKZhPH2ZlK_fpoau3R:-MqKZhPI0b5dP_r_ps2_:b-8s9lj6) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fdaea228ebe8a784489c6cfbf99723cd5dbc3bc/src/BloomExe/Book/BookCompressor.cs#L351)):*
> ```
> 			// Review: Do we want to allow the 'audio' and 'video' subfolders to have sub-subfolders? Currently
> 			// this code allows that.
> ```
I think you already implemented not allowing the audio and video subfolders to have sub-subfolders?  So I think we can delete this now.


<!-- Sent from Reviewable.io -->

2021-12-07 17:51 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookCompressor.cs, line 316 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-MqKYlBR4RG3a5K75DEF:-MqKzixHCh5yNPceburb:b-d58wtm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fdaea228ebe8a784489c6cfbf99723cd5dbc3bc/src/BloomExe/Book/BookCompressor.cs#L316)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> FileIsNotWhitelisted
> ```
I think this will be easier to grok by reversing the logic, i.e. having a function FileIsWhitelisted
</blockquote></details>

Done. I grok you. ;)
___
*[src/BloomExe/Book/BookCompressor.cs, line 351 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-MqKZhPH2ZlK_fpoau3R:-MqKvsbzBqrytGdvMXPz:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fdaea228ebe8a784489c6cfbf99723cd5dbc3bc/src/BloomExe/Book/BookCompressor.cs#L351)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

> ```
> 			// Review: Do we want to allow the 'audio' and 'video' subfolders to have sub-subfolders? Currently
> 			// this code allows that.
> ```
I think you already implemented not allowing the audio and video subfolders to have sub-subfolders?  So I think we can delete this now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-07 17:56 UTC, sujeffreyl approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookCompressor.cs, line 316 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-MqKYlBR4RG3a5K75DEF:-MqL1Tj33tEwi1Lcvif3:b32vhw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/9fdaea228ebe8a784489c6cfbf99723cd5dbc3bc/src/BloomExe/Book/BookCompressor.cs#L316)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done. I grok you. ;)
</blockquote></details>

:)


<!-- Sent from Reviewable.io -->

2021-12-07 17:57 UTC, sujeffreyl approved these changes
> Reviewed 1 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2021-12-07 17:57 UTC, sujeffreyl approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2021-12-07 17:57 UTC, sujeffreyl approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4843#-:-MqL1ktK3UeIEip80NFJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2021-12-07 17:57 UTC, merged