BL-10679 Don't publish multiple .htm files
BloomBooks/BloomDesktop pull request #4868
Opened 2021-12-10 19:25 UTC by gmartin7

* initial refactor
* delete all .htm/.html files in book folder other than the
   one we need for the book and configuration.htm and any
   readme files.
* Was initially concerned that this PR doesn't apply to bulk upload, but
   bulk upload only uploads books with only one .htm file.

2021-12-13 22:54 UTC, andrew-polk requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomExe/Book/BookStorage.cs, line 1561 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-Mqq-8BiE42togYyKDIR:-Mqq-8BiE42togYyKDIS:b-afmua1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d5f23bcfb077dca3058d5ad93a5c542c69c0bed3/src/BloomExe/Book/BookStorage.cs#L1561)):*
> ```
> PrefixForCorruptHtmFiles, // Used to rename corrupt htm files before restoring backup
> ```
I think we need to prevent these from getting deleted?
___
*[src/BloomExe/Publish/PublishModel.cs, line 124 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-Mqpxh8m-RoCfLzPEdM9:-Mqpxh8m-RoCfLzPEdMA:bsb36ot) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d5f23bcfb077dca3058d5ad93a5c542c69c0bed3/src/BloomExe/Publish/PublishModel.cs#L124)):*
> ```Smalltalk
> 				RobustFile.Delete(badFilePath);
> 			}
> 		}
> ```

I'm thinking the method which deletes all but the correct htm file probably belongs in BookStorage rather than PublishModel.
So I think you can basically move this logic into BookStorage and rename the method there.

A related issue:
I feel like we are sorta conflating two ideas:
1. non-publishable
2. ok to delete

Perhaps all that's needed is a naming change which I've already suggested above. But rather than referencing publishability, it is really something like DeleteInvalidHtmFiles?
___
*[src/BloomTests/Book/BookStorageTests.cs, line 1459 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-MqaBF2xBcG6xZP7EJSd:-MqaBF2xBcG6xZP7EJSe:b-8pewzn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d5f23bcfb077dca3058d5ad93a5c542c69c0bed3/src/BloomTests/Book/BookStorageTests.cs#L1459)):*
> ```
> BookStorageTests_getUniqueFolderPath
> ```
This wants to be something like `BookStorageTests_FindNonPublishableHtmFiles_DeletesTheRightFiles`


<!-- Sent from Reviewable.io -->

2022-01-03 20:13 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/BookStorage.cs, line 1561 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-Mqq-8BiE42togYyKDIR:-MsWNdNY8FXF4xf-MWxr:b56ctrc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d5f23bcfb077dca3058d5ad93a5c542c69c0bed3/src/BloomExe/Book/BookStorage.cs#L1561)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> PrefixForCorruptHtmFiles, // Used to rename corrupt htm files before restoring backup
> ```
I think we need to prevent these from getting deleted?
</blockquote></details>

Perhaps when you're back we can talk about this, since my PR didn't change this and I'm not sure of your reasoning?
___
*[src/BloomExe/Publish/PublishModel.cs, line 124 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-Mqpxh8m-RoCfLzPEdM9:-MsWQx-g8ny4_NQdW2sQ:b-r7qzbc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d5f23bcfb077dca3058d5ad93a5c542c69c0bed3/src/BloomExe/Publish/PublishModel.cs#L124)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm thinking the method which deletes all but the correct htm file probably belongs in BookStorage rather than PublishModel.
So I think you can basically move this logic into BookStorage and rename the method there.

A related issue:
I feel like we are sorta conflating two ideas:
1. non-publishable
2. ok to delete

Perhaps all that's needed is a naming change which I've already suggested above. But rather than referencing publishability, it is really something like DeleteInvalidHtmFiles?
</blockquote></details>

I moved "Ensure..." to BookStorage and renamed the "FindNonPublishableHtmlFiles" method to "FindDeletableHtmFiles". This also involved some renaming in the tests.
___
*[src/BloomTests/Book/BookStorageTests.cs, line 1459 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-MqaBF2xBcG6xZP7EJSd:-MsWC6QWDj6kVFNyf9Ge:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d5f23bcfb077dca3058d5ad93a5c542c69c0bed3/src/BloomTests/Book/BookStorageTests.cs#L1459)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BookStorageTests_getUniqueFolderPath
> ```
This wants to be something like `BookStorageTests_FindNonPublishableHtmFiles_DeletesTheRightFiles`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-10 22:15 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[src/BloomExe/Book/BookStorage.cs, line 1561 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-Mqq-8BiE42togYyKDIR:-Mt52eOU2hJEHYiDl_Xl:brtmcl2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d5f23bcfb077dca3058d5ad93a5c542c69c0bed3/src/BloomExe/Book/BookStorage.cs#L1561)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Perhaps when you're back we can talk about this, since my PR didn't change this and I'm not sure of your reasoning?
</blockquote></details>

I'm not sure why I picked that one to want to preserve, either, since they are corrupt. But I could see merit to maintaining conflict files.
As we discussed, let's make this a quick post-meeting discussion topic with the team tomorrow morning.


<!-- Sent from Reviewable.io -->

2022-01-11 20:05 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Book/BookStorage.cs, line 1561 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-Mqq-8BiE42togYyKDIR:-Mt9jkdL7eN59iQw07Fp:b-hko6bw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/d5f23bcfb077dca3058d5ad93a5c542c69c0bed3/src/BloomExe/Book/BookStorage.cs#L1561)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure why I picked that one to want to preserve, either, since they are corrupt. But I could see merit to maintaining conflict files.
As we discussed, let's make this a quick post-meeting discussion topic with the team tomorrow morning.
</blockquote></details>

redone.


<!-- Sent from Reviewable.io -->

2022-01-11 20:29 UTC, gmartin7 reviewed
The only publishing case this doesn't yet cover is making BloomPacks. Unfortunately, that process never copies the directory to a staging area, it's a direct "send this directory's files to a zipStream". Harder to intercept.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-:-Mt9ozp18he_PwS8nqkk:bo12mik)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)



<!-- Sent from Reviewable.io -->

2022-01-11 21:10 UTC, andrew-polk requested changes
I guess epub already handles this a different way?

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-:-Mt9yR5R-_JLffwBT8GO:bmgjflk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2022-01-11 21:13 UTC, gmartin7 reviewed
See new comment on BookStorage.EnsureSingleHtmFile().

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-:-Mt9z-VD4WOqIhTpaYaF:bxfzxuo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2022-01-11 21:49 UTC, andrew-polk approved these changes
Let's make sure the fact that this is not happening for BloomPacks is captured in the card.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4868#-:-MtA6Ket0-1E2WD5rpa_:b-1okjcq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2022-01-11 21:49 UTC, merged