Fix Shift + Enter being stripped out when uploaded to web (BL-10630)
BloomBooks/BloomDesktop pull request #4897
Opened 2022-01-06 19:42 UTC by sujeffreyl

2022-01-06 19:43 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 2 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 496 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MskuY1g4EB0bORw7NaO:-MskuY1g4EB0bORw7NaP:b-immjvp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/542647515c81063e42b018b7897b392ced3d3eb0/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L496)):*
> ```Smalltalk
> 			var newThumbPath = ChooseBestUploadingThumbnailPath(_model.Book).ToLocalhost();
> 
> 			// FYI, we used to get newTitle from _model.Book.TitleBestForUserDisplay, but for multi-line titles,
> ```

Gordon and I couldn't think of any reason why we need to specifically use TitleBestForUserDisplay over BookInfo.Title, but please let me know if you do!


<!-- Sent from Reviewable.io -->

2022-01-06 22:00 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MslOdCG5xhdGut9cp-d:-MslOdCG5xhdGut9cp-e:b-8nw08s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/542647515c81063e42b018b7897b392ced3d3eb0/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L499)):*
> ```Smalltalk
> 			// TitleBestForUserDisplay just deletes the newlines, whereas originalTitle preserves them.
> 			// Switched to BookInfo.Title because it also preserves newlines, the better to match originalTitle's formatting.
> 			var newTitle = _model.Book.BookInfo.Title;
> ```

`TitleBestForUserDisplay` seems to mostly about choosing which language to use. How do these semantics compare to what we get with just `TItle`, which seems to get the last `title` element out of the head of the HTML, in the normal (best) case ?



_Code quote:_
```Smalltalk
TitleBestForUserDisplay
```


<!-- Sent from Reviewable.io -->

2022-01-07 15:49 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MslOdCG5xhdGut9cp-d:-MspCjfz9kRZyl13bup4:b5bkaba) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/542647515c81063e42b018b7897b392ced3d3eb0/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L499)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

`TitleBestForUserDisplay` seems to mostly about choosing which language to use. How do these semantics compare to what we get with just `TItle`, which seems to get the last `title` element out of the head of the HTML, in the normal (best) case ?
</blockquote></details>

Are we talking about Book.Title or Book.BookInfo.Title? Book.BookInfo.Title seems to get the title from meta.json from what I see.

1) I tried making a collection with langs=[en, en]. Then i created a book w/an English title and uploaded it.
2) Changed langs to [es, es]. Gave it a Spanish title. Both the existing code and my new code gave the result in the same language (Spanish).
3) Switch back to [en, en]. Both versions give title same lang.
4) [es, en]. Same.
5) [en, es]. Same.
6) [es, es]. Same.

Does that seem satisfactory? Let me know if there's more scenarios you want me to test.


<!-- Sent from Reviewable.io -->

2022-01-07 16:41 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MslOdCG5xhdGut9cp-d:-MspNcTb9GfTooe8_GBB:b4svbwp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/542647515c81063e42b018b7897b392ced3d3eb0/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L499)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Are we talking about Book.Title or Book.BookInfo.Title? Book.BookInfo.Title seems to get the title from meta.json from what I see.

1) I tried making a collection with langs=[en, en]. Then i created a book w/an English title and uploaded it.
2) Changed langs to [es, es]. Gave it a Spanish title. Both the existing code and my new code gave the result in the same language (Spanish).
3) Switch back to [en, en]. Both versions give title same lang.
4) [es, en]. Same.
5) [en, es]. Same.
6) [es, es]. Same.

Does that seem satisfactory? Let me know if there's more scenarios you want me to test.
</blockquote></details>

OK yeah I was looking at `Book.Title` not `BookInfor.Title`.  But the the concern is the same: it's so hard to know under what conditions you'll get a different title than the old code which used, logically, the correct "Title" function: as the name implies, `TitleBestForUserDisplay` is exactly for these situations: what is the version of the title that we should be displaying to this user right now? However, the stakes are low... this is just a dialog in a corner case.

Anyhow that other path got messed up when we allowed people to set a file name. Problem 1) BookInfo.NameLocked should have been "FileNameLocked".  2) Once the thumbnail name was no longer necessarily the Title, it should not longer be using `TitleBestForUserDisplay`... instead that other commit wrongly, I think, modified it to show the file name.  Sigh


<!-- Sent from Reviewable.io -->

2022-01-07 16:51 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MslOdCG5xhdGut9cp-d:-MspR_OeA070WQ660hpl:bugvauv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/542647515c81063e42b018b7897b392ced3d3eb0/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L499)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

OK yeah I was looking at `Book.Title` not `BookInfor.Title`.  But the the concern is the same: it's so hard to know under what conditions you'll get a different title than the old code which used, logically, the correct "Title" function: as the name implies, `TitleBestForUserDisplay` is exactly for these situations: what is the version of the title that we should be displaying to this user right now? However, the stakes are low... this is just a dialog in a corner case.

Anyhow that other path got messed up when we allowed people to set a file name. Problem 1) BookInfo.NameLocked should have been "FileNameLocked".  2) Once the thumbnail name was no longer necessarily the Title, it should not longer be using `TitleBestForUserDisplay`... instead that other commit wrongly, I think, modified it to show the file name.  Sigh
</blockquote></details>

So... I guess you're saying that TitleBestForUserDisplay is incorrect, and we should fix it so that it formats Shift+Enter as spaces? And back out the changes in this file. Is that right?


<!-- Sent from Reviewable.io -->

2022-01-07 17:04 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MslOdCG5xhdGut9cp-d:-MspTUVsEY1aQYNyPfN2:blqpswj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/542647515c81063e42b018b7897b392ced3d3eb0/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L499)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

So... I guess you're saying that TitleBestForUserDisplay is incorrect, and we should fix it so that it formats Shift+Enter as spaces? And back out the changes in this file. Is that right?
</blockquote></details>

Sorry to make things complicated for you! Backing up, we has this function `TitleBestForUserDisplay` which as fine when the title mostly = filename. Now that these are two different ideas (you can have title "foo" and filename "blah"), that property name is ambiguous. We should go through the 30 or so uses and see... are there in fact two sets of scenarios, one in which we want the file name, and one in which we want the title?  Assuming yes, I expect that we should not be using TBFUD() in the former, but some simple file name property. Does that sound right?

Then, from what you know would we also need, in the places still using TBFUD(), to differentiate between those places that want a single line, those that want the new lines? If so, would it be easy to change it to a method that takes a parameter saying which you want?


<!-- Sent from Reviewable.io -->

2022-01-07 17:47 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @hatton and @sujeffreyl)

___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 499 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MslOdCG5xhdGut9cp-d:-MspcyEg2FQ0hRlFDnoF:b-89a4oy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/542647515c81063e42b018b7897b392ced3d3eb0/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L499)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry to make things complicated for you! Backing up, we has this function `TitleBestForUserDisplay` which as fine when the title mostly = filename. Now that these are two different ideas (you can have title "foo" and filename "blah"), that property name is ambiguous. We should go through the 30 or so uses and see... are there in fact two sets of scenarios, one in which we want the file name, and one in which we want the title?  Assuming yes, I expect that we should not be using TBFUD() in the former, but some simple file name property. Does that sound right?

Then, from what you know would we also need, in the places still using TBFUD(), to differentiate between those places that want a single line, those that want the new lines? If so, would it be easy to change it to a method that takes a parameter saying which you want?
</blockquote></details>

OK, I'll look into that on Monday. I'll do that as a separate commit but part of the same PR. I'm moving this PR to draft status.

Ah, actually I think I spoke imprecisely earlier. OriginalTitle and stuff return is with newlines as newlines. They just get transferred to HTML land as newlines too,  but in HTML land newlines are treated as spaces. I think it would be reasonable and OK to return it with newlines, and the caller can easily present it as either newlines-treated-as-spaces or newlines-as-linebreaks.


<!-- Sent from Reviewable.io -->

2022-01-07 22:26 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @hatton, @JohnThomson, and @sujeffreyl)

___
*[src/BloomExe/Book/BookData.cs, line 1767 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MsqcTls9-h2osMLyJQT:-MsqcTls9-h2osMLyJQU:bgskcr0) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7eafd4ca9e4a25c2ca99316dc099e4f256be4696/src/BloomExe/Book/BookData.cs#L1767)):*
> ```Smalltalk
> 			// Handle Shift+Enter, which gets translated to <span class="bloom-linebreak" />
> 			// This is being handled using at the XElement level instead of string level, so that it'll work regardless of
> 			// whether it uses the <span /> form or <span></span> form. (I do see places in the debugger where the data is in <span></span> form.)
> ```

shift-enter normally inserts both this span and also a zero-width-non-joiner (&#xfeff;). Maybe it would be useful to remove that too if it's present? Such invisible characters can be puzzling in causing things like Find commands to fail mysteriously.


<!-- Sent from Reviewable.io -->

2022-01-11 17:53 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @hatton, @JohnThomson, and @sujeffreyl)

___
*[src/BloomExe/Book/Book.cs, line 214 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-Mt9GOVS2ABvvtWO-sg0:-Mt9GOVS2ABvvtWO-sg1:b1qaf8e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/72eaa1c70893c95c2e8354b8010b9a29c8ffaad3/src/BloomExe/Book/Book.cs#L214)):*
> ```Smalltalk
> 		/// Note, this isn't going to be the best for choosing a filename, which we are more likely to want in a national language
> 		/// </summary>
> 		public virtual string TitleOrNameBestForUserDisplay
> ```

Revision 2 is temporary. This is not ready for review yet.


<!-- Sent from Reviewable.io -->

2022-01-12 19:15 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: 0 of 18 files reviewed, 4 unresolved discussions (waiting on @hatton, @JohnThomson, and @sujeffreyl)

___
*[src/BloomExe/Book/BookData.cs, line 1767 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MsqcTls9-h2osMLyJQT:-MtEgN-A5AXy0OemlmmY:b-wbnybm) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7eafd4ca9e4a25c2ca99316dc099e4f256be4696/src/BloomExe/Book/BookData.cs#L1767)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

shift-enter normally inserts both this span and also a zero-width-non-joiner (&#xfeff;). Maybe it would be useful to remove that too if it's present? Such invisible characters can be puzzling in causing things like Find commands to fail mysteriously.
</blockquote></details>

Ok, i did find it inserted the zero-width character as well. I removed it.

However, here's an awkward conundrum I face. It would be a lot more straightforward code-wise to just detect the zero-widtch character and turn that into a newline or space or whatever is appropriate. And completely ignore the <span class="bloom-linebreak">

However, I feel like that span is what better represents that there is a linebreak, so I feel like the "right" thing to do is to handle that.

Thoughts?


<!-- Sent from Reviewable.io -->

2022-01-21 19:53 UTC, JohnThomson requested changes
Can we get the TitleOrName commits out of this PR? I haven't reviewed them, assuming they've been reviewed elsewhere, but they make it difficult to figure out what's really in this change.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-:-MtyBXR-7CnvHRzFl5ef:b-dsruf2)* status: 0 of 18 files reviewed, 3 unresolved discussions (waiting on @hatton, @JohnThomson, and @sujeffreyl)

___
*[src/BloomExe/Book/BookData.cs, line 1767 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MsqcTls9-h2osMLyJQT:-Mty6R2NEwu9wESbWU5_:bybtjhn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7eafd4ca9e4a25c2ca99316dc099e4f256be4696/src/BloomExe/Book/BookData.cs#L1767)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Ok, i did find it inserted the zero-width character as well. I removed it.

However, here's an awkward conundrum I face. It would be a lot more straightforward code-wise to just detect the zero-widtch character and turn that into a newline or space or whatever is appropriate. And completely ignore the <span class="bloom-linebreak">

However, I feel like that span is what better represents that there is a linebreak, so I feel like the "right" thing to do is to handle that.

Thoughts?
</blockquote></details>

I agree. The zwsp is just something Bloom puts in to help us put the insertion point where we want it. We may come up with a better way to do that. We shouldn't depend on it.
___
*[src/BloomExe/Book/BookData.cs, line 1762 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-Mty6xjh67oeNn0bMlpA:-Mty6xjh67oeNn0bMlpB:bqxcvxh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/BookData.cs#L1762)):*
> ```Smalltalk
> 
> 			// Shift-enter also inserts a zero-width no-break space, so delete that out
> 			input = input.Replace(((char)65279).ToString(), "");
> ```

I'm not sure this character never affects rendering...it might prevent a break where one would normally be allowed? Seems safest only to delete it immediately following the span.


<!-- Sent from Reviewable.io -->

2022-01-21 21:39 UTC, JohnThomson requested changes
> Reviewed 18 of 18 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897)* status: all files reviewed, 10 unresolved discussions (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/Book.cs, line 225 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyYEHJAcbzctLCLXO2:-MtyYEHJAcbzctLCLXO3:bo8ve9m) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/Book.cs#L225)):*
> ```Smalltalk
> 		/// If the user has renamed the book, returns that. Otherwise, returns the title
> 		/// </summary>
> 		public virtual string NameBestForUserDisplay
> ```

Is it possible to comment on this method and/or the title one about any guiding principles that should determine when one or the other is used? For example, the name is used in the button caption and wherever we're deriving a related file name...I would think it should be used in messages about the book, since if the user has given it a name that's probably how he'd like us to refer to it...where should the Title be used?
___
*[src/BloomExe/Book/Book.cs, line 291 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyQMN_92r6Mff9G5zl:-MtyQMN_92r6Mff9G5zm:blhi9ij) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/Book.cs#L291)):*
> ```Smalltalk
> 		public enum LineBreakSpanConversionMode
> 		{
> 			Ignore,
> ```

They won't exactly be ignored, because it still parses the input and then just returns the innerText. So basically they will disappear, typically concatenating two words. Do we have any actual use for this? If so, I'd be inclined to call it ToNothing.
___
*[src/BloomExe/Book/Book.cs, line 304 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyRBDBAlZDQ5oBcwDo:-MtyRBDBAlZDQ5oBcwDp:b-mqd0ez) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/Book.cs#L304)):*
> ```Smalltalk
> 				{
> 					// Shift-enter also inserts a zero-width no-break space, so delete that out
> 					input = input.Replace(((char)65279).ToString(), "");
> ```

I'm dubious about deleting them all...they may have some effect on rendering when not adjacent to something we render as a line-break. For example, they might prevent what is normally an optional line break.
I also wonder whether it is necessary or helpful to do a fancy contains(concat( search for the class. AFAIK, this class is used only for this one purpose and is then the only class and attribute on the element.
So, I'm wondering whether it would be better to just do a regex that will find either form of a span with this class and nothing else, optionally followed by the 65279.
___
*[src/BloomExe/Book/Book.cs, line 317 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyR-icB8qB6iA8f7uf:-MtyR-icB8qB6iA8f7ug:btzpdoj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/Book.cs#L317)):*
> ```Smalltalk
> 					// whether it uses the <span /> form or <span></span> form. (I do see places in the debugger where the data is in <span></span> form.)
> 					var lineBreaks = doc.SafeSelectNodes("//span[contains(concat(' ', normalize-space(@class), ' '), ' bloom-linebreak ')]");
> 					var lineBreakElements = lineBreaks.Cast<XmlElement>();
> ```

I think you need something like ToArray() here so that you aren't modifying the DOM while iterating.
___
*[src/BloomExe/Book/BookData.cs, line 1756 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyTCV8-Wm_jpJsLp_j:-MtyTCV8-Wm_jpJsLp_k:b-ucps06) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/BookData.cs#L1756)):*
> ```Smalltalk
> 		/// <param name="input">Must be HTML-encoded.</param>
> 		/// <returns></returns>
> 		internal static string TextOfInnerHtml(string input)
> ```

Could this use RemoveXmlMarkup? Or both of them use a function in some new utility location? Seems like they should end up exactly consistent in how they handle these linebreak spans and possible zwnbs at least.



_Code quote (from src/BloomExe/Book/Book.cs):_
```Smalltalk
RemoveXmlMarkup
```
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 612 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyU0zaEEQYJfG0JgsI:-MtyU0zaEEQYJfG0JgsJ:b-iod5wg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/CollectionTab/LibraryListView.cs#L612)):*
> ```Smalltalk
> 				var langCodes = _model.CollectionSettings.GetAllLanguageCodes().ToList();
> 
> 				var bestBookName = bookInfo.GetBestTitleForUserDisplay(langCodes);
> ```

Since we're now sharply distinguishing the best Name and best Title, it feels odd to assign a best Title to a variable called bestName. bestLabel? bestCaption? bestButtonText? Similarly titleBestUsedForUserDisplay...maybe you could just reuse the same variable for this? I don't think bestBookName is used again after it is possibly shortened.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1200 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyVV7i5hU9hWmeFrKH:-MtyVV7i5hU9hWmeFrKI:bicik8y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/CollectionTab/LibraryListView.cs#L1200)):*
> ```Smalltalk
> 		}
> 
> 		private void BringBookNameButtonUpToDate(Book.Book book)
> ```

BringBookButtonNameUpToDate? The Name is the thing being brought up to date, not a modifier identifying the button to bring up to date.
Also, wondering if this should have (and preferably share) the full logic you improved above in ImproveAndRefreshBookButtons.
But maybe the idea is that here we should not do anything here that requires LoadBookAndBringItUpToDate, for performance reasons?
And maybe there's a reason not to consider the title here...maybe we want the button label to always be based on the folder name (which will be roughly the title, unless FileNameLocked is true.
Anyway, it would be nice to put these two bits of code that both determine book button captions close together and comment why they are different if in fact they should be.
___
*[src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs, line 496 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MskuY1g4EB0bORw7NaO:-MtyZGWJDFdfO2n4-DJn:bjrnjsf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/542647515c81063e42b018b7897b392ced3d3eb0/src/BloomExe/Publish/BloomLibrary/BloomLibraryUploadControl.cs#L496)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Gordon and I couldn't think of any reason why we need to specifically use TitleBestForUserDisplay over BookInfo.Title, but please let me know if you do!
</blockquote></details>

Why would we use Title rather than Name here? (Or anywhere...if the user has explicitly set a Name by which he wants to refer to this book, why ever call it something else?)


<!-- Sent from Reviewable.io -->

2022-01-24 21:53 UTC, sujeffreyl reviewed
Answered in Flowdock. TitleOrName addresses one of the review comments here and intersects with one of the scenarios that needs to be fixed.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-:-MuD0klcCYA4PzZXWPgn:b-lug0io)* status: all files reviewed, 9 unresolved discussions (waiting on @JohnThomson)

___
*[src/BloomExe/Book/Book.cs, line 225 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyYEHJAcbzctLCLXO2:-MuCc2kzBaaNh_Qd4xN0:byacoyj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/Book.cs#L225)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it possible to comment on this method and/or the title one about any guiding principles that should determine when one or the other is used? For example, the name is used in the button caption and wherever we're deriving a related file name...I would think it should be used in messages about the book, since if the user has given it a name that's probably how he'd like us to refer to it...where should the Title be used?
</blockquote></details>

Ok. Added my thoughts
___
*[src/BloomExe/Book/Book.cs, line 291 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyQMN_92r6Mff9G5zl:-MuCcG_81j9teQ4-15AS:b-q5qzi4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/Book.cs#L291)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

They won't exactly be ignored, because it still parses the input and then just returns the innerText. So basically they will disappear, typically concatenating two words. Do we have any actual use for this? If so, I'd be inclined to call it ToNothing.
</blockquote></details>

Depends on the perspective, which layer you're looking at it from.
Since this isn't actually really being used (we never call it with this value), I decided to just delete it.
___
*[src/BloomExe/Book/Book.cs, line 304 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyRBDBAlZDQ5oBcwDo:-MuCtug36ux7NRe6b1sa:b-mnxdri) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/Book.cs#L304)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm dubious about deleting them all...they may have some effect on rendering when not adjacent to something we render as a line-break. For example, they might prevent what is normally an optional line break.
I also wonder whether it is necessary or helpful to do a fancy contains(concat( search for the class. AFAIK, this class is used only for this one purpose and is then the only class and attribute on the element.
So, I'm wondering whether it would be better to just do a regex that will find either form of a span with this class and nothing else, optionally followed by the 65279.
</blockquote></details>

Ok, I moved it into the same part where we deal with lineBreakSpan.
___
*[src/BloomExe/Book/Book.cs, line 317 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyR-icB8qB6iA8f7uf:-MuCu-na7JYXlJ58jUyH:by42ytp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/Book.cs#L317)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think you need something like ToArray() here so that you aren't modifying the DOM while iterating.
</blockquote></details>

I didn't verify, but I just slapped on a ToArray().
___
*[src/BloomExe/Book/BookData.cs, line 1767 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MsqcTls9-h2osMLyJQT:-MuCutpn7Y0Wv8wPIRPG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/7eafd4ca9e4a25c2ca99316dc099e4f256be4696/src/BloomExe/Book/BookData.cs#L1767)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I agree. The zwsp is just something Bloom puts in to help us put the insertion point where we want it. We may come up with a better way to do that. We shouldn't depend on it.
</blockquote></details>

Done.
___
*[src/BloomExe/Book/BookData.cs, line 1756 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyTCV8-Wm_jpJsLp_j:-MuCuAFB0KHdSvAFdUMH:b3pbnh4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/BookData.cs#L1756)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Could this use RemoveXmlMarkup? Or both of them use a function in some new utility location? Seems like they should end up exactly consistent in how they handle these linebreak spans and possible zwnbs at least.
</blockquote></details>

Yeah, I thought about this topic before and it's one of those minor things that gives you major headaches. Well, the code in the two places is highly similar, but they don't have the same input type (one is XNode, and the other is XmlNode). Since C# isn't duck-typed, it felt like a lot trouble for close to no gain since I'd have to write multiple versions of the function still.
___
*[src/BloomExe/Book/BookData.cs, line 1762 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-Mty6xjh67oeNn0bMlpA:-MuCur5SEz_s6yoeBz9x:b-886gsx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/BookData.cs#L1762)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not sure this character never affects rendering...it might prevent a break where one would normally be allowed? Seems safest only to delete it immediately following the span.
</blockquote></details>

Fixed
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 612 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyU0zaEEQYJfG0JgsI:-MuCvP4f--6ypTZVq_xr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/CollectionTab/LibraryListView.cs#L612)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since we're now sharply distinguishing the best Name and best Title, it feels odd to assign a best Title to a variable called bestName. bestLabel? bestCaption? bestButtonText? Similarly titleBestUsedForUserDisplay...maybe you could just reuse the same variable for this? I don't think bestBookName is used again after it is possibly shortened.
</blockquote></details>

Done.
___
*[src/BloomExe/CollectionTab/LibraryListView.cs, line 1200 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyVV7i5hU9hWmeFrKH:-MuCxs7d-RHrZuMVZGEx:bmp1ymn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/CollectionTab/LibraryListView.cs#L1200)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

BringBookButtonNameUpToDate? The Name is the thing being brought up to date, not a modifier identifying the button to bring up to date.
Also, wondering if this should have (and preferably share) the full logic you improved above in ImproveAndRefreshBookButtons.
But maybe the idea is that here we should not do anything here that requires LoadBookAndBringItUpToDate, for performance reasons?
And maybe there's a reason not to consider the title here...maybe we want the button label to always be based on the folder name (which will be roughly the title, unless FileNameLocked is true.
Anyway, it would be nice to put these two bits of code that both determine book button captions close together and comment why they are different if in fact they should be.
</blockquote></details>

Hmm. I disagree that "The Name is the thing being brought up to date". Th [...]

2022-01-26 14:43 UTC, JohnThomson approved these changes
Looks good to me. One small request for a couple of comments.

> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-:-MuLpqmNESQJmaSHOK-v:b-qvzjc6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

___
*[src/BloomExe/Book/BookData.cs, line 1756 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-MtyTCV8-Wm_jpJsLp_j:-MuLo_0f6QPZD8c2Fn2W:b-lqhu6s) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/37ef6cbffe0e397d55a441583b8235e0a0174ec0/src/BloomExe/Book/BookData.cs#L1756)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Yeah, I thought about this topic before and it's one of those minor things that gives you major headaches. Well, the code in the two places is highly similar, but they don't have the same input type (one is XNode, and the other is XmlNode). Since C# isn't duck-typed, it felt like a lot trouble for close to no gain since I'd have to write multiple versions of the function still.
</blockquote></details>

Would you give them each a comment referencing the other, to help remind us that any changes to one probably should be made to the other also?


<!-- Sent from Reviewable.io -->

2022-01-31 20:17 UTC, JohnThomson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4897#-:-MulmKKb3Xso6PHqc5BA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2022-02-01 16:00 UTC, merged