BL-10388 Improved font UI for Format dialog
BloomBooks/BloomDesktop pull request #4996
Opened 2022-02-22 19:51 UTC by gmartin7

* finally talk getPageFrame() into not complaining
   in VS Code
* wire up new React panel for Format dialog
* add story to Storybook
* get select menu items from fontdata
* get font list to overlay main dialog
* get current font to show correctly
* show font in that font face
* show colored badge to right
* get font change to actually propagate to text
* get popover working
* get a more complete font list, but marked for suitability
* add stories
* add FontDisplayBar as a separate component
* differentiate between fonts in dropdown and selected
* turn input red if unsuitable
* feed hovered font into popover (FontInformationPane)
* don't use disabled on MenuItems; still gray out not-OK
* get info pane formatted correctly
* close popover on any click instead of mouse leave
* add info button and font detail alert
* localize FontInformationPane

2022-02-23 00:09 UTC, andrew-polk requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996)* status: all files reviewed, 10 unresolved discussions (waiting on @gmartin7)

___
*[src/BloomBrowserUI/bloomMaterialUITheme.ts, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYmfmL7ZTosf4TurZw:-MwYmfmL7ZTosf4TurZx:b-6jleoq) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/bloomMaterialUITheme.ts#L51)):*
> ```XML
>         modal: 60001, // match bookEdit/css/bloomDialog.less dialogZindexPlusOne
>         tooltip: 60002 // needs to be higher than modal
>     },
> ```

Setting this in the theme seems very odd to me. 
If this the best way to accomplish this, I think it deserves a comment. It would be helpful if that comment explains why we are not goign to negatively affect other things using this theme.

Also, if we need to keep the values the same here and in `bloomDialog.less`, we should add a comment there, too.
___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 1081 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYoLpj0t5sua9FnBbU:-MwYoLpj0t5sua9FnBbV:bb4ei5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1081)):*
> ```XML
>                         if (!noFormatChange) {
>                             // Getting an outside change of font into here might be tricky
>                             // (if, for instance, the style changes).
> ```

Sorry; I don't understand this comment.
Are you saying that current.fontName won't be updated in the component if it changes?
But it looks like you dealt with that below. 



_Code quote:_
```XML
                            // Getting an outside change of font into here might be tricky
                            // (if, for instance, the style changes).
```
___
*[src/BloomBrowserUI/react_components/fontDisplayBar.tsx, line 9 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYqZ6Q2zTOHEJFZjIV:-MwYqZ6Q2zTOHEJFZjIW:b-8ys6tv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontDisplayBar.tsx#L9)):*
> ```XML
> import CheckCircleIcon from "@material-ui/icons/CheckCircle"; // used for 'font is "ok"'
> import ErrorIcon from "@material-ui/icons/Error"; // used for 'font is "unsuitable"'
> import HelpIcon from "@material-ui/icons/Help"; // used for 'font is "unknown"'
> ```

You can rename these imports here to match the current context. I think that would be an improvement.
___
*[src/BloomBrowserUI/react_components/fontDisplayBar.tsx, line 20 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYq5fVBePf2kSEOhVF:-MwYq5fVBePf2kSEOhVG:b7n79xd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontDisplayBar.tsx#L20)):*
> ```XML
> const FontDisplayBar: React.FunctionComponent<FontDisplayBarProps> = props => {
>     const kGray = "#bbb";
>     const kBloomRed = "#D65649";
> ```

Looks like we should be getting this from colorUtils.ts or bloomMaterialUITheme.ts. Probably the latter since you are already getting some colors from there.



_Code quote:_
```XML
#D65649
```
___
*[src/BloomBrowserUI/react_components/fontDisplayBar.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYqtzwBAutKRkbApXd:-MwYqtzwBAutKRkbApXe:bxdssn5) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontDisplayBar.tsx#L55)):*
> ```XML
>                 <ErrorIcon
>                     htmlColor={props.inDropdownList ? kGray : kBloomRed}
>                     aria-owns={
> ```

I think it is possible to extract all the props besides htmlColor and reuse them with `...commonProps` or similar.



_Code quote:_
```XML
                    aria-owns={
                        props.isPopoverOpen ? "mouse-over-popover" : undefined
                    }
                    aria-haspopup="true"
                    onMouseEnter={event => {
                        if (props.onHover)
                            props.onHover(event, props.fontMetadata);
                    }}
```
___
*[src/BloomBrowserUI/react_components/fontInformationPane.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYszq4-_rwYzTtVCNG:-MwYszq4-_rwYzTtVCNH:b-skss1x) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontInformationPane.tsx#L10)):*
> ```XML
> import { useL10n } from "./l10nHooks";
> 
> const kGray = "#bbb";
> ```

This should be put somewhere to be shared between this and FontDisplayBar



_Code quote:_
```XML
const kGray = "#bbb";
```
___
*[src/BloomBrowserUI/react_components/fontInformationPane.tsx, line 183 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYtu3TCvu4PzjseLza:-MwYtu3TCvu4PzjseLzb:buiwze1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontInformationPane.tsx#L183)):*
> ```XML
>                     {/* LicenseURL */}
>                     {props.metadata.licenseURL && (
>                         <Link
> ```

Seems worth extracting this to a component in this file.

I would even consider extracting the body2 Typography.



_Code quote:_
```XML
                        <Link
                            href={props.metadata.licenseURL}
                            variant="body2"
                            underline="always"
                        >
```
___
*[src/BloomExe/FontProcessing/FontFileFinder.cs, line 138 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYhhxh56U09ASwsgqi:-MwYhhxi8XXonqGFU1xy:bc307pw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomExe/FontProcessing/FontFileFinder.cs#L138)):*
> ```Smalltalk
> 				// Now that our UI needs to give people information about fonts they shouldn't use (BL-10388),
> 				// we need to handle this differently, while still allowing ePUB publishing to note that
> 				// particular fonts are not embeddable.
> ```

Unfortunately, this comment won't make sense outside the context of this change.
Can you modify it to speak to your future self when looking at this code apart from the change?
Or maybe it isn't even needed?

Actually, this isn't changing the behavior, is it? Didn't you just extract the method?



_Code quote:_
```Smalltalk
				// Now that our UI needs to give people information about fonts they shouldn't use (BL-10388),



				// we need to handle this differently, while still allowing ePUB publishing to note that
				// particular fonts are not embeddable.
```
___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 205 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYm6bw2Uh4op2ls5F-:-MwYm6bw2Uh4op2ls5F0:b6y1939) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomExe/FontProcessing/FontMetadata.cs#L205)):*
> ```Smalltalk
> 			// Now for the hard part: setting DeterminedSuitability
> 			// First we declare unsuitable font types that we don't know how to handle (like .ttc)
> 			var fontFileTypesBloomKnows = new string[] { "ttf", "otf", "woff", "woff2" };
> ```

Seems like this should be a shared const with the other place we need to know about this list.
(that might mean making the other place not be a switch)



_Code quote:_
```Smalltalk
var fontFileTypesBloomKnows = new string[] { "ttf", "otf", "woff", "woff2" };
```
___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 207 at r1](https://reviewable.io/reviews/bloombooks/bloomdes [...]

2022-02-23 19:58 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996)* status: all files reviewed, 11 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 207 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYm2_08OCRRNkYJYE5:-Mwc9Sz53nCQEI5WzzlD:b-56yfc7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomExe/FontProcessing/FontMetadata.cs#L207)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably safer to use System.IO.Path.GetExtension()
</blockquote></details>

+1 from me
___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 208 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-Mwc9JiFDiA3ahrLH0wZ:-Mwc9JiFDiA3ahrLH0w_:bq2fpus) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomExe/FontProcessing/FontMetadata.cs#L208)):*
> ```Smalltalk
> 			var fontPath = gtf.FontUri.AbsolutePath;
> 			var fontExtension = fontPath.Substring(fontPath.LastIndexOf('.') + 1);
> 			var bloomKnows = fontFileTypesBloomKnows.Any(
> ```

Optional: FontFileTypesBloomKnows could be a HashSet, and then I think the code to find out if fontExtension is in there would be a little more readable.


<!-- Sent from Reviewable.io -->

2022-02-24 19:30 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996)* status: 7 of 14 files reviewed, 12 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/bloomMaterialUITheme.ts, line 51 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYmfmL7ZTosf4TurZw:-MwcYRR7E1BvykK04dst:bow3evg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/bloomMaterialUITheme.ts#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Setting this in the theme seems very odd to me. 
If this the best way to accomplish this, I think it deserves a comment. It would be helpful if that comment explains why we are not goign to negatively affect other things using this theme.

Also, if we need to keep the values the same here and in `bloomDialog.less`, we should add a comment there, too.
</blockquote></details>

Good. I found a better way in the StyleEditor.less file.
___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 1081 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYoLpj0t5sua9FnBbU:-Mwb_RQW25vNbEp06dkY:b-i8pn5q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1081)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I don't understand this comment.
Are you saying that current.fontName won't be updated in the component if it changes?
But it looks like you dealt with that below. 
</blockquote></details>

Deleted; out-of-date.
___
*[src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts, line 1188 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwhCQLt8HLqWfX9wW1N:-MwhCQLt8HLqWfX9wW1O:b-u0j46b) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4ca25131f435a03b248500b20b02c795f382b35b/src/BloomBrowserUI/bookEdit/StyleEditor/StyleEditor.ts#L1188)):*
> ```XML
>                         $("html").off("click.toolbar");
>                         $("html").on("click.toolbar", event =>
>                             this.closeDialog(event, toolbar)
> ```

I extracted this method thinking I might need to use it to disable/re-enable clicking, but that didn't turn out to be necessary. Left it this way, because it simplifies things.
___
*[src/BloomBrowserUI/react_components/fontDisplayBar.tsx, line 9 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYqZ6Q2zTOHEJFZjIV:-Mwbagb3DgFFlqW0nMuF:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontDisplayBar.tsx#L9)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You can rename these imports here to match the current context. I think that would be an improvement.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/fontDisplayBar.tsx, line 20 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYq5fVBePf2kSEOhVF:-Mwc3CJB7iquJ9kJjgm1:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontDisplayBar.tsx#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like we should be getting this from colorUtils.ts or bloomMaterialUITheme.ts. Probably the latter since you are already getting some colors from there.
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/fontDisplayBar.tsx, line 55 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYqtzwBAutKRkbApXd:-Mwc6AlY9Tvu9LK7AbPe:b-s2ndia) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontDisplayBar.tsx#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it is possible to extract all the props besides htmlColor and reuse them with `...commonProps` or similar.
</blockquote></details>

I managed to pull out the `onMouseEnter` attribute and define an `ariaOwns` constant to use for that attribute. Unfortunately, the 2 `aria` attributes can't be extracted the same way as the method, apparently because they contain hyphens. :( [Later: Ha! Figured it out. The aria attributes just needed quotes around them.]
___
*[src/BloomBrowserUI/react_components/fontInformationPane.tsx, line 10 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYszq4-_rwYzTtVCNG:-MwcHHpT361ilIv0lA_H:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontInformationPane.tsx#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This should be put somewhere to be shared between this and FontDisplayBar
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/react_components/fontInformationPane.tsx, line 183 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYtu3TCvu4PzjseLza:-MwcK2JC6SiuLftzPCN1:bokb1wz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomBrowserUI/react_components/fontInformationPane.tsx#L183)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems worth extracting this to a component in this file.

I would even consider extracting the body2 Typography.
</blockquote></details>

Done. Yep. Well worth it. :)
___
*[src/BloomExe/FontProcessing/FontFileFinder.cs, line 138 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYhhxh56U09ASwsgqi:-MwcgpYGAafz3_-8MbEA:b-dghxwg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomExe/FontProcessing/FontFileFinder.cs#L138)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unfortunately, this comment won't make sense outside the context of this change.
Can you modify it to speak to your future self when looking at this code apart from the change?
Or maybe it isn't even needed?

Actually, this isn't changing the behavior, is it? Didn't you just extract the method?
</blockquote></details>

Comment modified.
Yes it does change behavior! This is the bit that stripped out .ttc and .compositefont files before. Now it only strips them out if we're publishing and lets the user know that those fonts can't be embedded in digital books.
___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 205 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYm6bw2Uh4op2ls5F-:-MwgMv9QCGRQf-IFlCvs:bk7r8h3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomExe/FontProcessing/FontMetadata.cs#L205)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like this should be a shared const with the other place we need to know about this list.
(that might mean making the other place not be a switch)
</blockquote></details>

I couldn't make a const out of the HashSet<string>, but I did make it a static that I can use in both places.
___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 207 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwYm2_08OCRRNkYJYE5:-MwckxK2CStJucvvpLXS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/e318e050d338f4f08b3c086c03c4f2730a08a7d6/src/BloomExe/FontProcessing/FontMetadata.cs#L207)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

+1 from me
</blockquote></details>

Done.
___
*[src/BloomExe/FontProcessing/FontMetadata.cs, line 208 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-Mwc9JiFDiA3ahrLH0wZ:-MwcoaUv4cgv-s9FpmKS:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/ [...]

2022-02-24 20:44 UTC, andrew-polk requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk, @gmartin7, and @sujeffreyl)

___
*[src/BloomBrowserUI/react_components/fontInformationPane.tsx, line 10 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwhR0ObDMgpZwWBYEMk:-MwhR0ObDMgpZwWBYEMl:b9sl2jy) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4ca25131f435a03b248500b20b02c795f382b35b/src/BloomBrowserUI/react_components/fontInformationPane.tsx#L10)):*
> ```XML
> import { useL10n } from "./l10nHooks";
> import { kDisabledControlGray } from "../bloomMaterialUITheme";
> import { string } from "prop-types";
> ```

Is this used? Why wouldn't we be using the primitive `string`?



_Code quote:_
```XML
import { string } from "prop-types";
```


<!-- Sent from Reviewable.io -->

2022-02-24 21:30 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/react_components/fontInformationPane.tsx, line 10 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996#-MwhR0ObDMgpZwWBYEMk:-Mwhd5Bm0c0Fvo7ib9kH:b-lc41mp) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/4ca25131f435a03b248500b20b02c795f382b35b/src/BloomBrowserUI/react_components/fontInformationPane.tsx#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this used? Why wouldn't we be using the primitive `string`?
</blockquote></details>

Unused. Done.


<!-- Sent from Reviewable.io -->

2022-02-24 23:10 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/4996)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)



<!-- Sent from Reviewable.io -->

2022-02-24 23:11 UTC, andrew-polk commented
Approved but not merged bc I think there was a UI question this morning. If not, feel free to merge.

2022-02-25 16:10 UTC, merged