Make video of playing a bloom book (BL-10991)
BloomBooks/BloomDesktop pull request #5020
Opened 2022-03-08 16:51 UTC by JohnThomson

2022-03-08 17:04 UTC, jsubloom requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: 0 of 32 files reviewed, 1 unresolved discussion (waiting on @JohnThomson and @sujeffreyl)

___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 352 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeU2REC-bJlb8zqpIP:-MxeU2REC-bJlb8zqpIQ:b-5jrx2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L352)):*
> ```Smalltalk
> 			_ffmpegProcess.WaitForExit();
> 			Debug.WriteLine("merge errors:");
> 			Debug.WriteLine( _errorData.ToString());
> ```

Could we add some kind of detection and notification if ffmpeg errors out?

Right now if it errors out, when the user clicks Play Recording they will get a NonFatal saying The File could not be found, which isn't super directly informative of the real underlying cause.
As well as, could there be an easy way that the user could get the message from FFmpeg and be able to report it to developers?


<!-- Sent from Reviewable.io -->

2022-03-08 17:09 UTC, andrew-polk requested changes
I haven't finished, but I'm publishing what I have for now.

> Reviewed 15 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-:-MxeVO3x2ZR5STVoKAGw:bdsq6yq)* status: 15 of 32 files reviewed, 5 unresolved discussions (waiting on @andrew-polk, @JohnThomson, and @sujeffreyl)

___
*[src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less, line 7 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeTp1cEIGuRxbOU1yk:-MxeTp1d8gjbRg7fFjIf:b-sotyc2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublish.less#L7)):*
> ```Less
>         padding: 0;
>     }
> }
> ```

Doesn't seem like this belongs in ReaderPublish.less
___
*[src/BloomBrowserUI/react_components/infoBox.tsx, line 31 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeUEBV1UDvSkxcp2GW:-MxeUEBV1UDvSkxcp2GX:b-hgj64e) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/react_components/infoBox.tsx#L31)):*
> ```XML
>         </div>
>     );
> };
> ```

Does this want to live in the same file as WarningBox, NoteBox, and ErrorBox?
___
*[src/BloomExe/BloomExe.csproj, line 1564 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeVB2z83xfZa33xCwD:-MxeVB2z83xfZa33xCwE:b-kf0i9y) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/BloomExe.csproj#L1564)):*
> ```XML
>     <Content Include="Firefox\xul.dll" />
>     <None Include="Resources\video-camera.png" />
>     <None Include="Resources\videoCamera.png" />
> ```

I'm not sure what it means, but I see two things added here, but only one in Resources.resx.
___
*[src/BloomExe/Book/HtmlDom.cs, line 2261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeUy2_9RY_s-ZxNlVE:-MxeUy2_9RY_s-ZxNlVF:b-adyveh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Book/HtmlDom.cs#L2261)):*
> ```Smalltalk
> 			// is how BloomPlayer decides which to skip.
> 			return _dom.SelectSingleNode("//div[contains(@class, 'bloom-interactive-page')]")!= null;
> 		}
> ```

I think the old way would pick up legacy quizzes whereas this won't. (Maybe we don't care?)


<!-- Sent from Reviewable.io -->

2022-03-08 21:07 UTC, andrew-polk requested changes
> Reviewed 17 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: all files reviewed, 22 unresolved discussions (waiting on @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 1026 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfGEJ3D-6BY_VW01KN:-MxfGEJ3D-6BY_VW01KO:ba8qrls) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/DistFiles/localization/en/Bloom.xlf#L1026)):*
> ```XML
>         <note>Used for a link that signifies "Bring up a dialog for sending a report of a problem. We usually want all-caps, unless inappropriate in a particular language"</note>
>       </trans-unit>
>       <!-- 5.3
> ```

Why create them but leave them commented?
___
*[DistFiles/localization/en/Bloom.xlf, line 4036 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfG2Bx3Q0E7It4rlw5:-MxfG2By7KYFnnKwgWgR:brzye7t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/DistFiles/localization/en/Bloom.xlf#L4036)):*
> ```XML
>           that is associated wtih this file type.
>         </source>
>         <note>ID: ublishTab.RecordVideo.WillOpenProgram</note>
> ```

PublishTab
There are several more like this, too



_Code quote:_
```XML
ublishTab
```
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfJmmn8wYJe2o1icQc:-MxfJmmn8wYJe2o1icQd:bhzpo8n) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L1)):*
> ```XML
> /** @jsx jsx **/
> ```

Should these new files be under VideoPublish rather than ReaderPublish?
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfIhNC3k1IB0nQJAvh:-MxfIhNC3k1IB0nQJAvi:b61ysm2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L172)):*
> ```XML
>     const pathToOutputBrowser = inStorybookMode ? "./" : "../../";
>     const usbWorking = useL10n("Publishing", "PublishTab.Common.Publishing");
>     const wifiWorking = useL10n("Publishing", "PublishTab.Common.Publishing");
> ```

These two *Working lines are not used
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfIuAu-0rtFrNWFnc-:-MxfIuAu-0rtFrNWFnc0:b-qqc4a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L202)):*
> ```XML
>     return (
>         <React.Fragment>
>             <BulkBloomPubDialog />
> ```

Why is this here?



_Code quote:_
```XML
BulkBloomPubDialog />
```
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 423 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfJbtL1RcbM3PQ-Cdg:-MxfJbtL1RcbM3PQ-Cdh:b-u7i160) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L423)):*
> ```XML
>                             />
>                         </FormGroup>
>                     )}
> ```

Should we be trying to extract more of these shared pieces?
___
*[src/BloomExe/Publish/PublishView.cs, line 601 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-Mxf8Pml-tWg4v8Cz-d4:-Mxf8Pml-tWg4v8Cz-d5:b24trqe) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/PublishView.cs#L601)):*
> ```Smalltalk
> 					_saveButton.Enabled = _printButton.Enabled = false; // Can't print or save in this mode...wouldn't be obvious what would be saved.
> 					BloomPubMaker.ControlForInvoke = ParentForm; // something created on UI thread that won't go away
> 					ShowHtmlPanel(BloomFileLocator.GetBrowserFile(false, "publish", "ReaderPublish", "RecordVideoWindow.html"));
> ```

VideoPublish?



_Code quote:_
```Smalltalk
ReaderPublish
```
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-Mxf8d382EXEpebWx4QU:-Mxf8d382EXEpebWx4QV:b8yepzn) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L18)):*
> ```Smalltalk
> using SIL.IO;
> 
> namespace Bloom.Publish.Android
> ```

Bloom.Publish.Video?



_Code quote:_
```Smalltalk
Bloom.Publish.Android
```
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-Mxf8hfE0K_AfZvQGH7-:-Mxf8hfE0K_AfZvQGH70:b-ddtt7j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L21)):*
> ```Smalltalk
> {
> 	/// <summary>
> 	/// This class manages a windows that appears when the 'Record' button is pressed in the
> ```

window
same on line below



_Code quote:_
```Smalltalk
windows
```
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 101 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfA8xq8pk4nhzjHnNE:-MxfA8xq8pk4nhzjHnNF:b15nw2u) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L101)):*
> ```Smalltalk
> 			}
> 
> 			Show(mainWindow);
> ```

Seems like we should either have this Show call inside the null check or remove the null check. Or am I missing something?
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfAcr370SR0t7US3-e:-MxfAcr370SR0t7US3-f:bg5g3gg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L135)):*
> ```Smalltalk
> 
> 			// Configure ffmpeg to record the video.
> 			// Todo Linux: gdigrab is Windows-only, we'll need to find something else.
> ```

Should we go ahead and disable the video option for Linux while we're thinking about it?



_Code quote:_
```Smalltalk
// Todo Linux: gdigrab is Windows-only, we'll need to find something else.
```
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 138 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfB2wP2Xp_neU-_hex:-MxfB2wP2Xp_neU-_hey:b9gcvy1) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L138)):*
> ```Smalltalk
> 			// I believe ffmpeg has an option to capture the content of an XWindow.
> 			var args =
> 				"-f gdigrab " // basic command for using a windows window as a video input stream
> ```

This is the third time I see the term "windows" but now it is followed by "window" 
Is this a specific type of object?
If so, maybe the comment could be enhanced a little to clarify?



_Code quote:_
```Smalltalk
windows window
```
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 171 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfBcIJEA11LqI7W40u:-MxfBcIJEA11LqI7W40v:byjlwqx) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L171)):*
> ```Smalltalk
> 				}
> 			};
> 			Debug.WriteLine("args: " + args);
> ```

Let's either comment/remove this or give it context in the log (like `ffmpeg args:`).



_Code quote:_
```Smalltalk
Debug.WriteLine("args: " + args);
```
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 317 at r1](https://reviewable.io/r [...]

2022-03-09 14:15 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: 21 of 33 files reviewed, 22 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[DistFiles/localization/en/Bloom.xlf, line 1026 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfGEJ3D-6BY_VW01KN:-Mxfh0Tu0NlT4PDuZgBu:b21360a) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/DistFiles/localization/en/Bloom.xlf#L1026)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why create them but leave them commented?
</blockquote></details>

We've been not publishing things for new features until they stabilize, so translators don't waste time on them.
___
*[DistFiles/localization/en/Bloom.xlf, line 4036 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfG2Bx3Q0E7It4rlw5:-MxfjMgA9tkE3DOgrP2V:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/DistFiles/localization/en/Bloom.xlf#L4036)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

PublishTab
There are several more like this, too
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfJmmn8wYJe2o1icQc:-Mxfl_NA5uncOplmz27O:b4698ft) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should these new files be under VideoPublish rather than ReaderPublish?
</blockquote></details>

It's a good question. I sort of think of Video publishing as a subset or special case of ReaderPublish since the video is of a reader publication (and thus there's a bit of common code, though not as much as I initially expected). Doesn't feel quite like it deserves a new folder to me, but I can if you want.
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 172 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfIhNC3k1IB0nQJAvh:-Mxfm97K8W7XsZ7oMj1L:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L172)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These two *Working lines are not used
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 202 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfIuAu-0rtFrNWFnc-:-MxfmFr85W9B8f_lyAaM:bozoxvw) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L202)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why is this here?
</blockquote></details>

File began life as a copy of ReaderPublishScreen :-<
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 423 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfJbtL1RcbM3PQ-Cdg:-Mxfmu93BLZKBter9cOb:b5yldbd) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L423)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we be trying to extract more of these shared pieces?
</blockquote></details>

I don't know. It feels a bit much to just copy and paste like I did, not enough for its own file.
___
*[src/BloomExe/BloomExe.csproj, line 1564 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeVB2z83xfZa33xCwD:-MxfrQhbB1Et0zPkolBT:b8pqlc2) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/BloomExe.csproj#L1564)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure what it means, but I see two things added here, but only one in Resources.resx.
</blockquote></details>

I think it's all cleaned up, and now using a better icon JohnH made
___
*[src/BloomExe/Book/HtmlDom.cs, line 2261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeUy2_9RY_s-ZxNlVE:-Mxfs5Iq-TDugbL3Jrxy:b-dbsova) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Book/HtmlDom.cs#L2261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think the old way would pick up legacy quizzes whereas this won't. (Maybe we don't care?)
</blockquote></details>

Maybe I'm just being lazy, but I don't want to slow BloomPlayer down by searching for classes that only occur in an obsolete approach to comprehension questions that I don't think was much used. Xpaths can be slow, especially when doing something like contains on every class attribute. The worst case is that the video shows a few seconds of quiz that we would prefer to have skipped. And I don't see any benefit in having the warning message if we aren't actually going to skip the pages.
___
*[src/BloomExe/Publish/PublishView.cs, line 601 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-Mxf8Pml-tWg4v8Cz-d4:-Mxft7a678P43Z4WSqnT:b-appm6q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/PublishView.cs#L601)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

VideoPublish?
</blockquote></details>

Only if we decide to move it to a new folder...which I'm not yet convinced we do.
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-Mxf8d382EXEpebWx4QU:-MxftLx-7Zz8tR7HBz3q:b-xb6llg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Bloom.Publish.Video?
</blockquote></details>

Again, I think of video publishing as a subset of Android publishing (both ways of looking at BloomPUBs). But I can move the new pieces if you think I should.
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 21 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-Mxf8hfE0K_AfZvQGH7-:-Mxg0WqN6NwB306glH0N:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L21)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

window
same on line below
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 101 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfA8xq8pk4nhzjHnNE:-Mxftlix24VBj4aYvpr1:br2iu88) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like we should either have this Show call inside the null check or remove the null check. Or am I missing something?
</blockquote></details>

The null check is something of a belt-and-braces thing. I can't imagine how this would get called with no Bloom Shell running.  I can remove it if you like. But if somehow there's another client, there's not much harm in going ahead and showing it. It's perfectly fine to call Show(null); the new window just opens at a default position.
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 135 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfA [...]

2022-03-09 16:44 UTC, andrew-polk reviewed
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 423 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfJbtL1RcbM3PQ-Cdg:-MxjYH_T9yOxGOnZzBgh:b-tx61fi) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L423)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't know. It feels a bit much to just copy and paste like I did, not enough for its own file.
</blockquote></details>

Discussed. Sounds ok.
___
*[src/BloomExe/Book/HtmlDom.cs, line 2261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeUy2_9RY_s-ZxNlVE:-MxjYLh3EhptJbuL8X7m:byy7fjz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Book/HtmlDom.cs#L2261)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe I'm just being lazy, but I don't want to slow BloomPlayer down by searching for classes that only occur in an obsolete approach to comprehension questions that I don't think was much used. Xpaths can be slow, especially when doing something like contains on every class attribute. The worst case is that the video shows a few seconds of quiz that we would prefer to have skipped. And I don't see any benefit in having the warning message if we aren't actually going to skip the pages.
</blockquote></details>

Discussed. Decided just to add a comment on the bp side saying why we decided against looking for legacy quizzes to skip.


<!-- Sent from Reviewable.io -->

2022-03-09 17:44 UTC, sujeffreyl reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 352 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeU2REC-bJlb8zqpIP:-MxjldVL-Wg_t_tcfm2j:b-u4jdap) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L352)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've made an attempt.
</blockquote></details>

It works!


<!-- Sent from Reviewable.io -->

2022-03-09 18:00 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: 21 of 33 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[src/BloomExe/Book/HtmlDom.cs, line 2261 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxeUy2_9RY_s-ZxNlVE:-MxjpIMD4cN-Us-mOPgF:b7lgeeh) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Book/HtmlDom.cs#L2261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Discussed. Decided just to add a comment on the bp side saying why we decided against looking for legacy quizzes to skip.
</blockquote></details>

After further thought I decided to change it to recognize the legacy quiz pages and other possibly obsolete ones.
___
*[src/BloomExe/Publish/PublishView.cs, line 601 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-Mxf8Pml-tWg4v8Cz-d4:-MxjpbWxDIzGHwXHsj1g:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/PublishView.cs#L601)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Only if we decide to move it to a new folder...which I'm not yet convinced we do.
</blockquote></details>

done
___
*[src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx, line 1 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxfJmmn8wYJe2o1icQc:-MxjpfS37SFPaKcVmisn:b-jljacf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomBrowserUI/publish/ReaderPublish/RecordVideoWindow.tsx#L1)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's a good question. I sort of think of Video publishing as a subset or special case of ReaderPublish since the video is of a reader publication (and thus there's a bit of common code, though not as much as I initially expected). Doesn't feel quite like it deserves a new folder to me, but I can if you want.
</blockquote></details>

I just called it Video. It's already under a directory called Publish, so I don't see any need to repeat that.
___
*[src/BloomExe/Publish/Android/RecordVideoWindow.cs, line 18 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-Mxf8d382EXEpebWx4QU:-MxjpZQVBNNsb6CF5EUt:bb6un1j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1e6e7c291f8ada9a76d7ffd8b72327289ed95fe4/src/BloomExe/Publish/Android/RecordVideoWindow.cs#L18)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again, I think of video publishing as a subset of Android publishing (both ways of looking at BloomPUBs). But I can move the new pieces if you think I should.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-03-09 18:10 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: 21 of 33 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.html, line 1 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjrqLE17pYQPmUBrHx:-MxjrqLF7tdiAN5vZETc:b-9kqrbr) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/src/BloomBrowserUI/publish/video/RecordVideoWindow.html#L1)):*
> ```HTML
> <!DOCTYPE html>
> ```

This folder is in publish/video, but wouldn't publish/videoPublish or publish/VideoPublish be more parallel with publish/ePUBPublish and publish/ReaderPublish?


<!-- Sent from Reviewable.io -->

2022-03-09 18:12 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: 21 of 33 files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[DistFiles/localization/en/Bloom.xlf, line 4034 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjsUXmCv0zAsIgDWrJ:-MxjsUXmCv0zAsIgDWrK:bb7r32j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/DistFiles/localization/en/Bloom.xlf#L4034)):*
> ```XML
>         <source xml:lang="en">
>           This will open the program on your computer
>           that is associated wtih this file type.
> ```

with



_Code quote:_
```XML
wtih
```
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 341 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjsOeKCtgDVGKvcID5:-MxjsOeKCtgDVGKvcID6:bb7r32j) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L341)):*
> ```XML
>                                 >
>                                     This will open the program on your computer
>                                     that is associated wtih this file type.
> ```

with



_Code quote:_
```XML
wtih
```


<!-- Sent from Reviewable.io -->

2022-03-09 19:44 UTC, sujeffreyl requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: 21 of 33 files reviewed, 8 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[src/BloomExe/Publish/Video/PublishToVideoApi.cs, line 65 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjtRep6iYxKzQ0Jv3l:-MxjtRep6iYxKzQ0Jv3m:b-7rsjms) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/src/BloomExe/Publish/Video/PublishToVideoApi.cs#L65)):*
> ```Smalltalk
> 			}, true, false);
> 
> 			apiHandler.RegisterBooleanEndpointHandlerExact(kApiUrlPart + "hasActivities",
> ```

I pulled the latest, yarn && yarn gulp, cleaned solution:got:
NonFatal error in /bloom/api/publish/video/hasActivities. (FYI, i couldn't get any more detailed error info to load)

(FYI, there is also an error message complaining that font serif will be substitued with Andika New Basic, it could be possible that they're deadlocking or something)
___
*[src/BloomExe/Publish/Video/RecordVideoWindow.cs, line 461 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxkBrhC151f3S8JKEfH:-MxkBrhC151f3S8JKEfI:b2opa2q) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ed4e96b99f74cbec64522b89877b4df5abbbdc18/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L461)):*
> ```Smalltalk
> 					desiredHeight = landscape ? 720 : 1280;
> 					desiredWidth = landscape ? 1280 : 720;
> 					codec = "h.264";
> ```

Not sure if John Hatton has already specified that the UI should specifically be this way, but while I was working in the code, I realized...
We are basing our decisions around what codec the user has selected. However, I think users are way more likely to be familar with mp4, 3gp, and mp3 than with h.264, h.263, and (i guess still mp3). What do you think about either specifying the extension/container (i.e. mp4) instead of, or in addition to, the codec?


<!-- Sent from Reviewable.io -->

2022-03-09 20:22 UTC, andrew-polk approved these changes
> Reviewed 11 of 12 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2022-03-09 20:23 UTC, andrew-polk approved these changes
Approved.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-:-MxkLM264aM8Deqx5Z5F:b-czl1ri)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2022-03-09 20:38 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: all files reviewed, 5 unresolved discussions (waiting on @sujeffreyl)

___
*[DistFiles/localization/en/Bloom.xlf, line 4034 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjsUXmCv0zAsIgDWrJ:-MxkLuEf48oE9mCas5-S:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/DistFiles/localization/en/Bloom.xlf#L4034)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

with
</blockquote></details>

Done.
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.html, line 1 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjrqLE17pYQPmUBrHx:-MxkAHh369FZAx94NgFm:bjch8p7) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/src/BloomBrowserUI/publish/video/RecordVideoWindow.html#L1)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

This folder is in publish/video, but wouldn't publish/videoPublish or publish/VideoPublish be more parallel with publish/ePUBPublish and publish/ReaderPublish?
</blockquote></details>

It would, but I hate to extend a bad idea. I think publish/reader and publish/ePUB would be much better (less redundant) names. If you disagree, well, I suppose it's better to be consistent.
___
*[src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx, line 341 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjsOeKCtgDVGKvcID5:-MxkLzqoBl-koC3aV0Or:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/src/BloomBrowserUI/publish/video/RecordVideoWindow.tsx#L341)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

with
</blockquote></details>

Done.
___
*[src/BloomExe/Publish/Video/PublishToVideoApi.cs, line 65 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjtRep6iYxKzQ0Jv3l:-MxkMMxf6nWW3gguUJ5A:b-9kz9a8) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/src/BloomExe/Publish/Video/PublishToVideoApi.cs#L65)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

I pulled the latest, yarn && yarn gulp, cleaned solution:got:
NonFatal error in /bloom/api/publish/video/hasActivities. (FYI, i couldn't get any more detailed error info to load)

(FYI, there is also an error message complaining that font serif will be substitued with Andika New Basic, it could be possible that they're deadlocking or something)
</blockquote></details>

You can do better than this! Compile error? runtime? repeatable? What steps to reproduce?
___
*[src/BloomExe/Publish/Video/RecordVideoWindow.cs, line 461 at r4](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxkBrhC151f3S8JKEfH:-MxkNwKS4XE5cl3UNEaA:b-o32su3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/ed4e96b99f74cbec64522b89877b4df5abbbdc18/src/BloomExe/Publish/Video/RecordVideoWindow.cs#L461)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Not sure if John Hatton has already specified that the UI should specifically be this way, but while I was working in the code, I realized...
We are basing our decisions around what codec the user has selected. However, I think users are way more likely to be familar with mp4, 3gp, and mp3 than with h.264, h.263, and (i guess still mp3). What do you think about either specifying the extension/container (i.e. mp4) instead of, or in addition to, the codec?
</blockquote></details>

I'm not understanding this. I'm quite closely following JohnH's design at https://www.figma.com/file/Lq8CwuPq7GDfolDkI7y0OuWJ/Publish?node-id=196%3A4242. The option labels already say things like "Facebook...1280x720...MP4 H.264" so I think we're doing exactly what you're suggesting: giving both (in fact all three) ways the user might recognize a particular format, from the typical use (Facebook) through the container (MP4) to the semi-technical H.264.


<!-- Sent from Reviewable.io -->

2022-03-09 20:42 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: 32 of 33 files reviewed, 5 unresolved discussions (waiting on @andrew-polk and @sujeffreyl)

___
*[src/BloomExe/Publish/Video/PublishToVideoApi.cs, line 65 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020#-MxjtRep6iYxKzQ0Jv3l:-MxkPQo-EUYE8yCioVF_:bkjj1ol) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/16cb70cfef255847db38f8270be3da77c9320cd7/src/BloomExe/Publish/Video/PublishToVideoApi.cs#L65)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

You can do better than this! Compile error? runtime? repeatable? What steps to reproduce?
</blockquote></details>

I wonder if things have gotten into a bad state? I've been doing my usual thing and force-pushing amended commits on the PR, but that's somewhat risky if the commit that is being overwritten has been pulled elsewhere. Maybe the result has your repo in a weird state?


<!-- Sent from Reviewable.io -->

2022-03-09 20:45 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5020)* status: all files reviewed, 5 unresolved discussions (waiting on @sujeffreyl)



<!-- Sent from Reviewable.io -->

2022-03-09 20:48 UTC, merged