Minor refactoring
BloomBooks/BloomDesktop pull request #5060
Opened 2022-03-25 20:20 UTC by gmartin7

* removed more obsolete preview stuff
   (including 3 webpack bundles)

2022-03-25 20:45 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[src/BloomExe/Book/Book.cs, line 2665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060#-Mz1oiXF7oKyiSQCGHJF:-Mz1oiXF7oKyiSQCGHJG:b2hha7k) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bc7ac0a9239342ab82c05a2edce3a506006369fb/src/BloomExe/Book/Book.cs#L2665)):*
> ```Smalltalk
> 		internal void AddPreviewJavascript(HtmlDom dom)
> 		{
> 			dom.AddJavascriptFile("commonBundle.js".ToLocalhost());
> ```

@johnthomson Does `commonBundle.js` have anything to do with making stuff readonly? Or is that comment out-of-date?


<!-- Sent from Reviewable.io -->

2022-03-25 20:50 UTC, andrew-polk approved these changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)



<!-- Sent from Reviewable.io -->

2022-03-28 17:59 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Book/Book.cs, line 2665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060#-Mz1oiXF7oKyiSQCGHJF:-MzGfT_uA90fIbCQ3ecE:b-d4f4lg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bc7ac0a9239342ab82c05a2edce3a506006369fb/src/BloomExe/Book/Book.cs#L2665)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

@johnthomson Does `commonBundle.js` have anything to do with making stuff readonly? Or is that comment out-of-date?
</blockquote></details>

Actually, I don't think we need javascript inserted from C# anymore to get previews to work. It all seems to work without it!


<!-- Sent from Reviewable.io -->

2022-03-28 18:41 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomExe/Book/Book.cs, line 2665 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060#-Mz1oiXF7oKyiSQCGHJF:-MzGp5Z_9g9dvegZYeUL:bf5nxxa) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/bc7ac0a9239342ab82c05a2edce3a506006369fb/src/BloomExe/Book/Book.cs#L2665)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Actually, I don't think we need javascript inserted from C# anymore to get previews to work. It all seems to work without it!
</blockquote></details>

NVM! Both `js` files are necessary to keep the preview from being editable. I was really surprised to find that was the case, since the previews are in React now.


<!-- Sent from Reviewable.io -->

2022-03-28 18:47 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[src/BloomBrowserUI/webpack.common.js, line 86 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060#-MzGqKXV-7dZWyqU3F3P:-MzGqKXV-7dZWyqU3F3Q:bdey398) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c3365ac23dc98e9a785c70ec3c1b48a118eec58b/src/BloomBrowserUI/webpack.common.js#L86)):*
> ```JavaScript
>         // to NOT allow editing.
>         legacyBookPreviewBundle:
>             "./collectionsTab/collectionsTabBookPane/bookPreview.ts"
> ```

This `legacy` one is the same path as the non-legacy one you removed above.
Maybe I'm missing something, but don't we want to get rid of this one, keep the other one, and change Book.cs to add the non-legacy one?


<!-- Sent from Reviewable.io -->

2022-03-28 19:12 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[src/BloomBrowserUI/webpack.common.js, line 86 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060#-MzGqKXV-7dZWyqU3F3P:-MzGsHsj33M403xlxQ9o:b-tge45c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c3365ac23dc98e9a785c70ec3c1b48a118eec58b/src/BloomBrowserUI/webpack.common.js#L86)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This `legacy` one is the same path as the non-legacy one you removed above.
Maybe I'm missing something, but don't we want to get rid of this one, keep the other one, and change Book.cs to add the non-legacy one?
</blockquote></details>

Ah. So someone created 2 bundles for the same thing! I should have noticed that. I guess that's a logical enough change.


<!-- Sent from Reviewable.io -->

2022-03-28 19:14 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5060)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2022-03-28 19:14 UTC, merged