BL-11406 color picker fixes
BloomBooks/BloomDesktop pull request #5374
Opened 2022-09-02 20:22 UTC by gmartin7

* fix Android cover color detection regex to handle
   lowercase 'div' rules from templates
* keep black color for templates with preserveCoverColor
   (Comics and Video)

2022-09-02 20:47 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NAzwdXt2R_hLX86CpKs:-NAzwdXuE0PfRSVVUEfc:b56920v) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1da9dbd8dc4a3c5083ffdd1fd8634c31a3b286df/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L59)):*
> ```XML
> 
>     useEffect(() => {
>         setInternalColor(hasPreserveCoverColor ? "black" : bookCoverColor);
> ```

I don't think we want to assume a preserved cover color will always be black.
Shouldn't the question to the server be to ask which color rather than just a boolean?

But I'm not sure about the approach in general. 
Shouldn't the design be to make the cover color black unless the user changes it for these templates?
I'm looking now to see what previous behavior was.


<!-- Sent from Reviewable.io -->

2022-09-02 20:50 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NAzwdXt2R_hLX86CpKs:-NAzxiPm-U-GZpamR6Lo:b-qgmioo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1da9dbd8dc4a3c5083ffdd1fd8634c31a3b286df/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L59)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think we want to assume a preserved cover color will always be black.
Shouldn't the question to the server be to ask which color rather than just a boolean?

But I'm not sure about the approach in general. 
Shouldn't the design be to make the cover color black unless the user changes it for these templates?
I'm looking now to see what previous behavior was.
</blockquote></details>

Ok, 5.3 has the same bug you're fixing: the control is white and then changing the color doesn't change the book.
So disabling the control until we decide we want to allow the color to be changed is fine.

But I don't think we should assume black just because all examples of preserved colors currently are.


<!-- Sent from Reviewable.io -->

2022-09-06 14:03 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NAzwdXt2R_hLX86CpKs:-NBI603N6HuR8wpmkwyv:bctojno) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1da9dbd8dc4a3c5083ffdd1fd8634c31a3b286df/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L59)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, 5.3 has the same bug you're fixing: the control is white and then changing the color doesn't change the book.
So disabling the control until we decide we want to allow the color to be changed is fine.

But I don't think we should assume black just because all examples of preserved colors currently are.
</blockquote></details>

I can work on this Thursday. There's a C# regex that's not working because of comments in the color rule. I've started on a fix, but didn't get it finished.


<!-- Sent from Reviewable.io -->

2022-09-08 19:35 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx` line 59 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NAzwdXt2R_hLX86CpKs:-NBTaQtx975fShvuRalX:bsewx9z) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/1da9dbd8dc4a3c5083ffdd1fd8634c31a3b286df/src/BloomBrowserUI/publish/ReaderPublish/CoverColorGroup.tsx#L59)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

I can work on this Thursday. There's a C# regex that's not working because of comments in the color rule. I've started on a fix, but didn't get it finished.
</blockquote></details>

Finished.


<!-- Sent from Reviewable.io -->

2022-09-08 20:42 UTC, andrew-polk requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/Book/Book.cs` line 2684 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NBToeA1D2zbJSWaYpwy:-NBToeA1D2zbJSWaYpwz:b7jfi5c) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b5b095825d691e2f332d6fcde8f346910a409805/src/BloomExe/Book/Book.cs#L2684)):*
> ```Smalltalk
> 							}
> 						}
> 					}
> ```

Looks like if you just replace the original regex with 
`var match = new Regex(@"(DIV|div).bloom-page.coverColor\s*{.*?background-color:\s*(#[0-9a-fA-F]*|[a-z]*)", RegexOptions.Singleline)`
it makes your tests pass.


<!-- Sent from Reviewable.io -->

2022-09-08 21:59 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/Book.cs` line 2684 at r2](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NBToeA1D2zbJSWaYpwy:-NBU5qd18ISFaeb5XGKl:b-3pklcb) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/b5b095825d691e2f332d6fcde8f346910a409805/src/BloomExe/Book/Book.cs#L2684)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like if you just replace the original regex with 
`var match = new Regex(@"(DIV|div).bloom-page.coverColor\s*{.*?background-color:\s*(#[0-9a-fA-F]*|[a-z]*)", RegexOptions.Singleline)`
it makes your tests pass.
</blockquote></details>

Thanks! I didn't think there could be a regex to dig through all that other stuff and come up with the right answers. I'd like to get together and process a couple of bits of it some time.
In any case, here's the updated code.


<!-- Sent from Reviewable.io -->

2022-09-09 16:31 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomExe/Book/Book.cs` line 2664 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NBY4nve2uGHdxEddmr3:-NBY4nve2uGHdxEddmr4:brk6s88) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c4936947444c8fefe4dfa5d8fa6c64254c3cd2b1/src/BloomExe/Book/Book.cs#L2664)):*
> ```Smalltalk
> 				if (match.Success)
> 				{
> 					return match.Groups[2].Value;
> ```

Hm. I'm surprised this works getting the 2th group. Should it still be the 1th?


<!-- Sent from Reviewable.io -->

2022-09-09 16:32 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/Book.cs` line 2664 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NBY4nve2uGHdxEddmr3:-NBY533oBWFfSCG0qiSU:b-gw97gv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c4936947444c8fefe4dfa5d8fa6c64254c3cd2b1/src/BloomExe/Book/Book.cs#L2664)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. I'm surprised this works getting the 2th group. Should it still be the 1th?
</blockquote></details>

When we added the (DIV|div), that grabbed the 1st group.


<!-- Sent from Reviewable.io -->

2022-09-09 16:33 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[`src/BloomExe/Book/Book.cs` line 2664 at r3](https://reviewable.io/reviews/bloombooks/bloomdesktop/5374#-NBY4nve2uGHdxEddmr3:-NBY5P4-AO3aup0T8TRT:bbnqyo) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/c4936947444c8fefe4dfa5d8fa6c64254c3cd2b1/src/BloomExe/Book/Book.cs#L2664)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

When we added the (DIV|div), that grabbed the 1st group.
</blockquote></details>

Yes, of course.


<!-- Sent from Reviewable.io -->

2022-09-09 16:33 UTC, merged