Implement export and import of audio (BL-11505)
BloomBooks/BloomDesktop pull request #5384
Opened 2022-09-12 20:54 UTC by JohnThomson

2022-09-14 18:09 UTC, andrew-polk requested changes
Not done reviewing but publishing what I have so far...

> Reviewed 21 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-:-NBxBDmA2BT2wD5gEND_:b-heyzxy)* status: 21 of 23 files reviewed, 11 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomBrowserUI/spreadsheet/spreadsheetBundleRoot.ts` line 17 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBwyrVz-oNz--wSK9by:-NBwyrW-3Myt7W9BXBru:b-lvun16) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomBrowserUI/spreadsheet/spreadsheetBundleRoot.ts#L17)):*
> ```XML
>     return sentences.join("\n");
> }
> export { theOneLibSynphony };
> ```

As far as I can tell, this export isn't used anywhere.
If you remove it, you should update the comment above about using it.



_Code quote:_
```XML
export { theOneLibSynphony };
```
___
*[`src/BloomExe/Spreadsheet/InternalSpreadsheet.cs` line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx-7EIBTofeSEYCY23:-NBx-7EIBTofeSEYCY24:bdkhc7r) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L67)):*
> ```Smalltalk
> 					if (!content.EndsWith("]"))
> 						continue;
> 					if (content.Contains("audio"))
> ```

Better/safer to check for `StartsWith("[audio")`?
___
*[`src/BloomExe/Spreadsheet/SpreadsheetApi.cs` line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBwzeWcBQSZdlJNoOoi:-NBwzeWd74nwX9aQMb8u:b-72455t) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetApi.cs#L115)):*
> ```Smalltalk
> 				var importer = new SpreadsheetImporter(_webSocketServer, book, Path.GetDirectoryName(inputFilepath));
> 				var shell = Application.OpenForms.Cast<Form>().Where(x => x is Shell).FirstOrDefault();
> 				importer.ControlForInvoke = shell;
> ```

Use `Shell.GetShellOrOtherOpenForm()` instead?
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 280 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx32xOAQtgyedbAZlI:-NBx32xP19_Q_YMEClLj:bae9tv3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L280)):*
> ```Smalltalk
> 		{
> 			var id = elt.Attributes["id"]?.Value??"";
> 			if (_outputFolder != null)
> ```

Is this just a guard for an unexpected case? 
If yes, should we at least have a  Debug.Assert?
If no, could you add a comment explaining the case?
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx3ffY47uQVi7BMHAs:-NBx3ffY47uQVi7BMHAt:b-rr4nlj) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L291)):*
> ```Smalltalk
> 					// Somehow two blocks in the document have the same IDs. Maybe we should do a warning?
> 					// Anyway, it pretty much has to be the same file, so just leave it.
> 					if (!File.Exists(dest))
> ```

Though I don't think there is any difference at this point, you might as well use `RobustFile.Exists` here and a few lines above.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 360 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx-u2MA0t6Sj1vddfx:-NBx-u2MA0t6Sj1vddfy:bb7phvt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L360)):*
> ```Smalltalk
> 		}
> 
> 		private int GetOrAddColumnForAudioAlignnemt(string langCode)
> ```

typo



_Code quote:_
```Smalltalk
GetOrAddColumnForAudioAlignnemt
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 813 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxAh76EZ8KhTGfZCD4:-NBxAh76EZ8KhTGfZCD5:b-ic7hl) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L813)):*
> ```Smalltalk
> 			}
> 		}
> ```

Note to self:
I have not reviewed methods `AddAudio` or `AddAudioFile`.
But I have reviewed the rest of this file.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1057 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxAOkp0Vv6viTJ1hYF:-NBxAOkp0Vv6viTJ1hYG:bpp8q2o) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1057)):*
> ```Smalltalk
> 			}
> 			var destFile = SanitizeXHmlId(BookStorage.SanitizeNameForFileSystem(Path.GetFileName(audioFile)));
> 			var id = Path.GetFileNameWithoutExtension(destFile);
> ```

I would be somewhat surprised if we don't assume somewhere that audio file names or ids or both are guids (with a possible prepended i).

Have you explored that?
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1108 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx4Z_A3-32nSJXQeIB:-NBx4Z_A3-32nSJXQeIC:b-ln6ptf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1108)):*
> ```Smalltalk
> 		}
> 
> 		internal static string SanitizeXHmlId(string id)
> ```

`SanitizeXmlId`?



_Code quote:_
```Smalltalk
SanitizeXHmlId
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1121 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxAz14AEnQeCNnMXps:-NBxAz14AEnQeCNnMXpt:bcg4xyz) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1121)):*
> ```Smalltalk
> 			if (id.Length > 1)
> 				return id;
> 			return "empty"; // arbitrary, and likely a duplicate, but at least valid.
> ```

I think I would choose something which doesn't imply a meaning (e.g. that this audio file is empty). How about `audioId`?



_Code quote:_
```Smalltalk
empty
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1126 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx9C-eC2h1K--vREVF:-NBx9C-eC2h1K--vREVG:b-1sszec) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1126)):*
> ```Smalltalk
> 		private double GetDuration(string path)
> 		{
> 			// Review: is this library windows-only? If so what do we do on Linux?
> ```

Based on the other place we use this in code, it must be. So we better `ifdef` it and its import lest we break the Linux build right off the bat.

@stephenmcconnel thoughts on what we should do here?
Is import/export currently working on Linux?

@johnthomson what happens if we don't have a correct duration value?



_Code quote:_
```Smalltalk
windows-only
```


<!-- Sent from Reviewable.io -->

2022-09-14 21:55 UTC, andrew-polk requested changes
Completed initial review.

> Reviewed 2 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-:-NBxzrYS1L9vtExXEkom:b-2d6usg)* status: all files reviewed, 23 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 815 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxmBOD7N8T-tvYz_OB:-NBxmBOD7N8T-tvYz_OC:btbi346) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L815)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// Add any audio from the row to the editable.
> ```

Add any audio from the row to the editable for the given lang.



_Code quote:_
```Smalltalk
Add any audio from the row to the editable.
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 819 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxm-7_A3R8pRuhbsD7:-NBxm-7_A3R8pRuhbsD8:b-7l3jna) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L819)):*
> ```Smalltalk
> 		/// (and possibly one [audio alignments lg]), and the row has data in the cell
> 		/// that corresponds to the [audio lg] column.
> 		/// If it has, we next determine whether the group is recorded in text mode.
> ```

TextBox mode



_Code quote:_
```Smalltalk
text mode
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 822 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxltom4LSOHcVbADc8:-NBxltom4LSOHcVbADc9:bb7phvt) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L822)):*
> ```Smalltalk
> 		/// This is true if the relevant [audio alignments lg] cell is non-empty.
> 		/// (Report an error if this is true and there is more than one recording file.)
> 		/// (Report an error if any of any audio file does not exist or has the wrong
> ```

typo



_Code quote:_
```Smalltalk
Report an error if any of any audio file does not exist
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 826 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxmT1zAIkPjs7JPZQF:-NBxmT1zAIkPjs7JPZQG:b-7l3jna) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L826)):*
> ```Smalltalk
> 		/// currently, though our code for getting the duration might throw.)
> 		/// We will set data-audiorecordingmode to TextBox or Sentence accordingly,
> 		/// and in text-box mode, we will
> ```

TextBox mode



_Code quote:_
```Smalltalk
text-box mode
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 875 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxqXPq7ulVZWsZM7ZL:-NBxqXPq7ulVZWsZM7ZM:bv7j7p4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L875)):*
> ```Smalltalk
> 			// after we make some sanity checks. The immediate goal is to count sentences that could
> 			// have recording or alignment information.
> 			var paraSentences = new List<Tuple<XmlElement, string[]>>();
> ```

I would strongly consider using `fragment` anywhere we haven't verified something is a sentence throughout this method.



_Code quote:_
```Smalltalk
paraSentences
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 914 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxoUAbCT4xUbwRBqOL:-NBxoUAbCT4xUbwRBqOM:brdd6sf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L914)):*
> ```Smalltalk
> 				var audioFile = audioFilesList;
> 				var durationStr = AddAudioFile(editable, audioFile);
> 				var duration = double.Parse(durationStr);
> ```

Does this parse need to use invariant culture?
Same below.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 949 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxqzssC6bfJ-WDYAgY:-NBxqzssC6bfJ-WDYAgZ:b-veu6p3) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L949)):*
> ```Smalltalk
> 				if (sentenceCount == alignments.Length)
> 				{
> 					// treat as split textbox (although just possibly it was originally a single sentence
> ```

TextBox



_Code quote:_
```Smalltalk
textbox
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 950 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxr0QO7c64G9ppwyPu:-NBxr0QO7c64G9ppwyPv:b-7l3jna) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L950)):*
> ```Smalltalk
> 				{
> 					// treat as split textbox (although just possibly it was originally a single sentence
> 					// recorded in text box mode and never split)
> ```

TextBox mode



_Code quote:_
```Smalltalk
text box mode
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 959 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxr8RzEteBRK4QxkT6:-NBxr8RzEteBRK4QxkT7:b-uwemwv) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L959)):*
> ```Smalltalk
> 
> 						para.InnerText = "";
> 						foreach (var sentence1 in sentences)
> ```

`fragment in fragments`?

same in Sentence mode processing below



_Code quote:_
```Smalltalk
sentence1 in sentences
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 961 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxrBUl7f2SisyGGA9u:-NBxrBUm7MCw4Bn5iIV_:bfnv29w) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L961)):*
> ```Smalltalk
> 						foreach (var sentence1 in sentences)
> 						{
> 							var sentence = sentence1.Substring(1);
> ```

`var fragmentText = fragment.Substring(1);`?

same in Sentence mode processing below



_Code quote:_
```Smalltalk
var sentence = sentence1.Substring(1);
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 987 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxrqKdAjh6tqZVxXnt:-NBxrqKdAjh6tqZVxXnu:b-7l3jna) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L987)):*
> ```Smalltalk
> 					HtmlDom.AddClass(editable, "bloom-postAudioSplit");
> 				}
> 				// If there is just one alignment, but not just one sentence, we're in textbox mode, unsplit.
> ```

TextBox mode



_Code quote:_
```Smalltalk
textbox mode
```
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 999 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxp5Cp7WPVlWrSqiQN:-NBxp5Cp7WPVlWrSqiQO:bkl7463) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L999)):*
> ```Smalltalk
> 			else
> 			{
> 				// Sentence mode
> ```

Do we need to ensure the editable doesn't have `audio-sentence` class?
Are there other things we need to ensure get "undone" if the import is used to switch between TextBox and Sentence mode?

Do we need such unit tests?
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1008 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxsmoH15ewsUvOuAJ4:-NBxsmoH15ewsUvOuAJ5:biddr88) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1008)):*
> ```Smalltalk
> 				}
> 				editable.S [...]

2022-09-16 23:05 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384)* status: 17 of 23 files reviewed, 21 unresolved discussions (waiting on @andrew-polk and @StephenMcConnel)

___
*[`src/BloomBrowserUI/spreadsheet/spreadsheetBundleRoot.ts` line 17 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBwyrVz-oNz--wSK9by:-NC789fk2JhFJ4FqTNO6:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomBrowserUI/spreadsheet/spreadsheetBundleRoot.ts#L17)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As far as I can tell, this export isn't used anywhere.
If you remove it, you should update the comment above about using it.
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/InternalSpreadsheet.cs` line 67 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx-7EIBTofeSEYCY23:-NC78ML15UzBNRUejjXJ:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/InternalSpreadsheet.cs#L67)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Better/safer to check for `StartsWith("[audio")`?
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetApi.cs` line 115 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBwzeWcBQSZdlJNoOoi:-NC78Z5NBqCpzC6-09kd:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetApi.cs#L115)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Use `Shell.GetShellOrOtherOpenForm()` instead?
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 280 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx32xOAQtgyedbAZlI:-NC796fA-lypDhDWH6Vj:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L280)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this just a guard for an unexpected case? 
If yes, should we at least have a  Debug.Assert?
If no, could you add a comment explaining the case?
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 291 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx3ffY47uQVi7BMHAs:-NC79GUI8uCtE48JuVmr:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L291)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Though I don't think there is any difference at this point, you might as well use `RobustFile.Exists` here and a few lines above.
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetExporter.cs` line 360 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx-u2MA0t6Sj1vddfx:-NC79QvaBKDHR5yRczJ7:bb7f2mf) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetExporter.cs#L360)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

typo
</blockquote></details>

done
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 815 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxmBOD7N8T-tvYz_OB:-NC79nWEEyTC1qMa2gJK:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L815)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Add any audio from the row to the editable for the given lang.
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 819 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxm-7_A3R8pRuhbsD7:-NC79tbb0JF0LljOZgTG:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L819)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

TextBox mode
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 826 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxmT1zAIkPjs7JPZQF:-NC7A8VM81Wdy0BDdvsu:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L826)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

TextBox mode
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 875 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxqXPq7ulVZWsZM7ZL:-NC7B8xM8DxHsxKZdyZm:b-moguso) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L875)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would strongly consider using `fragment` anywhere we haven't verified something is a sentence throughout this method.
</blockquote></details>

I think I got them all. Good idea.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 914 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxoUAbCT4xUbwRBqOL:-NC7CLpi9Ndokbq-3DYw:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L914)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this parse need to use invariant culture?
Same below.
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 949 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxqzssC6bfJ-WDYAgY:-NC7CS-_BgmlwAOxgFym:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L949)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

TextBox
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 950 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxr0QO7c64G9ppwyPu:-NC7CXzACu66XYmxRG7_:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L950)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

TextBox mode
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 959 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxr8RzEteBRK4QxkT6:-NC7C_f_CjtVG9DHczX8:b-896fix) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L959)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`fragment in fragments`?

same in Sentence mode processing below
</blockquote></details>

Done.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 961 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxrBUl7f2SisyGGA9u:-NC7CrgPD1DMP7TenGh5:b-c1ovlc) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L961)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`var fragmentText = fragment.Substring(1);`?

same in Sentence mode processing below
</blockquote></details>

I think I had an even better idea.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporte [...]

2022-09-17 00:02 UTC, andrew-polk requested changes
> Reviewed 5 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1057 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxAOkp0Vv6viTJ1hYF:-NC7jpzgEP8iZEwpdulh:b-xuu9po) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1057)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I would be more surprised if we did. What is there about the ID being a guid that we could take advantage of? Except perhaps being able to assume that it's a valid filename and XML ID...but we're checking for those things here.
I can't really think how to explore it except for reading over all the audio-related code. So I suppose there's some risk involved. OTOH, guids are ugly IDs that are very hard for humans to process...if there's a possibility of using something meaningful, I'm reluctant to give it up.
</blockquote></details>

I have a vague recollection of having to change the PhotoStory3 converter to change the files to be guids.
I'll explore that project on Monday to see if I can find something.
___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1126 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBx9C-eC2h1K--vREVF:-NC7jdnX3qtNBL5LAzHv:bn0j8f4) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1126)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I created a card to follow up on this (https://issues.bloomlibrary.org/youtrack/issue/BL-11533/SS-Import-Fix-audio-import-for-Linux).


<!-- Sent from Reviewable.io -->

2022-09-19 17:04 UTC, andrew-polk approved these changes
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[`src/BloomExe/Spreadsheet/SpreadsheetImporter.cs` line 1057 at r1](https://reviewable.io/reviews/bloombooks/bloomdesktop/5384#-NBxAOkp0Vv6viTJ1hYF:-NCLgkli4WOICfHalPRU:bq78vcg) ([raw file](https://github.com/bloombooks/bloomdesktop/blob/08ae69494f3bc5471b32e8094d52b65f96e6e1f1/src/BloomExe/Spreadsheet/SpreadsheetImporter.cs#L1057)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I have a vague recollection of having to change the PhotoStory3 converter to change the files to be guids.
I'll explore that project on Monday to see if I can find something.
</blockquote></details>

Ok, I'm wrong. We don't convert the narration file names to guids.


<!-- Sent from Reviewable.io -->

2022-09-19 17:04 UTC, merged