BL-11539 AddPage dialog -> React
BloomBooks/BloomDesktop pull request #5612
Opened 2023-02-02 18:46 UTC by gmartin7

* get basic React dialog to appear
* get template urls loaded into React
* moved CSS from .less file to emotion
* get Storybook working
* upgrade files to latest emotion reference
* get stories working reliably
* dialog loads multiple groups
* fix title swapping by recreating dialog container
   each time
* filter out custom page if for change layout
* remove unused property on c# side
* pull out thumb image source function to page group
* get custom template images working
* add blue overlay
* selecting a page highlights it, activates the preview, and
   shows the appropriate image
* adjustments to size/layout of dialog
* fixed colors of title bar and dialog background
* move utility counting functions up to PageChooserDialog
* simplify open/close and submit button handling
* fix Learn More links to open external browser
* added enterprise-only page markers
* tweaked spacing and font-size
* fix initial double-selecting of 1st and default
* delete old files
* add error handling/reporting in case of bad template
   file or no template pages in file
* get double-click handler working

2023-02-02 22:41 UTC, gmartin7 reviewed
I added a 2nd commit that limits the dialog dragging to the main edit pane. Otherwise it can be dragged under the page list on the left or just clear off the screen! It's a separate commit in case it's not wanted.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-:-NNJHLUNBW_5mareZ_Q6:b-4hetzq)* status: 0 of 28 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-03 17:14 UTC, gmartin7 reviewed
OK, I just repushed the PR with a new 2nd commit for upgrading to MUI 5. The old 2nd commit (see above) is now the 3rd commit. :)

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-:-NNNGE_CDqgq5SPd2NHA:b-yhbe4q)* status: 0 of 28 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-02-03 19:47 UTC, JohnThomson requested changes
I've made a lot of comments, but it's a big piece of work! Thanks for taking it on. Don't regard my suggestions as gospel truth...I may well have missed a good reason for things to be the way they are, so feel free to push back. Even if a suggestion is doable, it may be more work than it is worth.

> Reviewed 21 of 28 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-:-NNJYcUvDwpQ7vWafgGf:b-m9jkps)* status: all files reviewed, 25 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJQmluBCFC2LHlz1JN:-NNJQmlvA_bkQrmm2VAj:b4ckeio) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L23)):*
> ```XML
>     orientation: string;
>     forChooseLayout: boolean;
>     onThumbSelect?: React.MouseEventHandler<HTMLDivElement>;
> ```

Thumbnail? or Page? Thumb by itself suggests the draggable part of a scroll bar. (Coming back to this: later I suggest that you want a single consistent name, probably TemplatePage, for the things the use can choose in the dialog.)
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 74 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJSF6dBmYz1UC_7sRF:-NNJSF6dBmYz1UC_7sRG:b6fass6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L74)):*
> ```XML
>                     result.data,
>                     "text/html"
>                 ).body;
> ```

We usually use JSON to pass complex data across Bloom's API. Why is this passed as HTML? Deserves a comment, at least.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 89 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJT4gYBMhLbA_AjTmK:-NNJT4gYBMhLbA_AjTmL:b-ce83qs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L89)):*
> ```XML
>                 // Don't add a group for books that don't have template pages; just move on.
>                 // (This will always be true for a newly created template.)
>                 if (originalPages.length === 0) {
> ```

Why are we testing originalPages, rather than the filtered list we are actually going to show? Do we really want a heading with no pages if none of them is 'extra'?
(For that matter: do we use the non-extra pages for anything? If not, why not filter them out on the sending side of the API? In fact, we could make the sending side responsible to not send books that don't have at least one addable page at all.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 111 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJSfApBi6_WCqTdcZD:-NNJSfApBi6_WCqTdcZE:bceoqpm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L111)):*
> ```XML
>                         (elem: HTMLElement) =>
>                             elem.id &&
>                             elem.getAttribute("data-page") === "extra"
> ```

Might deserve a comment? Why are the pages the user can add tagged "extra"?
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 158 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJUIqdDIJcjRWKaww8:-NNJUIqdDIJcjRWKaww9:b-ly6gad) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L158)):*
> ```XML
>         ? pageData.map((currentPageDiv: HTMLElement, index) => {
>               // Process each page and create a gridItem div containing a thumb and data and an overlay.
>               if (currentPageDiv.getAttribute("data-page") === "singleton")
> ```

Didn't we already make sure they all have data-page="extra"?
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 195 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJUlyyBj3sDJXyIP0S:-NNJUlyyBj3sDJXyIP0T:b-44vdv4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L195)):*
> ```XML
>               const enterpriseOnlyRules = isEnterprise
>                   ? `:after {
>                         content: "\u25cf";
> ```

Probably deserves to be a constant with a name and possibly comment somewhere.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 227 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJWKLME2Cs8bubpuRg:-NNJWKLME2Cs8bubpuRh:b-q2fbdd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L227)):*
> ```XML
>                           width: 104px;
>                           display: inline-block;
>                           position: sticky; //this makes the blue overlay, which is a child, be correctly positioned even when scrolled
> ```

I'd be very surprised if 'sticky' is what you want. I think you just need position: relative to make child positions be relative to this rather than an ancestor. Sticky does very little without specifying one of the position values (top, left, etc.) beyond 'relative' except perhaps to make its own stacking context. If that's what you want, try isolation:isolate. But try just position:relative first.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 222 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNNVj6kB3yxS3ZLI1q-:-NNNVj6kB3yxS3ZLI1q0:b-wy6s93) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc4b34c0892601bcdc0adb85c11fbb5064b98947/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L222)):*
> ```XML
>                       data-digital-only={isDigitalOnly(currentPageDiv)}
>                       data-tool-id={tool}
>                       data-help-link={helpLink}
> ```

In line with my later suggestion about how to handle selecting, consider whether it would work to pass this information as props to the element that represents a TemplatePage.
___
*[`src/BloomBrowserUI/pageChooser/ErrorGroup.tsx` line 12 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNNSdE--AUkCzKoFk7O:-NNNSdE--AUkCzKoFk7P:b-3joiis) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc4b34c0892601bcdc0adb85c11fbb5064b98947/src/BloomBrowserUI/pageChooser/ErrorGroup.tsx#L12)):*
> ```XML
> }
> 
> export const ErrorGroup: React.FunctionComponent<IErrorGroupProps> = props => {
> ```

More specific name? And/Or class comment? I gather this class is used in place of showing a template book's pages when something is wrong?
___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 61 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJZNe27d8UFi6F386P:-NNJZNe3-GufCwhCDgQv:bpzlkbh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L61)):*
> ```XML
>         string | undefined
>     >(undefined);
>     const [enterpriseAvailable, setEnterpriseAvailable] = useState(false);
> ```

I think we have a specific function for enterprise, something like useIsEnterpriseEnabled
___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 104 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJZuf5AxjxfMHgOWW1:-NNJZuf5AxjxfMHgOWW2:b26xwuu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L104)):*
> ```XML
>             setDefaultPageToSelect(defaultPageId);
>          [...]

2023-02-10 17:57 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612)* status: 20 of 29 files reviewed, 25 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJQmluBCFC2LHlz1JN:-NNc7K66-WHuwLB7tQbQ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L23)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Thumbnail? or Page? Thumb by itself suggests the draggable part of a scroll bar. (Coming back to this: later I suggest that you want a single consistent name, probably TemplatePage, for the things the use can choose in the dialog.)
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 74 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJSF6dBmYz1UC_7sRF:-NNcELhO3KMp6CV4ra67:bg74b55) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L74)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

We usually use JSON to pass complex data across Bloom's API. Why is this passed as HTML? Deserves a comment, at least.
</blockquote></details>

Commented. I am quite happy with converting what we did before to good React, but I think changing the basic API goes beyond what I want to do, at least in this PR.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 89 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJT4gYBMhLbA_AjTmK:-NNcGLxx9uTL61iHT2ny:b4kfxcj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L89)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why are we testing originalPages, rather than the filtered list we are actually going to show? Do we really want a heading with no pages if none of them is 'extra'?
(For that matter: do we use the non-extra pages for anything? If not, why not filter them out on the sending side of the API? In fact, we could make the sending side responsible to not send books that don't have at least one addable page at all.
</blockquote></details>

Took me a minute to realize you meant the extra page filter farther down. Good point. I rearranged things a bit. For the API question, it's probably a good idea, but see my previous comment about the API.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 111 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJSfApBi6_WCqTdcZD:-NNcIMQ0CYjp_ZgLevUv:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L111)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Might deserve a comment? Why are the pages the user can add tagged "extra"?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 158 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJUIqdDIJcjRWKaww8:-NNcIOE09JfvL0fv7BPw:bmnd3zm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Didn't we already make sure they all have data-page="extra"?
</blockquote></details>

Good point. Removed.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 195 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJUlyyBj3sDJXyIP0S:-NNhH8mv4FhlM5r_fSWP:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L195)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Probably deserves to be a constant with a name and possibly comment somewhere.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 227 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJWKLME2Cs8bubpuRg:-NNcJPlS5sPt0A8EjI1E:b-vzjfwy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L227)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'd be very surprised if 'sticky' is what you want. I think you just need position: relative to make child positions be relative to this rather than an ancestor. Sticky does very little without specifying one of the position values (top, left, etc.) beyond 'relative' except perhaps to make its own stacking context. If that's what you want, try isolation:isolate. But try just position:relative first.
</blockquote></details>

You were correct! `position: relative` was sufficient.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 222 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNNVj6kB3yxS3ZLI1q-:-NNrPHkn12vwtxi5o49h:b-v370w2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc4b34c0892601bcdc0adb85c11fbb5064b98947/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L222)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

In line with my later suggestion about how to handle selecting, consider whether it would work to pass this information as props to the element that represents a TemplatePage.
</blockquote></details>

Done. I'm not sure if I actually did what you had in mind, but the whole selection mechanism has been reworked.
___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 61 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJZNe27d8UFi6F386P:-NNcLAAVEuBvafSLOghD:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L61)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think we have a specific function for enterprise, something like useIsEnterpriseEnabled
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 104 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJZuf5AxjxfMHgOWW1:-NNcLE8w4lM4PFeoyJdJ:b-51twoq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L104)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

IIRC, each of these may cause a render. If so, it may be best to set the book URLs last, so that when you actually have content to render, all the other state things are already right.
</blockquote></details>

I commented in the code on what I found in reading online. I did the re-ordering, but multiple state setters in a `useEffect` appear to get batched so there's only one new render. Who knew!?
___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 123 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNJ_Mz51rd9-1O52bnm:-NNiFJYD1Rkyp1HTwEDN:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/670b681e0763ba40b9ebf4d4147bde14f0be4937/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L123)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

There might be a good performance reason for the above, but it should be documented. Otherwise, it's not very Reac [...]

2023-02-10 21:48 UTC, JohnThomson requested changes
Thanks for doing all that. It's a bit difficult to follow all the changes, but I think it's in pretty good shape now. I just picked up a few minor things.

> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-:-NNxHyAM8fXOPd5bcFIB:b-wv3ie5)* status: all files reviewed, 6 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 40 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNx8NjK0lG8VC1P1oVR:-NNx8NjK0lG8VC1P1oVS:byasrr0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L40)):*
> ```XML
> 
> // Unicode character used to mark pages that are only available to enterprise users.
> const bulletCharacter = "\u25cf";
> ```

It's not obvious why a 'bullet' character would be associated with Enterprise. Maybe enterpriseCharacter?
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 156 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNx9VLQD4fQvJP4l5b_:-NNx9VLQD4fQvJP4l5ba:b-e7z3i8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L156)):*
> ```XML
>                           display: inline-block;
>                           // This makes the blue overlay, which is a child, be correctly positioned
>                           // even when scrolled.
> ```

I'm not sure this comment needs changing, but you might want to review the stuff about position in our CSS course. It's not only scrolling that can throw this off! An absolutely positioned element uses top, left, etc to position itself next to the nearest ancestor that has SOME kind of positioning. The nice thing about position:relative is that it usually does nothing to the position of the element that has it (unless it has its own top: etc). But it means that absolutely positioned children will be positioned relative to this, not some ancestor.
I would have commented more like "the absolutely positioned blue overlay child needs to be placed relative to this, not an ancestor"
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 257 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNxBGta3YQsZFypK2oZ:-NNxBGta3YQsZFypK2o_:bqnkdjt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L257)):*
> ```XML
>             )}
>             {errorState && (
>                 <TemplateGroupErrorReplacement
> ```

Is a TemplateGroup something different from a TemplateBook? If not let's use the same name.
___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 487 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNNhWkM7W8EbCRnDL0T:-NNxGYwM6nfUpc0llEU5:bblk7m) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc4b34c0892601bcdc0adb85c11fbb5064b98947/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L487)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

The main problem seemed to be in the guts of the `useL10n()` hook. If we didn't remove and recreate the container, changing the `forChooseLayout` prop would always return the previous string from the hook. I wonder if the first usage was being cached by the LocalizationManager, or something. Ideas are welcome.
</blockquote></details>

How is it that forChooseLayout is even changing? Isn't that fixed for the life of the dialog?
If we want a different string, surely it should have a different L10nId? And I would consider it a bug if useL10n is not re-rendering when the ID changes.
___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 136 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNxDrlH6Nx05gmk4CXx:-NNxDrlH6Nx05gmk4CXy:bm85m40) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L136)):*
> ```XML
>                 const imgSrc = img.src.replace(/%2F/g, "/");
>                 // force the image to be reloaded
>                 if (imgSrc.startsWith(src)) {
> ```

Why startsWith here? Won't it reload without help if the src is changed in any way?
___
*[`src/BloomBrowserUI/pageChooser/ErrorGroup.tsx` line 12 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNNSdE--AUkCzKoFk7O:-NNxHNuR4th11Txnr7Lc:bgkydna) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc4b34c0892601bcdc0adb85c11fbb5064b98947/src/BloomBrowserUI/pageChooser/ErrorGroup.tsx#L12)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

`TemplateGroupErrorReplacement` :+1: 
</blockquote></details>

As noted above, unless a TemplateGroup is something different from a TemplateBook, I think you should use TemplateBook here too.


<!-- Sent from Reviewable.io -->

2023-02-13 19:34 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612)* status: 22 of 32 files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 487 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNNhWkM7W8EbCRnDL0T:-NNxZSfJ471rwRPps_eX:bhu1nsc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc4b34c0892601bcdc0adb85c11fbb5064b98947/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L487)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How is it that forChooseLayout is even changing? Isn't that fixed for the life of the dialog?
If we want a different string, surely it should have a different L10nId? And I would consider it a bug if useL10n is not re-rendering when the ID changes.
</blockquote></details>

Yeah, I think there's a bug in the `useL10n()` hook. If you don't recreate the whole dialog container, you can open the Add Page dialog (it'll have the correct title), close it and open the Change Layout dialog, it'll still say Add Page and vice versa. I've created BL-11927 to investigate that.
___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 136 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNxDrlH6Nx05gmk4CXx:-NOBF9s695RIZxlS1qNi:btaabu0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L136)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why startsWith here? Won't it reload without help if the src is changed in any way?
</blockquote></details>

I added some comments and renamed the `src` variable to `updatedThumbUrl`.
The basic problem here is that `imgSrc` always starts with a param "generateThumbnailIfNecessary=true" postpended, whereas the url that's coming into the method doesn't.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 40 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNx8NjK0lG8VC1P1oVR:-NOAt38-E_XAHsahCqH7:b-h38hqs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L40)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not obvious why a 'bullet' character would be associated with Enterprise. Maybe enterpriseCharacter?
</blockquote></details>

switched to `enterpriseMarkerChar`
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 156 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNx9VLQD4fQvJP4l5b_:-NOAtmb54jf3KTvmCDnp:b-ix40j6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L156)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not sure this comment needs changing, but you might want to review the stuff about position in our CSS course. It's not only scrolling that can throw this off! An absolutely positioned element uses top, left, etc to position itself next to the nearest ancestor that has SOME kind of positioning. The nice thing about position:relative is that it usually does nothing to the position of the element that has it (unless it has its own top: etc). But it means that absolutely positioned children will be positioned relative to this, not some ancestor.
I would have commented more like "the absolutely positioned blue overlay child needs to be placed relative to this, not an ancestor"
</blockquote></details>

Done. Thanks for the clarification.
___
*[`src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx` line 257 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNxBGta3YQsZFypK2oZ:-NOAtEsCDoad5gTiubm6:b-9gwtfq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/ChooserPageGroup.tsx#L257)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is a TemplateGroup something different from a TemplateBook? If not let's use the same name.
</blockquote></details>

Using `TemplateBookErrorReplacement`.
___
*[`src/BloomBrowserUI/pageChooser/ErrorGroup.tsx` line 12 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNNSdE--AUkCzKoFk7O:-NOAsQMCDuT8gtZnv3_H:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bc4b34c0892601bcdc0adb85c11fbb5064b98947/src/BloomBrowserUI/pageChooser/ErrorGroup.tsx#L12)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As noted above, unless a TemplateGroup is something different from a TemplateBook, I think you should use TemplateBook here too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-14 21:00 UTC, JohnThomson approved these changes
I'm ready to approve this. I'll leave it open for now in case you think the startsWith is worth improving after my last comment, but I'm also OK if you decide it's not.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-:-NOGiUM4DYAHMJTz7dOl:b-vnx6tr)* status: 22 of 32 files reviewed, 1 unresolved discussion (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2023-02-14 21:05 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612)* status: 22 of 32 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx` line 136 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612#-NNxDrlH6Nx05gmk4CXx:-NOGjHOJCOMt6FcrtjZa:b-vymgd6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6e3c981871de8beafad5650e0622fe324a0475b5/src/BloomBrowserUI/pageChooser/PageChooserDialog.tsx#L136)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That makes sense but if the page has pictures called, say, "dogs" and "dogs running" and "dogs playing" they will all update when you only meant to update the first one. That may be unlikely enough not to matter...I think the worst result would be a slight delay, maybe a flicker. The more precise thing would to match anything up to the question mark (if any). But it may not be worth it.
</blockquote></details>

I think maybe we won't bother unless a user brings it up, since our published templates generally won't even have this problem. This is only for templates where there is no `.svg` of the Portrait/Landscape version of the page already stored in the templates directory of the book.


<!-- Sent from Reviewable.io -->

2023-02-14 21:10 UTC, JohnThomson approved these changes
> Reviewed 6 of 10 files at r4, 1 of 1 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5612)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2023-02-14 21:10 UTC, merged