Publish to PDF and Print (BL-11262-6)
BloomBooks/BloomDesktop pull request #5634
Opened 2023-02-14 23:06 UTC by JohnThomson

Show preview of PDF (BL-11262)
Progress dialog creating PDF (BL-11263)
Add mode buttons (BL-11265)
Get print and Save working (BL-11264)
Printshop options (BL-11266)

2023-02-14 23:29 UTC, andrew-polk requested changes
Review in progress...

> Reviewed 16 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-:-NOHFk0I3hZP4Hv7rpYt:b-l04yhj)* status: 16 of 21 files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3795 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHBOeVEN_Uj36RUA6h:-NOHBOeVEN_Uj36RUA6i:b4up2ck) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/DistFiles/localization/en/Bloom.xlf#L3795)):*
> ```XML
>         <source xml:lang="en">The inside pages, re-arranged so that when folded, you get a booklet ready to staple.</source>
>         <note>ID: PublishTab.BodyOnly-description</note>
>       </trans-unit-->
> ```

We should mark these commented ones somehow so we can easily find them when we are finalizing 5.5.
___
*[`src/BloomBrowserUI/utils/colorUtils.ts` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHC35b6c4cb5vrRPtb:-NOHC35c8ZYmIvNWSLay:b7e4bo9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/src/BloomBrowserUI/utils/colorUtils.ts#L12)):*
> ```XML
> export const kBloomRed = "#d65649"; // See @bloom-red
> export const kBloomGray = "#575757"; // See @bloom-gray
> export const kDisabledButtonText = "rgba(0, 0, 0, 0.38)";
> ```

By our convention, it appears this should begin with "Bloom".
(Though I'm not sure I agree with the convention...)
___
*[`src/BloomExe/Publish/PDF/PdfViewer.cs` line 114 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHDzGb3-Rq2ujVEAEu:-NOHDzGb3-Rq2ujVEAEv:b-17z6bm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/src/BloomExe/Publish/PDF/PdfViewer.cs#L114)):*
> ```Smalltalk
> 			                                     | CoreWebView2PdfToolbarItems.SaveAs // We want our Save code, which checks things like not saving in the book folder
> 												 | CoreWebView2PdfToolbarItems.FullScreen // doesn't work right and is hard to recover from
> 												 | CoreWebView2PdfToolbarItems.MoreSettings; // none of its functions seem useful
> ```

We need these set here as well as in WebView2Browser? Or was that two iterations of changes, with one accidentally left in?
___
*[`src/WebView2PdfMaker/WebView2PdfComponent.cs` line 150 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHF7fS8QiR9-jKTNlf:-NOHF7fS8QiR9-jKTNlg:b-8cf5tm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/src/WebView2PdfMaker/WebView2PdfComponent.cs#L150)):*
> ```Smalltalk
> 		}
> 
> 		private void ReportFakeProgress(string doingWhat)
> ```

Something struck me oddly about the word "fake". Maybe I just assumed it was something for testing when I first saw it.
See if you think "simulated" or "feigned" or "contrived" are better.
If not, fine to leave as is.


<!-- Sent from Reviewable.io -->

2023-02-15 14:58 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634)* status: 12 of 21 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3795 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHBOeVEN_Uj36RUA6h:-NOKYog0B3L0WXUM_Kt6:b-akyjcd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/DistFiles/localization/en/Bloom.xlf#L3795)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We should mark these commented ones somehow so we can easily find them when we are finalizing 5.5.
</blockquote></details>

I suppose, though they were pretty easy to find by just searching for comments. Done.
___
*[`src/BloomBrowserUI/utils/colorUtils.ts` line 12 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHC35b6c4cb5vrRPtb:-NOKZC014zHk2m9riTh6:b-7aae32) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/src/BloomBrowserUI/utils/colorUtils.ts#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

By our convention, it appears this should begin with "Bloom".
(Though I'm not sure I agree with the convention...)
</blockquote></details>

Done. (But I agree with you. It's one thing to identify a particular shade of Red as the one we selected for all kinds of things in Bloom. But I don't think the names that really identify a purpose need it.)
___
*[`src/BloomExe/Publish/PDF/PdfViewer.cs` line 114 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHDzGb3-Rq2ujVEAEu:-NOKZDLE4RbtPSExev6T:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/src/BloomExe/Publish/PDF/PdfViewer.cs#L114)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

We need these set here as well as in WebView2Browser? Or was that two iterations of changes, with one accidentally left in?
</blockquote></details>

Done.
___
*[`src/WebView2PdfMaker/WebView2PdfComponent.cs` line 150 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHF7fS8QiR9-jKTNlf:-NOKZvR-EP__XhA44ajS:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/src/WebView2PdfMaker/WebView2PdfComponent.cs#L150)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Something struck me oddly about the word "fake". Maybe I just assumed it was something for testing when I first saw it.
See if you think "simulated" or "feigned" or "contrived" are better.
If not, fine to leave as is.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-15 18:04 UTC, andrew-polk requested changes
> Reviewed 3 of 21 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634)* status: 20 of 21 files reviewed, 12 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx` line 114 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL6hoL4qJshKaGtxdE:-NOL6hoL4qJshKaGtxdF:b4ngo1c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx#L114)):*
> ```XML
>                         apiEndpoint="publish/pdf/fullBleed"
>                         disabled={!allowFullBleed}
>                         // Todo: disabled if book does not have full bleed.
> ```

Is this still todo?



_Code quote:_
```XML
// Todo: disabled if book does not have full bleed.
```
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx` line 167 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL7HDE3Mf9kZN6svjJ:-NOL7HDE3Mf9kZN6svjK:bo1te2v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx#L167)):*
> ```XML
> // Review: should this be a material-ui button? Have to fight mui for many of the
> // CSS values such as text color and capitalization, so it seems more trouble than
> // it's worth, but maybe there are button-like behaviors I'm missing?
> ```

Not going to ask you to change it now that you've implemented it, but text color and capitalization are chosen by simple props, I'm pretty sure. But likely you just picked those as examples.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 39 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL8TS-11l1h1nZgU5P:-NOL8TS-11l1h1nZgU5Q:b-fjun9v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L39)):*
> ```XML
> 
> export const PDFPrintPublishScreen = () => {
>     const readable = new ReadableStream();
> ```

This doesn't seem to be used.
(If it is doing some magic, we need some comments.)
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 215 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLAVRN5bM2cbEN_Cok:-NOLAVRN5bM2cbEN_Col:b-r9z8mr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L215)):*
> ```XML
>     const rightSideControls = (
>         <React.Fragment>
>             <Button onClick={handlePrint} disabled={!path}>
> ```

Do these want to be `BloomButton`s? 
If not, we should probably comment why not.
And I think it would be an improvement to extract the display logic.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 272 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9ggq4jYasu0uIsmb:-NOL9ggq4jYasu0uIsmc:birifi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L272)):*
> ```XML
>                 {mainPanel}
>             </PublishScreenTemplate>
>             <Dialog open={progressOpen}>
> ```

Doesn't this want to be a ProgressDialog?
If not, it needs comments.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 317 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9m3HClYUbkCGnVTj:-NOL9m3HClYUbkCGnVTk:b-fpwmss) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L317)):*
> ```XML
>                 </div>
>             </Dialog>
>             <Dialog
> ```

Doesn't this want to be a BloomDialog?
If not, it needs comments.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 394 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL8A8v2YDGMMvMEC00:-NOL8A8v2YDGMMvMEC01:bj1bzkc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L394)):*
> ```XML
> };
> 
> // a bit goofy... currently the html loads everything in pdf. So all the publish screens
> ```

I think maybe this change was accidental?
Anyway, it seems incorrect now.



_Code quote:_
```XML
the html loads everything in pdf
```
___
*[`src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs` line 142 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL5TsbBpwKrp8HDAZR:-NOL5TsbBpwKrp8HDAZS:b-nw1zg1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs#L142)):*
> ```Smalltalk
> 						var creating = LocalizationManager.GetString("PublishTab.PdfMaker.Creating", "Creating PDF...");
> 						dynamic messageBundle = new DynamicJson();
> 						messageBundle.message = creating + "|Percent: " + percent * (100 - ProcessPdfWithGhostscript.kPdfCompressionShare) / 100;
> ```

The "Creating..." part is localized but not "Percent".

(here and during compression)

Hm. Now looking at the js side, it appears we never output the "Percent: " part to the user?
Could probably use a brief comment.
___
*[`src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs` line 282 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL4TJv6AtaYsiF12xW:-NOL4TJv6AtaYsiF12xX:b-49qlrn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs#L282)):*
> ```Smalltalk
> 		const string kPage = "Page ";
> 
> 		public const int kPdfCompressionShare = 75;
> ```

Is this just the default? A comment would probably be helpful.
___
*[`src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs` line 318 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL4aoz7XX2AbXk42nr:-NOL4aoz7XX2AbXk42ns:bahw0gq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs#L318)):*
> ```Smalltalk
> 					{
> 						var percentage = (int)(100.0F * (float)(pageNumber - _firstPage) / (float)_numPages);
> 						_worker.ReportProgress(percentage);
> ```

So do these ReportProgress messages not get used with the new system?
Anything worth doing now to help us clean them up when we get rid of the old system? (maybe not)
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 94 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLCsQ--sBHgUyWdmmd:-NOLCsQ--sBHgUyWdmme:b-7i98wo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L94)):*
> ```Smalltalk
> 
> 		private string _lastDirectory;
> 		// Adapted from PublishModel.Save()
> ```

It seems you've taken the approach of replacing PublishModel with PublishPdfApi. Is that accurate?
My leaning would be to keep the API class as simple/clean as possible and keep most of the logic in PublishModel.
Should we discuss?

... we did discuss and decided to try to keep as much of this in PublishModel as we can.

I also said I'll hold off on finalizing my review of this file due to that.


<!-- Sent from Reviewable.io -->

2023-02-15 19:59 UTC, JohnThomson reviewed
PR updated, but I also realized I need to do a Cancel button in the Progress dialog, so don't merge yet.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-:-NOLe2jD7vMzk2X-BbCj:b4ofko)* status: 14 of 22 files reviewed, 12 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx` line 114 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL6hoL4qJshKaGtxdE:-NOLTQkY3gGY365ET2Mh:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx#L114)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this still todo?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx` line 167 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL7HDE3Mf9kZN6svjJ:-NOLTcAPC8gDepDFhqiV:b-r6udvw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx#L167)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not going to ask you to change it now that you've implemented it, but text color and capitalization are chosen by simple props, I'm pretty sure. But likely you just picked those as examples.
</blockquote></details>

Might be new in MUI 5. IIRC, it took something like a theme (or custom CSS) to make color anything not in the current Bloom theme in MUI 4. But I think at this point I'll let JohnH UI-review it and see if anything is missing.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 39 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL8TS-11l1h1nZgU5P:-NOLUH6mAWzTokP5JhRk:b-17boc9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This doesn't seem to be used.
(If it is doing some magic, we need some comments.)
</blockquote></details>

It was there when I started; not sure at what point it was useful, but I took it out.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 215 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLAVRN5bM2cbEN_Cok:-NOL_Lc0AxSjzJMcW0GX:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L215)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Do these want to be `BloomButton`s? 
If not, we should probably comment why not.
And I think it would be an improvement to extract the display logic.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 272 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9ggq4jYasu0uIsmb:-NOL_wnu7DgynZGIquLy:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L272)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Doesn't this want to be a ProgressDialog?
If not, it needs comments.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 317 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9m3HClYUbkCGnVTj:-NOLb7TUEKrtNNKowSjn:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L317)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Doesn't this want to be a BloomDialog?
If not, it needs comments.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 394 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL8A8v2YDGMMvMEC00:-NOLbRCb6NB4yvoVAcVq:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L394)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think maybe this change was accidental?
Anyway, it seems incorrect now.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs` line 142 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL5TsbBpwKrp8HDAZR:-NOLbwq88RAfyah_y0M9:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/MakePdfUsingExternalPdfMakerProgram.cs#L142)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The "Creating..." part is localized but not "Percent".

(here and during compression)

Hm. Now looking at the js side, it appears we never output the "Percent: " part to the user?
Could probably use a brief comment.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs` line 282 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL4TJv6AtaYsiF12xW:-NOLcifu0K2PtjGgFAsr:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs#L282)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this just the default? A comment would probably be helpful.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs` line 318 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL4aoz7XX2AbXk42nr:-NOLdEe0DvP_qwSm_zNK:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs#L318)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

So do these ReportProgress messages not get used with the new system?
Anything worth doing now to help us clean them up when we get rid of the old system? (maybe not)
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 94 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLCsQ--sBHgUyWdmmd:-NOLdMpG8YRfCTQN5eQT:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L94)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It seems you've taken the approach of replacing PublishModel with PublishPdfApi. Is that accurate?
My leaning would be to keep the API class as simple/clean as possible and keep most of the logic in PublishModel.
Should we discuss?

... we did discuss and decided to try to keep as much of this in PublishModel as we can.

I also said I'll hold off on finalizing my review of this file due to that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-15 21:34 UTC, andrew-polk requested changes
> Reviewed 7 of 8 files at r3, 1 of 1 files at r4, 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634)* status: all files reviewed, 4 unresolved discussions (waiting on @JohnThomson)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3795 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOHBOeVEN_Uj36RUA6h:-NOLthzc3-kl89B5Gc9h:b551kkf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f58bd641eefc5226e25fac300dc703a7c2bc5548/DistFiles/localization/en/Bloom.xlf#L3795)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose, though they were pretty easy to find by just searching for comments. Done.
</blockquote></details>

You're probably right. I was thinking maybe there would be other commenting things, but I guess there shouldn't be.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 272 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9ggq4jYasu0uIsmb:-NOLuanA2pdYMtXPKCZt:b-6dwa2v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L272)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry; you may be right, but I'm not convinced yet.

The progress indicator could be swapped out, right?
And I don't see anything complicated in the props by use of colored messages. So can't we just ignore that complication here?

Even if we don't use ProgressDialog, should we have a new DeterminateProgressDialog? 

Recently, JH was bemoaning (rightly, I think) all the different UI variations we have for dialogs, even in react. So we need to use reusable components whenever we can.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 317 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9m3HClYUbkCGnVTj:-NOLuFJf9bNPzXkIiJeR:bkokkez) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L317)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. I think you can remove all the dragging stuff here now. 
(Seeing you reimplement that was what tipped me off that you should probably be using BloomDialog.)
___
*[`src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs` line 282 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL4TJv6AtaYsiF12xW:-NOLwBuwDz6qDmAvOZ_1:b-wcue7c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/ProcessPdfWithGhostscript.cs#L282)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks; that definitely clarified what was happening for me.
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 94 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLCsQ--sBHgUyWdmmd:-NOLxnywEbNwH6_6Ql7w:b-nq77if) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L94)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks. I think this is better for multiple reasons. (ease of review, history, separation, etc.)
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 30 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLxf_c6dIa4We6-dRN:-NOLxf_c6dIa4We6-dRO:bwjgch2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/36a85d8a3bb3ccb3990161591daa30d2d1cc580d/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L30)):*
> ```Smalltalk
> 		// This is to support orientation/page size changing during publishing, but we're not doing
> 		// that yet, so just defer to the current book.
> 		public Layout PageLayout => CurrentBook?.GetLayout() ?? Layout.A5Portrait;
> ```

Is it better to get this from the model now?
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 171 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLyWIHAQw0Jk7ymAbh:-NOLyWIHAQw0Jk7ymAbi:b-uk6yha) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/36a85d8a3bb3ccb3990161591daa30d2d1cc580d/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L171)):*
> ```Smalltalk
> 				var size = PageLayout.SizeAndOrientation.PageSizeName;
> 				return CurrentBook.BookInfo.BookletMakingIsAppropriate &&
> 				       (size != "A4" && size != "A3" && size != "B5" && size != "Letter" && size != "Device16x9");
> ```

It would be nice to share this list of excluded page sizes with the model if nothing else.


<!-- Sent from Reviewable.io -->

2023-02-16 22:54 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634)* status: 19 of 27 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 272 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9ggq4jYasu0uIsmb:-NORQw-23zsG0sUg9fg9:b-ndjgr2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L272)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; you may be right, but I'm not convinced yet.

The progress indicator could be swapped out, right?
And I don't see anything complicated in the props by use of colored messages. So can't we just ignore that complication here?

Even if we don't use ProgressDialog, should we have a new DeterminateProgressDialog? 

Recently, JH was bemoaning (rightly, I think) all the different UI variations we have for dialogs, even in react. So we need to use reusable components whenever we can.
</blockquote></details>

OK, I enhanced ProgressDialog enough to handle this case.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 317 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9m3HClYUbkCGnVTj:-NOQlyX_4Jh2NOdEbLUQ:b-ogoyzu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L317)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks. I think you can remove all the dragging stuff here now. 
(Seeing you reimplement that was what tipped me off that you should probably be using BloomDialog.)
</blockquote></details>

Done, though with some complications, since BloomDialog did not support dragging a dialog without a Title, and we don't really want one here.
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 30 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLxf_c6dIa4We6-dRN:-NOQmXX8CvFZqNbABBfI:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/36a85d8a3bb3ccb3990161591daa30d2d1cc580d/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L30)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is it better to get this from the model now?
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PDF/PublishPdfApi.cs` line 171 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOLyWIHAQw0Jk7ymAbh:-NOQoHlv9qdqFMfSbsbE:b3nvpon) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/36a85d8a3bb3ccb3990161591daa30d2d1cc580d/src/BloomExe/Publish/PDF/PublishPdfApi.cs#L171)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It would be nice to share this list of excluded page sizes with the model if nothing else.
</blockquote></details>

I decided to just use the function. We don't get anywhere near using this if DeterminePublishability() returns false, so it's use in PublishModel.AllowPdfBooklet is harmless.


<!-- Sent from Reviewable.io -->

2023-02-17 01:03 UTC, andrew-polk requested changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 272 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9ggq4jYasu0uIsmb:-NORs5FB6geNR1omSG2E:b76mpw3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L272)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

OK, I enhanced ProgressDialog enough to handle this case.
</blockquote></details>

Thanks. I apologize in advance if we never use it, but I would bet we will.
I, for one, will be looking for opportunities to. : )

And I think you've cleaned things up in multiple ways.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx` line 317 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NOL9m3HClYUbkCGnVTj:-NORsOkCAkkCL8bkOUGL:bqa7rg9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/65c2af413c87ee8f8da6e735ef7cdbf2ea29ad0c/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintPublishScreen.tsx#L317)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done, though with some complications, since BloomDialog did not support dragging a dialog without a Title, and we don't really want one here.
</blockquote></details>

Thanks. Sorry; that was a lot of work. But I think you've improved even the existing BloomDialog code while doing this.
___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 355 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NORtCWg33YggLehXBXh:-NORtCWg33YggLehXBXi:btqqj33) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/90f8240bb113a394b33c2608a2788d68fdab0185/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L355)):*
> ```XML
> 
> interface EnhancedPaperProps extends PaperProps {
>     id: string;
> ```

I'm wary of using "id" which already exists on all components, right? And can cause confusion as to what you're setting.
How about handleId? Or idForHandle? idOfHandle?


<!-- Sent from Reviewable.io -->

2023-02-17 16:12 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx` line 355 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5634#-NORtCWg33YggLehXBXh:-NOV8Z2n1dZI1YrGeVZ_:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/90f8240bb113a394b33c2608a2788d68fdab0185/src/BloomBrowserUI/react_components/BloomDialog/BloomDialog.tsx#L355)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm wary of using "id" which already exists on all components, right? And can cause confusion as to what you're setting.
How about handleId? Or idForHandle? idOfHandle?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-17 16:19 UTC, merged