BL-11303 better dialog solution
BloomBooks/BloomDesktop pull request #5690
Opened 2023-03-07 21:09 UTC by gmartin7

* instead of NotifyUserOfProblem, use BloomMessageBox
   which doesn't claim that Bloom had a problem when it
   didn't

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690)

2023-03-07 21:27 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomExe/Program.cs` line 322 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NPxx1J92PdHWpDkzk3k:-NPxx1J92PdHWpDkzk3l:bfo24gc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9f9d81fd433f0f8d1348bcd1b7a304ea5d639430/src/BloomExe/Program.cs#L322)):*
> ```Smalltalk
> 										// BloomMessageBox.Show() expects a window as 'owner', but we don't have our own window
> 										// open yet. This will pop up the dialog in the upper left corner. Not ideal, but the
> 										// best we can do in this case.
> ```

Does Shell.GetShellOrOtherOpenForm() work here?
If not, I'm pretty sure there is a way to tell winform dialogs to open in the middle of their screen.
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 835 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NPxxYP3DY7hVinbpz_S:-NPxxYP42vPU8eeZlpk9:b-yvkly6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9f9d81fd433f0f8d1348bcd1b7a304ea5d639430/src/BloomExe/Workspace/WorkspaceView.cs#L835)):*
> ```Smalltalk
> 						};
> 						var formToInvokeOn = Application.OpenForms.Cast<Form>().FirstOrDefault(f => f is Shell);
> 						formToInvokeOn.Invoke((Action)(() =>
> ```

Why do we need to invoke here? (I'm pretty sure we don't because we're in the else of a `if (InvokeRequired)`)

I think the form we want as owner is  Shell.GetShellOrOtherOpenForm() 


<!-- Sent from Reviewable.io -->

2023-03-09 22:42 UTC, gmartin7 reviewed
Made another method of `BloomMessageBox` called `ShowInfo()` that only takes a message string. Greatly simplifies things...

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-:-NQ7XErf0kDcJIaKkE9q:b-66ti4j)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Program.cs` line 322 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NPxx1J92PdHWpDkzk3k:-NPy9W7E7LiB8_8EJRv7:brbqwo2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9f9d81fd433f0f8d1348bcd1b7a304ea5d639430/src/BloomExe/Program.cs#L322)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does Shell.GetShellOrOtherOpenForm() work here?
If not, I'm pretty sure there is a way to tell winform dialogs to open in the middle of their screen.
</blockquote></details>

Nope and nope. I tried `Shell.GetShellOrOtherOpenForm()` and it still returned null. I tried telling `ReactDialog.cs` that if ShowDialog's 'owner' param was null, it should do `dlg.CenterFormInScreen()` and that didn't work either. :(
___
*[`src/BloomExe/Workspace/WorkspaceView.cs` line 835 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NPxxYP3DY7hVinbpz_S:-NPyAwCvCAlIzRHZ329h:b-t4gwqs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9f9d81fd433f0f8d1348bcd1b7a304ea5d639430/src/BloomExe/Workspace/WorkspaceView.cs#L835)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why do we need to invoke here? (I'm pretty sure we don't because we're in the else of a `if (InvokeRequired)`)

I think the form we want as owner is  Shell.GetShellOrOtherOpenForm() 
</blockquote></details>

OK, right. I was just copying... :D


<!-- Sent from Reviewable.io -->

2023-03-10 21:31 UTC, gmartin7 reviewed
Added Information as a new and better icon type.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-:-NQCQuF22asjMpgjgqm8:b-bdpfog)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)



<!-- Sent from Reviewable.io -->

2023-03-13 15:48 UTC, andrew-polk requested changes
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/utils/BloomMessageBox.tsx` line 110 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NQQUIet8Fsh4mffhUs7:-NQQUIet8Fsh4mffhUs8:b-7jn1ou) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/fafaaf204242b73101e20d2681e86158adee487c/src/BloomBrowserUI/utils/BloomMessageBox.tsx#L110)):*
> ```XML
>                         css={css`
>                             font-size: 3rem !important;
>                             color: ${kBloomYellow};
> ```

Does this color change need UI Review?
___
*[`src/BloomExe/Program.cs` line 322 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NPxx1J92PdHWpDkzk3k:-NQQQDXB6eyo-LccWiw-:bar2etl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9f9d81fd433f0f8d1348bcd1b7a304ea5d639430/src/BloomExe/Program.cs#L322)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Nope and nope. I tried `Shell.GetShellOrOtherOpenForm()` and it still returned null. I tried telling `ReactDialog.cs` that if ShowDialog's 'owner' param was null, it should do `dlg.CenterFormInScreen()` and that didn't work either. :(
</blockquote></details>

There's Form.CenterToScreen().
For some reason, the [doc](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.centertoscreen?redirectedfrom=MSDN&view=windowsdesktop-7.0#System_Windows_Forms_Form_CenterToScreen) says not to call this but instead set the form's StartPosition to to CenterScreen.
So I guess try the latter first, then the former if it doesn't work.

Also, should this be ShowInfo now?


<!-- Sent from Reviewable.io -->

2023-03-13 15:48 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690)* status: all files reviewed, 2 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomExe/Program.cs` line 322 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NPxx1J92PdHWpDkzk3k:-NQQeBEJA3qiSuetiOan:b-t1ig9b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9f9d81fd433f0f8d1348bcd1b7a304ea5d639430/src/BloomExe/Program.cs#L322)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

There's Form.CenterToScreen().
For some reason, the [doc](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.centertoscreen?redirectedfrom=MSDN&view=windowsdesktop-7.0#System_Windows_Forms_Form_CenterToScreen) says not to call this but instead set the form's StartPosition to to CenterScreen.
So I guess try the latter first, then the former if it doesn't work.

Also, should this be ShowInfo now?
</blockquote></details>

I got info for centering from https://stackoverflow.com/questions/4601827/how-do-i-center-a-window-on-the-screen-in-c-sharp-winforms


<!-- Sent from Reviewable.io -->

2023-03-13 17:41 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/utils/BloomMessageBox.tsx` line 110 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NQQUIet8Fsh4mffhUs7:-NQQq3_T-3pGF25YUuud:b-63en7b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/fafaaf204242b73101e20d2681e86158adee487c/src/BloomBrowserUI/utils/BloomMessageBox.tsx#L110)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this color change need UI Review?
</blockquote></details>

Hmm... I guess I thought I'd replaced all the warnings with information so it didn't matter, but there are still a couple of them in our code... I'm guessing JH would say change 'em all to information, but it would be simpler to revert my change here. In my defense, the difference is between #FFA500 and #FEBF00... fairly close.
___
*[`src/BloomExe/Program.cs` line 322 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690#-NPxx1J92PdHWpDkzk3k:-NQQxuVEAgzV_UPrrwXN:bryz7kn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9f9d81fd433f0f8d1348bcd1b7a304ea5d639430/src/BloomExe/Program.cs#L322)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I got info for centering from https://stackoverflow.com/questions/4601827/how-do-i-center-a-window-on-the-screen-in-c-sharp-winforms
</blockquote></details>

I hadn't changed this one to `ShowInfo()` because of the screen positioning issue, but now that it's centering on the screen when owner is null, I switched to `ShowInfo()`.
Dunno how come I didn't find that StartPosition option, I'm sure I've used it before. :(


<!-- Sent from Reviewable.io -->

2023-03-13 17:55 UTC, andrew-polk approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5690)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2023-03-13 17:55 UTC, merged