BL-11993 Make MXB Printing History a non-derived field
BloomBooks/BloomDesktop pull request #5697
Opened 2023-03-14 18:23 UTC by gmartin7

* added .bloom-removeWhenMakingDerivative class to the
   translation group
* added code in BookStarter that looks for this class and an
   associated 'data-book' key and removes the bloom-editable
   contents from the book and the datadiv.

2023-03-14 20:17 UTC, andrew-polk commented
Could you add a unit test or two?

2023-03-17 18:04 UTC, andrew-polk requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomExe/Book/BookStarter.cs` line 223 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697#-NQkhrU09fY9-UdDpnLr:-NQkhrU09fY9-UdDpnLs:b-enxqvr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30efbf23a46eeee0f2e0a4cf0d47c3964fd44fcd/src/BloomExe/Book/BookStarter.cs#L223)):*
> ```Smalltalk
> 			// Here we check for translation groups with the class bloom-clearWhenMakingDerivative. The "RemoveAllForms"
> 			// for ISBN above and the similar calls for "copyright" and "versionAcknowledgments" in "TransformCreditPageData()"
> 			// below are for standard fields. This check is primarily for custom xmatter and brandings.
> ```

Probably should document *why* we decided to keep two different ways.
Maybe better to document in the card and reference the card from here rather than trying to put it all in a comment here.
___
*[`src/BloomExe/Book/BookStarter.cs` line 276 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697#-NQkiwGc8YvOeg4squRo:-NQkiwGdAHfb13AMvlbB:bj47ijh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30efbf23a46eeee0f2e0a4cf0d47c3964fd44fcd/src/BloomExe/Book/BookStarter.cs#L276)):*
> ```Smalltalk
> 		/// 'internal' for testing only
> 		/// </summary>
> 		internal static void CheckForNonDerivativeData(HtmlDom dom, BookData bookData)
> ```

I'm unsure about this name.
It would be good if it communicates it is possibly clearing stuff.
ClearOriginalContentFromVersionSpecificFields?
ClearContentWhichShouldntBeCopiedToDerivative?
HandleClearingOfNonDerivativeData?
Something else?



_Code quote:_
```Smalltalk
CheckForNonDerivativeData
```
___
*[`src/BloomExe/Book/BookStarter.cs` line 285 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697#-NQkicD56yZ5kDdrBiB0:-NQkicD56yZ5kDdrBiB1:bk6xbpj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30efbf23a46eeee0f2e0a4cf0d47c3964fd44fcd/src/BloomExe/Book/BookStarter.cs#L285)):*
> ```Smalltalk
> 			foreach (XmlElement translationGroup in groupsToEmpty)
> 			{
> 				// Check to see if we have a .bloom-editable div for lang z.
> ```

I thought you decided you didn't need all this bloom-editable stuff (since we think it is only xmatter).


<!-- Sent from Reviewable.io -->

2023-03-21 17:40 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookStarter.cs` line 223 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697#-NQkhrU09fY9-UdDpnLr:-NR4Fayd5i5VDnAB0NFo:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30efbf23a46eeee0f2e0a4cf0d47c3964fd44fcd/src/BloomExe/Book/BookStarter.cs#L223)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably should document *why* we decided to keep two different ways.
Maybe better to document in the card and reference the card from here rather than trying to put it all in a comment here.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/BookStarter.cs` line 276 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697#-NQkiwGc8YvOeg4squRo:-NR3oQPb3UFW9UPgjq5I:bj8muj9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30efbf23a46eeee0f2e0a4cf0d47c3964fd44fcd/src/BloomExe/Book/BookStarter.cs#L276)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm unsure about this name.
It would be good if it communicates it is possibly clearing stuff.
ClearOriginalContentFromVersionSpecificFields?
ClearContentWhichShouldntBeCopiedToDerivative?
HandleClearingOfNonDerivativeData?
Something else?
</blockquote></details>

How about `ClearUnneededOriginalContentFromDerivative`?
___
*[`src/BloomExe/Book/BookStarter.cs` line 285 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697#-NQkicD56yZ5kDdrBiB0:-NR3nwpu8QMsiR8ZxcRe:b-mx2nwj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/30efbf23a46eeee0f2e0a4cf0d47c3964fd44fcd/src/BloomExe/Book/BookStarter.cs#L285)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I thought you decided you didn't need all this bloom-editable stuff (since we think it is only xmatter).
</blockquote></details>

After discussion in today's standup, we'll remove it because of YAGNI.


<!-- Sent from Reviewable.io -->

2023-03-21 17:43 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5697)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2023-03-21 17:43 UTC, merged