[5.4] BL-12005 keep disabled menu items
BloomBooks/BloomDesktop pull request #5721
Opened 2023-03-23 17:10 UTC by gmartin7

* add a tooltip explaining why the item is disabled

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721)

2023-03-23 17:13 UTC, andrew-polk commented
Draft until JH reviews the tooltip

2023-03-23 17:18 UTC, andrew-polk requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx` line 504 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721#-NRESm7rESYjQ9EzyBns:-NRESm7rESYjQ9EzyBnt:b-d9imtv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4dbc3ba59d743f2b858241c9dc81ec6ab211351e/src/BloomBrowserUI/collectionsTab/CollectionsTabPane.tsx#L504)):*
> ```XML
>                 // default logic for whether to show the command
>                 if (isEditableCollection) {
>                     // eliminate commands that require permission to change the book, if we don't have it
> ```

Comment is now incorrect (we don't eliminate but disable)
___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 100 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721#-NRETAzX3NJtQ1ZOZJ3f:-NRETAzX3NJtQ1ZOZJ3g:budujst) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4dbc3ba59d743f2b858241c9dc81ec6ab211351e/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L100)):*
> ```XML
>         : props.onClick;
> 
>     const requiresCheckingOutTooltip = useL10n(
> ```

There will be future reasons to disable menu items besides this.
I think we should pass in the disabledTooltip as a prop.
That will also keep you from having to duplicate this for each control here.
And we don't want to set temporarilyDisableLocalizationWarning to true, do we?
___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 111 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721#-NRETV99-1aAnAmWe1bh:-NRETV99-1aAnAmWe1bi:bafxvf0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4dbc3ba59d743f2b858241c9dc81ec6ab211351e/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L111)):*
> ```XML
>     return (
>         <div title={props.disabled ? requiresCheckingOutTooltip : undefined}>
>             {/* "div" wrapper is necessary to get the tooltip to work on a disabled item. */}
> ```

I think it would be better to put the comment above the div.


<!-- Sent from Reviewable.io -->

2023-03-24 14:52 UTC, andrew-polk requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 100 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721#-NRETAzX3NJtQ1ZOZJ3f:-NRJ4OV-Bix_W7vol6VU:bzep1j1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4dbc3ba59d743f2b858241c9dc81ec6ab211351e/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L100)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

> There will be future reasons to disable menu items besides this.
> I think we should pass in the disabledTooltip as a prop.

I think I get what you're saying... passed the string to makeMenuItems().

> And we don't want to set temporarilyDisableLocalizationWarning to true, do we?

right.
</blockquote></details>

I think it should be tooltipIfDisabled. At least in this component.

Maybe in CollectionsTabPane it should be something like tooltipIfCannotModifyBook or tooltipIfCannotSaveBook?


<!-- Sent from Reviewable.io -->

2023-03-24 22:09 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @gmartin7)

___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 100 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721#-NRETAzX3NJtQ1ZOZJ3f:-NRKZG7W4dlCb2iamLxt:b21c94e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4dbc3ba59d743f2b858241c9dc81ec6ab211351e/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L100)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it should be tooltipIfDisabled. At least in this component.

Maybe in CollectionsTabPane it should be something like tooltipIfCannotModifyBook or tooltipIfCannotSaveBook?
</blockquote></details>

Will do. But I thought that there would be multiple reasons...
We'll figure that out when we HAVE multiple reasons. :)
Went with `tooltipIfCannotSaveBook` in BookButton (and CollectionsTabPane).


<!-- Sent from Reviewable.io -->

2023-03-24 22:10 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 100 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721#-NRETAzX3NJtQ1ZOZJ3f:-NRKf46e-TjEAlexGbcA:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4dbc3ba59d743f2b858241c9dc81ec6ab211351e/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L100)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Will do. But I thought that there would be multiple reasons...
We'll figure that out when we HAVE multiple reasons. :)
Went with `tooltipIfCannotSaveBook` in BookButton (and CollectionsTabPane).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-24 22:14 UTC, andrew-polk approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 100 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5721#-NRETAzX3NJtQ1ZOZJ3f:-NRKfXtmBGrF6vuZCmjo:bt018tr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/4dbc3ba59d743f2b858241c9dc81ec6ab211351e/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L100)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The fact that we might have a variety of reasons for disabling is why I want to make the prop name as generic as the context allows.


<!-- Sent from Reviewable.io -->

2023-03-24 22:14 UTC, merged