Library publish features (BL-11582)
BloomBooks/BloomDesktop pull request #5725
Opened 2023-03-24 14:23 UTC by JohnThomson

2023-03-24 14:53 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: 0 of 28 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 371 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRJ5wM6AVlBlGK87noT:-NRJ5wM6AVlBlGK87noU:b-nh2kjs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f0ae3a82f3654bd6e803891a181a7a66149e813f/src/BloomExe/web/controllers/LibraryPublishApi.cs#L371)):*
> ```Smalltalk
> 			if (Model.BookIsAlreadyOnServer)
> 			{
> 				// TODO
> ```

All the TODOs in this file need to be implemented.
Also, could you make a quick pass through the code review comments I made in the original PR to see if any of them still need addressing?


<!-- Sent from Reviewable.io -->

2023-03-27 14:49 UTC, andrew-polk commented
*[`DistFiles/localization/en/Bloom.xlf` line 3532 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL3s4mBu9aPCRMEDSj:-NRL3s4mBu9aPCRMEDSk:b-tnmhqm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/DistFiles/localization/en/Bloom.xlf#L3532)):*
> ```XML
>       </trans-unit>
>       <!-- 5.5 -->
>       <trans-unit id="PublishTab.AccessibleVisually">
> ```

missed `translate="no"`


<!-- Sent from Reviewable.io -->

2023-03-27 14:49 UTC, andrew-polk commented
*[`DistFiles/localization/en/Bloom.xlf` line 3728 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL3pk86wlLDywaoALw:-NRL3pk86wlLDywaoALx:b-injcnw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/DistFiles/localization/en/Bloom.xlf#L3728)):*
> ```XML
>         <note>ID: PublishTab.Android.Settings</note>
>       </trans-unit>
>       <trans-unit id="PublishTab.Android.TalkingBookLanguages" sil:dynamic="true" translate="no">
> ```

Was this added by mistake?



_Code quote:_
```XML
translate="no"
```


<!-- Sent from Reviewable.io -->

2023-03-27 18:29 UTC, andrew-polk reviewed
> Reviewed 3 of 28 files at r1, 23 of 25 files at r2, 7 of 8 files at r3, 12 of 12 files at r4, 12 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: 25 of 28 files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx` line 114 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL-Hdq5VsmAu3wHbJ8:-NRL-Hdq5VsmAu3wHbJ9:b540zgt) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx#L114)):*
> ```XML
>                         >
>                             <path d="M0.847656 5.83079V11.8308H4.84766L9.84766 16.8308V0.830791L4.84766 5.83079H0.847656ZM14.3477 8.83079C14.3477 7.06079 13.3277 5.54079 11.8477 4.80079V12.8508C13.3277 12.1208 14.3477 10.6008 14.3477 8.83079ZM11.8477 0.060791V2.12079C14.7377 2.98079 16.8477 5.66079 16.8477 8.83079C16.8477 12.0008 14.7377 14.6808 11.8477 15.5408V17.6008C15.8577 16.6908 18.8477 13.1108 18.8477 8.83079C18.8477 4.55079 15.8577 0.970791 11.8477 0.060791Z" />
>                         </svg>
> ```

The ideal would be to have all these svgs in their own files.
I assume they got inlined because of the props needing to be changed based on looking disabled or not.
If it really isn't possible to pull them out as separate files, I would like to at least move them to the bottom of this file or even to another file where they don't provide this clutter...

(I wrote the above in Reviewable where the path is wrapped onto multiple lines. So maybe it wouldn't be so bad in an editor with wrapping off... but I still think it would be an improvement to pull them out.)

I see from comments you wrote after I initially wrote these that you have already thought about this. Not going to push for extra work you think is not warranted at this point... but it does seem highly likely we will reuse any of these icons which have similar duplicates elsewhere as soon as JH realizes we have two versions.

Anyway, I do think at least pulling them to the bottom of the file would be cleaner. (But if you're doing that, maybe it isn't much more work to pull them into files... GreyTriangleMenuIcon.tsx is one example where we changed to color of an svg using a prop... but it is pretty ugly... if that's really what it takes, maybe it isn't really worth it.)
___
*[`src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx` line 274 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL07KGDNHcktgaijr2:-NRL07KH0XtUObV6BNNj:b-uahmsn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx#L274)):*
> ```XML
>                                 ${visuallyImpairedEnabled
>                                     ? ""
>                                     : "opacity: 38%;"}
> ```

These opacities want to come from a constant in colorUtils.ts
___
*[`src/BloomBrowserUI/react_components/tickableBox.tsx` line 31 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRKz1Mn8mV01OgM7YDa:-NRKz1Mn8mV01OgM7YDb:b-xsdjtu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomBrowserUI/react_components/tickableBox.tsx#L31)):*
> ```XML
>                 // not displaying the check mark, but that didn't help.
>                 min-height: 26px;
>                 ${props.disabled ? "opacity: 0.38;" : ""}
> ```

This is now a constant in colorUtils.ts



_Code quote:_
```XML
0.38
```
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 135 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL1dgnDgpo3jYOpjeV:-NRL1dgnDgpo3jYOpjeW:b-shdcri) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomExe/web/controllers/LibraryPublishApi.cs#L135)):*
> ```Smalltalk
> 			Model.SetOnlySignLanguageToPublish(collectionSettings.SignLanguageTag);
> 			_webSocketServer.SendString("publish", "signLang", l.DesiredName);
> 			request.PostSucceeded();
> ```

Don't we need to respond right away (before the call to ` CollectionSettingsDialog.ChangeLanguage`) so the request doesn't time out?


<!-- Sent from Reviewable.io -->

2023-03-27 18:33 UTC, andrew-polk reviewed
> Reviewed 2 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: 27 of 28 files reviewed, 8 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Android/AndroidPublishSettings.cs` line 186 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZKvlMC8_-QZwdl2CT:-NRZKvlMC8_-QZwdl2CU:bbm60fs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/src/BloomExe/Publish/Android/AndroidPublishSettings.cs#L186)):*
> ```Smalltalk
> 				var book = bookServer.GetBookFromBookInfo(bookInfo);
> 				BloomLibraryPublishModel.InitializeLanguages(book);
> 			}
> ```

Seems like we should only need one of these if statements now.
But note that I've now had to add a harvester-path check for initialized audio settings.


<!-- Sent from Reviewable.io -->

2023-03-27 18:34 UTC, andrew-polk reviewed
> Reviewed 1 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: all files reviewed, 8 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2023-03-27 22:01 UTC, andrew-polk reviewed
> Reviewed 17 of 18 files at r6, 18 of 18 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx` line 114 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL-Hdq5VsmAu3wHbJ8:-NR_3ZdG2rp4MmCq4WmH:b69lwcp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx#L114)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The ideal would be to have all these svgs in their own files.
I assume they got inlined because of the props needing to be changed based on looking disabled or not.
If it really isn't possible to pull them out as separate files, I would like to at least move them to the bottom of this file or even to another file where they don't provide this clutter...

(I wrote the above in Reviewable where the path is wrapped onto multiple lines. So maybe it wouldn't be so bad in an editor with wrapping off... but I still think it would be an improvement to pull them out.)

I see from comments you wrote after I initially wrote these that you have already thought about this. Not going to push for extra work you think is not warranted at this point... but it does seem highly likely we will reuse any of these icons which have similar duplicates elsewhere as soon as JH realizes we have two versions.

Anyway, I do think at least pulling them to the bottom of the file would be cleaner. (But if you're doing that, maybe it isn't much more work to pull them into files... GreyTriangleMenuIcon.tsx is one example where we changed to color of an svg using a prop... but it is pretty ugly... if that's really what it takes, maybe it isn't really worth it.)
</blockquote></details>

Thanks! (I have no idea why Reviewable is striking through my thanks!)
___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 379 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NR_-ESl-mYaB0eyOM5f:-NR_-ESl-mYaB0eyOM5g:b-7ox7im) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L379)):*
> ```Smalltalk
> 		}
> 
> 		public bool BlindAccessibleToPublish
> ```

I know you inherited this name from the two methods below, but I'm really struggling with it.
Is it something like `IsL1AccessibleToTheBlind`? Or `IsAccessibleToTheBlind`? Or even `IsUserClaimingBlindAccessible`?

(and aren't the two methods now unused -- or at least could be replaced with setting this property everywhere?)
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 135 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL1dgnDgpo3jYOpjeV:-NR_1bXt6BaMb0MV1Au7:b-uqukne) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomExe/web/controllers/LibraryPublishApi.cs#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Don't we need to respond right away (before the call to ` CollectionSettingsDialog.ChangeLanguage`) so the request doesn't time out?
</blockquote></details>

(this now applies to PublishApi)
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 34 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NR_2ASI60hJA2f3l4Bk:-NR_2ASI60hJA2f3l4Bl:b-9zkho9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/acd9b02aeb04cb9034687de495f19c8a2351d3c1/src/BloomExe/web/controllers/LibraryPublishApi.cs#L34)):*
> ```Smalltalk
> 		private IProgress _progress;
> 
> 		private bool _signLanguageChecked;
> ```

I don't think this gets set.
___
*[`src/BloomTests/Book/BookInfoTests.cs` line 510 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NR_37sF-XI7thzDus4u:-NR_37sG1R9Izm7gvUQu:b-pllb6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5d25eac5e486657ce77b2131d07dac08a0069ee5/src/BloomTests/Book/BookInfoTests.cs#L510)):*
> ```Smalltalk
> 			Assert.AreEqual(featuresExpected, featuresResult, "Features");
> 			Assert.AreEqual(featuresExpected.Any(), featureBlindResult, "Feature_Blind");
> 		}
> ```

Should we be adding any blind feature tests to offset all these which are being removed?
(Sorry, it hard to fully understand exactly what is changing at the model level.)
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 130 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZwZxV1FdLtv5JWKjO:-NRZwZxV1FdLtv5JWKjP:btx9bs0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx#L130)):*
> ```XML
>             );
>         } else {
>             slTitle = slPresent;
> ```

I wonder if it is better to make the whole thing a link in this pathological case. 
Same for the other string below.
Thoughts?
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 151 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZxBxXA2aXaLU6uwPj:-NRZxBxXA2aXaLU6uwPk:b-cbru68) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx#L151)):*
> ```XML
>                         </MuiLink>
>                         {match[3]}
>                     </React.Fragment>
> ```

Maybe worth pulling this little fragment out into a reusable component?


<!-- Sent from Reviewable.io -->

2023-03-27 22:15 UTC, JohnThomson reviewed
I should probably do some more testing before we merge this, but I'm not sure what. There's lots of changes to take a look at, anyway, so I may as well put it out there to look at.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-:-NR_4tz05GdKXGvIlsba:b-hdqhv0)* status: 41 of 44 files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`DistFiles/localization/en/Bloom.xlf` line 3532 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL3s4mBu9aPCRMEDSj:-NRZnHLj1AJyOQJknXU0:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/DistFiles/localization/en/Bloom.xlf#L3532)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

missed `translate="no"`
</blockquote></details>

Done.
___
*[`DistFiles/localization/en/Bloom.xlf` line 3728 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL3pk86wlLDywaoALw:-NRZnVon8A0XAm4TFhZ6:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/DistFiles/localization/en/Bloom.xlf#L3728)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Was this added by mistake?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx` line 114 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL-Hdq5VsmAu3wHbJ8:-NR_4qWw0VdzO52Iaivt:b-pmiv0x) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx#L114)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks! (I have no idea why Reviewable is striking through my thanks!)
</blockquote></details>

Done. (I think you somehow managed to get your response in before my original response, which may have confused Reviewable.)
___
*[`src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx` line 274 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL07KGDNHcktgaijr2:-NRZuesWDy-a2AVuSOiS:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomBrowserUI/publish/ReaderPublish/PublishFeaturesGroup.tsx#L274)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These opacities want to come from a constant in colorUtils.ts
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/tickableBox.tsx` line 31 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRKz1Mn8mV01OgM7YDa:-NRZpyTu5lf-9g9trGP-:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomBrowserUI/react_components/tickableBox.tsx#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is now a constant in colorUtils.ts
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Android/AndroidPublishSettings.cs` line 186 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZKvlMC8_-QZwdl2CT:-NRZqDpGEWxq1NcqfLgO:bhzlnsl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/src/BloomExe/Publish/Android/AndroidPublishSettings.cs#L186)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like we should only need one of these if statements now.
But note that I've now had to add a harvester-path check for initialized audio settings.
</blockquote></details>

I don't see two statements that look redundant. Maybe whatever you meant got cleaned up in rebasing or something?
___
*[`src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs` line 379 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NR_-ESl-mYaB0eyOM5f:-NR_5oaTDxyftz-rTw_n:beuc4qe) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomExe/Publish/BloomLibrary/BloomLibraryPublishModel.cs#L379)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know you inherited this name from the two methods below, but I'm really struggling with it.
Is it something like `IsL1AccessibleToTheBlind`? Or `IsAccessibleToTheBlind`? Or even `IsUserClaimingBlindAccessible`?

(and aren't the two methods now unused -- or at least could be replaced with setting this property everywhere?)
</blockquote></details>

I had a go.
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 371 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRJ5wM6AVlBlGK87noT:-NRJ_OIPEwalBsJ5J-et:b-7y6s8v) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f0ae3a82f3654bd6e803891a181a7a66149e813f/src/BloomExe/web/controllers/LibraryPublishApi.cs#L371)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

All the TODOs in this file need to be implemented.
Also, could you make a quick pass through the code review comments I made in the original PR to see if any of them still need addressing?
</blockquote></details>

I think I have done all that.
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 135 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRL1dgnDgpo3jYOpjeV:-NRZucm9ArWLaZ0S1ndt:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/238f3060f81bea99ed06e20651384e0fcaac21e6/src/BloomExe/web/controllers/LibraryPublishApi.cs#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Don't we need to respond right away (before the call to ` CollectionSettingsDialog.ChangeLanguage`) so the request doesn't time out?
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 34 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NR_2ASI60hJA2f3l4Bk:-NR_606d9c2-Hno9b85K:b-34617l) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/acd9b02aeb04cb9034687de495f19c8a2351d3c1/src/BloomExe/web/controllers/LibraryPublishApi.cs#L34)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think this gets set.
</blockquote></details>

Yes, the constructor sets it.
___
*[`src/BloomTests/Book/BookInfoTests.cs` line 510 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NR_37sF-XI7thzDus4u:-NR_69Wy5Y3JCEnZ52md:b-u55odp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5d25eac5e486657ce77b2131d07dac08a0069ee5/src/BloomTests/Book/BookInfoTests.cs#L510)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we be adding any blind feature tests to offset all these which are being removed?
(Sorry, it hard to fully understand exactly what is changing at the model level.)
</blockquote></details>

This was testing a particular method which no longer has this responsibility. We're now setting the feature more directly. There may be something that deserves a new unit test, but I'm not sure what.
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 130 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZwZxV1FdLtv5JWKjO:-NR_6WCg35hamJ3vpxaA:b-hwdyyn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I wonder if it is better to make the whole thing a link in this pathological case. 
Same for the other string below.
Thoughts?
</blockquote></details>

Maybe @hatton ? I'm just following the mockup JohnH did in Zulip
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 151 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZxBxXA2aXaLU6uwPj:-NR_6v3t9km3kMOBI2co:bkgy5gv) ([raw file](https [...]

2023-03-27 22:38 UTC, andrew-polk reviewed
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: all files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomExe/Publish/Android/AndroidPublishSettings.cs` line 186 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZKvlMC8_-QZwdl2CT:-NR_9mQE9_BMU6lFS_KJ:b-w6s12p) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/src/BloomExe/Publish/Android/AndroidPublishSettings.cs#L186)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't see two statements that look redundant. Maybe whatever you meant got cleaned up in rebasing or something?
</blockquote></details>

Before your change, we had one check to initialize bloompub settings if they weren't initialized and another for bloomlibrary.
Now, we only care about bloomlibrary, so both if statements check the same settings (bloomlibrary) and initialize if needed.

(Setting apart the new check for audio for a moment...) I think the second whole check and code could go away and we wouldn't lose anything. But it is hard to know because I'm not sure what the difference is now between `PublishApi.InitializeLanguagesInBook` and `BloomLibraryPublishModel.InitializeLanguages`. Sorry; I'm probably being lazy by not looking myself...
Anyway, the way it is written, the second if will never be true because `PublishApi.InitializeLanguagesInBook` will ensure `bookInfo.PublishSettings.BloomLibrary.TextLangs` get initialized.

(But now we do need to ensure the audio gets set up as well.)
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 34 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NR_2ASI60hJA2f3l4Bk:-NR_B4OyDkaZ6LG3_qbK:b-ixqxr7) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/acd9b02aeb04cb9034687de495f19c8a2351d3c1/src/BloomExe/web/controllers/LibraryPublishApi.cs#L34)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, the constructor sets it.
</blockquote></details>

Sorry; I'm not seeing that in the published version of the code here: 
```
		public LibraryPublishApi(BloomWebSocketServer webSocketServer, PublishView publishView)
		{
			_publishView = publishView;
			_webSocketServer = webSocketServer;
			var progress = new WebSocketProgress(_webSocketServer, kWebSocketContext);
			_webSocketProgress = progress.WithL10NPrefix("PublishTab.Upload.");
			_webSocketProgress.LogAllMessages = true;
			_progress = new WebProgressAdapter(_webSocketProgress);
		}

```
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 130 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZwZxV1FdLtv5JWKjO:-NR_BgPu6HkHAgAogwK1:b-79ed1u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx#L130)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe @hatton ? I'm just following the mockup JohnH did in Zulip
</blockquote></details>

Sorry; either I'm misunderstanding or I'm failing to communicate.
I'm only talking about the pathological case where the translator failed to include the `{N}` (the else of the `if (match)`. If I'm reading the code correctly, it seems there will then be no link. I'm suggesting that in that case we just make the whole string the link.
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 151 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZxBxXA2aXaLU6uwPj:-NR_CMsfBaYXS3pKh5ak:bss00at) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx#L151)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not sure. Just now I did similar things twice, but they are just enough different to make reusability difficult. For a small fragment, there are a lot of variables: is the bit in braces translatable, or to be replaced (with what?)? Do we want to replace with a link that has an href, or an onClick, or...? Will we settle on a font size or let the client control it? It feels messy enough that I'm inclined to wait for another example before attempting it.
</blockquote></details>

I only meant a component in this file.
It would also have the advantage of moving the `showSignLanguageChooser` function with it.
But I'm not going to push if you don't think it is worth it.


<!-- Sent from Reviewable.io -->

2023-03-28 15:50 UTC, andrew-polk reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: all files reviewed, 4 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`src/BloomBrowserUI/react_components/muiCheckBox.tsx` line 149 at r9](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRct2Ag5plrc4Zj9aOD:-NRct2Ag5plrc4Zj9aOE:b-t81aw9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c33b80020d2df6e4cbeb7d721a8074286d75f124/src/BloomBrowserUI/react_components/muiCheckBox.tsx#L149)):*
> ```XML
>         // checkbox that we might cross over on the way.
>         // (Note the same delays are currently used in TickableBox, which is sometimes
>         // used in the same list, so they should probably be kept in sync.)
> ```

Sorry to drag this out more... that's one of the unfortunate things about large PRs... there can be a lot of stuff to comment on and then I start to feel bad about suggesting things...

It seems like these delay settings should either be
1. Universal to LightToolTip
2. Specific to the feature list

In other words, it shouldn't be dependent upon which component the tooltip happens to be on.

So, you could either move the settings into LightToolTip or pass some kind of prop which tells muCheckBox or tickableBox we need these delays. Obviously the former is simpler if there is no significant downside. 


<!-- Sent from Reviewable.io -->

2023-03-28 20:34 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: 37 of 44 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomBrowserUI/react_components/muiCheckBox.tsx` line 149 at r9](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRct2Ag5plrc4Zj9aOD:-NRcx1p-9H_ABx4yVXdm:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c33b80020d2df6e4cbeb7d721a8074286d75f124/src/BloomBrowserUI/react_components/muiCheckBox.tsx#L149)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry to drag this out more... that's one of the unfortunate things about large PRs... there can be a lot of stuff to comment on and then I start to feel bad about suggesting things...

It seems like these delay settings should either be
1. Universal to LightToolTip
2. Specific to the feature list

In other words, it shouldn't be dependent upon which component the tooltip happens to be on.

So, you could either move the settings into LightToolTip or pass some kind of prop which tells muCheckBox or tickableBox we need these delays. Obviously the former is simpler if there is no significant downside. 
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Android/AndroidPublishSettings.cs` line 186 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZKvlMC8_-QZwdl2CT:-NRdv7-EBE4CpF6kBw1Q:bpuehz9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/src/BloomExe/Publish/Android/AndroidPublishSettings.cs#L186)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Before your change, we had one check to initialize bloompub settings if they weren't initialized and another for bloomlibrary.
Now, we only care about bloomlibrary, so both if statements check the same settings (bloomlibrary) and initialize if needed.

(Setting apart the new check for audio for a moment...) I think the second whole check and code could go away and we wouldn't lose anything. But it is hard to know because I'm not sure what the difference is now between `PublishApi.InitializeLanguagesInBook` and `BloomLibraryPublishModel.InitializeLanguages`. Sorry; I'm probably being lazy by not looking myself...
Anyway, the way it is written, the second if will never be true because `PublishApi.InitializeLanguagesInBook` will ensure `bookInfo.PublishSettings.BloomLibrary.TextLangs` get initialized.

(But now we do need to ensure the audio gets set up as well.)
</blockquote></details>

I made the changes I thought appropriate to the Model version and made the other just call it.
With your change to include RequiredLanguages in AllPublishableLanguages I think we should be good.
___
*[`src/BloomExe/web/controllers/LibraryPublishApi.cs` line 34 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NR_2ASI60hJA2f3l4Bk:-NRcxg_t3IhRPh4QU28r:b-pxoe3w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/acd9b02aeb04cb9034687de495f19c8a2351d3c1/src/BloomExe/web/controllers/LibraryPublishApi.cs#L34)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I'm not seeing that in the published version of the code here: 
```
		public LibraryPublishApi(BloomWebSocketServer webSocketServer, PublishView publishView)
		{
			_publishView = publishView;
			_webSocketServer = webSocketServer;
			var progress = new WebSocketProgress(_webSocketServer, kWebSocketContext);
			_webSocketProgress = progress.WithL10NPrefix("PublishTab.Upload.");
			_webSocketProgress.LogAllMessages = true;
			_progress = new WebProgressAdapter(_webSocketProgress);
		}

```
</blockquote></details>

Sorry, was in a hurry last night and thought you were talking about _progress. Fixed.
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 130 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZwZxV1FdLtv5JWKjO:-NRcvrg3D2QfsQYTk6iq:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; either I'm misunderstanding or I'm failing to communicate.
I'm only talking about the pathological case where the translator failed to include the `{N}` (the else of the `if (match)`. If I'm reading the code correctly, it seems there will then be no link. I'm suggesting that in that case we just make the whole string the link.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 151 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZxBxXA2aXaLU6uwPj:-NRcvx7CBWYNiyYBQC-e:bk6f99s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx#L151)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I only meant a component in this file.
It would also have the advantage of moving the `showSignLanguageChooser` function with it.
But I'm not going to push if you don't think it is worth it.
</blockquote></details>

I've reorganized the code a bit. See what you think.


<!-- Sent from Reviewable.io -->

2023-03-28 21:04 UTC, andrew-polk reviewed
> Reviewed 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/react_components/muiCheckBox.tsx` line 149 at r9](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRct2Ag5plrc4Zj9aOD:-NRdwdKm0mOo3O0XyU4j:beogt0h) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c33b80020d2df6e4cbeb7d721a8074286d75f124/src/BloomBrowserUI/react_components/muiCheckBox.tsx#L149)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you missed removing them from muiCheckBox.
___
*[`src/BloomExe/Publish/Android/AndroidPublishSettings.cs` line 186 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZKvlMC8_-QZwdl2CT:-NRe0DgO-l7T40VzCV5n:by3aq6w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/src/BloomExe/Publish/Android/AndroidPublishSettings.cs#L186)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I made the changes I thought appropriate to the Model version and made the other just call it.
With your change to include RequiredLanguages in AllPublishableLanguages I think we should be good.
</blockquote></details>

Sigh. Communication is hard.
Let me try again.

I think the content of this method should now be:
```
			// Normally this is setup by the Publish (or library) screen, but if you've never visited such a screen for this book,
			// then this will be empty. In that case, initialize it here.
			// (also needed for setting the defaults for harvester for older books before the user could set settings)
			if (bookInfo.PublishSettings.BloomLibrary.TextLangs.Count == 0 || bookInfo.PublishSettings.BloomLibrary.AudioLangs.Count == 0)
			{
				var book = bookServer.GetBookFromBookInfo(bookInfo);
				BloomLibraryPublishModel.InitializeLanguages(book);
			}
			return FromBookInfo(bookInfo);
		}

```
Reasoning:
1. harvester no longer matters since we only ever use the library settings
2. we always want to ensure text and audio are initialized
3. the code inside the two ifs now do the same thing
___
*[`src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx` line 151 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZxBxXA2aXaLU6uwPj:-NRdwIYDC4COXJVfk6Je:bmqs2w9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/24e6e7a5c7bb3b821c73dc13afe453a075173285/src/BloomBrowserUI/publish/commonPublish/PublishFeaturesGroup.tsx#L151)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I've reorganized the code a bit. See what you think.
</blockquote></details>

Looks good. Thanks


<!-- Sent from Reviewable.io -->

2023-03-30 16:15 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: 42 of 44 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/react_components/muiCheckBox.tsx` line 149 at r9](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRct2Ag5plrc4Zj9aOD:-NRnFYgO1vzB680k81Fd:b-azo4un) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c33b80020d2df6e4cbeb7d721a8074286d75f124/src/BloomBrowserUI/react_components/muiCheckBox.tsx#L149)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think you missed removing them from muiCheckBox.
</blockquote></details>

Well, I changed them...just missed saving the changes :-).
___
*[`src/BloomExe/Publish/Android/AndroidPublishSettings.cs` line 186 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRZKvlMC8_-QZwdl2CT:-NRnIHeR4KL4X6fcVnTj:bxwwypr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ca4cedaaf37e24b06322fe08c331172a8ed79a89/src/BloomExe/Publish/Android/AndroidPublishSettings.cs#L186)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sigh. Communication is hard.
Let me try again.

I think the content of this method should now be:
```
			// Normally this is setup by the Publish (or library) screen, but if you've never visited such a screen for this book,
			// then this will be empty. In that case, initialize it here.
			// (also needed for setting the defaults for harvester for older books before the user could set settings)
			if (bookInfo.PublishSettings.BloomLibrary.TextLangs.Count == 0 || bookInfo.PublishSettings.BloomLibrary.AudioLangs.Count == 0)
			{
				var book = bookServer.GetBookFromBookInfo(bookInfo);
				BloomLibraryPublishModel.InitializeLanguages(book);
			}
			return FromBookInfo(bookInfo);
		}

```
Reasoning:
1. harvester no longer matters since we only ever use the library settings
2. we always want to ensure text and audio are initialized
3. the code inside the two ifs now do the same thing
</blockquote></details>

Sorry to be so dense. Done.


<!-- Sent from Reviewable.io -->

2023-03-30 16:24 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Publish/Android/AndroidPublishSettings.cs` line 173 at r11](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRnK6Q_6N-lDaAe3XLP:-NRnK6Q_6N-lDaAe3XLQ:bm6moeg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5cae268f8567797042bb53c1445d2a89724b40e1/src/BloomExe/Publish/Android/AndroidPublishSettings.cs#L173)):*
> ```Smalltalk
> 			// Normally this is setup by the Publish (or library) screen, but if you've never visited such a screen for this book,
> 			// perhaps because you are doing a bulk or command line publish, then one of them might be empty. In that case, initialize it here.
> 			if (bookInfo.PublishSettings.BloomPub.TextLangs.Count == 0 || bookInfo.PublishSettings.BloomLibrary.AudioLangs.Count == 0)
> ```

Somehow this was inadvertently changed to BloomPub instead of BloomLibrary in this last round.



_Code quote:_
```Smalltalk
BloomPub
```


<!-- Sent from Reviewable.io -->

2023-03-30 16:27 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: 43 of 44 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/Publish/Android/AndroidPublishSettings.cs` line 173 at r11](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725#-NRnK6Q_6N-lDaAe3XLP:-NRnL06lD79uum4H_DCo:b-dtzlxc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/5cae268f8567797042bb53c1445d2a89724b40e1/src/BloomExe/Publish/Android/AndroidPublishSettings.cs#L173)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Somehow this was inadvertently changed to BloomPub instead of BloomLibrary in this last round.
</blockquote></details>

Good catch. Sorry.


<!-- Sent from Reviewable.io -->

2023-03-30 16:27 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2023-03-30 18:35 UTC, andrew-polk approved these changes
> Reviewed 11 of 11 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2023-03-30 18:37 UTC, merged