BL-12053 Fix Shift+Enter
BloomBooks/BloomDesktop pull request #5731
Opened 2023-03-28 19:20 UTC by gmartin7

* The old code was actually adding the right span,
   but AFTER the paragraph element it was supposed to be
   inserting INTO.

2023-03-28 19:52 UTC, andrew-polk requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 92 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731#-NRdlQjQ38kzLujpze9g:-NRdlQjQ38kzLujpze9h:b-66kqgi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/71325bc284883e06cafdefb9b776742161f6c975/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L92)):*
> ```XML
>         // We put in a specially marked span which stylesheets can use to give us "soft return" in the
>         // midst of paragraphs which have either indents or prefixes (like "step 1", "step 2").
>         // We had to move away from deprecated code (execCommand), when it didn't work in WebView2.
> ```

Say more. We have lots of execCommand calls.

Seems like we should have had a unit test to cover this.
Can we add one now?



_Code quote:_
```XML
We had to move away from deprecated code (execCommand), when it didn't work in WebView2.
```


<!-- Sent from Reviewable.io -->

2023-03-28 21:36 UTC, jsubloom reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 92 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731#-NRdlQjQ38kzLujpze9g:-NRe88kGDgh5qUfEm8WP:b-svpcei) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/71325bc284883e06cafdefb9b776742161f6c975/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L92)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Say more. We have lots of execCommand calls.

Seems like we should have had a unit test to cover this.
Can we add one now?
</blockquote></details>

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
^ says it's deprecated

Quite concerning about the other calls actually.
___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 94 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731#-NRe8IEHEcEjebX-0LNW:-NRe8IEHEcEjebX-0LNX:b62rshz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/71325bc284883e06cafdefb9b776742161f6c975/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L94)):*
> ```XML
>         // We had to move away from deprecated code (execCommand), when it didn't work in WebView2.
>         const sel = window.getSelection();
>         const range = sel?.getRangeAt(0);
> ```

Optional: A null guard would remove a lot of ?. operators (which add a lot of theoretical branches -> theoretical complexity) and also allow one to skip creating the element if it's not actually needed.


<!-- Sent from Reviewable.io -->

2023-03-29 17:03 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @jsubloom)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts` line 92 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731#-NRdlQjQ38kzLujpze9g:-NRiJk8I8n2Gea1gdJU4:bc0ts92) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/71325bc284883e06cafdefb9b776742161f6c975/src/BloomBrowserUI/bookEdit/bloomField/BloomField.ts#L92)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand
^ says it's deprecated

Quite concerning about the other calls actually.
</blockquote></details>

I explained a bit better what's happening here.


<!-- Sent from Reviewable.io -->

2023-03-29 18:04 UTC, jsubloom approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts` line 394 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731#-NRiXHtt6qOyhlov3qBL:-NRiXHtt6qOyhlov3qBM:by9bfcz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd77e236d174e1982d5e31f889f4b35fefa6b147/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L394)):*
> ```XML
>                 // in favor of key, so KeyboardEventInit doesn't officially recognize it in the type
>                 // definition, but we need it anyway, so just force the types to work.
>                 // Review: (gjm) is the above comment still valid? I see no 'which' here.
> ```

I guess not. You can change it to:
const keyEventInit: KeyboardEventInit = { ...}


<!-- Sent from Reviewable.io -->

2023-03-29 18:12 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2023-03-29 21:13 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @jsubloom)

___
*[`src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts` line 394 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731#-NRiXHtt6qOyhlov3qBL:-NRjCqQL3PUu4Sshgkfh:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/bd77e236d174e1982d5e31f889f4b35fefa6b147/src/BloomBrowserUI/bookEdit/bloomField/bloomFieldSpec.ts#L394)):*
<details><summary><i>Previously, jsubloom wrote…</i></summary><blockquote>

I guess not. You can change it to:
const keyEventInit: KeyboardEventInit = { ...}
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-29 21:14 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5731)* status: all files reviewed, 1 unresolved discussion (waiting on @jsubloom)



<!-- Sent from Reviewable.io -->

2023-03-29 21:23 UTC, merged