BL-10638 Clear Bookshelf if Enterp. code has changed
BloomBooks/BloomDesktop pull request #5764
Opened 2023-04-14 21:28 UTC by gmartin7

* ApplicationContainer.cs and CollectionSettings.cs
   changes are just white-space.
* If Enterprise code changes, clear out Bookshelf unless
   the branding is still the same
* pull out custom hook to get current project and any
   associated bookshelves.
* put a progress warning in book upload, if there is not a
   valid subscription code, but a bookshelf is in the settings.
* disable menu items if they only apply to an expired code
* add a tooltip to BloomSplitButton that works when it is
   disabled
* disable the Upload button and put up an explanatory
   tooltip if the calls to the api error out or if the collection
   settings specify a bookshelf that isn't a valid one for the
   current (active) subscription (should be very rare)

2023-04-14 22:32 UTC, andrew-polk requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764)* status: all files reviewed, 9 unresolved discussions (waiting on @gmartin7)

___
*[`DistFiles/localization/en/Bloom.xlf` line 406 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0pCKVAxPoYYi5jclc:-NT0pCKVAxPoYYi5jcld:b-9rh037) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/DistFiles/localization/en/Bloom.xlf#L406)):*
> ```XML
>         <note>Name of a Front/Back Matter Pack that is used for talking/animating experiences</note>
>       </trans-unit>
>       <!-- New in 5.5 -->
> ```

If we put "New in 5.5." comment inside the trans-unit, it will make finding and removing translate="no" and the comment really easy.
Same for the other string.

This string should probably go in BloomLowPriority, too.

Should it read, "reach THE server"?
___
*[`DistFiles/localization/en/BloomLowPriority.xlf` line 49 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0pqMk-2ckCVzShTID:-NT0pqMl8RLxR-WK8IT7:b-xkb2iq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/DistFiles/localization/en/BloomLowPriority.xlf#L49)):*
> ```XML
>             <!-- New in 5.5-->
>             <trans-unit id="PublishTab.Upload.BookshelfError" translate="no">
>                 <source xml:lang="en">The collection's bookshelf was not on the list of bookshelves for this Subscription.</source>
> ```

"Subscription" => "Enterprise subscription"?
___
*[`src/BloomBrowserUI/collection/useEnterpriseBookshelves.tsx` line 11 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0sgRQ7oRruzg-qNNY:-NT0sgRQ7oRruzg-qNNZ:b-hil9me) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/collection/useEnterpriseBookshelves.tsx#L11)):*
> ```XML
> }
> 
> export function useEnterpriseBookshelves(): {
> ```

useGetEnterpriseBookshelves
___
*[`src/BloomBrowserUI/collection/useEnterpriseBookshelves.tsx` line 104 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0tBmZEXX2RckzvxuT:-NT0tBmZEXX2RckzvxuU:bagjmvq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/collection/useEnterpriseBookshelves.tsx#L104)):*
> ```XML
>         // This will usually be overwritten soon, but if we can't get to contentful
>         // to get the actual list of possibilities we will leave it here.
>         // Note that as we don't yet have any better label, we use defaultShelf.
> ```

we use defaultBookshelfUrlKey



_Code quote:_
```XML
we use defaultShelf
```
___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 484 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0rvmu7FeH5V8n8CXJ:-NT0rvmu7FeH5V8n8CXK:b17oif2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L484)):*
> ```XML
>                                         bookshelfHasProblem
>                                     }
>                                     title={
> ```

I think we're trying to use BloomToolTip now instead of title.

(and then you can get rid of the prop on bloomSplitButton)
___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 60 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0qG0H590H3HcB8cLb:-NT0qG0H590H3HcB8cLc:b-dupxj1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L60)):*
> ```XML
>     // but `useGetEnterpriseStatus()` returns "Subscription". That state of things is useful for the
>     // CollectionSettingsDialog, but not here in menu items. The absence of enterpriseAvailable needs to
>     // take precedence. But by rules of hooks we still need to run the hook and then modify the value.
> ```

Does it make things simpler to introduce an "Expired" status?
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 206 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0qsn6DWgSTQRFuCuo:-NT0qsn6DWgSTQRFuCup:br7oah8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L206)):*
> ```Smalltalk
> 				{
> 					// At least at this point, we aren't localizing this message, because the people with Enterprise
> 					// bookshelves know enough English to understand this message.
> ```

how about, "likely know enough English"?
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 208 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0qocx-HVI8qKgAMFx:-NT0qocx-HVI8qKgAMFy:bprf4e4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L208)):*
> ```Smalltalk
> 					// bookshelves know enough English to understand this message.
> 					progress.WriteWarning("This book was not uploaded to the '" + collectionSettings.DefaultBookshelf +
> 						"' bookshelf. Uploading to a bookshelf requires a valid Enterprise Subscription.");
> ```

Looks like we usually lower-case "subscription"
___
*[`src/BloomExe/web/controllers/CollectionSettingsApi.cs` line 121 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0rMx6AwqBKX_b3co8:-NT0rMx6AwqBKX_b3co9:b-ydt826) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L121)):*
> ```Smalltalk
> 					// we'll leave it alone, since they probably renewed for another year or so and want to use the
> 					// same bookshelf.
> 					if (DialogBeingEdited != null &&
> ```

How about
```
					if (SubscriptionCode != _collectionSettings.SubscriptionCode && newBranding != oldBranding)
							DialogBeingEdited?.PendingDefaultBookshelf = "";
```

Or can you not do that for an assignment?



_Code quote:_
```Smalltalk
					if (DialogBeingEdited != null &&
						SubscriptionCode != _collectionSettings.SubscriptionCode &&
						newBranding != oldBranding)
							DialogBeingEdited.PendingDefaultBookshelf = "";
```


<!-- Sent from Reviewable.io -->

2023-04-17 20:21 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764)* status: 5 of 13 files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 406 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0pCKVAxPoYYi5jclc:-NTF1Qll-DkLede157tO:bjzzlm1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/DistFiles/localization/en/Bloom.xlf#L406)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If we put "New in 5.5." comment inside the trans-unit, it will make finding and removing translate="no" and the comment really easy.
Same for the other string.

This string should probably go in BloomLowPriority, too.

Should it read, "reach THE server"?
</blockquote></details>

Done. Note that I didn't write this. I only uncommented it. ;)
___
*[`DistFiles/localization/en/BloomLowPriority.xlf` line 49 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0pqMk-2ckCVzShTID:-NTF1jlHBZTSh-iFNj5d:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/DistFiles/localization/en/BloomLowPriority.xlf#L49)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

"Subscription" => "Enterprise subscription"?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 484 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0rvmu7FeH5V8n8CXJ:-NTF6ejaEXEan8imsE_Z:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L484)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we're trying to use BloomToolTip now instead of title.

(and then you can get rid of the prop on bloomSplitButton)
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/react_components/localizableMenuItem.tsx` line 60 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0qG0H590H3HcB8cLb:-NTFY5PyCGRzPCR1WF9d:b-fo8ovf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/react_components/localizableMenuItem.tsx#L60)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does it make things simpler to introduce an "Expired" status?
</blockquote></details>

I don't think so. Not unless we need it elsewhere anyway.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 206 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0qsn6DWgSTQRFuCuo:-NTFYHDN8SL9rIEeH30G:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L206)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

how about, "likely know enough English"?
</blockquote></details>

Done.
___
*[`src/BloomExe/WebLibraryIntegration/BookUpload.cs` line 208 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0qocx-HVI8qKgAMFx:-NTFYLnFCvg6DbEEOtKa:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomExe/WebLibraryIntegration/BookUpload.cs#L208)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like we usually lower-case "subscription"
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/CollectionSettingsApi.cs` line 121 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0rMx6AwqBKX_b3co8:-NTFYf7q6UYtiv-2-DRr:b-6xnxox) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomExe/web/controllers/CollectionSettingsApi.cs#L121)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

How about
```
					if (SubscriptionCode != _collectionSettings.SubscriptionCode && newBranding != oldBranding)
							DialogBeingEdited?.PendingDefaultBookshelf = "";
```

Or can you not do that for an assignment?
</blockquote></details>

The "?" operator can't be on the left-hand side, apparently.
___
*[`src/BloomBrowserUI/collection/useEnterpriseBookshelves.tsx` line 11 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0sgRQ7oRruzg-qNNY:-NTF3eCW1FOXu2jiB7tg:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/collection/useEnterpriseBookshelves.tsx#L11)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

useGetEnterpriseBookshelves
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/collection/useEnterpriseBookshelves.tsx` line 104 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0tBmZEXX2RckzvxuT:-NTF3rUm88lw8i21rZCM:b-nv2lio) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/collection/useEnterpriseBookshelves.tsx#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

we use defaultBookshelfUrlKey
</blockquote></details>

Done. Yeah, copied from elsewhere, but you're right.


<!-- Sent from Reviewable.io -->

2023-04-17 20:22 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764)* status: 5 of 13 files reviewed, 9 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 484 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NT0rvmu7FeH5V8n8CXJ:-NTFsLp14hLL79L7qXZJ:b4f0u27) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/2f67ab030c5bc8c44e46540cda5fcd9c2ab243e5/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L484)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Took a bit, because I had to make the tool tip handle the case where it didn't actually have any text/content to make a tip from.


<!-- Sent from Reviewable.io -->

2023-04-17 21:03 UTC, andrew-polk requested changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764)* status: all files reviewed, 3 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx` line 94 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764#-NTG0igo8RdE08Jq5uTE:-NTG0igp2wW3zoGrMXFu:be6lvit) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/782bcca5b63cdf564e9777345099bb0907cdb25e/src/BloomBrowserUI/publish/LibraryPublish/LibraryPublishSteps.tsx#L94)):*
> ```XML
>         "The collection's bookshelf was not on the list of bookshelves for this Enterprise Subscription.",
>         "PublishTab.Upload.BookshelfError"
>     );
> ```

I think the two const above are no longer used.

While you're making changes, please lowercase the s in subscription for PublishTab.Upload.BookshelfError.
Thanks.


<!-- Sent from Reviewable.io -->

2023-04-18 15:37 UTC, andrew-polk approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5764)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2023-04-18 15:38 UTC, merged