BL-12116 More Polite Preview pane
BloomBooks/BloomDesktop pull request #5791
Opened 2023-04-27 17:17 UTC by gmartin7

* Don't auto start preview; wait for button click
* Fix up layout of preview and orientation buttons
* Move some basic CSS to Emotion
* Leave BPlayer preview blank until Preview button is
   pressed (it actually doesn't even load BPlayer)

2023-04-27 20:42 UTC, andrew-polk requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791)* status: all files reviewed, 6 unresolved discussions (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 33 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3PQmh3qAhHCfYiPFG:-NU3PQmh3qAhHCfYiPFH:b-8u1w1z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a532278de628455793cc424f6f71092e0ce5d456/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L33)):*
> ```XML
>         setLandscape(props.defaultLandscape);
>     }, [props]);
>     const refreshText = useL10n("Refresh", "Common.Refresh");
> ```

Looks like this can now be marked obsolete in the.xlf?
___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 39 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3P38Z8-qg-sWC_RYg:-NU3P38_BaLpMAKXf4JP:b-qj1vjn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L39)):*
> ```XML
>     showPreviewButton?: boolean;
>     highlightRefreshIcon?: boolean;
>     onRefresh?: () => void;
> ```

onPreview? Or onPreviewClicked? Or onPreviewButtonClicked?
___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 89 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3Ou3R3hGzAyAqLvUX:-NU3Ou3R3hGzAyAqLvUY:b-k9im8n) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L89)):*
> ```XML
>                         l10nKey="Common.Preview"
>                         enabled={true}
>                         onClick={() => props.onRefresh && props.onRefresh()}
> ```

props.onRefresh?.()



_Code quote:_
```XML
props.onRefresh && props.onRefresh()
```
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx` line 75 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3OBBf0Te2WHYLwBlP:-NU3OBBf0Te2WHYLwBlQ:b-54b3fm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx#L75)):*
> ```XML
> const EPUBPublishScreenInternal: React.FunctionComponent<{
>     onReset: () => void;
>     previewEnabled: boolean;
> ```

At first I thought this had to do with the preview button being enabled.
How about `isPreviewShowing` or `showPreview`?


Same for ReaderPublishScreen.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx` line 82 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3OQ-X8SnLeGU3eZRG:-NU3OQ-Y2LpPmv_1q1kl:blz5mdi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx#L82)):*
> ```XML
>     const [closePending, setClosePending] = useState(false);
>     const [highlightRefresh, setHighlightRefresh] = useState(false);
>     const [progressState, setProgressState] = useState(ProgressState.Done);
> ```

Maybe a comment like, 
Starting in the Done state hides the progress dialog initially.

Same for ReaderPublishScreen.
___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 151 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3NZkhBNn2-DtCfO-3:-NU3NZkhBNn2-DtCfO-4:btlzv3n) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L151)):*
> ```XML
>             <PreviewPanel>
>                 <StyledEngineProvider injectFirst>
>                     <ThemeProvider theme={darkTheme}>
> ```

Now that we no longer have the dark background, can we simplify by removing the ThemeProvider here? If yes, we can also get rid of StyledEngineProvider.

Same for ePUBPublishScreen


<!-- Sent from Reviewable.io -->

2023-04-28 16:09 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791)* status: 2 of 7 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 33 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3PQmh3qAhHCfYiPFG:-NU3fapBEph2v9kEQsmp:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a532278de628455793cc424f6f71092e0ce5d456/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L33)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like this can now be marked obsolete in the.xlf?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 36 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3fAlO88J7XyW_hINN:-NU3fAlO88J7XyW_hINO:b3y7poq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a532278de628455793cc424f6f71092e0ce5d456/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L36)):*
> ```XML
> 
>     const attentionClass = useDrawAttention(
>         props.highlightRefreshIcon ? 1 : 0,
> ```

Also changed this prop to `highlightPreviewButton`.
___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 39 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3P38Z8-qg-sWC_RYg:-NU3e_UC1vpAibIf9vEP:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L39)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

onPreview? Or onPreviewClicked? Or onPreviewButtonClicked?
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx` line 89 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3Ou3R3hGzAyAqLvUX:-NU3guqo0HQnsWvY6kCL:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/commonPublish/DeviceAndControls.tsx#L89)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

props.onRefresh?.()
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx` line 75 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3OBBf0Te2WHYLwBlP:-NU3hQbh4zeavkvJUM9L:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx#L75)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

At first I thought this had to do with the preview button being enabled.
How about `isPreviewShowing` or `showPreview`?


Same for ReaderPublishScreen.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx` line 82 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3OQ-X8SnLeGU3eZRG:-NU3hinmAWbyDGEKnzYd:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx#L82)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe a comment like, 
Starting in the Done state hides the progress dialog initially.

Same for ReaderPublishScreen.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx` line 151 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791#-NU3NZkhBNn2-DtCfO-3:-NU7bVVgCnSsSBAVMZOd:b-f71egw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8d3a4128d282a74bc60d2725160f18c7401512b/src/BloomBrowserUI/publish/ReaderPublish/ReaderPublishScreen.tsx#L151)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Now that we no longer have the dark background, can we simplify by removing the ThemeProvider here? If yes, we can also get rid of StyledEngineProvider.

Same for ePUBPublishScreen
</blockquote></details>

Done. Indeed those lines don't seem to add anything at this point. Good call.


<!-- Sent from Reviewable.io -->

2023-04-28 16:46 UTC, andrew-polk approved these changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2023-04-28 16:47 UTC, andrew-polk approved these changes
> Dismissed @gmartin7 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)



<!-- Sent from Reviewable.io -->

2023-04-28 16:47 UTC, merged