BL-12163 Title page Publish vs Edit
BloomBooks/BloomDesktop pull request #5818
Opened 2023-05-03 22:07 UTC by gmartin7

* removed an obsolete rule

2023-05-03 23:53 UTC, andrew-polk requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5818)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less` line 14 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5818#-NUZ0mzH28iACW5-1mcb:-NUZ0mzH28iACW5-1mcc:b-pyeidm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8eb7656314e65163c0fc4453fe899506f837525b/src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less#L14)):*
> ```Less
> too big. Let's see if we don't need this anymore. WV2 seems to have gotten it right!
> */
>     //font-size: 10.5pt;
> ```

I think maybe this has nothing to do with the switch to WV2?

If I understand correctly, it is left over from when edit was in gecko but pdf generation was in webkit?
So, now that they are both the same (both gecko for <=5.4 or both wv2 for >5.5), we don't need it?

So it should be removed from both here and whatever is setting it to 10pt for pdf generation, right?


<!-- Sent from Reviewable.io -->

2023-05-03 23:55 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5818)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less` line 14 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5818#-NUZ0mzH28iACW5-1mcb:-NUZ1VkO9NumvGRgMH5y:b-8ra4h9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8eb7656314e65163c0fc4453fe899506f837525b/src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think maybe this has nothing to do with the switch to WV2?

If I understand correctly, it is left over from when edit was in gecko but pdf generation was in webkit?
So, now that they are both the same (both gecko for <=5.4 or both wv2 for >5.5), we don't need it?

So it should be removed from both here and whatever is setting it to 10pt for pdf generation, right?
</blockquote></details>

Or if it can't be removed, it at least should be set to the same value in both places?
So does that argue for it being set in basePage.less instead?


<!-- Sent from Reviewable.io -->

2023-05-05 17:39 UTC, gmartin7 reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5818)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less` line 14 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5818#-NUZ0mzH28iACW5-1mcb:-NUgyWGA49IFmz2YVmyq:bqm3huq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8eb7656314e65163c0fc4453fe899506f837525b/src/BloomBrowserUI/bookEdit/css/editPaneGlobal.less#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Or if it can't be removed, it at least should be set to the same value in both places?
So does that argue for it being set in basePage.less instead?
</blockquote></details>

`basePage.less` sets font-size to 1em. That seems to be what is 'active' in edit and in pdf generation and in collection tab preview.


<!-- Sent from Reviewable.io -->

2023-05-05 17:40 UTC, gmartin7 commented
Closing this PR in favor of one on `5.4`.

2023-05-05 17:40 UTC, closed without merging