BL-12286 save epub without preview first fix
BloomBooks/BloomDesktop pull request #5903
Opened 2023-06-05 23:14 UTC by nabalone

Fixes Publish epub throws NullReferenceException unless you first preview
Corrects progress modal behavior
Makes epub not regenerate if settings have not changed
Fixes progress messages that were not displaying in the progress modal

2023-06-05 23:17 UTC, nabalone commented on src/BloomBrowserUI/publish/ePUBPublish/ePUBPublishScreen.tsx
Most of these changes copy https://github.com/BloomBooks/BloomDesktop/pull/5876

2023-06-05 23:18 UTC, nabalone commented on src/BloomExe/Book/PublishSettings.cs
> +			if (ReferenceEquals(null, obj)) return false;
I was thinking that null EpubSettings should not be equal to anything, is that what we want? I'm also not sure if this line is necessary. Also on line 407

2023-06-05 23:22 UTC, nabalone commented on src/BloomExe/Publish/Epub/PublishEpubApi.cs
> +		{
Should we have a `Debug.Assert(ControlForInvoke != null || Program.RunningUnitTests || Program.RunningOnUiThread);` here? If so, what is `Debug` and where does it come from?

2023-06-05 23:24 UTC, nabalone commented on src/BloomExe/Publish/Epub/PublishEpubApi.cs
> +			if (!_stagingEpub && _pendingSaveAsPath != null) // this should only happen if an output path was chosen
Should this block take the `_epubMakerLock`? I think it is not necessary, as worst case we run `RefreshPreview` unnecesarily. But I may not have thought of all the race conditions. `RefreshPreview` is a pretty long block to put in a lock

2023-06-05 23:27 UTC, nabalone commented on src/BloomExe/Publish/Epub/PublishEpubApi.cs
> +				_standardProgress.Message("PublishTab.Epub.Done", "Done");
Would it be better to do something like 
```
progress = _standardProgress.WithL10NPrefix("PublishTab.Epub.");
progress.Message("Done", "Done");
```
Similarly on lines 404 and 449
```

2023-06-06 19:25 UTC, andrew-polk requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[`src/BloomExe/Book/PublishSettings.cs` line 398 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218696681:-NXH9vlk1Ub-Vd6OquYL:bviqm78) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Book/PublishSettings.cs#L398)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I was thinking that null EpubSettings should not be equal to anything, is that what we want? I'm also not sure if this line is necessary. Also on line 407
</blockquote></details>

JH just pulled out all these overrides.
I'm in discussion with him about the best way forward.
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 175 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218702041:-NXH5rw40a3dg24Pyb3h:b-w2keb6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L175)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Should this block take the `_epubMakerLock`? I think it is not necessary, as worst case we run `RefreshPreview` unnecesarily. But I may not have thought of all the race conditions. `RefreshPreview` is a pretty long block to put in a lock
</blockquote></details>

This is a mess. (Not your fault, as it preexisted this change...)
We have a method called `RefreshPreview` which is relied upon to do the save... yuck.

I'm going to ask @JohnThomson to review this aspect and see if he can make sense of it since
1. I'm pretty sure he did all this locking, etc. to fix some issues with cancellation/restarting/leaving the page.
2. He is much better at parsing existing code than me.
3. He is also much better at understanding locking than me.
4. I'm lost.

Another existing problem I see:
We call `request.PostSucceeded();` after the user selects a destination file and the file is saved. This could easily time out.
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 196 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218703015:-NXH2b41EIeTygm_Rc6u:b-o4zdop) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L196)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Would it be better to do something like 
```
progress = _standardProgress.WithL10NPrefix("PublishTab.Epub.");
progress.Message("Done", "Done");
```
Similarly on lines 404 and 449
```
```

</blockquote></details>

Unless I'm missing something, we want all calls to use `_progress.Message...` and without the l10n prefix (as you did the other places below).
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 197 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXH4OEI41k1yc7aY3Ah:-NXH4OEI41k1yc7aY3Ai:bpbq0rz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L197)):*
> ReportAnalytics("Save ePUB");

Is there a better place for this?
Doesn't seem like it belongs in getSaveAsPath. 
Rather it wants to be wherever we are actually saving the file.


<!-- Sent from Reviewable.io -->

2023-06-06 19:34 UTC, andrew-polk commented
*[`src/BloomExe/Book/PublishSettings.cs` line 398 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218696681:-NXHBe0k6fM8ll2ymcx8:bwk8ft5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Book/PublishSettings.cs#L398)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

JH just pulled out all these overrides.
I'm in discussion with him about the best way forward.
</blockquote></details>

He doesn't remember. So let's just put back what was there:
(and let's add a #region Equals overrides with a comment stating we are currently doing a comparison of settings to determine if we need to regenerate the staged files -- or whatever is accurate)
```
		public override bool Equals(object obj)
		{
			var other = obj as EpubSettings;
			if (other == null)
				return false;
			return Equals(other);
		}

		protected bool Equals(EpubSettings other)
		{
			return HowToPublishImageDescriptions == other.HowToPublishImageDescriptions && RemoveFontSizes == other.RemoveFontSizes && Mode == other.Mode;
		}

		public override int GetHashCode()
		{
			unchecked
			{
				var hashCode = (int)HowToPublishImageDescriptions;
				hashCode = (hashCode * 397) ^ RemoveFontSizes.GetHashCode();
				hashCode = (hashCode * 397) ^ (Mode != null ? Mode.GetHashCode() : 0);
				return hashCode;
			}
		}

		public static bool operator ==(EpubSettings a, EpubSettings b)
		{
			if (Object.ReferenceEquals(a, b)) return true; // same object, including both null
			// If one is null, but not both, return false. The casts are needed to prevent
			// calling this method again recursively (and infinitely).
			if (((object)a == null) || ((object)b == null))
			{
				return false;
			}

			return a.Equals(b);
		}

		public static bool operator !=(EpubSettings a, EpubSettings b)
		{
			return !(a == b);
		}
```


<!-- Sent from Reviewable.io -->

2023-06-07 20:54 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @JohnThomson, and @nabalone)

___
*[`src/BloomExe/Book/PublishSettings.cs` line 398 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218696681:-NXMMWguBSjFz3vmPe3O:bebrt1w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Book/PublishSettings.cs#L398)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

He doesn't remember. So let's just put back what was there:
(and let's add a #region Equals overrides with a comment stating we are currently doing a comparison of settings to determine if we need to regenerate the staged files -- or whatever is accurate)
```
		public override bool Equals(object obj)
		{
			var other = obj as EpubSettings;
			if (other == null)
				return false;
			return Equals(other);
		}

		protected bool Equals(EpubSettings other)
		{
			return HowToPublishImageDescriptions == other.HowToPublishImageDescriptions && RemoveFontSizes == other.RemoveFontSizes && Mode == other.Mode;
		}

		public override int GetHashCode()
		{
			unchecked
			{
				var hashCode = (int)HowToPublishImageDescriptions;
				hashCode = (hashCode * 397) ^ RemoveFontSizes.GetHashCode();
				hashCode = (hashCode * 397) ^ (Mode != null ? Mode.GetHashCode() : 0);
				return hashCode;
			}
		}

		public static bool operator ==(EpubSettings a, EpubSettings b)
		{
			if (Object.ReferenceEquals(a, b)) return true; // same object, including both null
			// If one is null, but not both, return false. The casts are needed to prevent
			// calling this method again recursively (and infinitely).
			if (((object)a == null) || ((object)b == null))
			{
				return false;
			}

			return a.Equals(b);
		}

		public static bool operator !=(EpubSettings a, EpubSettings b)
		{
			return !(a == b);
		}
```
</blockquote></details>

Will do
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 175 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218702041:-NXMNHmX045YJVptLevI:bd7ver6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L175)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is a mess. (Not your fault, as it preexisted this change...)
We have a method called `RefreshPreview` which is relied upon to do the save... yuck.

I'm going to ask @JohnThomson to review this aspect and see if he can make sense of it since
1. I'm pretty sure he did all this locking, etc. to fix some issues with cancellation/restarting/leaving the page.
2. He is much better at parsing existing code than me.
3. He is also much better at understanding locking than me.
4. I'm lost.

Another existing problem I see:
We call `request.PostSucceeded();` after the user selects a destination file and the file is saved. This could easily time out.
</blockquote></details>

- Should I simply delete the `request.PostSucceeded` line or do we need to make sure to do that elsewhere?
- Looks like a lot of the locking and `pending_save_as_path` was in case the user clicked Save before the preview had finished, which shouldn't be possible now because the Progress Modal blocks the screen while the preview is generating. What are there other multi-threading race conditions we are worried about? The leaving the page scenario?
- I agree that this file is getting pretty tangled. Reassuring to hear because it took me a long time to parse. I would be happy to take a stab at refactoring it if that's what we want to do
- It does feel a little scary that various preview methods are relied upon to do things not suggested by their names
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 196 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218703015:-NXMRZbW56uI845x7uwG:b1dh227) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L196)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Unless I'm missing something, we want all calls to use `_progress.Message...` and without the l10n prefix (as you did the other places below).
</blockquote></details>

When moving the ReportAnalytics per your comment below I deleted this message. Is it helpful to anyone for us to say "Done" right after the user selects a save path?
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 197 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXH4OEI41k1yc7aY3Ah:-NXMPouK9fsL3auwwVV2:bebrt1w) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L197)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ReportAnalytics("Save ePUB");

Is there a better place for this?
Doesn't seem like it belongs in getSaveAsPath. 
Rather it wants to be wherever we are actually saving the file.
</blockquote></details>

Will do


<!-- Sent from Reviewable.io -->

2023-06-07 20:59 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 175 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218702041:-NXMdgYJAuX_FXd1vC7Q:bfkxgff) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L175)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

- Should I simply delete the `request.PostSucceeded` line or do we need to make sure to do that elsewhere?
- Looks like a lot of the locking and `pending_save_as_path` was in case the user clicked Save before the preview had finished, which shouldn't be possible now because the Progress Modal blocks the screen while the preview is generating. What are there other multi-threading race conditions we are worried about? The leaving the page scenario?
- I agree that this file is getting pretty tangled. Reassuring to hear because it took me a long time to parse. I would be happy to take a stab at refactoring it if that's what we want to do
- It does feel a little scary that various preview methods are relied upon to do things not suggested by their names
</blockquote></details>

I see that we do need the request.PostSucceeded. I'm not sure where to put it if we keep the current thread-friendly setup. What would happen if it timed out? 


<!-- Sent from Reviewable.io -->

2023-06-07 21:11 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: 1 of 3 files reviewed, 6 unresolved discussions (waiting on @andrew-polk, @JohnThomson, and @nabalone)

___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 175 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218702041:-NXMffWLAbV6djWRbU84:b-ep3ft8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L175)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I see that we do need the request.PostSucceeded. I'm not sure where to put it if we keep the current thread-friendly setup. What would happen if it timed out? 
</blockquote></details>

My best recollection is that we mainly needed locking because at one point, we started regenerating the preview any time any setting was changed that affected it. I believe now we do it when the user clicks the Preview or Save button, and until we implement Cancel, it's going to run to completion. So we probably don't need locking at all.

It's probably best to call PostSucceeded before we even start creating the Preview, unless we're depending on it to know that the Preview is complete. But it's probably best (if we're not already) to communicate that through a websocket message.

Hope that makes sense. I haven't reread all the code at this point, I'm just going on what I remember.


<!-- Sent from Reviewable.io -->

2023-06-07 21:22 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 155 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218701036:-NXMj19rCGQDCIIzJbnE:b-mlclnp) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L155)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Should we have a `Debug.Assert(ControlForInvoke != null || Program.RunningUnitTests || Program.RunningOnUiThread);` here? If so, what is `Debug` and where does it come from?
</blockquote></details>

I think we would also get to this code when creating artifacts for harvester, so you would need a condition for that. Not sure what it buys us.
Do you ask because there is similar code elsewhere which has this?
`Debug.Assert` runs an assertion only for debug builds. So it is kinda like a sanity check for developers which doesn't cause messaging or crashing during production.
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 196 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218703015:-NXMilpd70cAv8SD5Id0:b-ep13p5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L196)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

When moving the ReportAnalytics per your comment below I deleted this message. Is it helpful to anyone for us to say "Done" right after the user selects a save path?
</blockquote></details>

Good call. I guess we're still sending this message when the generation of the preview completes?


<!-- Sent from Reviewable.io -->

2023-06-07 21:23 UTC, andrew-polk requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @nabalone)



<!-- Sent from Reviewable.io -->

2023-06-10 19:42 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: 2 of 3 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Book/PublishSettings.cs` line 398 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218696681:-NXaig_mAv3WrT9x75PF:bb6un1j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Book/PublishSettings.cs#L398)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 155 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218701036:-NXaili20hob_Xnu_PCd:b-v4y8gi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L155)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we would also get to this code when creating artifacts for harvester, so you would need a condition for that. Not sure what it buys us.
Do you ask because there is similar code elsewhere which has this?
`Debug.Assert` runs an assertion only for debug builds. So it is kinda like a sanity check for developers which doesn't cause messaging or crashing during production.
</blockquote></details>

Yes, I saw Debug.Assert statement in similar code elsewhere. Couldn't figure out where Debug comes from/what I need to import into the file to make it work.

Do I need to do anything else to handle the harvester case here? CreateEpubArtifact takes in a control argument and sets 			maker.ControlForInvoke = control;
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 175 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218702041:-NXaoihl1wwgHEMtPtg6:b9mvtg9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L175)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

My best recollection is that we mainly needed locking because at one point, we started regenerating the preview any time any setting was changed that affected it. I believe now we do it when the user clicks the Preview or Save button, and until we implement Cancel, it's going to run to completion. So we probably don't need locking at all.

It's probably best to call PostSucceeded before we even start creating the Preview, unless we're depending on it to know that the Preview is complete. But it's probably best (if we're not already) to communicate that through a websocket message.

Hope that makes sense. I haven't reread all the code at this point, I'm just going on what I remember.
</blockquote></details>

I have removed the locks. Ebook preview generation ends pretty quickly when you click away from the Epub screen
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 196 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#gh-1218703015:-NXaoyrtCLEhGFRvCOp4:bx0dkzw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L196)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Good call. I guess we're still sending this message when the generation of the preview completes?
</blockquote></details>

Yes, we still send "Done" after preview generation completes
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 197 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXH4OEI41k1yc7aY3Ah:-NXaoswj7OWogQXnuW5x:bb6un1j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff8ada1c276d1bb13c5d0e8161efd1fff9f3a8ea/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L197)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-12 16:37 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 135 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkDgm04NTkGodInu-5:-NXkSyD52RJP3c9OXfmJ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0986079ff00e7eb2206bf473f5b8c23d9f343988/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe worth expounding a little.
Is this the case where the user cancelled during file selection?
Then the UI will know to simply do nothing because it never receives any websocket messages?

So something like:
> No output path means the user cancelled the file chooser dialog. 
> Simply posting a success with no other messages will cause the UI to do nothing further. 

?
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 140 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkD-5WCBt9_1C8ypLd:-NXkT01-2EP5Q6LSgIgv:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0986079ff00e7eb2206bf473f5b8c23d9f343988/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L140)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe worth a comment like:
> // Will only update the staged ePUB files if needed

And then you can also help document the behavior by making this line:
> RefreshPreview(request.CurrentBook.BookInfo.PublishSettings.Epub, forceUpdate:false);
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-12 18:04 UTC, JohnThomson requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @nabalone)

___
*[`src/BloomExe/Book/PublishSettings.cs` line 397 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkfbQnBv2wDOJCSyuS:-NXkfbQnBv2wDOJCSyuT:btypxl8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Book/PublishSettings.cs#L397)):*
> ```Smalltalk
> 
> 		
> 		#region We do a comparison of settings to determine whether the Epub files need to be regenerated
> ```

This is a good start at explaining what is going on, but it needs a little more. Typically, Equals is overridden because you want objects to be equal if all of their fields are equal (rather than only if they are the same object). So it's quite unusual to only take some fields into account. The comment above hints that that the only reason to test equality of two sets of settings is to find out whether they differ in a way that would require the preview to be rebuilt; but that should be said more explicitly. Maybe also spell out why a change of e.g. HowToPublishImageDescriptions would NOT require rebuilding the preview.
You could also consider, instead of redefininig equality, making a method that is clearly specific to this purpose, like RequiresDiffererentPreviewThan(PublishSettings other). Unfortunately that requires finding all the places that are using equality testing for this purpose, which may be difficult. Up to you both whether you like the idea and whether it is worth the effort.
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 142 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkj00o20egXe_l7ZOB:-NXkj00o20egXe_l7ZOC:b-8u908u) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L142)):*
> ```Smalltalk
> 				
> 			// Will only update the staged ePUB files if needed
> 			RefreshPreview(request.CurrentBook.BookInfo.PublishSettings.Epub, forceUpdate:false);
> ```

Is it possible for this to fail, so that there is no preview to save? For example, if the book uses  a font we're not allowed to embed, or enterprise features when that is turned off...Should we detect that here?
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 144 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkjbFR62D6gsxJF-W1:-NXkjbFR62D6gsxJF-W2:b9hfjuz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L144)):*
> ```Smalltalk
> 			RefreshPreview(request.CurrentBook.BookInfo.PublishSettings.Epub, forceUpdate:false);
> 			SaveAsEpub(destPath);
> 			request.PostSucceeded();
> ```

At one point we floated the idea of doing this early, for fear of a timeout while the user is picking a file name, or while we're generating the Epub for a very large book. Did you conclude that was not a good idea? (If you move it before getSaveAsPath(), remember to remove it from the Cancel path as well.)
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 150 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkhpRKBHPRr1XixVna:-NXkhpRKBHPRr1XixVnb:b6pimos) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/01ca7b16840b79935a80546d4dbf6a9b390a988f/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L150)):*
> ```Smalltalk
> 					_webSocketServer.SendString(kWebsocketContext, kWebsocketState_LicenseOK, (message == null) ? "true" : "false");
> 				}
> 			}, false); // in fact, must NOT be on UI thread
> ```

I don't think this has stopped being true, even though one reason went away...in fact we still throw if it happens. It's also not obvious, so I think the comment is worth keeping...maybe even improving, something like "must not be on the UI thread, because it's a long-running task and the UI thread must be available to update the progress dialog, respond to user actions, etc."
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 306 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkks4j6JueIPvLVOVH:-NXkks4j6JueIPvLVOVI:b-3c91tq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L306)):*
> ```Smalltalk
> 			if (EpubMaker != null)
> 				EpubMaker.AbortRequested = false;
> 			_stagingEpub = true;
> ```

Do we still need this variable? Seems like it was all about the detection of multiple threads trying to update the same epub at the same time, and if that can no longer happen, we might be able to get rid of it along with the locking.


<!-- Sent from Reviewable.io -->

2023-06-12 18:15 UTC, andrew-polk reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[`src/BloomExe/Book/PublishSettings.cs` line 397 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkfbQnBv2wDOJCSyuS:-NXknZAU9sBvswgEUN7-:b-kql7o) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Book/PublishSettings.cs#L397)):*
> Maybe also spell out why a change of e.g. HowToPublishImageDescriptions would NOT require rebuilding the preview.

I don't see that we are excluding that property from the check.

> You could also consider, instead of redefininig equality, making a method that is clearly specific to this purpose, like RequiresDiffererentPreviewThan(PublishSettings other). Unfortunately that requires finding all the places that are using equality testing for this purpose, which may be difficult. Up to you both whether you like the idea and whether it is worth the effort.

I really like this idea. Not overriding equals is much simpler.
By the way, John, she is only putting back the override methods which JH removed during his PublishSettings cleanup. But he (apparently) didn't realize we needed it to prevent extraneous preview creations.


<!-- Sent from Reviewable.io -->

2023-06-12 22:47 UTC, JohnThomson requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @nabalone)

___
*[`src/BloomExe/Book/PublishSettings.cs` line 397 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkfbQnBv2wDOJCSyuS:-NXixebN3HY0lgYrFsli:b-o5qh6c) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Book/PublishSettings.cs#L397)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Maybe also spell out why a change of e.g. HowToPublishImageDescriptions would NOT require rebuilding the preview.

I don't see that we are excluding that property from the check.

> You could also consider, instead of redefininig equality, making a method that is clearly specific to this purpose, like RequiresDiffererentPreviewThan(PublishSettings other). Unfortunately that requires finding all the places that are using equality testing for this purpose, which may be difficult. Up to you both whether you like the idea and whether it is worth the effort.

I really like this idea. Not overriding equals is much simpler.
By the way, John, she is only putting back the override methods which JH removed during his PublishSettings cleanup. But he (apparently) didn't realize we needed it to prevent extraneous preview creations.
</blockquote></details>

My bad. I have no idea what I was thinking. Maybe I was using a small window and could only see part of the code? I was in a bit of a hurry.
So, what you have is a perfectly reasonable version of Equals and needs no extra commenting. However, that makes two of us that like the RequiresDiffererentPreviewThan idea, and (since JohnH was removing the Equals override) it's clear that he also found it verbose and confusing...to the point that could not see why it was needed at all. RequiresDiffererentPreviewThan would just need the current definition of Equals, and all the related stuff (overriding operators and GetHashCode etc) can go. The only tricky thing is finding where we are using Equals to mean RequiresDiffererentPreviewThan. Hopefully that's clear from your earlier work or the previous history of this class.


<!-- Sent from Reviewable.io -->

2023-06-13 18:44 UTC, JohnThomson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-:-NXq3_TR-ih6wxEdo0IS:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @nabalone)



<!-- Sent from Reviewable.io -->

2023-06-13 18:48 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Book/PublishSettings.cs` line 397 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkfbQnBv2wDOJCSyuS:-NXpzj0W6ioDYSp4kZUk:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Book/PublishSettings.cs#L397)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

My bad. I have no idea what I was thinking. Maybe I was using a small window and could only see part of the code? I was in a bit of a hurry.
So, what you have is a perfectly reasonable version of Equals and needs no extra commenting. However, that makes two of us that like the RequiresDiffererentPreviewThan idea, and (since JohnH was removing the Equals override) it's clear that he also found it verbose and confusing...to the point that could not see why it was needed at all. RequiresDiffererentPreviewThan would just need the current definition of Equals, and all the related stuff (overriding operators and GetHashCode etc) can go. The only tricky thing is finding where we are using Equals to mean RequiresDiffererentPreviewThan. Hopefully that's clear from your earlier work or the previous history of this class.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 142 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkj00o20egXe_l7ZOB:-NXprucI2VkvoUXDYWtB:b-828vt6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L142)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it possible for this to fail, so that there is no preview to save? For example, if the book uses  a font we're not allowed to embed, or enterprise features when that is turned off...Should we detect that here?
</blockquote></details>

What should we do differently if the RefreshPreview fails? I assume that right now it'll behave the same as if you simply preview (which calls RefreshPreview) and then it fails
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 144 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkjbFR62D6gsxJF-W1:-NXpsaJN9DnFuKDwhOD7:b-dipmg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L144)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

At one point we floated the idea of doing this early, for fear of a timeout while the user is picking a file name, or while we're generating the Epub for a very large book. Did you conclude that was not a good idea? (If you move it before getSaveAsPath(), remember to remove it from the Cancel path as well.)
</blockquote></details>

Hmm, I think I did not properly understand the concern the first time. I don't know of any reason not to put it earlier. Done
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 150 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkhpRKBHPRr1XixVna:-NXpuxh146b-E2h9GxbR:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/01ca7b16840b79935a80546d4dbf6a9b390a988f/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L150)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think this has stopped being true, even though one reason went away...in fact we still throw if it happens. It's also not obvious, so I think the comment is worth keeping...maybe even improving, something like "must not be on the UI thread, because it's a long-running task and the UI thread must be available to update the progress dialog, respond to user actions, etc."
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 306 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkks4j6JueIPvLVOVH:-NXpuzK_AQl4Oz1sH2oe:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L306)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Do we still need this variable? Seems like it was all about the detection of multiple threads trying to update the same epub at the same time, and if that can no longer happen, we might be able to get rid of it along with the locking.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-13 18:51 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2023-06-13 18:56 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @nabalone)

___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 142 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkj00o20egXe_l7ZOB:-NXq5wSOCW95s5SRBjZw:bbzckd8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L142)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

What should we do differently if the RefreshPreview fails? I assume that right now it'll behave the same as if you simply preview (which calls RefreshPreview) and then it fails
</blockquote></details>

Hopefully it will have logged some error message to the Progress dialog. The only other thing would be for it NOT to attempt to zip up an epub file out of any incomplete set of files that may have ended up in the preview folder (and don't ask the user to pick a file to save to...but I think we already did that?)


<!-- Sent from Reviewable.io -->

2023-06-13 19:05 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Publish/Epub/PublishEpubApi.cs` line 142 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903#-NXkj00o20egXe_l7ZOB:-NXq7Rqa24Zdd7KweaJr:b1qzjqm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e2e33bc1d81e91c817e56042176a48103dfbdb03/src/BloomExe/Publish/Epub/PublishEpubApi.cs#L142)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Hopefully it will have logged some error message to the Progress dialog. The only other thing would be for it NOT to attempt to zip up an epub file out of any incomplete set of files that may have ended up in the preview folder (and don't ask the user to pick a file to save to...but I think we already did that?)
</blockquote></details>

Now that we aren't locking, we could do the refresh preview before we ask the user to select the file. My gut reaction is that this would be a worse user experience, but what do you think? 

Regardless, I will make it not save if the refresh preview failed


<!-- Sent from Reviewable.io -->

2023-06-13 21:22 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/5903)* status: all files reviewed, 5 unresolved discussions (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2023-06-13 21:22 UTC, merged