BL-12491 publish tab react tabs
BloomBooks/BloomDesktop pull request #6116
Opened 2023-09-25 20:28 UTC by nabalone

Make Publish Screen a single page with react tab bar

2023-09-25 20:41 UTC, nabalone commented on src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx
> +export interface PdfReadyMessage {
I use this it in publish tab, to be able to check if a PDF has been generated so we will know whether to include Download PDF options in the context menu

2023-09-26 00:00 UTC, andrew-polk requested changes
Great work!

> Reviewed 26 of 32 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-:-NfDmMHb0GJ6qEL2tXPg:b-9dwnzc)* status: 31 of 32 files reviewed, 14 unresolved discussions (waiting on @nabalone)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4421 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#gh-1336358808:-NfDUQ-O10pmAAj7Gem8:b-9ndbu3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e6d391ec18c3bb7d7c5511f2d889f333173fe19c/DistFiles/localization/en/Bloom.xlf#L4421)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

This used to be just in `PublishView.Designer.cs`. I added it here to be with the other publish tab tooltip localizations
</blockquote></details>

Nothing is using this ID, is it?
___
*[`DistFiles/localization/en/Bloom.xlf` line 3992 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDU5ioBpna2uCqQ6J4:-NfDU5ioBpna2uCqQ6J5:b-ae5v61) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/DistFiles/localization/en/Bloom.xlf#L3992)):*
> ```XML
>         <note>ID: PublishTab.ButtonThatShowsUploadForm-tooltip</note>
>       </trans-unit>
>       <!-- Added in 5.6 -->
> ```

I don't see value in the "added in" comments.
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#gh-1336368083:-NfDfi5M57iLX3_rrDrO:bcpgvbx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/85de04d865787f4b302b523da30014da4522da8b/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx#L20)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I use this in publish tab, to be able to check if a PDF has been generated so we will know whether to include Download PDF options in the context menu
</blockquote></details>

Based on my realization/comment that those context menu items actually belong in the context of the PDF specifically, this is probably not going to be needed.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 32 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDkTj40rBoN9Bui5O_:-NfDkTj40rBoN9Bui5Oa:ba1u5aw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L32)):*
> ```XML
> 
> export const PublishTabPane: React.FunctionComponent<{}> = () => {
>     const [canDownloadPDF, setcanDownloadPDF] = React.useState(false); // for context menu to be added
> ```

setCan... (capital C)

(but this probably wants to move to the pdf panel; see comment elsewhere)
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 52 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDkLIE0rosyqi4MoRu:-NfDkLIF9LB_vawMJWqM:bbmhp5f) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L52)):*
> ```XML
>     const [tabIndex, setTabIndex] = React.useState(5);
>     const setup = () => {
>         setTabIndex(5);
> ```

For here and where you set to "3", I would find it helpful to have a named constant to show what those numbers represent.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 55 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDdHu94ZJ5pjK-n3jC:-NfDdHu94ZJ5pjK-n3jD:b-yfg30s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L55)):*
> ```XML
>         get("publish/getInitialPublishTabInfo", result => {
>             // There should be a current selection by now but just in case:
>             if (!result.data.currentSelectionExists) {
> ```

Is this currentSelectionExists property really needed? Or can you get rid of it and just verify that your data is not falsey/empty? (and have the C# return either null or an empty object)
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 140 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDl4nb2HkYm2APZV_-:-NfDl4nb2HkYm2APZV_0:b-l75iid) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L140)):*
> ```XML
>                         <p>{needsEnterpriseText3}</p>
>                     </div>
>                 </div>
> ```

Feels like it would simplify things (at least, it would simplify this main component) to make this enterpriseNeeded UI a separate component.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 148 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfD_8IB2leHm6uLiTXt:-NfD_8IB2leHm6uLiTXu:b-iuiph6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L148)):*
> ```XML
>                     labelBackgroundColor={kPanelBackground}
>                     selectedIndex={tabIndex}
>                     onSelect={index => {
> ```

I would call "index" something like "newIndex".
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 337 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDjuh59kicCjDQnewH:-NfDjuh68xfSRy7bHTwB:bh3ih6e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L337)):*
> ```XML
>                     <TabPanel>
>                         <StyledEngineProvider injectFirst>
>                             <ThemeProvider theme={lightTheme}>
> ```

All these `StyledEngineProvider` and `ThemeProvider` components can go away and just have one which wraps the top level.

In theory, you can get rid of `StyledEngineProvider` altogether. But there could be some subtle UI change we might not notice, so better to keep it.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 31 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDaXtC5HqMqHfdPhkC:-NfDaXtC5HqMqHfdPhkD:brzeihu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomExe/Publish/PublishHelper.cs#L31)):*
> ```Smalltalk
> 		public PublishHelper()
> 		{
> 			if (!Program.RunningUnitTests && !Program.RunningInConsoleMode && WorkspaceView._tabSelection.ActiveTab != WorkspaceTab.publish  && !Program.RunningUnitTests && !Program.RunningInConsoleMode)
> ```

You've duplicated a couple conditions now.
___
*[`src/BloomExe/Publish/PublishView.cs` line 57 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDhfDzCoHwxREoZVKY:-NfDhfDzCoHwxREoZVKZ:bjk0ddh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomExe/Publish/PublishView.cs#L57)):*
> ```Smalltalk
> 			_L10NSharpExtender.SetLocalizationComment(this, null);
> 			_L10NSharpExtender.SetLocalizingId(this, "PublishTab");
> 			((System.ComponentModel.ISupportInitialize)(_L10NSharpExtender)).EndInit();
> ```

I'm pretty sure you can get rid of all the l10nSharpExtender stuff.
Look at other places we initialize a ReactControl not in designer. You probably only need whatever those have.
___
*[`src/BloomExe/Publish/PublishView.Designer.cs` line 199 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDXzVq6EosRR55aK5Q:-NfDXzVq6EosRR55aK5R:b-q0m3t5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f37b47d902b5092ec1a474d7db36969f3e225ee9/src/BloomExe/Publish/PublishView.Designer.cs#L199)):*
> ```Smalltalk
>             this._L10NSharpExtender.SetLocalizableToolTip(this._uploadRadio, null);
>             this._L10NSharpExtender.SetLocalizat [...]

2023-09-26 22:56 UTC, nabalone reviewed
Do I need to do anything with `PublishView.resx`?

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-:-NfIT-WP7tZduYcKrSad:b7vt6jm)* status: 25 of 32 files reviewed, 13 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4421 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#gh-1336358808:-NfGpfMz9buWCJOjWROF:bxd63o2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e6d391ec18c3bb7d7c5511f2d889f333173fe19c/DistFiles/localization/en/Bloom.xlf#L4421)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Nothing is using this ID, is it?
</blockquote></details>

I have the new tooltip now using the id, nothing else is
___
*[`DistFiles/localization/en/Bloom.xlf` line 3992 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDU5ioBpna2uCqQ6J4:-NfHByFy3h22PA3NCun0:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/DistFiles/localization/en/Bloom.xlf#L3992)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't see value in the "added in" comments.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 52 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDkLIE0rosyqi4MoRu:-NfHGv0dBDuVkCbpUdk2:b-ebktyk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

For here and where you set to "3", I would find it helpful to have a named constant to show what those numbers represent.
</blockquote></details>

Done. I still don't like using constant indexes here, I'm worried we'll change the tab order or something and not know to change these numbers. But I don't know how else to do it.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 55 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDdHu94ZJ5pjK-n3jC:-NfHI71iDpNHFbW_9RxM:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L55)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Is this currentSelectionExists property really needed? Or can you get rid of it and just verify that your data is not falsey/empty? (and have the C# return either null or an empty object)
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 140 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDl4nb2HkYm2APZV_-:-NfHpvXa7VobmW1URSbh:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L140)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Feels like it would simplify things (at least, it would simplify this main component) to make this enterpriseNeeded UI a separate component.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 148 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfD_8IB2leHm6uLiTXt:-NfHtS0m5j98houtP8wa:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L148)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would call "index" something like "newIndex".
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 337 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDjuh59kicCjDQnewH:-NfHv9HF0GXZWheM2dKo:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L337)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

All these `StyledEngineProvider` and `ThemeProvider` components can go away and just have one which wraps the top level.

In theory, you can get rid of `StyledEngineProvider` altogether. But there could be some subtle UI change we might not notice, so better to keep it.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PublishHelper.cs` line 31 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDaXtC5HqMqHfdPhkC:-NfHvMBM7B7PYjmSBUG8:bs7wumx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomExe/Publish/PublishHelper.cs#L31)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You've duplicated a couple conditions now.
</blockquote></details>

Done. 
___
*[`src/BloomExe/Publish/PublishView.cs` line 57 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDhfDzCoHwxREoZVKY:-NfISPjH5qJh7J4KykGv:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomExe/Publish/PublishView.cs#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty sure you can get rid of all the l10nSharpExtender stuff.
Look at other places we initialize a ReactControl not in designer. You probably only need whatever those have.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/PublishView.Designer.cs` line 199 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDXzVq6EosRR55aK5Q:-NfIVFFr-dfryxBWxHfM:b-l1eb6f) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f37b47d902b5092ec1a474d7db36969f3e225ee9/src/BloomExe/Publish/PublishView.Designer.cs#L199)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Did you check all the strings you're deleting to see if they need to be marked obsolete in the .xlf files?

I.e. each ID like "PublishTab.ButtonThatShowsUploadForm" either still needs to be used elsewhere or we need to mark it as "Obsolete as of 5.6" in the .xlf file.
</blockquote></details>

They are all still in use (mostly in `PublishTabPane.tsx`) or will be when we re-implement the right-click menu
___
*[`src/BloomExe/web/controllers/PublishApi.cs` line 294 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDe3BmCWINon3GRtcR:-NfIfesg6aMDMeMQ2Vu-:b-uaqv91) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomExe/web/controllers/PublishApi.cs#L294)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know you haven't finished implementing this yet, but now's when you're adding the endpoints, so this is when someone is goign to think about naming...

Let's drop "ToolStrip".
I would lean toward adding another part to the endpoint url like 
- publish/contextMenu/openHtmlInBrowser
- publish/contextMenu/openPdf
- publish/contextMenu/exportAudioFiles

By the way, now that I see this again, those first two really belong in the context of the PDF pane, not the Publish Tab generally. Maybe it is better just to not add these endpoints at all yet until you figure out the other end?
</blockquote></details>

Ok, deleted here and moved all this to another branch
___
*[`src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#gh-1336368083:-NfHCGHE4H9gxuvMX1wT:bb7f2mf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/85de04d865787f4b302b523da30014da4522da8b/src/BloomBrowserUI/publish/PDFPrintPublish/PDFPrintFeaturesGroup.tsx#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Based on my realization/comment that those context menu items actuall [...]

2023-09-26 23:11 UTC, andrew-polk requested changes
I'm pretty sure you can delete it.

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-:-NfIkhrhAMelRbudIc5S:bi2kj5i)* status: all files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4421 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#gh-1336358808:-NfIhU0j3tZ0hZuEejuh:b-vclqcu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e6d391ec18c3bb7d7c5511f2d889f333173fe19c/DistFiles/localization/en/Bloom.xlf#L4421)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I have the new tooltip now using the id, nothing else is
</blockquote></details>

Oh, ok. So it just wasn't working before I guess (because it wasn't in a .xlf file), so you fixed that?
___
*[`DistFiles/localization/en/Bloom.xlf` line 3992 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDU5ioBpna2uCqQ6J4:-NfIhcbKD-PViL03MLZw:bczt629) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/DistFiles/localization/en/Bloom.xlf#L3992)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks for removing the existing ones. Your new ones still have the comments, though.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 101 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfIjW89EmqYcp8NxDNB:-NfIjW89EmqYcp8NxDNC:b-kjxv6b) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f630f4b57d565c56de620068a322d3e9f327ef09/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L101)):*
> ```XML
>         numberOfFirstPageWithOverlay,
>         setNumberOfFirstPageWithOverlay
>     ] = React.useState(0);
> ```

Hm. I was hoping that moving the enterprise UI to another component would get rid of the two related state variables (or move them into that component.
But I think maybe they aren't needed regardless...
Can you just store anything from the server which is readonly in an object and just read it from there? In other words, I don't think the values need to be state, just accessible outside the setup function.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 104 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfIk7cE7puyfn6gNClc:-NfIk7cE7puyfn6gNCld:bcf2ewq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f630f4b57d565c56de620068a322d3e9f327ef09/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L104)):*
> ```XML
>     const [tabIndex, setTabIndex] = React.useState(waitForUserToChooseTabIndex);
>     const setup = () => {
>         setTabIndex(5);
> ```

Oops. Missed using the new `waitForUserToChooseTabIndex` here.
Let's rename those two `const`s to start with `k`.
___
*[`src/BloomExe/Publish/PublishView.Designer.cs` line 199 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDXzVq6EosRR55aK5Q:-NfIiGkp3t3du-3sp1rD:b-ucfkn4) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f37b47d902b5092ec1a474d7db36969f3e225ee9/src/BloomExe/Publish/PublishView.Designer.cs#L199)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

They are all still in use (mostly in `PublishTabPane.tsx`) or will be when we re-implement the right-click menu
</blockquote></details>

Thanks.


<!-- Sent from Reviewable.io -->

2023-09-27 18:47 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116)* status: 30 of 33 files reviewed, 4 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4421 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#gh-1336358808:-NfMTJcZ-VWID-WEK2SJ:b-rqf9b5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e6d391ec18c3bb7d7c5511f2d889f333173fe19c/DistFiles/localization/en/Bloom.xlf#L4421)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Oh, ok. So it just wasn't working before I guess (because it wasn't in a .xlf file), so you fixed that?
</blockquote></details>

Yes that seems to be the case. This single tooltip was not in a .xlf file before but the rest were, I don't know why. I assume we want to be able to localize them all?
___
*[`DistFiles/localization/en/Bloom.xlf` line 3992 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDU5ioBpna2uCqQ6J4:-NfMSm3W0FhCQWEwIrPE:boep8bi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/DistFiles/localization/en/Bloom.xlf#L3992)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thanks for removing the existing ones. Your new ones still have the comments, though.
</blockquote></details>

Oops I hadn't meant to get rid of the existing ones. Oh well now, I just made it so there are no more `Added in` comments in the file. Please let me know if I should put the unrelated ones back
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 32 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDkTj40rBoN9Bui5O_:-NfMTgBT9JmAlOyS5zsX:bmyboe6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L32)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

setCan... (capital C)

(but this probably wants to move to the pdf panel; see comment elsewhere)
</blockquote></details>

Took it out of this PR
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 101 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfIjW89EmqYcp8NxDNB:-NfMqWtW2B4a9z_PLRC-:b-j878ga) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f630f4b57d565c56de620068a322d3e9f327ef09/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. I was hoping that moving the enterprise UI to another component would get rid of the two related state variables (or move them into that component.
But I think maybe they aren't needed regardless...
Can you just store anything from the server which is readonly in an object and just read it from there? In other words, I don't think the values need to be state, just accessible outside the setup function.
</blockquote></details>

I'm not sure how to make it so the EnterpriseNeeded component loads with the title. Should I still be passing it as a prop? The way the code currently is, the title and page number don't show up
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 104 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfIk7cE7puyfn6gNClc:-NfMsjcm7EyKI8n5EpOd:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f630f4b57d565c56de620068a322d3e9f327ef09/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L104)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Oops. Missed using the new `waitForUserToChooseTabIndex` here.
Let's rename those two `const`s to start with `k`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-27 19:13 UTC, andrew-polk requested changes
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116)* status: 32 of 33 files reviewed, 2 unresolved discussions (waiting on @nabalone)

___
*[`DistFiles/localization/en/Bloom.xlf` line 4421 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#gh-1336358808:-NfMyVpr-VpZgLaeEXBa:b139i0r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e6d391ec18c3bb7d7c5511f2d889f333173fe19c/DistFiles/localization/en/Bloom.xlf#L4421)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Yes that seems to be the case. This single tooltip was not in a .xlf file before but the rest were, I don't know why. I assume we want to be able to localize them all?
</blockquote></details>

yes, probably just a mistake.
Thanks for correcting it.
___
*[`DistFiles/localization/en/Bloom.xlf` line 3992 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfDU5ioBpna2uCqQ6J4:-NfMyRoj6UKmjT5TmJ70:b-cq4r4t) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/ff1d62878eff3f48f079df8ebe6d6402afd6f343/DistFiles/localization/en/Bloom.xlf#L3992)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Oops I hadn't meant to get rid of the existing ones. Oh well now, I just made it so there are no more `Added in` comments in the file. Please let me know if I should put the unrelated ones back
</blockquote></details>

No need. Thanks.
___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 101 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfIjW89EmqYcp8NxDNB:-NfN2gh128q9-OsRH_dq:b-d1ibm6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f630f4b57d565c56de620068a322d3e9f327ef09/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L101)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I'm not sure how to make it so the EnterpriseNeeded component loads with the title. Should I still be passing it as a prop? The way the code currently is, the title and page number don't show up
</blockquote></details>

Sorry to cause a thrashing here.
As discussed, let's just move the server results into an object.


<!-- Sent from Reviewable.io -->

2023-09-27 19:13 UTC, andrew-polk reviewed
> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116)* status: all files reviewed, 2 unresolved discussions (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2023-09-27 20:22 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116)* status: 32 of 33 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx` line 101 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116#-NfIjW89EmqYcp8NxDNB:-NfNIYmvEFGs_uxE8KaG:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/f630f4b57d565c56de620068a322d3e9f327ef09/src/BloomBrowserUI/publish/PublishTab/PublishTabPane.tsx#L101)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry to cause a thrashing here.
As discussed, let's just move the server results into an object.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-27 20:40 UTC, andrew-polk reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2023-09-27 20:40 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6116)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2023-09-27 20:40 UTC, merged