Use the assigned font for BookButton labels (BL-12587)
BloomBooks/BloomDesktop pull request #6152
Opened 2023-10-17 22:47 UTC by StephenMcConnel

This fixes a display anomaly revealed by the screenshots in BL-12587. The effect of the fix may have nothing to do with surrogate pairs.

2023-10-17 22:56 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx` line 67 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqMAd8_Pa5oxq8DBC:-NgzqMAd8_Pa5oxq8DBD:b-gjhrlo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx#L67)):*
> ```XML
>             containsDownloadedBooks: false,
>             id: props.collectionId,
>             vernacularFont: "Andika"
> ```

I think we have a standard font "stack" defined somewhere?
___
*[`src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx` line 67 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqY3XAz6OlBqTicHj:-NgzqY3XAz6OlBqTicHk:b-yaciwq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx#L67)):*
> ```XML
>             containsDownloadedBooks: false,
>             id: props.collectionId,
>             vernacularFont: "Andika"
> ```

Does `vernacular` add anything? Should it be `languageFont`?
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 292 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqQc98EjWo-qH7-ff:-NgzqQc98EjWo-qH7-fg:boc69vo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomExe/web/controllers/CollectionApi.cs#L292)):*
> ```Smalltalk
> 			props.containsDownloadedBooks = collection.ContainsDownloadedBooks;
> 			if (collection.PathToDirectory == _settings.FolderPath)
> 				props.vernacularFont = _settings.Language1.FontName ?? "Andika";
> ```

Better, I think, to not define the default twice, both here and in tsx-land. One or the other?


<!-- Sent from Reviewable.io -->

2023-10-17 23:16 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx` line 67 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqMAd8_Pa5oxq8DBC:-NgzsMEY7jQM8WaK1MdZ:bpd3mc9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx#L67)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think we have a standard font "stack" defined somewhere?
</blockquote></details>

bloomMaterialUITheme.ts defines a kUiFontStack, but this doesn't necessarily work for local language data like book titles.
___
*[`src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx` line 67 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqY3XAz6OlBqTicHj:-NgztVEF4cZbleEuz0UV:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx#L67)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Does `vernacular` add anything? Should it be `languageFont`?
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 292 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqQc98EjWo-qH7-ff:-Ngzt_mA3n1PvJpYqwfz:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomExe/web/controllers/CollectionApi.cs#L292)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Better, I think, to not define the default twice, both here and in tsx-land. One or the other?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-17 23:42 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx` line 67 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqMAd8_Pa5oxq8DBC:-Nh--bRrB2vrDud_d2GR:blr2hft) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx#L67)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

bloomMaterialUITheme.ts defines a kUiFontStack, but this doesn't necessarily work for local language data like book titles.
</blockquote></details>

Sorry, I unclear. You're adding a default, "Andika", and I'm wondering that should be a default stack instead. Because Andika, also, doesn't have all the languages. But I suppose it could be a distinct constant from the UI one.


<!-- Sent from Reviewable.io -->

2023-10-17 23:43 UTC, hatton requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 292 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqQc98EjWo-qH7-ff:-Nh-0Cug3fa1ZS77u-CY:bx539zu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomExe/web/controllers/CollectionApi.cs#L292)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It's not clear to me that the default collection font should now be how we show thumbnails. This is a major UI change. What if we put the default language font *after* the defaultLanguageFontStack?


<!-- Sent from Reviewable.io -->

2023-10-18 15:31 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @hatton)

___
*[`src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx` line 67 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqMAd8_Pa5oxq8DBC:-Nh2NV3SEKA5-rCJi1Rc:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomBrowserUI/collectionsTab/BooksOfCollection.tsx#L67)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry, I unclear. You're adding a default, "Andika", and I'm wondering that should be a default stack instead. Because Andika, also, doesn't have all the languages. But I suppose it could be a distinct constant from the UI one.
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/CollectionApi.cs` line 292 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152#-NgzqQc98EjWo-qH7-ff:-Nh2NZ3WEH7wKlZ4TYIH:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c72645f99a142c338e5dd81a066a2e38ab0f0847/src/BloomExe/web/controllers/CollectionApi.cs#L292)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's not clear to me that the default collection font should now be how we show thumbnails. This is a major UI change. What if we put the default language font *after* the defaultLanguageFontStack?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-18 16:33 UTC, hatton reviewed
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2023-10-18 16:33 UTC, hatton reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6152)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2023-10-18 16:33 UTC, merged