Use input quality for output quality in jpeg size reduction (BL-12808)
BloomBooks/BloomDesktop pull request #6175
Opened 2023-10-26 23:08 UTC by StephenMcConnel

This seems to reliably result in smaller file sizes for smaller image dimensions.  A range limit on output quality ensures that we don't get something really awful on output.

2023-10-26 23:20 UTC, hatton commented
Happy to wait for 5.7 on this

2023-10-30 15:29 UTC, StephenMcConnel reviewed
I've rebased the PR to master (5.7).

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-:-Ni0ByuC86xg-LeG90Iy:b-myvl0r)* status: 0 of 1 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-11-03 13:16 UTC, hatton commented
Is it worth the risk, running a command with every image addition?

On Mon, Oct 30, 2023, 9:29 AM Steve McConnel ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
>
> I've rebased the PR to master (5.7).
>
> *Reviewable
> <https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-:-Ni0ByuC86xg-LeG90Iy:b-myvl0r>*
> status: 0 of 1 files reviewed, all discussions resolved
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BloomBooks/BloomDesktop/pull/6175#pullrequestreview-1704454189>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAACCAFSO2GY3NTYXJADU7LYB7BVZAVCNFSM6AAAAAA6R6NEXKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOMBUGQ2TIMJYHE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-11-03 20:33 UTC, JohnThomson requested changes
Looks basically good, assuming the answer to JohnH's question is "yes". I suggested a few improvements to naming and comments.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-:-NiLs0FY8zpl9I8BaRFW:ba2l739)* status: all files reviewed, 7 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 386 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLlXTkCimTTQzHKgxy:-NiLlXTkCimTTQzHKgxz:bnc5pq5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L386)):*
> ```Smalltalk
> 		/// <param name="width">original width (unknown orientation)</param>
> 		/// <param name="height">original height (unknown orientation)</param>
> 		/// <param name="maxWidth">smaller maximum dimension (portrait orientation)</param>
> ```

maxShortSide and maxLongSide?
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 400 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLjxTD0DpTBf13wJz1:-NiLjxTD0DpTBf13wJz2:b-q47hhz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L400)):*
> ```Smalltalk
> 				{
> 					if (aspect <= portraitAspect)
> 						return new Size(maxWidth, (int)(aspect * (double)maxWidth));
> ```

// most portraits are still closer to square than a standard page; size is limited by width
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 402 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLk0eP2YLjnZbjjj-h:-NiLk0eP2YLjnZbjjj-i:b-ysjfh5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L402)):*
> ```Smalltalk
> 						return new Size(maxWidth, (int)(aspect * (double)maxWidth));
> 					else
> 						return new Size((int)((double)maxHeight / aspect), maxHeight);
> ```

// Tall, skinny picture's size is limited by the height of a page
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 408 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLknaG5frI39DE3toS:-NiLknaG5frI39DE3toT:bwwouk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L408)):*
> ```Smalltalk
> 			{
> 				// landscape orientation
> 				if (height > maxWidth || width > maxHeight)
> ```

// We're going to determine the size based on fitting it on a landscape-oriented page
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 411 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLl-4I1GdBBceVUnDa:-NiLl-4I1GdBBceVUnDb:bvsv5ds) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L411)):*
> ```Smalltalk
> 				{
> 					if (aspect > landscapeAspect)
> 						return new Size((int)((double)maxWidth / aspect), maxWidth);
> ```

// Closer to square than the page. It's height is limited by the smaller dimension of the page, which becomes a height in landscape
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 413 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLlCDZ-EPrClJidnK4:-NiLlCD_6sUYqpV6Ipp-:b-jy73z9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L413)):*
> ```Smalltalk
> 						return new Size((int)((double)maxWidth / aspect), maxWidth);
> 					else
> 						return new Size(maxHeight, (int)(aspect * (double)maxHeight));
> ```

// Low, wide picture. It's width is limited by the larger page dimension, which becomes a width in landscape.
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 156 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLq6h4C2OBsT7a-CU5:-NiLq6h4C2OBsT7a-CU6:b-eya5le) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L156)):*
> ```Smalltalk
> 				var currentHeight = tagFile.Properties.PhotoHeight;
> 				if (imagePublishSettings.MaxWidth >= currentWidth && imagePublishSettings.MaxHeight >= currentHeight ||
> 					imagePublishSettings.MaxWidth >= currentHeight && imagePublishSettings.MaxHeight >= currentWidth)
> ```

Since we're here making (I think) a specific publication on a specific paper size, it's not obvious why we'd want the flipping of height and width.
If we actually do, a comment would help.
I also wonder if we could somehow reuse the logic in GetDesiredImageSize, if we DO want that swapping.
(Are MaxWidth and MaxHeight really, that, or are they really maxShortSide and MaxLongSide?)


<!-- Sent from Reviewable.io -->

2023-11-06 22:45 UTC, StephenMcConnel reviewed
We already run graphicsmagick on any images that we've decided have to shrink even for being source images in Bloom.  The program runs again only when we add an image that needs to be shrunk for use in a BloomPUB or ePUB book.  Using the program has these advantages:
1) using the same code for shrinking images wherever we need to do so.
2) maintaining the quality level of JPEG images so that we don't unnecessarily degrade their quality when shrinking, and also ensuring that shrinking the image will shrink the file size.
The graphicsmagick program, and the code we use to run it, are stable enough and have been used long enough that I don't see much risk in running it during the publication process.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-:-Niambg_1mz5j7leLhOE:b-1ost0x)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 386 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLlXTkCimTTQzHKgxy:-NialEwQ5yqO6zcSGMe-:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L386)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

maxShortSide and maxLongSide?
</blockquote></details>

Done.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 400 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLjxTD0DpTBf13wJz1:-NialGBcEmm0mycQJPqS:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L400)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

// most portraits are still closer to square than a standard page; size is limited by width
</blockquote></details>

Done.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 402 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLk0eP2YLjnZbjjj-h:-NialGjk2YBaOYi911fB:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L402)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

// Tall, skinny picture's size is limited by the height of a page
</blockquote></details>

Done.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 408 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLknaG5frI39DE3toS:-NialHEjBFYMt6zK8yY6:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L408)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

// We're going to determine the size based on fitting it on a landscape-oriented page
</blockquote></details>

Done.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 411 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLl-4I1GdBBceVUnDa:-NialHgJCLKotMpXEuls:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L411)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

// Closer to square than the page. It's height is limited by the smaller dimension of the page, which becomes a height in landscape
</blockquote></details>

Done.
___
*[`src/BloomExe/ImageProcessing/ImageUtils.cs` line 413 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLlCDZ-EPrClJidnK4:-NialIYZ3TtdM2g-wa0B:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/ImageProcessing/ImageUtils.cs#L413)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

// Low, wide picture. It's width is limited by the larger page dimension, which becomes a width in landscape.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 156 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175#-NiLq6h4C2OBsT7a-CU5:-NialJTx2UlS4gANWNVu:bpubue2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/0d5654992c8c05c7a83b0fdb1b7a5344794a90b1/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L156)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since we're here making (I think) a specific publication on a specific paper size, it's not obvious why we'd want the flipping of height and width.
If we actually do, a comment would help.
I also wonder if we could somehow reuse the logic in GetDesiredImageSize, if we DO want that swapping.
(Are MaxWidth and MaxHeight really, that, or are they really maxShortSide and MaxLongSide?)
</blockquote></details>

This code is determining whether or not a picture needs to be shrunk.  The MaxWidth and MaxHeight are really MaxLongSide and MaxShortSide because the setting is done relative to a landscape orientation like most TV and computer screens.
I've added comment to explain what is being checked here.


<!-- Sent from Reviewable.io -->

2023-11-06 22:52 UTC, JohnThomson approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6175)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2023-11-06 22:52 UTC, merged