Migrating to the theme system in EnsureUpToDate() (BL-12967)
BloomBooks/BloomDesktop pull request #6259
Opened 2024-01-22 21:14 UTC by JohnThomson

Migrating to the theme system is now handled like other one-time migrations using maintenanceLevel metadata. They therefore happen the first time 5.7 is able to EnsureUpToDate.

2024-01-22 21:18 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259)* status: 0 of 7 files reviewed, 1 unresolved discussion

___
*[`src/BloomExe/Book/BookStarter.cs` line 332 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259#-Non1FL9C3wTlAtdNqYG:-Non1FL9C3wTlAtdNqYH:b-c21q3g) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c01a79af01a18c16ae433877b0b827c7f1672431/src/BloomExe/Book/BookStarter.cs#L332)):*
> ```Smalltalk
>                 RobustFile.Copy(substituteCssPath, destPath, false);
>             }
> ```

We no longer need to do anything about migration in BookStarter. A newly created book is always run through EnsureUpToDate(), and this will migrate it to the theme system if it isn't already.


<!-- Sent from Reviewable.io -->

2024-01-24 20:01 UTC, StephenMcConnel requested changes
One minor comment on a comment, but otherwise looks okay.

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259#-:-Nox2xdR5tkp41G3himb:b-w8xb3v)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 154 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259#-NowS-ep0PlJldznVLWi:-NowS-eq-gWsuwHUZEnW:b4buglu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8dea1c205fae678f106b972df73683b1a278880/src/BloomExe/Book/BookStorage.cs#L154)):*
> ```Smalltalk
>         ///				 3 = Ensure main img comes first in image container
>         ///   Bloom 5.7 added kMediaMaintenanceLevel so we could distinguish migrations that affect
>         ///   Bloom 5.7  4 = Switched to using a theme (or explicitly using legacy)
> ```

This comment line seems out of place.  Should it swap with the line above it?


<!-- Sent from Reviewable.io -->

2024-01-25 19:23 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Book/BookStorage.cs` line 154 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259#-NowS-ep0PlJldznVLWi:-Np13n8W4dY6vCKbuFLo:beckud3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/d8dea1c205fae678f106b972df73683b1a278880/src/BloomExe/Book/BookStorage.cs#L154)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

This comment line seems out of place.  Should it swap with the line above it?
</blockquote></details>

It needed more than that. I think I've fixed things.


<!-- Sent from Reviewable.io -->

2024-01-26 00:14 UTC, StephenMcConnel approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-01-26 00:14 UTC, StephenMcConnel approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259#-:-Np26cOVAQvjiHtvUS-r:bnfp4nl)* status: all files reviewed, 1 unresolved discussion



<!-- Sent from Reviewable.io -->

2024-01-26 00:16 UTC, StephenMcConnel approved these changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6259)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2024-01-26 00:16 UTC, merged