BL-12977 OneDrive error dialog
BloomBooks/BloomDesktop pull request #6270
Opened 2024-01-30 19:38 UTC by nabalone

Catch OneDrive exceptions and give a clear notice with no report button

2024-01-30 20:02 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 0 of 15 files reviewed, 5 unresolved discussions

___
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQwP3VA5btCEtpt3yr:-NpQwP3VA5btCEtpt3ys:bhotm68) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L23)):*
> ```XML
>     secondaryLabel?: string; // The localized text that goes on the secondary action button. Omit or pass "" to disable the secondary action button.
> }> = props => {
>     if ([ProblemKind.Notify, ProblemKind.OneDriveNonFatal, ProblemKind.OneDriveFatal].includes(props.level)) { // TODO? is there a better way to do this?
> ```

Would it be better to do 
```
if (
    props.level === ProblemKind.Notify 
    || props.level === ProblemKind. OneDriveNonFatal
    || props.level === ProblemKind.ONeDriveFatal
)
```
___
*[`src/BloomBrowserUI/utils/linkHandler.ts` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQwml12Z2Oib74cRRW:-NpQwml21jJeAHNIdLuz:b-blnkv2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/utils/linkHandler.ts#L16)):*
> ```XML
>         return;
>     }
>     if (href.startsWith("http") || href.startsWith("mailto") || href.startsWith('file')) { // TODO? will it cause problems elsewhere to add file here?
> ```

I looked around and didn't see anything that looked like it would break because we changed `file://` handling but wasnt sure
___
*[`src/BloomExe/Book/BookInfo.cs` line 1014 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQwvvh4ayVWQVnqxO8:-NpQwvvh4ayVWQVnqxO9:b13lf72) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Book/BookInfo.cs#L1014)):*
> ```Smalltalk
>                     id = GetIdFromDamagedMetaDataString(RobustFile.ReadAllText(metaDataPath));
>                 }
>                 // TODO? should I replace all calls to RobustFile.Read... with wrapped versions?
> ```

i.e. make method(s) which call the `RobustFile.ReadAll()` functions but wrap them in a try/catch and convert IOExceptions to FileExceptions? And then put those everywhere? yagni?
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 742 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQxJOtDVLs-bIXN8if:-NpQxJOu-hXWVE-t0AnJ:bu1g9cr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/web/controllers/ProblemReportApi.cs#L742)):*
> ```Smalltalk
>             // }
> 
>             // TODO? is it worth splitting?
> ```

There's a lot of code shared between `ShowProblemDialog` and `CheckForAndHandleOneDriveExceptions`. I was trying to factor out the repeated dialog related code, but it would mean a helper method called twice that takes in a lot of parameters. Maybe we want to be able to arbitrarily adjust the two dialog behaviors independently of each other anyway?
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 862 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQxoypAhMbjQihPctQ:-NpQxoypAhMbjQihPctR:b-b47flm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/web/controllers/ProblemReportApi.cs#L862)):*
> ```Smalltalk
>         )
>         {
>             // TODO? do we want to localize any of these?
> ```

I am generally not sure how much is worth localizing


<!-- Sent from Reviewable.io -->

2024-01-31 18:38 UTC, andrew-polk requested changes
> Reviewed 14 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 14 of 15 files reviewed, 18 unresolved discussions (waiting on @nabalone)

___
*[`DistFiles/localization/en/Bloom.xlf` line 5140 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVNbqK7A6X8YY9gUuo:-NpVNbqK7A6X8YY9gUup:b-9lvbch) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/DistFiles/localization/en/Bloom.xlf#L5140)):*
> ```XML
>         <note>ID: ReportProblemDialog.WhatDoing</note>
>         <note>This is the label for the text field where the user enters what they were doing at the time of the problem.</note>
>       </trans-unit>
> ```

Generally, we are trying not to add things to Bloom.xlf. 
New strings should be added to the -Medium or -Low versions.
(I guess high-priority ones still go in Bloom.xlf??)

These can probably go in -Low.
___
*[`DistFiles/localization/en/Bloom.xlf` line 5146 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVNGxf2FAiV3MUx60j:-NpVNGxf2FAiV3MUx60k:betd1dg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/DistFiles/localization/en/Bloom.xlf#L5146)):*
> ```XML
>       </trans-unit>
>       <trans-unit id="ReportProblemDialog.OneDriveProblem" translate="no">
>         <source xml:lang="en">OneDriveProblem</source>
> ```

Shouldn't this source string be "OneDrive Problem"?
___
*[`src/BloomBrowserUI/problemDialog/NotifyDialog.tsx` line 27 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVYa21-FJfzdwdbLTw:-NpVYa21-FJfzdwdbLTx:b3lael) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L27)):*
> console.log(props);

Let's remove this.
___
*[`src/BloomBrowserUI/problemDialog/NotifyDialog.tsx` line 67 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVZ8qO6bkc_CorDG6i:-NpVZ8qO6bkc_CorDG6j:bbtdnxx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L67)):*
> #f0f0f0

I think it would be an improvement to use colorUtils' kFormBackground.
___
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 23 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQwP3VA5btCEtpt3yr:-NpVmBF22zdjcayyr_HB:b-v8atho) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L23)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Would it be better to do 
```
if (
    props.level === ProblemKind.Notify 
    || props.level === ProblemKind. OneDriveNonFatal
    || props.level === ProblemKind.ONeDriveFatal
)
```
</blockquote></details>

Either syntax is fine.
But as I say below, let's discuss the idea of having new "kinds" for OneDrive.
___
*[`src/BloomBrowserUI/problemDialog/theme.ts` line 41 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVO7NNCxr96WIohDRH:-NpVO7NOEZjf1JNCeQp2:bj73q1e) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/problemDialog/theme.ts#L41)):*
> #f44336

Since this is designed to be the same as the fatal color, let's extract that code as a const.
___
*[`src/BloomBrowserUI/utils/linkHandler.ts` line 16 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQwml12Z2Oib74cRRW:-NpVOPBLE8pLOldnDAu_:b-db7qxm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/utils/linkHandler.ts#L16)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I looked around and didn't see anything that looked like it would break because we changed `file://` handling but wasnt sure
</blockquote></details>

I'm not sure what else we can do but look around (as you did) and test.
Let's remove the TODO comment.
___
*[`src/BloomExe/Program.cs` line 1301 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVjqfb7meRYd9sCU9u:-NpVjqfb7meRYd9sCU9v:b-la5uks) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Program.cs#L1301)):*
> string filePath

Looks like this isn't used.
___
*[`src/BloomExe/Program.cs` line 1306 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVnNOdBuJclYiEFlH6:-NpVnNOe3ctCgxDeAxQW:b-ahvzdm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Program.cs#L1306)):*
> ```Smalltalk
> 
>             // Normally NotifyUserOfProblem would check for special exceptions and handle them appropriately.
>             // But, the code below doesn't use the usual NotifyUserOfProblem path (because we may want to SendReportWithoutUI below)
> ```

Sorry; I'm not processing this comment well.
Is this accurate?
Normally, NotifyUserOfProblem would take an exception and do this special-exception processing for us. But in this case, we don't pass the exception to NotifyUserOfProblem because we may subsequently end up calling SendReportWithoutUI. Therefore, we must check for the special exception independently.
___
*[`src/BloomExe/Program.cs` line 1307 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVmc8UEswVskybN5Dq:-NpVmc8UEswVskybN5Dr:bmz0fz9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Program.cs#L1307)):*
> There

Is this supposed to be "Therefore"?
___
*[`src/BloomExe/Book/BookInfo.cs` line 1014 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQwvvh4ayVWQVnqxO8:-NpVhLVu2DcLc2YWxR4w:b-q8sycb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Book/BookInfo.cs#L1014)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

i.e. make method(s) which call the `RobustFile.ReadAll()` functions but wrap them in a try/catch and convert IOExceptions to FileExceptions? And then put those everywhere? yagni?
</blockquote></details>

Putting them everywhere is definitely out of scope from what I understood.
If there was more than one place we were specifically wrapping a RobustFile. call, I would probably say it was worth a wrapper. But looks like other place you throw FileException is wrapping a bunch of stuff.
So, I could go either way. If you think there will likely be other places we wrap RobustFile. calls, specifically, you could make a wrapper now. But we could also wait until we do.
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 500 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVi5Jg-MqvGAVjS6s5:-NpVi5Jg-MqvGAVjS6s6:bf2xg5d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Collection/CollectionSettings.cs#L500)):*
> outerError

Rather than outer, isn't this inner? Or maybe "original" is better? (That matches the constructor signature for FileException.)
___
*[`src/BloomExe/CollectionTab/CollectionTabView.cs` line 288 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVOjrx82ymjFrMNCae:-NpVOjrx82ymjFrMNCaf:buh4ndv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/CollectionTab/CollectionTabView.cs#L288)):*
> ```Smalltalk
>         }
> 
>         private void CheckForDuplicates()
> ```

Assuming that it actually does, how about `CheckForDuplicatesAndRepair`? Or similar.

Same for BookInfo's version.
___
*[`src/BloomExe/ErrorReporter/HtmlErrorReporter.cs` line 234 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVif9zDSrY8rUeSSad:-NpVif9zDSrY8rUeSSae:b [...]

2024-01-31 23:59 UTC, andrew-polk requested changes
> Reviewed 15 of 16 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 16 of 17 files reviewed, 6 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxOcN1R-4ESx5R1yu:-NpWxOcN1R-4ESx5R1yv:bmshbw3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L20)):*
> ```XML
>     reportLabel?: string; // The localized text that goes on the Report button. Omit or pass "" to disable Report button.
>     secondaryLabel?: string; // The localized text that goes on the secondary action button. Omit or pass "" to disable the secondary action button.
>     notifyOnly?: boolean; // If true, use the NotifyDialog with no report button regardless of the level.
> ```

According to the comment on reportLabel, leaving that off should be enough to prevent the report button.
So if that isn't true, we should either make it true and remove this prop, or update the comment.
___
*[`src/BloomExe/ErrorReporter/HtmlErrorReporter.cs` line 231 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxJaZ5LaTdSlF-rwS:-NpWxJaZ5LaTdSlF-rwT:b19zeac) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L231)):*
> ```Smalltalk
>                 )
>                 {
>                     return; // TODO make sure we are letting go of the lock
> ```

// TODO

I know you're still working on this. I'm just adding this to make sure it doesn't get lost or left in.
___
*[`src/BloomExe/Utils/FileException.cs` line 24 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVjyjx3opgCy13_7gj:-NpWwGlc3E_hCGTSbMgb:b-f6pdg8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Utils/FileException.cs#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this be GetFilePathIfPresent?
</blockquote></details>

Oops. Should be capital `Get`
___
*[`src/BloomExe/Utils/OneDriveUtils.cs` line 30 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWwx-a1iPOX0qmM25b:-NpWwx-a1iPOX0qmM25c:bmdtzvn) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomExe/Utils/OneDriveUtils.cs#L30)):*
> ```Smalltalk
>         };
> 
>         public static bool isOneDriveErrorCode(string errorCode)
> ```

Remember, unlike js/ts, in C#, we capitalize method names.
___
*[`src/BloomExe/Utils/OneDriveUtils.cs` line 40 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWx5SA36XTziH7FeV9:-NpWx5SA36XTziH7FeVA:b19zeac) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomExe/Utils/OneDriveUtils.cs#L40)):*
> ```Smalltalk
>                     "ReportProblemDialog.OneDriveErrorMessage",
>                     "There is a problem with your Microsoft OneDrive which is preventing Bloom from accessing files."
>                 ) + Environment.NewLine; // TODO I thought I got rid of this...
> ```

// TODO

I know you're still working on this. I'm just adding this to make sure it doesn't get lost or left in.


<!-- Sent from Reviewable.io -->

2024-02-02 15:26 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 12 of 18 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`DistFiles/localization/en/Bloom.xlf` line 5140 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVNbqK7A6X8YY9gUuo:-NpW64RjEcHeGPW4KGNf:b-5kltb1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/DistFiles/localization/en/Bloom.xlf#L5140)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Generally, we are trying not to add things to Bloom.xlf. 
New strings should be added to the -Medium or -Low versions.
(I guess high-priority ones still go in Bloom.xlf??)

These can probably go in -Low.
</blockquote></details>

Oh ok, Done. I was just trying to keep them together with other problem dialog text.
___
*[`DistFiles/localization/en/Bloom.xlf` line 5146 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVNGxf2FAiV3MUx60j:-NpW6ZKr5oXeleyXaiba:b-nrfmh0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/DistFiles/localization/en/Bloom.xlf#L5146)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Shouldn't this source string be "OneDrive Problem"?
</blockquote></details>

Done. oops
___
*[`src/BloomBrowserUI/problemDialog/NotifyDialog.tsx` line 27 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVYa21-FJfzdwdbLTw:-NpW6d73C8nrmx4qRxQF:b-r2w617) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L27)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> console.log(props);

Let's remove this.
</blockquote></details>

Done. Oops 🤦‍♀️I searched my diff for leftover TODOs but forgot to search for console.logs. Sorry about that
___
*[`src/BloomBrowserUI/problemDialog/NotifyDialog.tsx` line 67 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVZ8qO6bkc_CorDG6i:-NpW7G53CC6mdXKBS6EJ:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L67)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> #f0f0f0

I think it would be an improvement to use colorUtils' kFormBackground.
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxOcN1R-4ESx5R1yu:-Np_w_KY6YMiH19Bcu3p:b5e7lda) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

According to the comment on reportLabel, leaving that off should be enough to prevent the report button.
So if that isn't true, we should either make it true and remove this prop, or update the comment.
</blockquote></details>

Ah ok, I tried to clarify
___
*[`src/BloomExe/Program.cs` line 1301 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVjqfb7meRYd9sCU9u:-NpW9BEP6d0JK3k0VJvx:b-12utm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Program.cs#L1301)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> string filePath

Looks like this isn't used.
</blockquote></details>

Done. But do we eventually want to add filePaths to the error message or log now that we might have them here
___
*[`src/BloomExe/Program.cs` line 1306 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVnNOdBuJclYiEFlH6:-NpWBfi_7jqfWFCKLmjE:b-35y33k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Program.cs#L1306)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I'm not processing this comment well.
Is this accurate?
Normally, NotifyUserOfProblem would take an exception and do this special-exception processing for us. But in this case, we don't pass the exception to NotifyUserOfProblem because we may subsequently end up calling SendReportWithoutUI. Therefore, we must check for the special exception independently.
</blockquote></details>

Done. Yes, that is what I was trying to say! much better
___
*[`src/BloomExe/Book/BookInfo.cs` line 1014 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpQwvvh4ayVWQVnqxO8:-NpWD-IsEpoTtawz0PuK:b-lvjp34) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Book/BookInfo.cs#L1014)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Putting them everywhere is definitely out of scope from what I understood.
If there was more than one place we were specifically wrapping a RobustFile. call, I would probably say it was worth a wrapper. But looks like other place you throw FileException is wrapping a bunch of stuff.
So, I could go either way. If you think there will likely be other places we wrap RobustFile. calls, specifically, you could make a wrapper now. But we could also wait until we do.
</blockquote></details>

Ok, I'll leave it is as is for now
___
*[`src/BloomExe/Collection/CollectionSettings.cs` line 500 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVi5Jg-MqvGAVjS6s5:-NpWDQBb9fwwKQI4vCVG:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Collection/CollectionSettings.cs#L500)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> outerError

Rather than outer, isn't this inner? Or maybe "original" is better? (That matches the constructor signature for FileException.)
</blockquote></details>

Done.
___
*[`src/BloomExe/CollectionTab/CollectionTabView.cs` line 288 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVOjrx82ymjFrMNCae:-NpWDv_87gy2i2pfuZvf:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/CollectionTab/CollectionTabView.cs#L288)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Assuming that it actually does, how about `CheckForDuplicatesAndRepair`? Or similar.

Same for BookInfo's version.
</blockquote></details>

Done.
___
*[`src/BloomExe/ErrorReporter/HtmlErrorReporter.cs` line 234 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVif9zDSrY8rUeSSad:-NpWGVMk2uaCXxZXrgF1:bro5dqi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L234)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

```
                    if (!wasAlreadyLocked)
                    {
                        System.Threading.Monitor.Exit(_lock);
                    }

```
Unless I'm missing something, this isn't needed. The finally block will do it.
</blockquote></details>

You're right, looks like I shouldn't need it. But I put it in in response to the lock not getting released somewhere. So hopefully I did eventually fix that problem... 
___
*[`src/BloomExe/Utils/FileException.cs` line 24 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVjyjx3opgCy13_7gj:-NpWH4iw4e8SLItyDZ0x:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Utils/FileException.cs#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should this be GetFilePathIfPresent?
</blockquote></details>

Done.
___
*[`src/BloomExe/Utils/FileException.cs` line 30 at r1](https://reviewabl [...]

2024-02-02 15:36 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 12 of 18 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/ErrorReporter/HtmlErrorReporter.cs` line 231 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxJaZ5LaTdSlF-rwS:-NpeQYwJ3SLK23MrLXxP:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomExe/ErrorReporter/HtmlErrorReporter.cs#L231)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

// TODO

I know you're still working on this. I'm just adding this to make sure it doesn't get lost or left in.
</blockquote></details>

Done.
___
*[`src/BloomExe/Utils/OneDriveUtils.cs` line 40 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWx5SA36XTziH7FeV9:-NpeQUn_BbYGwgxnBg7x:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomExe/Utils/OneDriveUtils.cs#L40)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

// TODO

I know you're still working on this. I'm just adding this to make sure it doesn't get lost or left in.
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 629 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpeQjFS8q3Y2zWq9rZm:-NpeQjFS8q3Y2zWq9rZn:b46nsz6) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L629)):*
> ```Smalltalk
>         // ENHANCE: Reduce duplication in HtmlErrorReporter and ProblemReportApi code. Some of the ProblemReportApi code can move to HtmlErrorReporter code.
> 
>         // ENHANCE: I think levelOfProblem would benefit from being required and being an enum.
> ```

I see we have ProblemLevel.cs (https://github.com/BloomBooks/BloomDesktop/blob/master/src/BloomExe/ErrorReporter/ProblemLevel.cs)
It feels bad to still use string literals here, in the defaults for ShowProblemDialog and CheckForAndHandleOneDriveExceptions below. Is there an easy way to improve that now?


<!-- Sent from Reviewable.io -->

2024-02-02 18:23 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 12 of 18 files reviewed, 5 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 629 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpeQjFS8q3Y2zWq9rZm:-Npf2Wei7v-MHx3pCKhS:b-fa9hn1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L629)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I see we have ProblemLevel.cs (https://github.com/BloomBooks/BloomDesktop/blob/master/src/BloomExe/ErrorReporter/ProblemLevel.cs)
It feels bad to still use string literals here, in the defaults for ShowProblemDialog and CheckForAndHandleOneDriveExceptions below. Is there an easy way to improve that now?
</blockquote></details>

I guess I'm not sure whether to problemLevel to an enum now and if so how far up/down the callstacks to make that change


<!-- Sent from Reviewable.io -->

2024-02-05 17:29 UTC, andrew-polk requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: all files reviewed, 4 unresolved discussions (waiting on @nabalone)

___
*[`DistFiles/localization/en/Bloom.xlf` line 5140 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVNbqK7A6X8YY9gUuo:-Npu4Dla8qScta1qfKOd:b8ol185) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/DistFiles/localization/en/Bloom.xlf#L5140)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Oh ok, Done. I was just trying to keep them together with other problem dialog text.
</blockquote></details>

Ah, yeah, I guess that would have made sense, too.
But putting them in low seems right for these. Thanks.
___
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxOcN1R-4ESx5R1yu:-Npu7k0T9m-cSVWd48Ue:b-dn0qrc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L20)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Ah ok, I tried to clarify
</blockquote></details>

Sigh. I see now why you introducing a new ProblemKind(s). We had conflated the idea of which dialog to present and which theme to use. It worked previously because there was no overlap but now there is.
It seems like the ideal would be to separate them. So I'm trying to figure out how worth it it is....
One option is to add a NotifyFatal ProblemKind, but that just perpetuates the problem.
Another option is to make two separate props, one for which problem kind, one for which theme. 
A third option is to have a theme override such that you would pass Notify as the kind in this case but pass in a theme override of Fatal. I'm leaning toward option #3. What do you think? Happy to discuss in person...


As a somewhat separate concern... if we have all these props which are actually specific to the NotifyDialog, it seems like maybe we should define INotifyDialogProps in NotifyDialog.tsx and make the type here `level:ProblemKind | INotifyDialogProps` or whatever the syntax is. I can pair with you on this if needed.
___
*[`src/BloomExe/Program.cs` line 1301 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVjqfb7meRYd9sCU9u:-Npu3tIQ8nib0FFH3kz8:b-a6v4ms) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Program.cs#L1301)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done. But do we eventually want to add filePaths to the error message or log now that we might have them here
</blockquote></details>

Yes, adding it to the log sounds right. I don't think we want to add it to the error message which already has the path to the collection.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 633 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpuAYuk8S6b0Qxi9ZG5:-NpuAYul2b8FBpHkwm2z:b-27l0r9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L633)):*
> Show Rpoblem Dialog

Show Problem Dialog
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 641 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpuAjWi5cMPS6_lXACU:-NpuAjWi5cMPS6_lXACV:b-lk48sr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L641)):*
> ```Smalltalk
>         /// <param name="controlForScreenshotting"></param>
>         /// <param name="exception"></param>
>         /// <param name="height"></param>
> ```

Let's remove all these empty param tags.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 867 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpuIyLc3tEaavaIeydY:-NpuIyLc3tEaavaIeydZ:bi7p1yj) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L867)):*
> ```Smalltalk
>         }
> 
>         private static void ShowOneDriveExceptionFallbackDialog(
> ```

Should we move this and the next method into OneDriveUtils?


<!-- Sent from Reviewable.io -->

2024-02-07 16:36 UTC, nabalone commented
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxOcN1R-4ESx5R1yu:-NpuZpix4FCQOqDyraxo:bw2a6yc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sigh. I see now why you introducing a new ProblemKind(s). We had conflated the idea of which dialog to present and which theme to use. It worked previously because there was no overlap but now there is.
It seems like the ideal would be to separate them. So I'm trying to figure out how worth it it is....
One option is to add a NotifyFatal ProblemKind, but that just perpetuates the problem.
Another option is to make two separate props, one for which problem kind, one for which theme. 
A third option is to have a theme override such that you would pass Notify as the kind in this case but pass in a theme override of Fatal. I'm leaning toward option #3. What do you think? Happy to discuss in person...


As a somewhat separate concern... if we have all these props which are actually specific to the NotifyDialog, it seems like maybe we should define INotifyDialogProps in NotifyDialog.tsx and make the type here `level:ProblemKind | INotifyDialogProps` or whatever the syntax is. I can pair with you on this if needed.
</blockquote></details>

Do you mean that the level or the notify dialog props should be a single argument? As in, if the level is "notify", then instead of the string "notify", the "level" should just be an INotifyDialogPropsObject? Is this better than making a second, optional argument?


<!-- Sent from Reviewable.io -->

2024-02-07 16:57 UTC, andrew-polk commented
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxOcN1R-4ESx5R1yu:-Nq3UvXkBOvHUFrt72NF:b-s3kkou) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L20)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Do you mean that the level or the notify dialog props should be a single argument? As in, if the level is "notify", then instead of the string "notify", the "level" should just be an INotifyDialogPropsObject? Is this better than making a second, optional argument?
</blockquote></details>

Sorry, I confused you because I didn't use the right syntax.
I'm suggesting that the type of the props for ProblemDialog be the union of `level:ProblemKind` and `INotifyDialogProps`.


<!-- Sent from Reviewable.io -->

2024-02-07 17:07 UTC, andrew-polk commented
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxOcN1R-4ESx5R1yu:-Nq3XGIu6wRuzqMpSXvO:b9jcj8z) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, I confused you because I didn't use the right syntax.
I'm suggesting that the type of the props for ProblemDialog be the union of `level:ProblemKind` and `INotifyDialogProps`.
</blockquote></details>

I played with it a little just now in code. I would require an intersection (&) to do what I'm talking about.
But I'm second-guessing that it is worth it. I was just trying to document via type that the other props are really just for the notify dialog. But it doesn't feel clean as I try to make it work.


<!-- Sent from Reviewable.io -->

2024-02-07 17:31 UTC, nabalone commented
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxOcN1R-4ESx5R1yu:-Nq3brIt-T5rBxokW2Eh:b9jbvce) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L20)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I played with it a little just now in code. I would require an intersection (&) to do what I'm talking about.
But I'm second-guessing that it is worth it. I was just trying to document via type that the other props are really just for the notify dialog. But it doesn't feel clean as I try to make it work.
</blockquote></details>

Oh. Do you not like this?
```
export const ProblemDialog: React.FC<{level:ProblemKind} & Partial<INotifyDialogProps>> = props => {

    if (props.level === ProblemKind.Notify) {

        return <NotifyDialog {...props} />;

    } else {

        return <ReportDialog kind\={props.level} />;

    }

};
```


<!-- Sent from Reviewable.io -->

2024-02-07 17:41 UTC, andrew-polk requested changes
> Reviewed 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomBrowserUI/problemDialog/ProblemDialog.tsx` line 20 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpWxOcN1R-4ESx5R1yu:-Nq3e2F3AEc6bdpwfkYB:b-v640t8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/76b64926c1bded2d6f4f70f154303c6127176ea9/src/BloomBrowserUI/problemDialog/ProblemDialog.tsx#L20)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Oh. Do you not like this?
```
export const ProblemDialog: React.FC<{level:ProblemKind} & Partial<INotifyDialogProps>> = props => {

    if (props.level === ProblemKind.Notify) {

        return <NotifyDialog {...props} />;

    } else {

        return <ReportDialog kind\={props.level} />;

    }

};
```
</blockquote></details>

That works!
You did a better job of figuring it out.
___
*[`src/BloomExe/Program.cs` line 1301 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVjqfb7meRYd9sCU9u:-Nq3dZwc4bfTbhhWIFZi:b-o2plu2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Program.cs#L1301)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yes, adding it to the log sounds right. I don't think we want to add it to the error message which already has the path to the collection.
</blockquote></details>

Sorry, I meant to suggest we go ahead and log it now.


<!-- Sent from Reviewable.io -->

2024-02-07 22:14 UTC, nabalone reviewed
I am testing throwing exceptions and catching them and I am getting a "Invoke or BeginInvoke cannot be called on a control until the window handle has been created." error while trying to display the error dialog. I am worried that this looks like a timing thing and that users could reach it while encountering OneDrive errors. I have not yet figured out how to fix it

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-:-Nq4bySpAi3NOQJuDF6D:b-wb8ugz)* status: 15 of 18 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Program.cs` line 1301 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpVjqfb7meRYd9sCU9u:-Nq3wX1R-FETE7rnRxA9:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/403c999f44b1b394c175c0b2751d9a801b4e6072/src/BloomExe/Program.cs#L1301)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry, I meant to suggest we go ahead and log it now.
</blockquote></details>

Done.
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 633 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpuAYuk8S6b0Qxi9ZG5:-Npug2QYE5ybflEtUYoc:bn9cco2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L633)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Show Rpoblem Dialog

Show Problem Dialog
</blockquote></details>

Done. (will push )
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 641 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpuAjWi5cMPS6_lXACU:-Npug6xy4fvvu7yl_bcN:b-t1br4g) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L641)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's remove all these empty param tags.
</blockquote></details>

Done. (will push)
___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 867 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpuIyLc3tEaavaIeydY:-NpugaZ18j7iHx_bEQFj:bsjx17d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L867)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should we move this and the next method into OneDriveUtils?
</blockquote></details>

I'm not sure it makes any sense outside the context of `CheckForAndHandleOneDriveExceptions`, and I feel like they should stay together since they have a lot of the same text. Can I put it inside `CheckForAndHandleOneDriveExceptions` instead? I also factored out the text they share


<!-- Sent from Reviewable.io -->

2024-02-07 22:16 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 15 of 18 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/problemDialog/NotifyDialog.tsx` line 75 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-Nq4cxaREafreTxRvFz1:-Nq4cxaS75-L2KaJh9lN:b-m4f507) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/c9f370f9dea6c2025392ffd507036f01c4ddd986/src/BloomBrowserUI/problemDialog/NotifyDialog.tsx#L75)):*
> ```XML
>                                     margin-bottom: 20px; 
>                                     a {
>                                         color: ${kBloomBlue}; // we are passing links in the text
> ```

This feels like a band aid. Wondering if it is worth it try and handle links and styling better


<!-- Sent from Reviewable.io -->

2024-02-07 23:30 UTC, nabalone commented
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 657 at r6](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-Nq4u0Hg9SDKX9f60j0R:-Nq4u0Hg9SDKX9f60j0S:b-3j3owx) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/91ef21bb0c1f46f7462625738c87a237d8d889bf/src/BloomExe/web/controllers/ProblemReportApi.cs#L657)):*
> ```Smalltalk
>                         // this one, while apparently redundant might be wise to keep since closing the splash screen
>                         // needs to be done on the UI thread.
>                         try
> ```

Here I catch the `Invoke or BeginInvoke cannot be called on a control until the window handle has been created.` exception that was happening, at least this should catch it in OneDrive  error cases


<!-- Sent from Reviewable.io -->

2024-02-07 23:33 UTC, nabalone commented
> I am testing throwing exceptions and catching them and I am getting a "Invoke or BeginInvoke cannot be called on a control until the window handle has been created." error while trying to display the error dialog. I am worried that this looks like a timing thing and that users could reach it while encountering OneDrive errors. I have not yet figured out how to fix it

Was happening on an attempt to close the splash screen. I added an additional try/catch to catch it.

2024-02-07 23:53 UTC, andrew-polk requested changes
> Reviewed 1 of 3 files at r5, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/web/controllers/ProblemReportApi.cs` line 867 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270#-NpuIyLc3tEaavaIeydY:-Nq4zGGBCVd4CgLRqgQy:b-xge3ej) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a95f1af02dd07a01d7b7605d949f71c5ad40e54f/src/BloomExe/web/controllers/ProblemReportApi.cs#L867)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I'm not sure it makes any sense outside the context of `CheckForAndHandleOneDriveExceptions`, and I feel like they should stay together since they have a lot of the same text. Can I put it inside `CheckForAndHandleOneDriveExceptions` instead? I also factored out the text they share
</blockquote></details>

Sorry; I actually meant to move both `ShowOneDriveExceptionFallbackDialog` and `CheckForAndHandleOneDriveExceptions` to OneDriveUtils. Is that feasible?


<!-- Sent from Reviewable.io -->

2024-02-08 15:23 UTC, andrew-polk approved these changes
> Reviewed 5 of 5 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: all files reviewed, 2 unresolved discussions



<!-- Sent from Reviewable.io -->

2024-02-08 15:24 UTC, andrew-polk approved these changes
> Dismissed @nabalone from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6270)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @nabalone)



<!-- Sent from Reviewable.io -->

2024-02-08 15:24 UTC, merged