Fix Bible for Children branding comic to show white back page (BL-13138)
BloomBooks/BloomDesktop pull request #6337
Opened 2024-03-04 17:49 UTC by StephenMcConnel

The final page used to have a white background in comics before we merged the final two backmatter pages back together for comics.

2024-03-07 23:02 UTC, JohnThomson requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 602 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337#-NsPzzS3EuBG1Wtvoi_b:-NsPzzS3EuBG1Wtvoi_c:b-n05t4f) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8926cdf4007dc3bdeb67254cc72fbb8e14a44fe6/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L602)):*
> ```Smalltalk
>                 }
>             }
>         }
> ```

It seems very unprincipled to take a meta value that was intended to prevent automatically generating a cover color, reinterpret it to mean "this book has a black cover", and then apply it to only one of the four cover pages, just so we can make a rule for one branding.
What would you think of applying some logic like https://stackoverflow.com/questions/9733288/how-to-programmatically-calculate-the-contrast-ratio-between-two-colors to the cover color and use it to add (or not add) to each cover page a class darkBackground? Make it present if white text will contrast better than black.
It would then actually make sense to say that if a Bible-for-children book has a dark back cover, we need to force it white to make their logo readable. Whereas it's completely counter-intuitive to change the cover color because there is an attribute present that apparently tells us to preserve it (!!).
It would also have a chance of being useful for other things. For example, we could have a single principled rule somewhere to say that when this class is present the foreground color should be white, instead of embedding a whole bunch of rules about that in the Digital Comic Book template. But that's beyond the scope of this card.
The tricky bit is when to do this. Any time we change the cover color, of course, it needs updating. And somehow it has to get introduced when migrating books that need it to 5.7. To minimize the cost of that it could be a new 'maintenanceLevel'. So it would be a bit more code, but I think it might be worth it.
This is the sort of thing where @hatton might have an even more elegant idea.
Feel free to push back or think of another idea. But I'd really like to avoid reinterpreting 'preserveCoverColor' as 'cover is dark'. (One day some branding may always want a yellow cover.)


<!-- Sent from Reviewable.io -->

2024-03-13 22:17 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[`src/BloomExe/Publish/BloomPub/BloomPubMaker.cs` line 602 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337#-NsPzzS3EuBG1Wtvoi_b:-NstscUABhmV1d5F0nSf:bduyxhz) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8926cdf4007dc3bdeb67254cc72fbb8e14a44fe6/src/BloomExe/Publish/BloomPub/BloomPubMaker.cs#L602)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It seems very unprincipled to take a meta value that was intended to prevent automatically generating a cover color, reinterpret it to mean "this book has a black cover", and then apply it to only one of the four cover pages, just so we can make a rule for one branding.
What would you think of applying some logic like https://stackoverflow.com/questions/9733288/how-to-programmatically-calculate-the-contrast-ratio-between-two-colors to the cover color and use it to add (or not add) to each cover page a class darkBackground? Make it present if white text will contrast better than black.
It would then actually make sense to say that if a Bible-for-children book has a dark back cover, we need to force it white to make their logo readable. Whereas it's completely counter-intuitive to change the cover color because there is an attribute present that apparently tells us to preserve it (!!).
It would also have a chance of being useful for other things. For example, we could have a single principled rule somewhere to say that when this class is present the foreground color should be white, instead of embedding a whole bunch of rules about that in the Digital Comic Book template. But that's beyond the scope of this card.
The tricky bit is when to do this. Any time we change the cover color, of course, it needs updating. And somehow it has to get introduced when migrating books that need it to 5.7. To minimize the cost of that it could be a new 'maintenanceLevel'. So it would be a bit more code, but I think it might be worth it.
This is the sort of thing where @hatton might have an even more elegant idea.
Feel free to push back or think of another idea. But I'd really like to avoid reinterpreting 'preserveCoverColor' as 'cover is dark'. (One day some branding may always want a yellow cover.)
</blockquote></details>

Done.  I decided that since the darkCoverColor class applies only to xmatter pages, it needs to be done whenever xmatter updates, so it's not really a migration issue per se.  But I don't think it's too expensive.


<!-- Sent from Reviewable.io -->

2024-03-26 17:31 UTC, JohnThomson approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> But I'd like Andrew's or John's opinion of the idea before merging.

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337#-:-NtvoAlyExFvo0vC2-Tf:b-g6swyv)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2024-03-26 18:53 UTC, andrew-polk reviewed
The overall approach makes sense... detect we have a dark cover and allow the css to change things based on a class indicating that.

Do we have an idea of the performance cost?
A couple ideas if we thought it might be costly at all:
1. JT had suggested a migration. 
2. We could hard-code a look up for the values we expect, such as this dark one and the default colors we assign (and maybe the defaults from the color picker, too?).

JT in a separate thread brought up his second-guessing his suggestion of the class name .darkCoverColor, wondering if it should have the bloom- prefix but noting that we have other related classes without it now so we would lose some consistency. That's a hard call, but I guess I would lean toward keeping it more like the existing classes (so without the prefix).

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337#-:-Ntw53YI6soEYRAS6Aln:b-1ui4fo)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2024-04-02 18:37 UTC, StephenMcConnel reviewed
I fixed the code to predefine the luminance for white (which is 1.0 after all), and tried measuring how long it tooks to compute the IsDark value.  The answer for method duration always came back as 0 ms and then as 0 ticks when I tried finer granularity.  I don't think this computation is going to be very costly.  :-)
Since we have to check this every time the xmatter gets rebuilt, I don't think a migration per se is appropriate or necessary.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337#-:-NuV3xuK0K0Opb-ng5ur:b-5aupaw)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2024-04-02 18:52 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6337)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)



<!-- Sent from Reviewable.io -->

2024-04-02 18:53 UTC, merged