Check for unreadable localization file for license (BL-13115)
BloomBooks/BloomDesktop pull request #6353
Opened 2024-03-21 21:30 UTC by StephenMcConnel

Also BL-13167 and BL-13168.  We have no idea what is happening, but this check might provide at least a clue on fixing it on the user's computer.

2024-03-25 16:29 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)* status: all files reviewed, 4 unresolved discussions (waiting on @StephenMcConnel)

___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqOq0E9J8gNnxWAGFn:-NtqOq0E9J8gNnxWAGFo:bgu952r) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/DistFiles/localization/en/BloomMediumPriority.xlf#L495)):*
> ```XML
>         <source xml:lang="en">Bloom was unable to read a localization file.</source>
>         <note>Localization.CannotReadFile</note>
>       </trans-unit>
> ```

@hatton 
Just verifying that it was your intention that we would present a message to the user in a modal for this case of not finding localization of license info for major languages.
Secondarily, is it worth localizing?

@StephenMcConnel if we do keep this, I think we want it in BloomLowPriority.xlf
___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 244 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqQ8xzDA1a_T-itjhT:-NtqQ8xzDA1a_T-itjhU:b2rcvfs) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L244)):*
> ```Smalltalk
>         /// See BL-13115, BL-13167, and BL-13168 for user reports of a known localization not being found.
>         /// </remarks>
>         private static void CheckForMissingLocalization(List<string> langPriorities, string languageUsedForDescription)
> ```

I think this method wants to live somewhere else. (Not sure where, but something related to l10n as opposed to book?)
___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 244 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqQJ-n3CmGy1beI2J-:-NtqQJ-n3CmGy1beI2J0:bs212er) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L244)):*
> ```Smalltalk
>         /// See BL-13115, BL-13167, and BL-13168 for user reports of a known localization not being found.
>         /// </remarks>
>         private static void CheckForMissingLocalization(List<string> langPriorities, string languageUsedForDescription)
> ```

Maybe I misunderstood, but I thought we were doing something more simplistic.
I thought the idea was just to see if `fr` or `es` didn't come back with localized strings, and then report.

1. I don't think we want to do this for other languages where we know localizations may not or won't be present.
2. You're doing a lot more to check files, etc. than I understood we were going to do. Maybe that's worth putting in the log, but I'm not sure it is worth presenting to the user.

But maybe there was more to the discussion than I remember or there were other discussions I wasn't part of.

Happy to discuss.
___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 250 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqPkbv2gdoIUIrsEV_:-NtqPkbv2gdoIUIrsEVa:bm3gcqa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L250)):*
> ```Smalltalk
>             // If the language used for the description is not the first priority, we need to check if a localization file
>             // is missing or unreadable.  The final value in langPriorities is "en", so we don't need to check it.
>             string localizationFolder=null;
> ```

@StephenMcConnel 
Do you have CSharpier set up?
I think it would put spaces around the `=`.


<!-- Sent from Reviewable.io -->

2024-03-25 17:48 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 244 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqQJ-n3CmGy1beI2J-:-NtqbIjK9sB4n2LVEaIl:b-1xnn8d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L244)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe I misunderstood, but I thought we were doing something more simplistic.
I thought the idea was just to see if `fr` or `es` didn't come back with localized strings, and then report.

1. I don't think we want to do this for other languages where we know localizations may not or won't be present.
2. You're doing a lot more to check files, etc. than I understood we were going to do. Maybe that's worth putting in the log, but I'm not sure it is worth presenting to the user.

But maybe there was more to the discussion than I remember or there were other discussions I wasn't part of.

Happy to discuss.
</blockquote></details>

The check is NOT for whether the string has been localized, but for whether the file is readable (and has presumably been read by L10NSharp).  This information may still be of interest even if the actual string hasn't yet been localized.
Whether to present the information to the user in a localized form, or just log it in English for programmers is a good question.  My thought is that by presenting the message to the user, maybe somebody local can help them fix the problem.  But maybe I'm too optimistic about local support.
___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 244 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqQ8xzDA1a_T-itjhT:-NtqcM97Crbf6OmSF47U:b9gi0t3) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L244)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this method wants to live somewhere else. (Not sure where, but something related to l10n as opposed to book?)
</blockquote></details>

I really don't want to go through the pain of modifying L10NSharp itself.  I've added a class LocalizationHelper to the BloomExe/Utils folder and moved this method and associated data there.
___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 250 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqPkbv2gdoIUIrsEV_:-NtqZgyL19mYeVujFSAm:b-foaxu1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L250)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

@StephenMcConnel 
Do you have CSharpier set up?
I think it would put spaces around the `=`.
</blockquote></details>

I think I have CSharpier working now.  I had it installed, but hadn't turned on the flag in VS that forced reformatting on save.
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqOq0E9J8gNnxWAGFn:-NtqbDkg9cPlqc9wtpZ1:bavuo6k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/DistFiles/localization/en/BloomMediumPriority.xlf#L495)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

@hatton 
Just verifying that it was your intention that we would present a message to the user in a modal for this case of not finding localization of license info for major languages.
Secondarily, is it worth localizing?

@StephenMcConnel if we do keep this, I think we want it in BloomLowPriority.xlf
</blockquote></details>

moved to BloomLowPriority.xlf


<!-- Sent from Reviewable.io -->

2024-03-25 18:02 UTC, andrew-polk reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton)

___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 244 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqQ8xzDA1a_T-itjhT:-Ntqka6d2l46uMSaBUrM:bhb08mf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L244)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I really don't want to go through the pain of modifying L10NSharp itself.  I've added a class LocalizationHelper to the BloomExe/Utils folder and moved this method and associated data there.
</blockquote></details>

Thanks. Yes, that's what I meant, not to alter L10NSharp.


<!-- Sent from Reviewable.io -->

2024-03-25 20:18 UTC, hatton reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)* status: all files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 244 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqQJ-n3CmGy1beI2J-:-NtrFkq43Ktsd_4Nxg-U:bhsiups) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L244)):*
> I thought the idea was just to see if `fr` or `es` didn't come back with localized strings, and then report.

me too
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqOq0E9J8gNnxWAGFn:-NtrFox27S3XvYTmOusz:bh7ra49) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/DistFiles/localization/en/BloomMediumPriority.xlf#L495)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

moved to BloomLowPriority.xlf
</blockquote></details>

We should just be throwing an error, no need for localization at all.


<!-- Sent from Reviewable.io -->

2024-03-25 23:25 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookCopyrightAndLicense.cs` line 244 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqQJ-n3CmGy1beI2J-:-Ntrn3G09Ie8QCE5hlxw:bt2z2tm) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/src/BloomExe/Book/BookCopyrightAndLicense.cs#L244)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

> I thought the idea was just to see if `fr` or `es` didn't come back with localized strings, and then report.

me too
</blockquote></details>

I've restricted the check to fr and es.
___
*[`DistFiles/localization/en/BloomMediumPriority.xlf` line 495 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-NtqOq0E9J8gNnxWAGFn:-Ntrn2-02_bb9KuLDRvI:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/6abd5fb078e48b5182261b9ee0d8c402570f59b2/DistFiles/localization/en/BloomMediumPriority.xlf#L495)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We should just be throwing an error, no need for localization at all.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-26 16:43 UTC, andrew-polk requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Utils/LocalizationHelper.cs` line 18 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-Ntvc4dn3Vi_piOV5B0j:-Ntvc4dn3Vi_piOV5B0k:b5qdi3k) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c5e65868266daac69bc425eef485a17c509b9ff/src/BloomExe/Utils/LocalizationHelper.cs#L18)):*
> and warn the user if so.

nit - Rather this now throws an exception.
___
*[`src/BloomExe/Utils/LocalizationHelper.cs` line 57 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-Ntvbl_WCxZDoh6QgXM8:-Ntvbl_WCxZDoh6QgXM9:b-yprc4s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c5e65868266daac69bc425eef485a17c509b9ff/src/BloomExe/Utils/LocalizationHelper.cs#L57)):*
> ```Smalltalk
>                 if (!_warningsIssued.Contains(filepath))
>                 {
>                     _warningsIssued.Add(filepath);
> ```

As far as I can tell, _warningsIssued is not used anymore.
___
*[`src/BloomExe/Utils/LocalizationHelper.cs` line 61 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-Ntvbswv8tu3MoIklxR-:-Ntvbswv8tu3MoIklxR0:b5wyu53) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c5e65868266daac69bc425eef485a17c509b9ff/src/BloomExe/Utils/LocalizationHelper.cs#L61)):*
> ```Smalltalk
>                         $"Unexpected failure to get localized string from {filepath}",
>                         except
>                     );
> ```

Seems like we should add the requested-and-failed language tag to the message.

Ideally, we'd also add the l10n ID. But I see that is not straightforward to get. I guess we'll at least get the stacktrace which would indicate what we're trying to do.


<!-- Sent from Reviewable.io -->

2024-03-26 19:37 UTC, StephenMcConnel reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Utils/LocalizationHelper.cs` line 18 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-Ntvc4dn3Vi_piOV5B0j:-NtwFGX40K_cdVwvRyTm:b-7ql1td) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c5e65868266daac69bc425eef485a17c509b9ff/src/BloomExe/Utils/LocalizationHelper.cs#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> and warn the user if so.

nit - Rather this now throws an exception.
</blockquote></details>

fixed
___
*[`src/BloomExe/Utils/LocalizationHelper.cs` line 57 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-Ntvbl_WCxZDoh6QgXM8:-NtwF_iL6z21AZjjQXZX:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c5e65868266daac69bc425eef485a17c509b9ff/src/BloomExe/Utils/LocalizationHelper.cs#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As far as I can tell, _warningsIssued is not used anymore.
</blockquote></details>

Done.
___
*[`src/BloomExe/Utils/LocalizationHelper.cs` line 61 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-Ntvbswv8tu3MoIklxR-:-NtwFRgPEAgJy7MJxCMh:b-a9lxab) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c5e65868266daac69bc425eef485a17c509b9ff/src/BloomExe/Utils/LocalizationHelper.cs#L61)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like we should add the requested-and-failed language tag to the message.

Ideally, we'd also add the l10n ID. But I see that is not straightforward to get. I guess we'll at least get the stacktrace which would indicate what we're trying to do.
</blockquote></details>

The desired language tag is part of the filepath.  But I've added it explicitly to the message.


<!-- Sent from Reviewable.io -->

2024-03-26 20:22 UTC, andrew-polk approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`src/BloomExe/Utils/LocalizationHelper.cs` line 61 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6353#-Ntvbswv8tu3MoIklxR-:-NtwQBSv9vqMS4owqqwZ:bcydtek) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9c5e65868266daac69bc425eef485a17c509b9ff/src/BloomExe/Utils/LocalizationHelper.cs#L61)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

The desired language tag is part of the filepath.  But I've added it explicitly to the message.
</blockquote></details>

Ah. I had thought maybe it did but then didn't see that at first blush. I didn't look deeply enough. 
Thanks.


<!-- Sent from Reviewable.io -->

2024-03-26 20:22 UTC, merged