BL-13215 fix background colors and flashing button outline
BloomBooks/BloomDesktop pull request #6397
Opened 2024-04-09 23:12 UTC by nabalone

- Fix dark oval around collection name dropdown menu triangle
- editing tab left pane color consistency
- Fix flashing white outline around "Add Page" button when changing page selection

2024-04-10 14:26 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 0 of 6 files reviewed, 2 unresolved discussions

___
*[`src/BloomExe/Book/Book.cs` line 2296 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OJVT8F8L6i801f9U:-Nv7OJVT8F8L6i801f9V:beqf2o) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/Book.cs#L2296)):*
> ```Smalltalk
>                 var coverColorIsDark = ColorUtils.IsDark(coverColor);
>                 foreach (
>                     var page in bookDOM
> ```

Just whitespace, not sure why it did this. 
___
*[`src/BloomExe/Edit/EditingView.cs` line 531 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OQQrBElylRXkgru9:-Nv7OQQtAWtMU92grk9W:b-ppuzus) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Edit/EditingView.cs#L531)):*
> ```Smalltalk
>                 _model.CheckForBL2634("navigated to page");
>                 SetModalState(false); // ensure _pageListView is enabled (BL-9712).
>                 _pageListView.Focus();
> ```

I'm a little nervous that there will be side effects of removing this line that I didn't notice. But focus goes back to the page you are editing very soon anyway, and it seems complicated to keep this line and yet prevent the browser from putting the :focus-visible automatic outline


<!-- Sent from Reviewable.io -->

2024-04-10 15:04 UTC, JohnThomson approved these changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: all files reviewed, 2 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/Edit/EditingView.cs` line 531 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OQQrBElylRXkgru9:-Nv7VKPN6rbPH3OIn7ZC:bx9ikks) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Edit/EditingView.cs#L531)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I'm a little nervous that there will be side effects of removing this line that I didn't notice. But focus goes back to the page you are editing very soon anyway, and it seems complicated to keep this line and yet prevent the browser from putting the :focus-visible automatic outline
</blockquote></details>

I would not think we ever want the page list view focused, unless the user does something explicit with the keyboard (like pressing tab key) to manipulate those controls with the keyboard. The natural place for initial focus is somewhere in the page content. Even if there's nothing there to focus, I'm not sure we want focus in the page list.
You might try checking in git in case blame ties this line to a YouTrack issue that would suggest a reason for it or something we should test to make sure removing it doesn't re-introduce a problem. But I wouldn't spend a lot of time on it.


<!-- Sent from Reviewable.io -->

2024-04-10 15:14 UTC, andrew-polk commented
*[`src/BloomExe/Edit/EditingView.cs` line 531 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OQQrBElylRXkgru9:-Nv7ZbnQ0nYq4qYOmEaH:b-zbr9pg) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Edit/EditingView.cs#L531)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I would not think we ever want the page list view focused, unless the user does something explicit with the keyboard (like pressing tab key) to manipulate those controls with the keyboard. The natural place for initial focus is somewhere in the page content. Even if there's nothing there to focus, I'm not sure we want focus in the page list.
You might try checking in git in case blame ties this line to a YouTrack issue that would suggest a reason for it or something we should test to make sure removing it doesn't re-introduce a problem. But I wouldn't spend a lot of time on it.
</blockquote></details>

I have a vague recollection that Gordon did this to work around some bizarro bug.
I even have the vague recollection that we decided to live with this flashing as a result.
So yes, if you can use history to look at why we did, that would be good.


<!-- Sent from Reviewable.io -->

2024-04-10 15:31 UTC, nabalone commented
*[`src/BloomExe/Edit/EditingView.cs` line 531 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OQQrBElylRXkgru9:-Nv7cVSE2-oKMMiGYMbZ:b-n0ccy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Edit/EditingView.cs#L531)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I have a vague recollection that Gordon did this to work around some bizarro bug.
I even have the vague recollection that we decided to live with this flashing as a result.
So yes, if you can use history to look at why we did, that would be good.
</blockquote></details>

![image.png](https://files.reviewableusercontent.io/images/reviewable/22460975/fK5DypS3vliPy53Ma_2yxp8d/image.png)
Looks like JH added it 12 years ago. I don't see any related information in the commit


<!-- Sent from Reviewable.io -->

2024-04-10 15:34 UTC, nabalone commented
*[`src/BloomExe/Edit/EditingView.cs` line 531 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OQQrBElylRXkgru9:-Nv7dAI1EGvypTDVYRMT:b-6rj6ic) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Edit/EditingView.cs#L531)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

![image.png](https://files.reviewableusercontent.io/images/reviewable/22460975/fK5DypS3vliPy53Ma_2yxp8d/image.png)
Looks like JH added it 12 years ago. I don't see any related information in the commit
</blockquote></details>

Looks like it came up in https://issues.bloomlibrary.org/youtrack/issue/BL-11539/WV2-add-page-dialogue-reappears-briefly-after-closing, I'm looking at what is going on there


<!-- Sent from Reviewable.io -->

2024-04-10 15:35 UTC, nabalone commented
*[`src/BloomExe/Edit/EditingView.cs` line 531 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OQQrBElylRXkgru9:-Nv7dYba8uzKVz50oCE1:b-hcln4f) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Edit/EditingView.cs#L531)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Looks like it came up in https://issues.bloomlibrary.org/youtrack/issue/BL-11539/WV2-add-page-dialogue-reappears-briefly-after-closing, I'm looking at what is going on there
</blockquote></details>

Ah, was considered Issues We'll Live With: https://issues.bloomlibrary.org/youtrack/issue/BL-11980/WV2-styling-difference-for-Add-Page-button


<!-- Sent from Reviewable.io -->

2024-04-10 15:51 UTC, andrew-polk commented
*[`src/BloomExe/Edit/EditingView.cs` line 531 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OQQrBElylRXkgru9:-Nv7hGPu84lWLpODsWog:b8p38r9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Edit/EditingView.cs#L531)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Ah, was considered Issues We'll Live With: https://issues.bloomlibrary.org/youtrack/issue/BL-11980/WV2-styling-difference-for-Add-Page-button
</blockquote></details>

I think this is the change I was thinking of. So probably not related.
https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641


<!-- Sent from Reviewable.io -->

2024-04-11 18:57 UTC, andrew-polk requested changes
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3847 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDVhE79ZRcI2uUUSe9:-NvDVhE79ZRcI2uUUSeA:b28lwx8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/BookStorage.cs#L3847)):*
> ```Smalltalk
>             "pageControls.css",
>             "pageThumbnailList.css",
>         };
> ```

I'm pretty sure this list of css files should only include ones which are part of the book.
But you've added a couple which are part of the Bloom UI.

At least, that's what I would expect in BookStorage. But maybe I'm wrong. I see editMode and previewMode there, too. But at least those are about how to show the book. The two new ones you added are not.

Hopefully your other PR is making all this irrelevant, but if we need two lists like this for some reason, 
1. Let's put the one which has UI stuff in it in another class
2. Let's make on derived from the other 


<!-- Sent from Reviewable.io -->

2024-04-11 20:21 UTC, nabalone commented
*[`src/BloomExe/Book/BookStorage.cs` line 3847 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDVhE79ZRcI2uUUSe9:-NvDoUh1BBeK9dr8KRvn:bl5ov04) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/BookStorage.cs#L3847)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty sure this list of css files should only include ones which are part of the book.
But you've added a couple which are part of the Bloom UI.

At least, that's what I would expect in BookStorage. But maybe I'm wrong. I see editMode and previewMode there, too. But at least those are about how to show the book. The two new ones you added are not.

Hopefully your other PR is making all this irrelevant, but if we need two lists like this for some reason, 
1. Let's put the one which has UI stuff in it in another class
2. Let's make on derived from the other
</blockquote></details>

Hmm, is this better? 


<!-- Sent from Reviewable.io -->

2024-04-11 20:27 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3828 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDpqjY1xTdYQELFOVz:-NvDpqjY1xTdYQELFOW-:bkhhtz5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/fb677d91f23f245170b62eaf6e7bdb71a19d7ace/src/BloomExe/Book/BookStorage.cs#L3828)):*
> ```Smalltalk
> 
>         // These go before "unknown" stylesheets in the sort order
>         public static readonly string[] AutomaticallyAddedCssPrefixesPart1 =
> ```

Also not sure what to name these


<!-- Sent from Reviewable.io -->

2024-04-15 15:49 UTC, andrew-polk commented
*[`src/BloomExe/Book/BookStorage.cs` line 3847 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDVhE79ZRcI2uUUSe9:-NvXQQQAAwmGsJVIdJSR:bmt1yvo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/BookStorage.cs#L3847)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Hmm, is this better?
</blockquote></details>

The comment 
// MakeDomRelocatable adds these and uses this list to get rid of old ones before addding new ones.

Does not seem to be true. In fact, `AutomaticallyAddedCssFilePrefixes` isn't used anywhere. Probably things got messed up when you tried to pull the PRs apart.
So maybe it is best/easiest just to make it all one PR.
Whatever is going to be easiest to move this forward for you.


<!-- Sent from Reviewable.io -->

2024-04-15 16:30 UTC, andrew-polk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @nabalone)



<!-- Sent from Reviewable.io -->

2024-04-16 15:39 UTC, andrew-polk requested changes
@JohnThomson will you please review this?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-:-NvbZ4oo9VHeP_lpHFGr:b-bifarg)* status: 3 of 12 files reviewed, 2 unresolved discussions (waiting on @JohnThomson and @nabalone)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3847 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDVhE79ZRcI2uUUSe9:-NvbZ--Q0Vqr8tUCh6sY:b-wb7ioq) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/BookStorage.cs#L3847)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The comment 
// MakeDomRelocatable adds these and uses this list to get rid of old ones before addding new ones.

Does not seem to be true. In fact, `AutomaticallyAddedCssFilePrefixes` isn't used anywhere. Probably things got messed up when you tried to pull the PRs apart.
So maybe it is best/easiest just to make it all one PR.
Whatever is going to be easiest to move this forward for you.
</blockquote></details>

I'm still missing something, because `AutomaticallyAddedCssFilePrefixes` still doesn't appear to be used.


<!-- Sent from Reviewable.io -->

2024-04-16 21:38 UTC, andrew-polk reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 3 of 12 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3847 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDVhE79ZRcI2uUUSe9:-Nvcq8oB7ijtmyIfM1tA:bbaygyo) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/BookStorage.cs#L3847)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

It's just for RemoveNormalStyleSheetsLinks  in HtmlDom.css (I added a review comment to flag it)
</blockquote></details>

Thanks. Sorry; I don't know why I wasn't finding that before.


<!-- Sent from Reviewable.io -->

2024-04-16 22:40 UTC, JohnThomson requested changes
Looks pretty good. I caught a few things and made some suggestions.

> Reviewed 8 of 9 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-:-Nvd3LxC22ZTQWQnnY-w:btqkniw)* status: all files reviewed, 11 unresolved discussions (waiting on @andrew-polk and @nabalone)

___
*[`src/BloomExe/Book/Book.cs` line 655 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvcttaf5GQ6kvcU_XV4:-Nvcttaf5GQ6kvcU_XV5:bf083z8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/Book.cs#L655)):*
> ```Smalltalk
>             var result = Storage.MakeDomRelocatable(inputDom);
>             result.AddStyleSheets("previewMode.css");
>             return result;
> ```

I think this is probably right. But is it a deliberate change that previewMode.css is now only added to the result, not to inputDom?
___
*[`src/BloomExe/Book/BookStorage.cs` line 3828 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDpqjY1xTdYQELFOVz:-Nvcv-PtEoIItg-IR23V:b-jybrhd) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/fb677d91f23f245170b62eaf6e7bdb71a19d7ace/src/BloomExe/Book/BookStorage.cs#L3828)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Also not sure what to name these
</blockquote></details>

How about, PrefixesOfCssFilesToSortBeforeUnknownStylesheets? And then PrefixesOfCssFilesToSortAfterUnknownStylesheets? It would be nice to get in there the notion that they are ordered, though. Maybe OrderedPrefixesOfCssFilesToSortBeforeUnknownStylesheets? We only use these in a couple of places, so we can afford to be verbose.
___
*[`src/BloomExe/Book/BookStorage.cs` line 3825 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvcvuiB86yyNX9pG_49:-NvcvuiB86yyNX9pG_4A:bybdoii) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/BookStorage.cs#L3825)):*
> ```Smalltalk
>             AutomaticallyAddedCssPrefixesPart1.Concat(AutomaticallyAddedCssPrefixesPart2).ToArray();
> 
>         // These are split up for the sake of the StyleSheetLinkSorter
> ```

Looks like this applies to the line above. Usually we put comments before the line they describe.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 269 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd1QCeBPFNIy5gc24B:-Nvd1QCf8ytowLeVqhY8:bn9cje0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/HtmlDom.cs#L269)):*
> ```Smalltalk
>             {
>                 var href = linkNode.GetAttribute("href");
>                 if (Path.GetFileName(href) == Path.GetFileName(path))
> ```

On thing we've changed here is losing the GetFileName. I was assuming we don't need it because the stylesheets (except ../customCollectionStyles.css) are always at the root of the book folder, and we always pass the plain file names. But that isn't true down where EpubMaker is passing some full paths, or even ToLocalHost() of some full paths. I'm not keen to put GetFileName() back in, because I want it to handle ../customCollectionStyles.css correctly. But you need to check callers, maybe even worth asserting that anything other than ../customCollectionStyles.css doesn't have path separators.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 2951 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvcDdZR4b608JHxdHg9:-Nvd-V_T948zG-kkG47b:bfrtde1) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Book/HtmlDom.cs#L2951)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I don't really understand why this is the way it is. Could a reviewer please check if it looks like my refactor preserves behavior here?
</blockquote></details>

I think what we need is 
anyAdded = targetBookDom.AddStyleSheetsWithoutSorting(sourceBookDom.GetTemplateStyleSheets().ToArray());
targetBookDom.SortStyleSheetLinks();
return anyAdded.

Alternatively, you could make AddStyleSheets() return anyAdded, and then it would all collapse to
return targetBookDom.AddStyleSheets(...);

It raises an interesting question of whether AddStyleSheets() should sort if nothing was added. In some cases (but I'm not sure how many) it would save work if we didn't. OTOH in at least one place we are adding several things and then counting on one call to AddStyleSheets to sort them all. I'm guessing it's fairly unusual that nothing gets added. so probably not a case worth optimizing for.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 254 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvczBQdE11UxGFvjrbJ:-NvczBQdE11UxGFvjrbK:b-285sd2) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/HtmlDom.cs#L254)):*
> ```Smalltalk
>         internal bool UseOriginalImages { get; set; }
> 
>         public void AddStyleSheets(params string[] paths)
> ```

I think this deserves a comment along the lines "Make sure the DOM has a link to each of the stylesheets passed, and that all stylesheet links are in the right order.
Another idea is to go with the name we had before in BookStorage. EnsureStylesheets or EnsureStylesheetLinks is not as unwieldy as AddStylesheetIfMissing, but it does convey the idea that we will add them only if necessary.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 261 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvcw52b1WLehvPBnVOY:-Nvcw52b1WLehvPBnVOZ:b-p6vqpv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/HtmlDom.cs#L261)):*
> ```Smalltalk
> 
>         /// <summary>
>         /// Add a reference to the specified stylesheet if we don't already have it.
> ```

Needs a little tweaking to describe a list of paths.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 283 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvcxm3k8v3CTq5lILqh:-Nvcxm3k8v3CTq5lILqi:bzjlmk) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/HtmlDom.cs#L283)):*
> ```Smalltalk
>             var pathToCheck = path;
>             if (Environment.OSVersion.Platform == PlatformID.Win32NT)
>                 pathToCheck = pathToCheck.ToLowerInvariant();
> ```

I'm having second thoughts about messing with case here. These are not random names the user typed. They are known names of standard stylesheets we use. If we get the case wrong in the name we pass to this method, unless it's already present with the right case, Linux won't find the file. We won't find that out, of course, until we start supporting Linux again.
Then again, if we do get it wrong, and don't check like this, currently on Windows all that will happen is that the old one won't get removed. So we'll have two links to 'the same' file.
Suggestion: remove the case changing code here. Remove it below also. Then down where we compare paths, do this:

filename = filename.Replace('\\', '/');
if (filename == pathToCheck)
   return false;
Debug.Assert(filename.ToLowerInvariant != pathToCheck.ToLowerInvariant, "passing a filename with wrong case: " + filename).

That way, we both don't waste time ignoring case in production, and do get immediate definite developer feedback if we're using the wrong case.
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1683 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd2a2H7PE9TMclaK5P:-Nvd2a2H7PE9TMclaK5Q:b8r5e71) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Publish/Epub/EpubMaker.cs#L1683)):*
> ```Smalltalk
>                 pageDom.AddStyleSheetsWithoutSorting(
>                     baseEpubPath.ToLocalhost(),
>                     brandi [...]

2024-04-17 21:28 UTC, nabalone commented
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1683 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd2a2H7PE9TMclaK5P:-NvhxFLW3CcGYj-Uv3rS:b-snue52) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Publish/Epub/EpubMaker.cs#L1683)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not sure why we're passing full paths and ToLocalhost() results here, but I think the new version of AddStyleSheets just wants file names...assuming the files are going to end up in the right place. I would expect our EpubMaker tests to have caught this...make sure they pass before you submit! (In fact this change is risky enough that you should run ALL our unit tests.)
</blockquote></details>

Should I keep `Storage.GetFileLocator().LocateFileWithThrow(@"baseEPUB.css");` in there so that it will still throw if the file can't be located?


<!-- Sent from Reviewable.io -->

2024-04-18 14:04 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 5 of 12 files reviewed, 11 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Book/Book.cs` line 655 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvcttaf5GQ6kvcU_XV4:-NvgQD0q3ZztBPgQ5zAX:bmabzfy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/Book.cs#L655)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think this is probably right. But is it a deliberate change that previewMode.css is now only added to the result, not to inputDom?
</blockquote></details>

The code on master is:
```
            //inputHead.ParentNode.ReplaceChild(importNode, inputHead);
            var result = Storage.MakeDomRelocatable(inputDom);
            Storage.EnsureHasLinkToStyleSheet(result, "previewMode.css");
            return result;
```

I think I had changed it to add previewMode.css to the inputDom and then changed it back
___
*[`src/BloomExe/Book/BookStorage.cs` line 3828 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDpqjY1xTdYQELFOVz:-NviXzeS3mi9SpAaZtM-:b-7ra9d5) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/fb677d91f23f245170b62eaf6e7bdb71a19d7ace/src/BloomExe/Book/BookStorage.cs#L3828)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How about, PrefixesOfCssFilesToSortBeforeUnknownStylesheets? And then PrefixesOfCssFilesToSortAfterUnknownStylesheets? It would be nice to get in there the notion that they are ordered, though. Maybe OrderedPrefixesOfCssFilesToSortBeforeUnknownStylesheets? We only use these in a couple of places, so we can afford to be verbose.
</blockquote></details>

Is it okay that that doesn't specify what css files should be in the list? I'm okay with it though

Also should we still keep `AutomaticallyAddedCssFilePrefixes` with its current name?
___
*[`src/BloomExe/Book/BookStorage.cs` line 3825 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvcvuiB86yyNX9pG_49:-NvgqHNf03CSzMXiPn28:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/BookStorage.cs#L3825)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Looks like this applies to the line above. Usually we put comments before the line they describe.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 269 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd1QCeBPFNIy5gc24B:-NviPOix00uJ_s7UScGR:bfqjwoa) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/HtmlDom.cs#L269)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

On thing we've changed here is losing the GetFileName. I was assuming we don't need it because the stylesheets (except ../customCollectionStyles.css) are always at the root of the book folder, and we always pass the plain file names. But that isn't true down where EpubMaker is passing some full paths, or even ToLocalHost() of some full paths. I'm not keen to put GetFileName() back in, because I want it to handle ../customCollectionStyles.css correctly. But you need to check callers, maybe even worth asserting that anything other than ../customCollectionStyles.css doesn't have path separators.
</blockquote></details>

What is the situation with `css/fonts.css`? 
___
*[`src/BloomExe/Book/HtmlDom.cs` line 2951 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvcDdZR4b608JHxdHg9:-NvhQmggCIdy7XIyYBBz:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Book/HtmlDom.cs#L2951)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think what we need is 
anyAdded = targetBookDom.AddStyleSheetsWithoutSorting(sourceBookDom.GetTemplateStyleSheets().ToArray());
targetBookDom.SortStyleSheetLinks();
return anyAdded.

Alternatively, you could make AddStyleSheets() return anyAdded, and then it would all collapse to
return targetBookDom.AddStyleSheets(...);

It raises an interesting question of whether AddStyleSheets() should sort if nothing was added. In some cases (but I'm not sure how many) it would save work if we didn't. OTOH in at least one place we are adding several things and then counting on one call to AddStyleSheets to sort them all. I'm guessing it's fairly unusual that nothing gets added. so probably not a case worth optimizing for.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 254 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvczBQdE11UxGFvjrbJ:-NvgrtA0-Aw17CnzdTAU:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/HtmlDom.cs#L254)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think this deserves a comment along the lines "Make sure the DOM has a link to each of the stylesheets passed, and that all stylesheet links are in the right order.
Another idea is to go with the name we had before in BookStorage. EnsureStylesheets or EnsureStylesheetLinks is not as unwieldy as AddStylesheetIfMissing, but it does convey the idea that we will add them only if necessary.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 261 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvcw52b1WLehvPBnVOY:-NvgsCab0ibTUeCE--lg:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/HtmlDom.cs#L261)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Needs a little tweaking to describe a list of paths.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 283 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvcxm3k8v3CTq5lILqh:-NvhFA9t-7-NUS_vp3Ax:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Book/HtmlDom.cs#L283)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm having second thoughts about messing with case here. These are not random names the user typed. They are known names of standard stylesheets we use. If we get the case wrong in the name we pass to this method, unless it's already present with the right case, Linux won't find the file. We won't find that out, of course, until we start supporting Linux again.
Then again, if we do get it wrong, and don't check like this, currently on Windows all that will happen is that the old one won't get removed. So we'll have two links to 'the same' file.
Suggestion: remove the case changing code here. Remove it below also. Then down where we compare paths, do this:

filename = filename.Replace('\\', '/');
if (filename == pathToCheck)
   return false;
Debug.Assert(filename.ToLowerInvariant != pathToCheck.ToLowerInvariant, "passing a filename with wrong case: " + filename).

That way, we both don't waste time ignoring case in production, and do get immediate definite developer feedback if we're using the wrong case.
</blockquote></details>

Done.
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1695 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd30BYB-Pt6WIpl0ql:-NviMDzR0tXJBZRM0p8p:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Publish/Epub/EpubMaker.cs#L1695)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Again, the new version won't handle paths.
</blo [...]

2024-04-18 14:09 UTC, nabalone commented
*[`src/BloomExe/Book/XMatterHelper.cs` line 350 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvlXD2B375dqZqhRyw4:-NvlXD2B375dqZqhRyw5:bntzdur) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a272590ac827c6c17a0b15be7709cf3064ab1dd0/src/BloomExe/Book/XMatterHelper.cs#L350)):*
> ```Smalltalk
>             //makes it easy to drop into a css editor and fix it up with the content we're looking at.
>             //TODO:But then later, we want to save it so that these are found in the same dir as the book.
>             _bookDom.EnsureStylesheetLinks(Path.GetFileName(PathToXMatterStylesheet));
> ```

@JohnThomson  is this change okay? If not, how do we want to handle the path? The original code is 
` _bookDom.AddStyleSheet(PathToXMatterStylesheet.ToLocalhost());` (https://github.com/BloomBooks/BloomDesktop/blob/d6e59e7943a203cec590863a6643eb138e54489f/src/BloomExe/Book/XMatterHelper.cs#L346C1-L350C75)


<!-- Sent from Reviewable.io -->

2024-04-18 16:28 UTC, JohnThomson requested changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 5 of 12 files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`src/BloomExe/Book/BookStorage.cs` line 3828 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvDpqjY1xTdYQELFOVz:-NvlqWdx1YH-yd2yD2jZ:b-tqnthy) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/fb677d91f23f245170b62eaf6e7bdb71a19d7ace/src/BloomExe/Book/BookStorage.cs#L3828)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Is it okay that that doesn't specify what css files should be in the list? I'm okay with it though

Also should we still keep `AutomaticallyAddedCssFilePrefixes` with its current name?
</blockquote></details>

I think what you have now is good.
___
*[`src/BloomExe/Book/HtmlDom.cs` line 269 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd1QCeBPFNIy5gc24B:-Nvlr8ob3LWjuHoeTK_u:bwf81ro) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/HtmlDom.cs#L269)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

What is the situation with `css/fonts.css`?
</blockquote></details>

I'm not sure. I'm afraid you probably need to look at all callers. If they are passing something other than a name with no path separators, make sure the relevant code is still working: that the link we put into the book is actually finding a stylesheet. If you can get the DOM on screen in a browser, the Network tab will tell you whether each file request was successful.
For example, if something is passing css/fonts.css, then hopefully something is making sure that the right fonts.css file is in a css folder under the book folder. If in fact fonts.css is being put in the root folder, then you should change the caller to just pass fonts.css.
___
*[`src/BloomExe/Book/XMatterHelper.cs` line 350 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvlXD2B375dqZqhRyw4:-NvltSDE3cN_K9CFWGkk:b-jvk6nv) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a272590ac827c6c17a0b15be7709cf3064ab1dd0/src/BloomExe/Book/XMatterHelper.cs#L350)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

@JohnThomson  is this change okay? If not, how do we want to handle the path? The original code is 
` _bookDom.AddStyleSheet(PathToXMatterStylesheet.ToLocalhost());` (https://github.com/BloomBooks/BloomDesktop/blob/d6e59e7943a203cec590863a6643eb138e54489f/src/BloomExe/Book/XMatterHelper.cs#L346C1-L350C75)
</blockquote></details>

It's a bit tricky. The original code would LOOK for an exiting link with the same filename, and if it found it, leave it and not add the new one. But otherwise (which is probably more common) it would add the new one complete with its path.
I wrote that code quite recently, but it now seems clearly wrong: if the current caller wants a link to, say, ../customCollectionStyles.css, we should not just ignore that because we find one to customCollectionStyles.css.
The current xmatter stylesheet gets copied to the book folder, so a simple link to the filename will work. I'm about 95% sure that there is no longer a debugging advantage to pointing the link at the original (like the old comment says). JohnH's latest change (which might not be in your source yet unless you rebase) causes things to be automatically updated when a new xmatter CSS is created. So I think it is fine that we just point to the local copy. In fact, it will probably make things more robust. I think we should go with the change you've made. But you should probably do a bit of testing that changing xmatter packs has the expected effects.
___
*[`src/BloomExe/Edit/EditingView.cs` line 531 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nv7OQQrBElylRXkgru9:-Nvlykje-V_PApZ0t_Y1:b-8wa64a) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Edit/EditingView.cs#L531)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this is the change I was thinking of. So probably not related.
https://reviewable.io/reviews/BloomBooks/BloomDesktop/5641
</blockquote></details>

Looks like we've done all we can to look for reasons why focus was needed there. I think we can go ahead and remove it, as you have done.
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1683 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd2a2H7PE9TMclaK5P:-NvlzPeFCrVYgjIX9Leg:b-m0cny9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Publish/Epub/EpubMaker.cs#L1683)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Should I keep `Storage.GetFileLocator().LocateFileWithThrow(@"baseEPUB.css");` in there so that it will still throw if the file can't be located?
</blockquote></details>

I don't really think we need it. We've been reliably generating these files for a long time now.
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1767 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvig6D6BNpQBTWqjxpV:-Nvm-pZZ0_p_A1CWk0Nr:beq0ntr) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Publish/Epub/EpubMaker.cs#L1767)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Flagging here `css/fonts.css` that is also not a filename but seems like we still want href=css/fonts.css?
</blockquote></details>

Yes, looks like we want that. Check that the sorter has what it needs to sort this in the sequence we want, if it's in that list at all. Also that the file is, indeed, getting kept in this css directory. (Though I find myself asking, why?? Seems like if we have a CSS directory, all our CSS should be there, not just one file?? But let's not complicate this PR with trying to fix yet another historical mistake!)
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1688 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvlzaSs6SnHQFFCFMz2:-NvlzaSs6SnHQFFCFMz3:bdh0gw9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/88beedcb80e10081a2820c2579b61f62f0af5b3a/src/BloomExe/Publish/Epub/EpubMaker.cs#L1688)):*
> ```Smalltalk
>                 // Adding basePage.css is definitely a bad idea, because it's now possible we want basePageLegacy instead.
>                 Storage.GetFileLocator().LocateFileWithThrow(@"previewMode.css");
>                 Storage.GetFileLocator().LocateFileWithThrow(@"origami.css");
> ```

I don't think we need to locate the files here any more. Something, probably BookStorage.UpdateSupportFiles(), should be copying all the CSS we need into the book folder; that code should fail appropriately if they can't be found.
It's just possible that previewMode.css does NOT get copied into the book folder, if we only use it at runtime, in which case we may actually NEED to put some sort of full path to it into the link. Worth checking that it actually gets copied and found (probably you already did).
If we DO need a path here, we need to think about implications for the sorter. If we put previewMode.css into the link with a path, it won't match the entry in the sorter list.


<!-- Sent from Reviewable.io -->

2024-04-18 21:22 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/HtmlDom.cs` line 269 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd1QCeBPFNIy5gc24B:-NvmsjXQC2FzRCr69GEK:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7191a0876c183773cdd509742a07817dfaa74fbb/src/BloomExe/Book/HtmlDom.cs#L269)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not sure. I'm afraid you probably need to look at all callers. If they are passing something other than a name with no path separators, make sure the relevant code is still working: that the link we put into the book is actually finding a stylesheet. If you can get the DOM on screen in a browser, the Network tab will tell you whether each file request was successful.
For example, if something is passing css/fonts.css, then hopefully something is making sure that the right fonts.css file is in a css folder under the book folder. If in fact fonts.css is being put in the root folder, then you should change the caller to just pass fonts.css.
</blockquote></details>

Done.
___
*[`src/BloomExe/Book/XMatterHelper.cs` line 350 at r5](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvlXD2B375dqZqhRyw4:-Nvn3jUzBolrNY750GU_:bb6un1j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/a272590ac827c6c17a0b15be7709cf3064ab1dd0/src/BloomExe/Book/XMatterHelper.cs#L350)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's a bit tricky. The original code would LOOK for an exiting link with the same filename, and if it found it, leave it and not add the new one. But otherwise (which is probably more common) it would add the new one complete with its path.
I wrote that code quite recently, but it now seems clearly wrong: if the current caller wants a link to, say, ../customCollectionStyles.css, we should not just ignore that because we find one to customCollectionStyles.css.
The current xmatter stylesheet gets copied to the book folder, so a simple link to the filename will work. I'm about 95% sure that there is no longer a debugging advantage to pointing the link at the original (like the old comment says). JohnH's latest change (which might not be in your source yet unless you rebase) causes things to be automatically updated when a new xmatter CSS is created. So I think it is fine that we just point to the local copy. In fact, it will probably make things more robust. I think we should go with the change you've made. But you should probably do a bit of testing that changing xmatter packs has the expected effects.
</blockquote></details>

Done
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1683 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvd2a2H7PE9TMclaK5P:-NvmWap4EwrB0YGk4T6k:bb6un1j) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Publish/Epub/EpubMaker.cs#L1683)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't really think we need it. We've been reliably generating these files for a long time now.
</blockquote></details>

Done
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1767 at r4](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvig6D6BNpQBTWqjxpV:-NvmWEWX1gSmVRcH7qhr:bxkdwo9) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/dc4726b07127d8f2f714598bcf87c3c9ad77dd71/src/BloomExe/Publish/Epub/EpubMaker.cs#L1767)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Yes, looks like we want that. Check that the sorter has what it needs to sort this in the sequence we want, if it's in that list at all. Also that the file is, indeed, getting kept in this css directory. (Though I find myself asking, why?? Seems like if we have a CSS directory, all our CSS should be there, not just one file?? But let's not complicate this PR with trying to fix yet another historical mistake!)
</blockquote></details>

It works. Looks like there are other files in the css directory as well, not sure what the situation is
___
*[`src/BloomExe/Publish/Epub/EpubMaker.cs` line 1688 at r7](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvlzaSs6SnHQFFCFMz2:-NvmWQxh6HPF0SBhVW_R:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/88beedcb80e10081a2820c2579b61f62f0af5b3a/src/BloomExe/Publish/Epub/EpubMaker.cs#L1688)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think we need to locate the files here any more. Something, probably BookStorage.UpdateSupportFiles(), should be copying all the CSS we need into the book folder; that code should fail appropriately if they can't be found.
It's just possible that previewMode.css does NOT get copied into the book folder, if we only use it at runtime, in which case we may actually NEED to put some sort of full path to it into the link. Worth checking that it actually gets copied and found (probably you already did).
If we DO need a path here, we need to think about implications for the sorter. If we put previewMode.css into the link with a path, it won't match the entry in the sorter list.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-18 21:43 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 4 of 12 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2986 at r8](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvn6SamE8PJaQO5GpB2:-Nvn6SamE8PJaQO5GpB3:bbhozt0) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Book/BookStorage.cs#L2986)):*
> ```Smalltalk
> 
>             // If we're not supposed to have these links, make sure we don't.
>             AppearanceSettings.PossibleAppearanceRelatedCssFiles
> ```

@JohnThomson did you tell me to delete these lines? I think so but don't remember very well and just wanted to make sure it was intentional


<!-- Sent from Reviewable.io -->

2024-04-18 22:49 UTC, JohnThomson requested changes
Sorry, picked up one more thing I missed earlier. Looking good overall.

> Reviewed 3 of 7 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-:-NvnOWrA16jpmpE-YWyP:bneo7rl)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`src/BloomExe/Book/BookStorage.cs` line 2986 at r8](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-Nvn6SamE8PJaQO5GpB2:-NvnMkJN9kY2f55_-afK:b-tllqrc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/e1509209b90b7ea225afbd4a39f4034fe62d08f6/src/BloomExe/Book/BookStorage.cs#L2986)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

@JohnThomson did you tell me to delete these lines? I think so but don't remember very well and just wanted to make sure it was intentional
</blockquote></details>

Yes, the whole block removing PossibleAppearanceRelatedCssFiles can go, because we verified that all the files in it area already cleaned out by RemoveNormalStylesheetsLinks (you may want to check that one more time).
___
*[`src/BloomExe/Book/HtmlDom.cs` line 269 at r9](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvnNB3R4OX2zTftqHdR:-NvnNB3R4OX2zTftqHdS:bgy0pwf) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/56485a2cea1c84b196aaa0dbd06cb8b6a364768d/src/BloomExe/Book/HtmlDom.cs#L269)):*
> ```Smalltalk
>         /// Return true if any stylesheets were added
>         /// </summary>
>         public bool AddStyleSheetsWithoutSorting(params string[] paths)
> ```

Let's be consistent and call this EnsureStylesheetLinksWithoutSorting.
Also: it's not obvious to me whether it should be Stylesheet or StyleSheet. You might see which we use most often. I think stylesheet is a single word (my spell checker thinks so, anyway) in which case we should not be capitalizing "sheet". Let's at least get all the names we're changing consistent with whichever we decide is right.


<!-- Sent from Reviewable.io -->

2024-04-19 00:29 UTC, nabalone reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/HtmlDom.cs` line 269 at r9](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6397#-NvnNB3R4OX2zTftqHdR:-Nvnj2-Q06NVcyY2An8a:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/56485a2cea1c84b196aaa0dbd06cb8b6a364768d/src/BloomExe/Book/HtmlDom.cs#L269)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Let's be consistent and call this EnsureStylesheetLinksWithoutSorting.
Also: it's not obvious to me whether it should be Stylesheet or StyleSheet. You might see which we use most often. I think stylesheet is a single word (my spell checker thinks so, anyway) in which case we should not be capitalizing "sheet". Let's at least get all the names we're changing consistent with whichever we decide is right.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-19 15:05 UTC, merged