Check whether this version is allowed to download (BL-13283)
BloomBooks/BloomDesktop pull request #6420
Opened 2024-04-17 15:53 UTC by JohnThomson

This code is roughly copied (one small change to a variable name) from Bloom 5.7. Not a cherry-pick because of  that one name change and I didn't want to bring other changes (even to tests) along. It should be merged normally into 5.6 but probably null-merged into 5.7.

2024-04-17 16:13 UTC, andrew-polk requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BookDownload.cs` line 163 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420#-NvgotjA4qzf2H-ln8hK:-NvgotjA4qzf2H-ln8hL:brnbdtu) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7a324505509d3dccb77813a2b514ab45d2e0a759/src/BloomExe/WebLibraryIntegration/BookDownload.cs#L163)):*
> ```Smalltalk
> 					LocalizationManager.GetString(
> 						"PublishTab.Upload.OldVersion",
> 						"Sorry, this version of Bloom Desktop is not compatible with the current version of BloomLibrary.org. Please upgrade to a newer version."
> ```

JH changed the message. See the card.
I guess we should go ahead and add this to the .xlf for 5.5 now.


<!-- Sent from Reviewable.io -->

2024-04-17 19:14 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BookDownload.cs` line 163 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420#-NvgotjA4qzf2H-ln8hK:-NvhT6Md7thvCu5NBaSc:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/7a324505509d3dccb77813a2b514ab45d2e0a759/src/BloomExe/WebLibraryIntegration/BookDownload.cs#L163)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

JH changed the message. See the card.
I guess we should go ahead and add this to the .xlf for 5.5 now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-17 22:37 UTC, andrew-polk reviewed
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BookDownload.cs` line 161 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420#-NviB3PdDsl5O0b5og8h:-NviB3PeBd3L6NbXa0C1:b-l7a53s) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/754980ad079092e8db9fea394846f64dbc0b7d32/src/BloomExe/WebLibraryIntegration/BookDownload.cs#L161)):*
> ```Smalltalk
> 				var minVersionStr = HttpUtility.ParseQueryString(new Uri(order).Query)[
> 					"minVersion"
> 				];
> ```

I started wondering if this could throw and would need a guard....
However, I see now that we only seem to return false from `IsThisVersionAllowedToDownload` if we successfully parsed it.
I wonder if it is better to return the minVersion from `IsThisVersionAllowedToDownload` as an out parameter?
I see pros and cons. So I'll throw it out there as an idea and let you decide.


<!-- Sent from Reviewable.io -->

2024-04-18 13:59 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomExe/WebLibraryIntegration/BookDownload.cs` line 161 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420#-NviB3PdDsl5O0b5og8h:-NvlUp8qCxxHEJT5zLrO:b-vv9yfc) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/754980ad079092e8db9fea394846f64dbc0b7d32/src/BloomExe/WebLibraryIntegration/BookDownload.cs#L161)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I started wondering if this could throw and would need a guard....
However, I see now that we only seem to return false from `IsThisVersionAllowedToDownload` if we successfully parsed it.
I wonder if it is better to return the minVersion from `IsThisVersionAllowedToDownload` as an out parameter?
I see pros and cons. So I'll throw it out there as an idea and let you decide.
</blockquote></details>

I tossed up on that, too. One reason to leave it this way is that IsThisVersionAllowedToDownload is left exactly the same as 5.7. I'm hoping that makes the merge easier! And performance is not an issue here.


<!-- Sent from Reviewable.io -->

2024-04-18 14:57 UTC, andrew-polk approved these changes
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[`src/BloomExe/WebLibraryIntegration/BookDownload.cs` line 161 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6420#-NviB3PdDsl5O0b5og8h:-NvlhVmm4s7HV5_01kvG:beex9zl) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/754980ad079092e8db9fea394846f64dbc0b7d32/src/BloomExe/WebLibraryIntegration/BookDownload.cs#L161)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I tossed up on that, too. One reason to leave it this way is that IsThisVersionAllowedToDownload is left exactly the same as 5.7. I'm hoping that makes the merge easier! And performance is not an issue here.
</blockquote></details>

Ok, feel free to merge.
Or, if you feel inclined, maybe a comment explaining why this line is safe and doesn't need a guard?


<!-- Sent from Reviewable.io -->

2024-04-18 16:52 UTC, merged