Various improvements to Start controls
BloomBooks/BloomDesktop pull request #6573
Opened 2024-07-18 16:07 UTC by JohnThomson

- Add a section for item controls, move Delete and Duplicate into it
- "Part of the answer" control moves into it and is shown only when relevant
- new control to associate sound with image
- fixed a bug where bubbleManager could pick a hidden (e.g., Correct tab) item to select initially.
- cleanup and simplify some code...found places useMemo can replace useState+useEffect

2024-07-18 16:37 UTC, andrew-polk requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573)* status: all files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx` line 817 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O25fOBfDH4peNr3gzVH:-O25fOBgDyIddzGeE8cr:bs3yjws) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87c869e6fffb57cd15aef13e7db705e28cd564a8/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx#L817)):*
> ```XML
>         const page = getPage();
>         setSoundFolder(result.data);
>         setSound(which, result.data, false); // already copied, and not in our sounds folder
> ```

I think it would be helpful to rewrite this as 

```
var copyBuiltIn = false; // already copied, and not in our sounds folder
setSound(which, result.data, copyBuiltIn);
```
___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx` line 1608 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O25g6bK9lzA04ewVgQ0:-O25g6bK9lzA04ewVgQ1:b-mjc13d) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87c869e6fffb57cd15aef13e7db705e28cd564a8/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx#L1608)):*
> ```XML
> 
> // Three kinds of sound we can set with a dropdown.
> type soundType = "correct" | "wrong" | "image";
> ```

I think types are usually PascalCase.

Then I think it would be better to change "which" everywhere to "soundType".
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 4666 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O25ciNX3C-WLpI6Bhz-:-O25ciNY196AtPpcKKfi:b-le1o3l) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87c869e6fffb57cd15aef13e7db705e28cd564a8/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L4666)):*
> ```XML
> }
> 
> // Review: is there a better place for this??
> ```

What do you think of EditableDivUtils?


<!-- Sent from Reviewable.io -->

2024-07-18 20:55 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx` line 817 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O25fOBfDH4peNr3gzVH:-O26cE44-k7VcK-_ilpj:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87c869e6fffb57cd15aef13e7db705e28cd564a8/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx#L817)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think it would be helpful to rewrite this as 

```
var copyBuiltIn = false; // already copied, and not in our sounds folder
setSound(which, result.data, copyBuiltIn);
```
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx` line 1608 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O25g6bK9lzA04ewVgQ0:-O26bNyCDBXJ17L9AQtl:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87c869e6fffb57cd15aef13e7db705e28cd564a8/src/BloomBrowserUI/bookEdit/toolbox/dragActivity/dragActivityTool.tsx#L1608)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think types are usually PascalCase.

Then I think it would be better to change "which" everywhere to "soundType".
</blockquote></details>

Done.
___
*[`src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts` line 4666 at r1](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O25ciNX3C-WLpI6Bhz-:-O26aVtb2mGlfs5RC5DD:b-896fix) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/87c869e6fffb57cd15aef13e7db705e28cd564a8/src/BloomBrowserUI/bookEdit/toolbox/talkingBook/audioRecording.ts#L4666)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What do you think of EditableDivUtils?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-07-19 00:20 UTC, andrew-polk reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts` line 492 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O27LkM_7DUiKYIbjgoB:-O27LkM_7DUiKYIbjgoC:b-sppvfb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9130e8b92526426763e9482451eca2f4eb615e63/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L492)):*
> ```XML
> }
> 
> export function isInHiddenLanguageBlock(elem: Element) {
> ```

I don't know why we made EditableDivUtils a class with a bunch of statics.
But it seems odd to make this function be an outlier.
Should we just include it in the class until we convert the whole file to plain functions?

If you disagree or if you move it, feel free to merge.


<!-- Sent from Reviewable.io -->

2024-07-19 16:20 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts` line 492 at r2](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O27LkM_7DUiKYIbjgoB:-O2AmtXp9BNdHGxLKbZD:bgc8yh) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/9130e8b92526426763e9482451eca2f4eb615e63/src/BloomBrowserUI/bookEdit/js/editableDivUtils.ts#L492)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't know why we made EditableDivUtils a class with a bunch of statics.
But it seems odd to make this function be an outlier.
Should we just include it in the class until we convert the whole file to plain functions?

If you disagree or if you move it, feel free to merge.
</blockquote></details>

I made it a static on the class.


<!-- Sent from Reviewable.io -->

2024-07-19 16:30 UTC, andrew-polk requested changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573)* status: all files reviewed, 2 unresolved discussions (waiting on @JohnThomson)

___
*[`src/BloomExe/Book/BookFileFilter.cs` line 282 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O2AoPCm4Vy3sEZzI7nO:-O2AoPCnEV7bYl7Xay0W:b-nbjzmi) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8607683d7d9edac38ab50cd1d5857b7cf0e61ba3/src/BloomExe/Book/BookFileFilter.cs#L282)):*
> ```Smalltalk
>                     if (NarrationFiles.Contains(path[1]))
>                         return true;
>                     if (IncludeFilesNeededForBloomPlayer && SpecialAudioFiles.Contains(path[1]))
> ```

Perhaps this is more of a naming issue than anything, but don't we also want these files for upload? And creating a BloomPack? (basically everything except PDF?)
___
*[`src/BloomExe/Book/BookFileFilter.cs` line 344 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O2AoilJBA_ZDlQBrWs1:-O2AoilK0nVBJoYjIE1t:bog6vj8) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8607683d7d9edac38ab50cd1d5857b7cf0e61ba3/src/BloomExe/Book/BookFileFilter.cs#L344)):*
> ```Smalltalk
>         }
> 
>         HashSet<string> SpecialAudioFiles
> ```

I know there's nothing in the attribute names which requires these to be used for games, but while they are only used for games, it seems like it would helpful to just go ahead and label these as GameAudioFiles.
Or at the least, we should comment stating what these "special" files are about.


<!-- Sent from Reviewable.io -->

2024-07-19 17:11 UTC, JohnThomson reviewed
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`src/BloomExe/Book/BookFileFilter.cs` line 282 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O2AoPCm4Vy3sEZzI7nO:-O2Aw-Wc0hK0XuuwC1-s:b-yh9dhb) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8607683d7d9edac38ab50cd1d5857b7cf0e61ba3/src/BloomExe/Book/BookFileFilter.cs#L282)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Perhaps this is more of a naming issue than anything, but don't we also want these files for upload? And creating a BloomPack? (basically everything except PDF?)
</blockquote></details>

This is tricky. Maybe it's an existing naming problem.
The BloomPack and upload filters both set IncludeFilesForContinuedEditing, which sets this. So they will always be a superset of the files needed for bloom player.
I added a comment.
___
*[`src/BloomExe/Book/BookFileFilter.cs` line 344 at r3](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573#-O2AoilJBA_ZDlQBrWs1:-O2Ayalw2l6HlNwV3r9v:bty37fw) ([raw file](https://github.com/BloomBooks/BloomDesktop/blob/8607683d7d9edac38ab50cd1d5857b7cf0e61ba3/src/BloomExe/Book/BookFileFilter.cs#L344)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I know there's nothing in the attribute names which requires these to be used for games, but while they are only used for games, it seems like it would helpful to just go ahead and label these as GameAudioFiles.
Or at the least, we should comment stating what these "special" files are about.
</blockquote></details>

I commented.


<!-- Sent from Reviewable.io -->

2024-07-19 17:13 UTC, andrew-polk approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/BloomDesktop/6573)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)



<!-- Sent from Reviewable.io -->

2024-07-19 17:13 UTC, merged